import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({transaction:vi.fn(),execute:vi.fn(),invalidate:vi.fn(),create:vi.fn(),find:vi.fn(),verifyUser:vi.fn(),consume:vi.fn()}));
vi.mock("@/lib/db",()=>({db:{$transaction:mocks.transaction}}));vi.mock("@/lib/email/mailer",()=>({sendVerificationEmail:vi.fn()}));
import{isVerificationTokenShape,issueEmailVerification,verifyEmailToken}from"./email-verification";
const tokenRecord=(overrides={})=>({id:"token-id",userId:"admin-id",expiresAt:new Date(Date.now()+60_000),usedAt:null,...overrides});
beforeEach(()=>{vi.clearAllMocks();mocks.execute.mockResolvedValue(0);mocks.invalidate.mockResolvedValue({count:1});mocks.create.mockResolvedValue({});mocks.find.mockResolvedValue(tokenRecord());mocks.verifyUser.mockResolvedValue({count:1});mocks.consume.mockResolvedValue({count:1});mocks.transaction.mockImplementation(async(fn)=>fn({$executeRaw:mocks.execute,emailVerificationToken:{updateMany:vi.fn((args)=>args.where.id?mocks.consume(args):mocks.invalidate(args)),create:mocks.create,findUnique:mocks.find},user:{updateMany:mocks.verifyUser}}))});
describe("email verification security",()=>{
 it("creates a 256-bit shaped token only after successful delivery, under a user lock",async()=>{const deliver=vi.fn().mockResolvedValue(undefined);await issueEmailVerification("admin-id","admin@example.com",deliver);const sent=deliver.mock.calls[0][1];expect(isVerificationTokenShape(sent)).toBe(true);expect(mocks.execute).toHaveBeenCalled();expect(mocks.invalidate.mock.invocationCallOrder[0]).toBeLessThan(mocks.create.mock.invocationCallOrder[0]);expect(mocks.create.mock.calls[0][0].data.tokenHash).toMatch(/^[a-f0-9]{64}$/);expect(mocks.create.mock.calls[0][0].data).not.toHaveProperty("token")});
 it("preserves the existing token state when SMTP delivery fails",async()=>{const deliver=vi.fn().mockRejectedValue(new Error("SMTP secret detail"));await expect(issueEmailVerification("admin-id","admin@example.com",deliver)).rejects.toThrow();expect(mocks.transaction).not.toHaveBeenCalled();expect(mocks.invalidate).not.toHaveBeenCalled()});
 it("rejects malformed, expired, and used tokens",async()=>{expect(await verifyEmailToken("bad")).toBe(false);mocks.find.mockResolvedValueOnce(tokenRecord({expiresAt:new Date(Date.now()-1)}));expect(await verifyEmailToken("a".repeat(43))).toBe(false);mocks.find.mockResolvedValueOnce(tokenRecord({usedAt:new Date()}));expect(await verifyEmailToken("b".repeat(43))).toBe(false);expect(mocks.verifyUser).not.toHaveBeenCalled()});
 it("verifies exactly the token owner and consumes the token once",async()=>{expect(await verifyEmailToken("c".repeat(43))).toBe(true);expect(mocks.verifyUser).toHaveBeenCalledWith(expect.objectContaining({where:{id:"admin-id",role:"COMPANY_ADMIN",emailVerifiedAt:null}}));expect(mocks.consume).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"token-id",userId:"admin-id",usedAt:null})}))});
 it("fails safely and does not consume on role or data mismatch",async()=>{mocks.verifyUser.mockResolvedValue({count:0});expect(await verifyEmailToken("d".repeat(43))).toBe(false);expect(mocks.consume).not.toHaveBeenCalled()});
 it("fails safely when another request wins token consumption",async()=>{mocks.consume.mockResolvedValue({count:0});expect(await verifyEmailToken("e".repeat(43))).toBe(false)});
 it("serializes concurrent successful replacements for the same user",async()=>{const deliver=vi.fn().mockResolvedValue(undefined);await Promise.all([issueEmailVerification("admin-id","admin@example.com",deliver),issueEmailVerification("admin-id","admin@example.com",deliver)]);expect(mocks.execute).toHaveBeenCalledTimes(2);expect(mocks.create).toHaveBeenCalledTimes(2)});
});
