import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { salesHeaderCapabilities, salesHeaderPresentation } from "./sales-header-policy";
import { resolveWorkspaceAccess, type WorkspacePrincipal } from "./workspace-policy";
const actor=(salesRole:WorkspacePrincipal["salesRole"],managerType:WorkspacePrincipal["managerType"]=null,overrides:Partial<WorkspacePrincipal>={}):WorkspacePrincipal=>({companyId:"company",role:salesRole==="PRIMARY_ADMIN"?"COMPANY_ADMIN":salesRole==="ADMIN"?"FIELD_ADMIN":salesRole==="MANAGER"?"MANAGER":"SALES",isActive:true,salesRole,accountRole:null,salesAccessActive:true,accountAccessActive:false,managerType,...overrides} as WorkspacePrincipal);
const none={canManageEmployees:false,canManageBilling:false,canManageSettings:false};
describe("Sales workspace header authorization",()=>{
 it("gives Primary Admin its permission-derived navigation",()=>{expect(salesHeaderPresentation("PRIMARY_ADMIN",null)).toEqual({kind:"ADMIN",label:"Primary Admin"});expect(salesHeaderCapabilities(actor("PRIMARY_ADMIN"),"SALESPUNCH360")).toEqual({canManageEmployees:true,canManageBilling:true,canManageSettings:true})});
 it("labels Additional Admin without Primary-only navigation",()=>{expect(salesHeaderPresentation("ADMIN",null)).toEqual({kind:"ADMIN",label:"Additional Admin"});expect(salesHeaderCapabilities(actor("ADMIN"),"SALESPUNCH360")).toEqual(none)});
 it("keeps a dual-role Additional Admin switch independent from Sales navigation",()=>{const dual=actor("ADMIN",null,{accountRole:"ACCOUNTANT",accountAccessActive:true});expect(resolveWorkspaceAccess(dual,"SALESPUNCH360_PLUS").canSwitchWorkspace).toBe(true);expect(salesHeaderCapabilities(dual,"SALESPUNCH360_PLUS")).toEqual(none)});
 it("rejects a stale Account role in the Sales-only edition",()=>{const stale=actor("ADMIN",null,{accountRole:"ACCOUNT_ADMIN",accountAccessActive:true});expect(resolveWorkspaceAccess(stale,"SALESPUNCH360").canSwitchWorkspace).toBe(false);expect(salesHeaderCapabilities(stale,"SALESPUNCH360")).toEqual(none)});
 it.each([["MANAGER","FIELD_MANAGER","Sales Manager"],["MANAGER","MANAGER_ONLY","Office Manager"],["SALES",null,"Sales"]] as const)("keeps %s navigation permission-scoped",(salesRole,managerType,label)=>{expect(salesHeaderPresentation(salesRole,managerType)?.label).toBe(label);expect(salesHeaderCapabilities(actor(salesRole,managerType),"SALESPUNCH360")).toEqual(none)});
 it("wires each protected link to an explicit capability and keeps switching separate",()=>{const header=readFileSync("src/components/workspace/workspace-header.tsx","utf8"),layout=readFileSync("src/app/workspace/layout.tsx","utf8");for(const capability of ["canManageEmployees","canManageBilling","canManageSettings"])expect(header).toContain(`${capability}?[`);expect(layout).toContain("salesHeaderCapabilities");expect(header).toContain("canSwitchWorkspace&&")});
});
