import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({auth:vi.fn(),leadList:vi.fn(),leadGet:vi.fn(),leadFromVisit:vi.fn(),leadTransition:vi.fn(),followUp:vi.fn(),report:vi.fn(),reportActor:vi.fn(),targetList:vi.fn(),targetCreate:vi.fn(),targetEdit:vi.fn(),log:vi.fn()}));
vi.mock("@/lib/logging",()=>({logEvent:mocks.log}));
vi.mock("@/lib/mobile/auth",()=>({authenticateMobileToken:mocks.auth}));
vi.mock("@/lib/mobile/leads",()=>({mobileLeads:mocks.leadList,mobileLead:mocks.leadGet,mobileLeadFromVisit:mocks.leadFromVisit,mobileTransitionLead:mocks.leadTransition,mobileFollowUp:mocks.followUp}));
vi.mock("@/lib/mobile/reports",()=>({mobileReport:mocks.report}));
vi.mock("@/lib/mobile/report-actor",()=>({mobileReportActor:mocks.reportActor}));
vi.mock("@/lib/targets/service",()=>({listTargetsForActor:mocks.targetList,createTargetForActor:mocks.targetCreate,editTargetForActor:mocks.targetEdit}));
import{GET as leadsGet,POST as leadsPost}from"./leads/route";import{GET as reportsGet}from"./reports/route";import{GET as targetsGet,POST as targetsPost,PATCH as targetsPatch}from"./targets/route";
const secret="postgresql://user:password@private-db-host/database SQL failure /private/storage/key token=secret",headers={authorization:`Bearer ${"a".repeat(40)}`,"content-type":"application/json"};
const get=(query="")=>new Request(`http://localhost/api/v1/mobile/test${query}`,{headers});const request=(method:string,body:unknown)=>new Request("http://localhost/api/v1/mobile/test",{method,headers,body:JSON.stringify(body)});
async function safe(response:Response){const body=await response.json(),serialized=JSON.stringify(body),logs=JSON.stringify(mocks.log.mock.calls);expect(response.status).toBe(500);expect(body).toEqual({error:"SERVER_ERROR",referenceId:expect.stringMatching(/^[0-9a-f-]{36}$/)});for(const value of ["postgresql://","password","private-db-host","/private/storage","token=secret","SQL failure",secret]){expect(serialized).not.toContain(value);expect(logs).not.toContain(value)}}
describe("remaining mobile route unexpected failures",()=>{beforeEach(()=>{vi.clearAllMocks();mocks.auth.mockResolvedValue({});mocks.reportActor.mockReturnValue({});});it("uses safe 500 responses for both lead operations",async()=>{mocks.leadList.mockRejectedValueOnce(new Error(secret));await safe(await leadsGet(get()));mocks.leadTransition.mockRejectedValueOnce(new Error(secret));await safe(await leadsPost(request("POST",{action:"TRANSITION"})))});it("uses a safe 500 response for reports",async()=>{mocks.report.mockRejectedValueOnce(new Error(secret));await safe(await reportsGet(get("?type=attendance")))});it("uses safe 500 responses for every target operation",async()=>{mocks.targetList.mockRejectedValueOnce(new Error(secret));await safe(await targetsGet(get()));mocks.targetCreate.mockRejectedValueOnce(new Error(secret));await safe(await targetsPost(request("POST",{})));mocks.targetEdit.mockRejectedValueOnce(new Error(secret));await safe(await targetsPatch(request("PATCH",{})))})});
