package com.salespunch360.mobile.ui.account.expense
import android.provider.OpenableColumns;import android.content.Intent;import android.net.Uri;import java.io.ByteArrayOutputStream;import java.io.File;import androidx.core.content.FileProvider;import androidx.activity.compose.rememberLauncherForActivityResult;import androidx.activity.result.contract.ActivityResultContracts;import androidx.compose.foundation.clickable;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.lazy.*;import androidx.compose.material.icons.Icons;import androidx.compose.material.icons.filled.*;import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.Modifier;import androidx.compose.ui.platform.LocalContext;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.unit.dp;import androidx.lifecycle.compose.collectAsStateWithLifecycle;import androidx.lifecycle.viewmodel.compose.viewModel;import com.salespunch360.mobile.AccountExpenseViewModel;import com.salespunch360.mobile.account.*;import kotlinx.coroutines.Dispatchers;import kotlinx.coroutines.launch;import kotlinx.coroutines.withContext;import kotlinx.serialization.json.*
private const val MAX_EXPENSE_ATTACHMENT_BYTES=10L*1024L*1024L
private suspend fun readExpenseAttachment(context:android.content.Context,uri:Uri):Triple<String,String,ByteArray> = withContext(Dispatchers.IO){var name="attachment";var declared:Long?=null;context.contentResolver.query(uri,arrayOf(OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE),null,null,null)?.use{c->if(c.moveToFirst()){name=c.getString(0)?:name;declared=c.getLong(1).takeIf{it>=0}}};if(declared!=null&&declared!!>MAX_EXPENSE_ATTACHMENT_BYTES)throw IllegalArgumentException("Attachment is larger than 10 MB.");val input=context.contentResolver.openInputStream(uri)?:throw IllegalArgumentException("Attachment could not be opened.");val out=ByteArrayOutputStream(if(declared!=null)minOf(declared!!,MAX_EXPENSE_ATTACHMENT_BYTES).toInt()else 32*1024);input.use{stream->val buffer=ByteArray(32*1024);var total=0L;while(true){val count=stream.read(buffer);if(count<0)break;total+=count;if(total>MAX_EXPENSE_ATTACHMENT_BYTES)throw IllegalArgumentException("Attachment is larger than 10 MB.");out.write(buffer,0,count)};if(total==0L)throw IllegalArgumentException("Attachment is empty.")};Triple(name,context.contentResolver.getType(uri)?:"application/pdf",out.toByteArray())}
@Composable fun ExpenseScreen(padding:PaddingValues,vm:AccountExpenseViewModel=viewModel()){val s=vm.state.collectAsStateWithLifecycle().value;val context=LocalContext.current;var fileError by remember{mutableStateOf<String?>(null)};LaunchedEffect(s.downloaded){s.downloaded?.let{d->try{val file=withContext(Dispatchers.IO){com.salespunch360.mobile.data.safeAttachmentFile(context.cacheDir,d.first).also{target->target.outputStream().buffered().use{it.write(d.second)}}};val uri=FileProvider.getUriForFile(context,"${context.packageName}.files",file);context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType("application/octet-stream").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION),"Share attachment"))}catch(e:Exception){fileError=e.message?:"Attachment could not be prepared."}finally{vm.consumedDownload()}}};Column(Modifier.fillMaxSize().padding(padding).padding(horizontal=16.dp)){Row{OutlinedTextField(s.query,vm::search,label={Text("Search expense or reference")},modifier=Modifier.weight(1f));IconButton(vm::refresh){Icon(Icons.Default.Refresh,"Refresh")};FilledIconButton(vm::create,enabled=!s.saving&&s.options["canCreateExpense"]?.jsonPrimitive?.booleanOrNull==true){Icon(Icons.Default.Add,"New expense")}};LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf<String?>(null,"DRAFT","PENDING_APPROVAL","APPROVED","POSTED","REJECTED","REVERSED")){x->FilterChip(s.status==x,{vm.filter(x)},{Text(x?.replace('_',' ')?:"All")})}};if(s.loading)LinearProgressIndicator(Modifier.fillMaxWidth());s.message?.let{Text(it)};fileError?.let{Text(it,color=MaterialTheme.colorScheme.error)};s.error?.let{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.errorContainer)){Row(Modifier.padding(12.dp)){Text(it,Modifier.weight(1f));TextButton(vm::refresh){Text("Retry")}}}};if(!s.loading&&s.rows.isEmpty())Text("No expenses match these filters.",Modifier.padding(24.dp));LazyColumn{items(s.rows,key={it.str("id")}){x->ListItem(headlineContent={Text(x.str("transactionNumber"),fontWeight=FontWeight.Bold)},supportingContent={Text("${x.str("transactionDate").take(10)} · ${x.str("type").replace('_',' ')}")},trailingContent={Column{Text("₹${x.str("totalAmount")}");Text(x.str("status"))}},modifier=Modifier.clickable{vm.open(x.str("id"))})}}};s.editing?.let{key(s.requestKey){ExpenseEditor(it,s.options,s.saving,s.error,s.newCategoryId,vm::dismiss,{p,n->vm.save(p,n)},{vm.showCategory(true)})}};s.detail?.let{ExpenseDetail(it,s.saving,s.error,vm::dismiss,vm::edit,vm::action,vm::attach,vm::download,vm::recurring)};if(s.categoryOpen)CategoryEditor(buildJsonObject{},s.options.array("ledgers").map{it.jsonObject},s.saving,s.error,{vm.showCategory(false)},vm::saveCategory)}
@Composable private fun ExpenseEditor(existing:JsonObject,options:JsonObject,saving:Boolean,error:String?,newCategoryId:String?,onClose:()->Unit,onSave:(JsonObject,Boolean)->Unit,addCategory:()->Unit){
 var branch by remember{mutableStateOf(existing.str("branchId").ifBlank{options.array("branches").firstOrNull()?.jsonObject?.str("id").orEmpty()})};var category by remember{mutableStateOf(existing.str("categoryId"))};var account by remember{mutableStateOf(existing.str("moneyAccountId"))};var project by remember{mutableStateOf(existing.str("projectId"))};val allowed=(options["allowedTypes"] as? JsonArray)?.map{it.jsonPrimitive.content}.orEmpty();var type by remember{mutableStateOf(existing.str("type").ifBlank{allowed.firstOrNull()?:"OFFICE_EXPENSE"})};var amount by remember{mutableStateOf(existing.str("taxableAmount"))};var tax by remember{mutableStateOf(existing.str("taxRate").ifBlank{"0"})};var cess by remember{mutableStateOf(existing.str("cessRate").ifBlank{"0"})};var mode by remember{mutableStateOf(existing.str("taxMode").ifBlank{options.str("defaultTaxMode").ifBlank{"EXCLUSIVE"}})};var credit by remember{mutableStateOf(existing.str("taxCreditTreatment").ifBlank{"ELIGIBLE"})};var supply by remember{mutableStateOf(existing.str("stateOfSupplyCode"))};var gst by remember{mutableStateOf((tax.toDoubleOrNull()?:0.0)>0||(cess.toDoubleOrNull()?:0.0)>0)};var date by remember{mutableStateOf(existing.str("transactionDate").take(10).ifBlank{java.time.LocalDate.now().toString()})};var reference by remember{mutableStateOf(existing.str("reference"))};var notes by remember{mutableStateOf(existing.str("notes"))};var charges by remember{mutableStateOf(existing.str("additionalCharges").ifBlank{"0"})};var round by remember{mutableStateOf(existing["roundOffEnabled"]?.jsonPrimitive?.booleanOrNull==true)};var lines by remember{mutableStateOf(existing.array("billedItems").map{val l=it.jsonObject;ExpenseLine(l.str("name"),l.str("quantity"),l.str("rate"))})};var confirmClose by remember{mutableStateOf(false)}
 LaunchedEffect(newCategoryId){newCategoryId?.let{category=it}}
 val income=type=="OTHER_INCOME";val categories=options.array("categories").filter{val sc=it.jsonObject.str("scope");sc=="BOTH"||sc==(if(income)"INCOME"else "EXPENSE")};val accounts=options.array("moneyAccounts").filter{it.jsonObject.str("branchId").let{b->b.isBlank()||b==branch}};val projects=options.array("projects").filter{it.jsonObject.str("branchId")==branch};val preview=expensePreview(amount,lines,charges,if(gst&&!income)tax else "0",if(gst&&!income)cess else "0",mode,round,options["compositionEnabled"]?.jsonPrimitive?.booleanOrNull==true)
 fun save(saveNew:Boolean){onSave(buildJsonObject{put("branchId",branch);put("categoryId",category);put("type",type);put("projectId",project);put("moneyAccountId",account);put("transactionDate",date);put("taxableAmount",if(lines.isEmpty())amount else "0");put("billedItems",JsonArray(lines.map{l->buildJsonObject{put("name",l.name);put("quantity",l.quantity);put("rate",l.rate)}}));put("additionalCharges",charges);put("roundOffEnabled",round);put("taxRate",if(gst&&!income)tax else "0");put("cessRate",if(gst&&!income)cess else "0");put("taxMode",mode);put("taxCreditTreatment",credit);put("stateOfSupplyCode",supply);put("reference",reference);put("notes",notes)},saveNew)}
 AlertDialog(onDismissRequest={if(!saving)confirmClose=true},title={Text(if(existing.containsKey("id"))"Edit draft expense" else "New expense / income")},text={LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){
 item{Text("Firm: ${options.str("companyName")}");val series=options.array("numbering").firstOrNull{it.str("branchId")==branch};val number=if(existing.containsKey("id"))existing.str("transactionNumber")else if(series!=null)series.str("prefix")+series.str("nextSequence").padStart(series["padding"]?.jsonPrimitive?.intOrNull?:6,'0')+series.str("suffix")else (if(income)"OI-"else "EXP-")+"000001";Text("Number ${if(existing.containsKey("id"))number else "$number (preview; assigned by server when saved)"}")}
 item{SelectText("Transaction type",type,allowed){type=it;category="";project="";if(it=="OTHER_INCOME"){gst=false;tax="0";cess="0"}}}
 item{Select("Branch",branch,options.array("branches"),{branch=it;account="";project=""})}
 item{Select("Category",category,categories,{category=it})}
 if(options["canCreateCategory"]?.jsonPrimitive?.booleanOrNull==true)item{TextButton(addCategory,enabled=!saving){Text("Add expense / income category")}}
 item{Select("Cash / bank account",account,accounts,{account=it},if(type=="REIMBURSEMENT")"Reimbursement payable"else "Select account")}
 item{Select("Project",project,projects,{project=it},"No project")}
 item{OutlinedTextField(date,{date=it},label={Text("Transaction date (YYYY-MM-DD)")})}
 item{Text("Billed items",fontWeight=FontWeight.Bold)}
 items(lines.size){i->val l=lines[i];Column{OutlinedTextField(l.name,{v->lines=lines.mapIndexed{j,x->if(i==j)x.copy(name=v)else x}},label={Text("Item ${i+1} name")});OutlinedTextField(l.quantity,{v->lines=lines.mapIndexed{j,x->if(i==j)x.copy(quantity=v)else x}},label={Text("Item ${i+1} quantity")});OutlinedTextField(l.rate,{v->lines=lines.mapIndexed{j,x->if(i==j)x.copy(rate=v)else x}},label={Text("Item ${i+1} rate")});TextButton({lines=lines.filterIndexed{j,_->j!=i}},enabled=!saving){Text("Remove item ${i+1}")}}}
 item{TextButton({lines=lines+ExpenseLine("","1","0")},enabled=!saving&&lines.size<200){Text("Add billed item")}}
 if(lines.isEmpty())item{OutlinedTextField(amount,{amount=it},label={Text("Entered amount")})}
 item{OutlinedTextField(charges,{charges=it},label={Text("Additional taxable charges")})}
 item{Row{Checkbox(round,{round=it});Text("Round total to nearest rupee")}}
 item{Row{Switch(gst&&!income,{gst=it;if(!it){tax="0";cess="0"}},enabled=!income);Text("GST / tax")}}
 if(income)item{Text("Other Income is non-taxable. GST and CESS are zero.")}
 if(gst&&!income){item{OutlinedTextField(tax,{tax=it},label={Text("GST rate (%)")})};item{OutlinedTextField(cess,{cess=it},label={Text("CESS rate (%)")})};item{SelectText("Tax mode",mode,listOf("EXCLUSIVE","INCLUSIVE")){mode=it}};item{SelectText("Input tax credit",credit,listOf("ELIGIBLE","INELIGIBLE","BLOCKED")){credit=it}};item{OutlinedTextField(supply,{supply=it},label={Text("State of supply code")})}}
 item{Text(preview?.let{"Taxable ₹${it.taxable} · Tax ₹${it.tax} · Round off ₹${it.rounding} · Total ₹${it.total}"}?:"Complete positive amounts to preview totals.")}
 item{OutlinedTextField(reference,{reference=it},label={Text("Reference")})};item{OutlinedTextField(notes,{notes=it},label={Text("Notes")})};error?.let{item{Text(it,color=MaterialTheme.colorScheme.error)}}
 }},confirmButton={Column{Button({save(false)},enabled=!saving&&branch.isNotBlank()&&category.isNotBlank()&&preview!=null&&(type=="REIMBURSEMENT"||account.isNotBlank())&&(type!="PROJECT_EXPENSE"||project.isNotBlank())){Text(if(saving)"Saving…"else "Save draft")};if(!existing.containsKey("id"))TextButton({save(true)},enabled=!saving&&preview!=null&&category.isNotBlank()&&(type=="REIMBURSEMENT"||account.isNotBlank())&&(type!="PROJECT_EXPENSE"||project.isNotBlank())){Text("Save & New")}}},dismissButton={TextButton({confirmClose=true},enabled=!saving){Text("Cancel")}})
 if(confirmClose)AlertDialog(onDismissRequest={confirmClose=false},title={Text("Discard unsaved changes?")},confirmButton={TextButton(onClose){Text("Discard")}},dismissButton={TextButton({confirmClose=false}){Text("Keep editing")}})
}
@OptIn(ExperimentalLayoutApi::class) @Composable private fun ExpenseDetail(x:JsonObject,saving:Boolean,error:String?,onClose:()->Unit,onEdit:(JsonObject)->Unit,onAction:(String,String,String?,String?,String?)->Unit,onAttach:(String,String,String,ByteArray)->Unit,onDownload:(String,String)->Unit,onRecurring:(JsonObject)->Unit){
 val context=LocalContext.current;val scope=rememberCoroutineScope();val id=x.str("id");val cap=x["capabilities"] as? JsonObject;fun can(k:String)=cap?.get(k)?.jsonPrimitive?.booleanOrNull==true
 var reject by remember{mutableStateOf(false)};var reverse by remember{mutableStateOf(false)};var schedule by remember{mutableStateOf(false)};var fileBusy by remember{mutableStateOf(false)};var fileError by remember{mutableStateOf<String?>(null)}
 val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri->if(uri!=null&&!fileBusy){fileBusy=true;fileError=null;scope.launch{try{val(name,mime,bytes)=readExpenseAttachment(context,uri);onAttach(id,name,mime,bytes)}catch(e:Exception){fileError=e.message?:"Attachment could not be read."}finally{fileBusy=false}}}}
 fun related(k:String)= (x[k] as? JsonObject)?.str("name").orEmpty().ifBlank{"Not recorded"}
 fun person(userId:String)=x.array("people").map{it.jsonObject}.firstOrNull{it.str("id")==userId}?.str("name")?:"Historical user"
 AlertDialog(onDismissRequest={if(!saving)onClose()},title={Text(x.str("transactionNumber"))},text={LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){
 item{Text("${x.str("type").replace('_',' ')} · ${x.str("status")}",fontWeight=FontWeight.Bold)}
 item{Text("Date ${x.str("transactionDate").take(10)} · Branch ${related("branch")}")}
 item{Text("Category ${related("category")} · Project ${related("project")}")}
 item{Text("Cash / bank ${related("moneyAccount")}")}
 item{Text("Taxable ₹${x.str("taxableAmount")} · Tax ₹${x.str("taxAmount")}")}
 item{Text("CGST ${x.str("cgstAmount")} · SGST ${x.str("sgstAmount")} · IGST ${x.str("igstAmount")} · CESS ${x.str("cessAmount")}")}
 item{Text("${x.str("taxMode")} · ITC ${x.str("taxCreditTreatment")} · Supply ${x.str("stateOfSupplyCode")}")}
 items(x.array("billedItems")){l->val v=l.jsonObject;Text("${v.str("name")} · ${v.str("quantity")} × ₹${v.str("rate")}")}
 item{Text("Charges ₹${x.str("additionalCharges")} · Round off ₹${x.str("roundOffAmount")}")}
 item{Text("Total ₹${x.str("totalAmount")}",style=MaterialTheme.typography.titleLarge)}
 item{Text("Reference ${x.str("reference")}");Text("Notes ${x.str("notes")}");Text("Created by ${person(x.str("createdById"))}");if(x.str("approvedById").isNotBlank())Text("Approved by ${person(x.str("approvedById"))} · ${x.str("approvedAt")}")}
 error?.let{message->item{Text(message,color=MaterialTheme.colorScheme.error)}};fileError?.let{message->item{Text(message,color=MaterialTheme.colorScheme.error)}}
 item{FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){if(can("edit"))Button({onEdit(x)},enabled=!saving){Text("Edit draft")};if(can("submit"))Button({onAction(id,"TRANSITION","PENDING_APPROVAL",null,null)},enabled=!saving){Text("Submit")};if(can("cancel"))OutlinedButton({onAction(id,"TRANSITION","CANCELLED",null,null)},enabled=!saving){Text("Cancel expense")};if(can("approve"))Button({onAction(id,"TRANSITION","APPROVED",null,null)},enabled=!saving){Text("Approve")};if(can("reject"))OutlinedButton({reject=true},enabled=!saving){Text("Reject")};if(can("post"))Button({onAction(id,"POST",null,null,null)},enabled=!saving){Text("Post")};if(can("reverse"))OutlinedButton({reverse=true},enabled=!saving){Text("Reverse")}}}
 if(can("attach"))item{OutlinedButton({picker.launch("*/*")},enabled=!saving&&!fileBusy){Text(if(fileBusy)"Reading attachment…"else "Attach PDF/image")}}
 items(x.array("attachments")){a->val o=a.jsonObject;TextButton({onDownload(o.str("id"),o.str("displayName"))},enabled=!saving){Text("Download / share ${o.str("displayName")}")}}
 items(x.array("history")){h->val o=h.jsonObject;val reason=(o["metadata"] as? JsonObject)?.str("reason").orEmpty();Text("${o.str("eventType").replace('_',' ')} · ${person(o.str("actorUserId"))} · ${o.str("createdAt")}${if(reason.isBlank())""else " · $reason"}",style=MaterialTheme.typography.bodySmall)}
 if(can("attach")&&x.str("type")in listOf("OFFICE_EXPENSE","PROJECT_EXPENSE"))item{OutlinedButton({schedule=true},enabled=!saving){Text("Create separate future expense schedule")};Text("Scheduling is separate from this saved transaction; it does not post another expense now.")}
 }},confirmButton={TextButton(onClose,enabled=!saving){Text("Close")}})
 if(reject)ReasonDialog("Reject expense",saving,error,false,{reject=false}){reason,_->onAction(id,"TRANSITION","REJECTED",reason,null)}
 if(reverse)ReasonDialog("Reverse posted expense",saving,error,true,{reverse=false}){reason,date->onAction(id,"REVERSE",null,reason,date)}
 if(schedule)ScheduleDialog(x,saving,error,{schedule=false},onRecurring)
 LaunchedEffect(x.str("status")){reject=false;reverse=false}
}
@Composable private fun ReasonDialog(title:String,saving:Boolean,error:String?,withDate:Boolean,onClose:()->Unit,onConfirm:(String,String?)->Unit){var reason by remember{mutableStateOf("")};var date by remember{mutableStateOf(java.time.LocalDate.now().toString())};AlertDialog(onDismissRequest={if(!saving)onClose()},title={Text(title)},text={Column{OutlinedTextField(reason,{if(it.length<=500)reason=it},label={Text("Reason")});if(withDate)OutlinedTextField(date,{date=it},label={Text("Reversal date (YYYY-MM-DD)")});error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button(enabled=!saving&&reason.isNotBlank()&&(!withDate||runCatching{java.time.LocalDate.parse(date)}.isSuccess),onClick={onConfirm(reason,if(withDate)date else null)}){Text(if(saving)"Saving…"else "Confirm")}},dismissButton={TextButton(onClose,enabled=!saving){Text("Cancel")}})}
@Composable private fun ScheduleDialog(x:JsonObject,saving:Boolean,error:String?,close:()->Unit,save:(JsonObject)->Unit){var frequency by remember{mutableStateOf("MONTHLY")};var due by remember{mutableStateOf(java.time.LocalDate.now().plusMonths(1).toString())};var amount by remember{mutableStateOf(x.str("taxableAmount"))};AlertDialog(onDismissRequest={if(!saving)close()},title={Text("Separate future expense schedule")},text={Column{Text("This schedule creates future expense drafts. It does not repeat Other Income or copy tax/payment details.");SelectText("Frequency",frequency,listOf("WEEKLY","MONTHLY","QUARTERLY","YEARLY")){frequency=it};OutlinedTextField(due,{due=it},label={Text("First due date (YYYY-MM-DD)")});OutlinedTextField(amount,{amount=it},label={Text("Future expense base amount")});error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={Button(enabled=!saving&&amount.toBigDecimalOrNull()?.let{it.signum()>0}==true&&runCatching{java.time.LocalDate.parse(due)}.isSuccess,onClick={save(buildJsonObject{put("branchId",x.str("branchId"));if(x.str("projectId").isNotBlank())put("projectId",x.str("projectId"));put("categoryId",x.str("categoryId"));put("frequency",frequency);put("nextDueDate",due);put("amount",amount)})}){Text(if(saving)"Saving…"else "Save schedule")}},dismissButton={TextButton(close,enabled=!saving){Text("Close")}})}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun Select(label:String,value:String,values:List<JsonElement>,onValue:(String)->Unit,empty:String="Select"){var open by remember{mutableStateOf(false)};val selected=values.map{it.jsonObject}.firstOrNull{it.str("id")==value};ExposedDropdownMenuBox(open,{open=it}){OutlinedTextField(selected?.str("name").orEmpty(),{},readOnly=true,label={Text(label)},trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(open)},modifier=Modifier.menuAnchor());ExposedDropdownMenu(open,{open=false}){DropdownMenuItem({Text(empty)},{onValue("");open=false});values.forEach{e->val o=e.jsonObject;DropdownMenuItem({Text(o.str("name"))},{onValue(o.str("id"));open=false})}}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun SelectText(label:String,value:String,values:List<String>,onValue:(String)->Unit){var open by remember{mutableStateOf(false)};ExposedDropdownMenuBox(open,{open=it}){OutlinedTextField(value.replace('_',' '),{},readOnly=true,label={Text(label)},modifier=Modifier.menuAnchor());ExposedDropdownMenu(open,{open=false}){values.forEach{v->DropdownMenuItem({Text(v.replace('_',' '))},{onValue(v);open=false})}}}}
