import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";import{join}from"node:path";
const root=process.cwd(),read=(p:string)=>readFileSync(join(root,p),"utf8");
describe("Lead and Telecalling UI contract",()=>{
 it("keeps Lead list actions compact and All Leads continuous",()=>{const s=read("src/app/workspace/leads/page.tsx");expect(s).toContain("lead-card-title-row");expect(s).toContain("LeadCallAction");expect(s).toContain("visibleTitle");expect(s).toContain("leads.map");expect(s).not.toContain("LeadStage.entries.filter");});
 it("keeps Call result out of Lead detail while retaining Call History",()=>{const detail=read("src/app/workspace/leads/[id]/page.tsx"),call=read("src/app/workspace/leads/lead-call-action.tsx");expect(detail).toContain("Call History");expect(detail).not.toContain("CallResultForm");expect(detail).not.toContain("<h2>Call</h2>");expect(call).toContain("Update call result");expect(call).toContain("showDialer={false}");});
 it("keeps duplicate Add Follow-up out of Lead detail",()=>{const s=read("src/app/workspace/leads/[id]/page.tsx");expect(s).toContain("lead-action-edit");expect(s).toContain("lead-action-delete");expect(s).toContain("Follow-up History");expect(s).not.toContain("Add Follow-up");});
 it("does not dump all company leads on Telecalling load",()=>{const s=read("src/app/workspace/telecalling/page.tsx");expect(s).toContain("search?listTelecallingLeads(search):Promise.resolve([])");expect(s).toContain("splitCallbackQueue");expect(s).toContain("queues.map");expect(s).toContain("Find a Lead");});
 it("supports paid Telecaller Call follow-up assignment",()=>{const form=read("src/app/workspace/leads/follow-up-form.tsx"),service=read("src/lib/follow-up-tasks/telecaller-assignment.ts");expect(form).toContain("Assign call to");expect(form).toContain("assignedUserId");expect(service).toContain("assertActiveTelecallerEntitlement");expect(service).toContain("follow_up_tasks");});
 it("matches the Android Lead and Telecalling flow",()=>{const leads=read("android/app/src/main/java/com/salespunch360/mobile/ui/LeadsScreen.kt"),tele=read("android/app/src/main/java/com/salespunch360/mobile/ui/TelecallingScreen.kt");expect(leads).toContain("items(visible");expect(leads).toContain("state.telecallers");expect(leads).toContain("Call History");expect(leads).not.toContain("Button(call,");expect(leads).not.toContain("OutlinedButton(followUp");expect(tele).toContain("listOf(\"Overdue\",\"Today\",\"Upcoming\")");expect(tele).toContain("vm::search");});
});
