import Link from "next/link";
import { notFound } from "next/navigation";
import { WorkspacePageHeader } from "@/components/workspace/workspace-page-header";
import { accountOverview } from "@/lib/account/service";
import { saveAccountMaster } from "@/app/actions/account-masters";

const titles:Record<string,string>={"financial-years":"Financial year & currency",customers:"Account customers",vendors:"Vendors",units:"Units",categories:"Categories",products:"Products",services:"Services","work-categories":"Work categories","work-packages":"Work / packages"};
const input=(name:string,label:string,type="text",required=false)=><label>{label}<input name={name} type={type} required={required}/></label>;
export default async function MasterPage({params}:{params:Promise<{master:string}>}){const {master}=await params;if(!titles[master])notFound();const d=await accountOverview();let fields:React.ReactNode;
 if(master==="financial-years")fields=<>{input("name","Label","text",true)}{input("startDate","Start date","date",true)}{input("endDate","End date","date",true)}<label><input name="isCurrent" type="checkbox" value="true"/> Current year</label></>;
 else if(master==="units")fields=<>{input("name","Name","text",true)}{input("symbol","Symbol","text",true)}</>;
 else if(master==="categories")fields=<>{input("name","Name","text",true)}{input("description","Description")}<label>Scope<select name="scope"><option value="BOTH">Product & service</option><option value="PRODUCT">Product</option><option value="SERVICE">Service</option></select></label></>;
 else if(master==="work-categories")fields=<>{input("name","Name","text",true)}{input("description","Description")}</>;
 else if(master==="customers"||master==="vendors")fields=<>{input("name","Business name","text",true)}{input("contactPerson","Contact person")}{input("phone","Phone","tel")}{input("email","Email","email")}{input("address","Billing / address")}{master==="customers"&&input("shippingAddress","Shipping / site address")}{input("gstin","GSTIN")}{input("stateCode","GST state code")}<label>GST registration<select name="gstRegistrationType"><option>UNREGISTERED</option><option>REGULAR</option><option>COMPOSITION</option><option>SEZ</option></select></label>{input("pan","PAN")}{input("notes","Notes")}</>;
 else {const work=master==="work-packages";fields=<>{input("name","Name","text",true)}{input("code","Code / SKU")}{work&&<label>Work category<select name="workCategoryId" required><option value="">Select</option>{d.workCategories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}{!work&&<label>Category<select name="categoryId"><option value="">None</option>{d.accountCategories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label>Unit<select name="unitId"><option value="">None</option>{d.accountUnits.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>{input("description","Description / specification")}{input("sellingRate","Selling rate","number")}{input("cost","Estimated / cost rate","number")}{!work&&input("taxRate","GST %","number")}{!work&&input("hsnSacCode",master==="products"?"HSN":"SAC")}</>}
 const rows=master==="customers"?d.customers:master==="vendors"?d.vendors:master==="units"?d.accountUnits:master==="categories"?d.accountCategories:master==="products"?d.accountProducts:master==="services"?d.accountServices:master==="work-categories"?d.workCategories:master==="work-packages"?d.workPackages:d.financialYears;
 return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title={titles[master]} backHref="/workspace/account"/><form action={saveAccountMaster} className="account-master-form"><input type="hidden" name="type" value={master}/>{fields}<button className="primary-button">Add</button></form>{master==="financial-years"&&<form action={saveAccountMaster} className="account-master-form"><input type="hidden" name="type" value="currency"/><label>Base currency<input name="baseCurrency" defaultValue={d.accountSettings?.baseCurrency??"INR"} maxLength={3}/></label><button>Save currency</button></form>}<div className="customer-grid">{rows.map(x=><article key={x.id}><h2>{x.name}</h2>{"symbol" in x&&<p>{String(x.symbol)}</p>}{"code" in x&&<p>{String(x.code??"")}</p>}{"isCurrent" in x&&x.isCurrent&&<strong>Current</strong>}</article>)}</div><Link href="/workspace/account">Back to Account</Link></section></main>}
