import type { LeadStage, ManagerType, SalesRole } from "@prisma/client";
export class LeadError extends Error { constructor(public code:"NOT_FOUND"|"INVALID_ASSIGNMENT"|"STALE"|"TERMINAL"|"INVALID_REFERENCE"|"ACTIVE_FOLLOW_UP"){super(code)} }
type Actor={id:string;salesRole:SalesRole;managerType?:ManagerType|null};
type Assignee={id:string;salesRole:SalesRole|null;managerType?:ManagerType|null;isActive:boolean;salesAccessActive?:boolean;managerId:string|null};
export function canAssign(actor:Actor,assignee:Assignee){const actorRole=actor.salesRole,assigneeRole=assignee.salesRole;if(!assignee.isActive||assignee.salesAccessActive===false||(assigneeRole!=="MANAGER"&&assigneeRole!=="SALES"))return false;if(assigneeRole==="MANAGER"&&assignee.managerType==="MANAGER_ONLY")return false;if(actorRole==="PRIMARY_ADMIN"||actorRole==="ADMIN")return true;if(actorRole==="SALES")return assignee.id===actor.id&&assigneeRole==="SALES";return actorRole==="MANAGER"&&((actor.managerType!=="MANAGER_ONLY"&&assignee.id===actor.id&&assigneeRole==="MANAGER")||(assigneeRole==="SALES"&&assignee.managerId===actor.id));}
function assertActorRole(role:SalesRole):SalesRole{if(!["PRIMARY_ADMIN","ADMIN","MANAGER","SALES"].includes(role))throw new LeadError("NOT_FOUND");return role;}
export function visibilityWhere(actor:Actor){const actorRole=assertActorRole(actor.salesRole);if(actorRole==="PRIMARY_ADMIN"||actorRole==="ADMIN")return {};if(actorRole==="MANAGER")return actor.managerType==="MANAGER_ONLY"?{assignedUser:{salesRole:"SALES" as const,managerId:actor.id}}:{OR:[{assignedUserId:actor.id},{assignedUser:{salesRole:"SALES" as const,managerId:actor.id}}]};return {assignedUserId:actor.id};}
export const activeStages:LeadStage[]=["NEW","QUALIFIED","PROPOSAL","NEGOTIATION"];
export type PipelineActor={id:string;companyId:string;salesRole:SalesRole;managerType?:ManagerType|null};
export function pendingVisitWhere(actor:PipelineActor){const actorRole=assertActorRole(actor.salesRole);return {companyId:actor.companyId,visitType:"NEW" as const,leadId:null,OR:[{contactPhone:null},{contactPhone:""}],...(actorRole==="SALES"?{userId:actor.id}:actorRole==="MANAGER"?(actor.managerType==="MANAGER_ONLY"?{user:{salesRole:"SALES" as const,managerId:actor.id}}:{AND:[{OR:[{userId:actor.id},{user:{salesRole:"SALES" as const,managerId:actor.id}}]}]}):{})};}
export function leadVisitCount(lead:{sourceVisitId:string|null;visits:{id:string}[]}){const ids=new Set(lead.visits.map(v=>v.id));if(lead.sourceVisitId)ids.add(lead.sourceVisitId);return ids.size;}
export function transitionKind(_salesRole:SalesRole,from:LeadStage,to:LeadStage){const allowed:Record<LeadStage,LeadStage[]>={NEW:["QUALIFIED"],QUALIFIED:["PROPOSAL"],PROPOSAL:["NEGOTIATION"],NEGOTIATION:["WON","LOST"],WON:[],LOST:[]};if(!allowed[from].includes(to))throw new LeadError("TERMINAL");return to==="WON"?"WON":to==="LOST"?"LOST":"STAGE_CHANGED";}
