import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { assertOperationalWrite } from "@/lib/billing/entitlement";
import { requireRole } from "@/lib/auth/authorization";
import { canAssign, LeadError, transitionKind, visibilityWhere } from "./policy";
import { createLeadFromVisitSchema, createLeadSchema, editLeadSchema, leadFilterSchema, transitionLeadSchema, type CreateLeadInput, type EditLeadInput, type TransitionLeadInput } from "./validation";
export async function leadActor(){const u=await requireRole("COMPANY_ADMIN","MANAGER","SALES");if(!u.companyId)throw new LeadError("NOT_FOUND");return {...u,companyId:u.companyId};}
async function assignee(tx:Prisma.TransactionClient,a:Awaited<ReturnType<typeof leadActor>>,id:string){const v=await tx.user.findFirst({where:{id,companyId:a.companyId},select:{id:true,role:true,isActive:true,managerId:true}});if(!v||!canAssign(a,v))throw new LeadError("INVALID_ASSIGNMENT");return v;}
const value=(v:string|undefined)=>v===undefined?null:new Prisma.Decimal(v);
export async function createLead(raw:CreateLeadInput){return createLeadForActor(await leadActor(),raw);}
export async function createLeadForActor(a:Awaited<ReturnType<typeof leadActor>>,raw:unknown){if(a.role==="SALES")throw new LeadError("NOT_FOUND");await assertOperationalWrite(a.companyId);const d=createLeadSchema.parse(raw);return db.$transaction(async tx=>{await assignee(tx,a,d.assignedUserId);if(d.customerId&&!await tx.customer.findFirst({where:{id:d.customerId,companyId:a.companyId},select:{id:true}}))throw new LeadError("INVALID_REFERENCE");const lead=await tx.lead.create({data:{...d,estimatedValue:value(d.estimatedValue),companyId:a.companyId,createdByUserId:a.id,stage:"NEW"}});await tx.leadActivity.create({data:{companyId:a.companyId,leadId:lead.id,actorUserId:a.id,type:"CREATED",newAssignedUserId:d.assignedUserId,toStage:"NEW"}});return lead;});}
export async function createLeadFromVisit(raw:unknown){return createLeadFromVisitForActor(await leadActor(),raw);}
export async function createLeadFromVisitForActor(a:Awaited<ReturnType<typeof leadActor>>,raw:unknown){await assertOperationalWrite(a.companyId);if(a.role==="COMPANY_ADMIN")throw new LeadError("NOT_FOUND");const d=createLeadFromVisitSchema.parse(raw);return db.$transaction(async tx=>{await assignee(tx,a,d.assignedUserId);const visit=await tx.customerVisit.findFirst({where:{id:d.visitId,companyId:a.companyId,userId:a.id},select:{id:true,customerId:true}});if(!visit)throw new LeadError("NOT_FOUND");const {visitId: omittedVisitId,...fields}=d;void omittedVisitId;const lead=await tx.lead.create({data:{...fields,estimatedValue:value(fields.estimatedValue),companyId:a.companyId,createdByUserId:a.id,customerId:visit.customerId,source:"CUSTOMER_VISIT",sourceVisitId:visit.id,stage:"NEW"}});await tx.leadActivity.create({data:{companyId:a.companyId,leadId:lead.id,actorUserId:a.id,type:"CREATED",newAssignedUserId:d.assignedUserId,toStage:"NEW"}});return lead;});}
export async function editLead(raw:EditLeadInput){return editLeadForActor(await leadActor(),raw);}
export async function editLeadForActor(a:Awaited<ReturnType<typeof leadActor>>,raw:unknown){const d=editLeadSchema.parse(raw);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "leads" WHERE "id"=${d.leadId}::uuid AND "companyId"=${a.companyId}::uuid FOR UPDATE`;const old=await tx.lead.findFirst({where:{id:d.leadId,companyId:a.companyId,...visibilityWhere(a)}});if(!old)throw new LeadError("NOT_FOUND");if(old.version!==d.version)throw new LeadError("STALE");await assignee(tx,a,d.assignedUserId);if(d.customerId&&!await tx.customer.findFirst({where:{id:d.customerId,companyId:a.companyId},select:{id:true}}))throw new LeadError("INVALID_REFERENCE");if(old.sourceVisitId&&d.source!=="CUSTOMER_VISIT")throw new LeadError("INVALID_REFERENCE");const {leadId: omittedLeadId,version: omittedVersion,...fields}=d;void omittedLeadId;void omittedVersion;const changedAssignment=old.assignedUserId!==fields.assignedUserId,changedFollow=old.followUpAt?.getTime()!==fields.followUpAt?.getTime();const updated=await tx.lead.update({where:{id:d.leadId},data:{...fields,estimatedValue:value(fields.estimatedValue),version:{increment:1}}});await tx.leadActivity.create({data:{companyId:a.companyId,leadId:d.leadId,actorUserId:a.id,type:changedAssignment?"ASSIGNED":changedFollow?"FOLLOW_UP_CHANGED":"UPDATED",previousAssignedUserId:changedAssignment?old.assignedUserId:null,newAssignedUserId:changedAssignment?fields.assignedUserId:null}});return updated;});}
export async function transitionLead(raw:TransitionLeadInput){return transitionLeadForActor(await leadActor(),raw);}
export async function transitionLeadForActor(a:Awaited<ReturnType<typeof leadActor>>,raw:unknown){const d=transitionLeadSchema.parse(raw);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "leads" WHERE "id"=${d.leadId}::uuid AND "companyId"=${a.companyId}::uuid FOR UPDATE`;const old=await tx.lead.findFirst({where:{id:d.leadId,companyId:a.companyId,...visibilityWhere(a)}});if(!old)throw new LeadError("NOT_FOUND");if(old.version!==d.version)throw new LeadError("STALE");const kind=transitionKind(a.role,old.stage,d.toStage);const now=new Date();const terminal=d.toStage==="WON"?{wonAt:now,lostAt:null,lostReason:null}:d.toStage==="LOST"?{lostAt:now,wonAt:null,lostReason:d.lostReason!}:{wonAt:null,lostAt:null,lostReason:null};const changed=await tx.lead.updateMany({where:{id:d.leadId,companyId:a.companyId,version:d.version,stage:old.stage},data:{stage:d.toStage,...terminal,version:{increment:1}}});if(changed.count!==1)throw new LeadError("STALE");await tx.leadActivity.create({data:{companyId:a.companyId,leadId:d.leadId,actorUserId:a.id,type:kind,fromStage:old.stage,toStage:d.toStage}});});}
export async function listLeads(raw:unknown={}){return listLeadsForActor(await leadActor(),raw);}
export async function listLeadsForActor(a:Awaited<ReturnType<typeof leadActor>>,raw:unknown={}){const f=leadFilterSchema.parse(raw);const now=new Date(),start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),end=new Date(start.getTime()+86400000);const follow=f.followUp==="overdue"?{lt:start}:f.followUp==="today"?{gte:start,lt:end}:f.followUp==="upcoming"?{gte:end}:undefined;return db.lead.findMany({where:{companyId:a.companyId,...visibilityWhere(a),stage:f.stage,assignedUserId:f.assignedUserId,followUpAt:follow,...(f.q?{OR:[{title:{contains:f.q,mode:"insensitive"}},{companyName:{contains:f.q,mode:"insensitive"}},{customer:{name:{contains:f.q,mode:"insensitive"}}}]}:{})},include:{customer:{select:{name:true}},assignedUser:{select:{id:true,name:true}},_count:{select:{activities:true}}},orderBy:{updatedAt:"desc"},take:200});}
export async function getLead(id:string){return getLeadForActor(await leadActor(),id);}
export async function getLeadForActor(a:Awaited<ReturnType<typeof leadActor>>,id:string){return db.lead.findFirst({where:{id,companyId:a.companyId,...visibilityWhere(a)},include:{customer:true,assignedUser:{select:{id:true,name:true}},activities:{include:{actorUser:{select:{name:true}}},orderBy:{createdAt:"desc"}}}});}
export async function leadOptions(){const a=await leadActor();const users=await db.user.findMany({where:{companyId:a.companyId,isActive:true,role:{in:["MANAGER","SALES"]},...(a.role==="MANAGER"?{OR:[{id:a.id},{role:"SALES",managerId:a.id}]}:a.role==="SALES"?{id:a.id}:{})},select:{id:true,name:true,role:true},orderBy:{name:"asc"}});const customers=await db.customer.findMany({where:{companyId:a.companyId},select:{id:true,name:true},orderBy:{name:"asc"},take:500});return {users,customers};}
