import { LeadSource, LeadStage } from "@prisma/client";
import { z } from "zod";
const emptyToUndefined=(v:unknown)=>v===""||v===null?undefined:v;
const optionalText=(max:number)=>z.preprocess(emptyToUndefined,z.string().trim().max(max).optional());
const optionalUuid=z.preprocess(emptyToUndefined,z.string().uuid().optional());
const optionalDate=z.preprocess(emptyToUndefined,z.coerce.date().optional());
export const moneySchema=z.preprocess(emptyToUndefined,z.string().regex(/^\d{1,16}(\.\d{1,2})?$/).optional());
const editable={title:z.string().trim().min(1).max(200),customerId:optionalUuid,contactName:optionalText(150),phone:optionalText(30),email:z.preprocess(emptyToUndefined,z.string().trim().toLowerCase().email().max(320).optional()),companyName:optionalText(200),source:z.nativeEnum(LeadSource),estimatedValue:moneySchema,currencyCode:z.preprocess(emptyToUndefined,z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).default("INR")),followUpAt:optionalDate,notes:optionalText(5000)};
export const createLeadSchema=z.object({...editable,source:z.nativeEnum(LeadSource).refine(v=>v!=="CUSTOMER_VISIT"),assignedUserId:z.string().uuid()}).strict();
export const createLeadFromVisitSchema=z.object({...editable,assignedUserId:z.string().uuid(),visitId:z.string().uuid()}).omit({customerId:true,source:true}).strict();
export const editLeadSchema=z.object({leadId:z.string().uuid(),version:z.coerce.number().int().positive(),...editable,assignedUserId:z.string().uuid()}).strict();
export const transitionLeadSchema=z.object({leadId:z.string().uuid(),version:z.coerce.number().int().positive(),toStage:z.nativeEnum(LeadStage),lostReason:optionalText(1000)}).strict().superRefine((v,c)=>{if(v.toStage==="LOST"&&!v.lostReason)c.addIssue({code:"custom",path:["lostReason"],message:"A lost reason is required"});});
export const leadFilterSchema=z.object({stage:z.nativeEnum(LeadStage).optional(),assignedUserId:z.string().uuid().optional(),followUp:z.enum(["overdue","today","upcoming"]).optional(),q:z.string().trim().max(100).optional()}).strict();
export type CreateLeadInput=z.infer<typeof createLeadSchema>; export type EditLeadInput=z.infer<typeof editLeadSchema>; export type TransitionLeadInput=z.infer<typeof transitionLeadSchema>;
