"use client";
import Link from "next/link";
import {useMemo,useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {createCommercialDocumentAction} from "@/app/actions/commercial";
import {updateSalesInvoicePrefixAction} from "@/app/actions/account-settings";
import {commercialLinePayload,newCommercialLine,type EditableLine} from "./commercial-editor";

type Option={id:string;name:string;branchId?:string;phone?:string|null;balance?:string;salePrice?:string;sellingRate?:string;taxRate?:string|null;trackInventory?:boolean};
type Preferences={cashSaleByDefault?:boolean;billingName?:boolean;rateTaxMode?:boolean;transactionDiscount?:boolean;stateOfSupply?:boolean};
type Props={options:{branches:Option[];customers:Option[];products:Option[];services:Option[];warehouses:Option[];accountSettings?:{defaultTaxMode?:string;defaultStateCode?:string|null;transactionDefaults?:{transactionPreferences?:Preferences}};numberingSeries?:Array<{branchId:string;prefix:string;suffix:string;padding:number;nextSequence:number}>}};
const money=new Intl.NumberFormat("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
export function saleInvoicePreview(series:Props["options"]["numberingSeries"],branchId:string){const row=series?.find(x=>x.branchId===branchId);return row?`${row.prefix}${String(row.nextSequence).padStart(Math.max(2,row.padding),"0")}${row.suffix}`:"01"}
export function SaleInvoiceEditor({options}:Props){
 const router=useRouter(),preferences=options.accountSettings?.transactionDefaults?.transactionPreferences??{},[branchId]=useState(options.branches[0]?.id??""),[saleMode,setSaleMode]=useState<"CREDIT"|"CASH">(preferences.cashSaleByDefault?"CASH":"CREDIT"),[partyId,setParty]=useState(""),[billingName,setBillingName]=useState(""),[issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[lines,setLines]=useState<EditableLine[]>([]),[invoiceOpen,setInvoiceOpen]=useState(false),[itemsOpen,setItemsOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[customerOpen,setCustomerOpen]=useState(false),[customerQuery,setCustomerQuery]=useState(""),[prefixOpen,setPrefixOpen]=useState(false),[prefixDraft,setPrefixDraft]=useState(""),[seriesPrefix,setSeriesPrefix]=useState(options.numberingSeries?.find(x=>x.branchId===(options.branches[0]?.id??""))?.prefix??""),[moreOpen,setMoreOpen]=useState(false),[manualNumber,setManualNumber]=useState(""),[numberDraft,setNumberDraft]=useState(""),[prefixMode,setPrefixMode]=useState<"NONE"|"PREFIX">("PREFIX"),[previewOffset,setPreviewOffset]=useState(0),[error,setError]=useState(""),[pending,startTransition]=useTransition(),dateRef=useRef<HTMLInputElement>(null),submittingRef=useRef(false);
 const series=options.numberingSeries?.find(x=>x.branchId===branchId),autoNumber=series?`${seriesPrefix}${String(series.nextSequence+previewOffset).padStart(Math.max(2,series.padding),"0")}${series.suffix}`:saleInvoicePreview(options.numberingSeries,branchId),shownNumber=manualNumber||autoNumber,customers=options.customers.filter(x=>!x.branchId||x.branchId===branchId);
 const total=useMemo(()=>lines.reduce((sum,x)=>{const base=(Number(x.quantity)||0)*(Number(x.rate)||0),discount=x.discountType==="PERCENTAGE"?base*(Number(x.discountValue)||0)/100:x.discountType==="FIXED"?Number(x.discountValue)||0:0,taxable=Math.max(0,base-discount);return sum+taxable+taxable*(Number(x.taxRate)||0)/100},0),[lines]);
 function patch(i:number,key:keyof EditableLine,value:string){setLines(old=>old.map((line,n)=>n===i?{...line,[key]:value}:line))}
 function addItem(kind:"PRODUCT"|"SERVICE",item:Option){setLines(old=>[...old,{...newCommercialLine(kind),sourceId:item.id,itemName:item.name,rate:item.salePrice??item.sellingRate??"",taxRate:item.taxRate??""}]);setItemsOpen(false)}
 function submit(saveAndNew:boolean){if(pending||submittingRef.current)return;submittingRef.current=true;if(!partyId){setError(`${saleMode==="CREDIT"?"Credit sale":"Sale"} requires a customer.`);submittingRef.current=false;return}if(!lines.length){setError("Add at least one item. Manual amount sales are not enabled by the current commercial rules.");submittingRef.current=false;return}setError("");const payload={type:"SALES_INVOICE",branchId,partyId,documentNumber:manualNumber||undefined,issueDate,taxMode:options.accountSettings?.defaultTaxMode??"EXCLUSIVE",stateOfSupplyCode:options.accountSettings?.defaultStateCode??undefined,tcsRate:"0",lines:lines.map(commercialLinePayload)};startTransition(async()=>{try{const created=await createCommercialDocumentAction(payload);if(saveAndNew){setParty("");setBillingName("");setLines([]);setManualNumber("");setNumberDraft("");setIssueDate(new Date().toISOString().slice(0,10));setPreviewOffset(x=>x+1);submittingRef.current=false}else router.push(`/workspace/account/transactions/${created.id}`)}catch(e){submittingRef.current=false;setError(e instanceof Error&&e.message.includes("DUPLICATE_DOCUMENT_NUMBER")?"That invoice number already exists for this branch. Choose another number.":"The sale could not be saved. Check the customer, items, inventory and accounting date.")}})}
 return <main className="sale-entry">
  <header className="sale-entry-header"><Link href="/workspace/account" aria-label="Back">‹</Link><h1>Sale</h1><div className="sale-mode" aria-label="Sale payment type">{(["CREDIT","CASH"] as const).map(mode=><button type="button" aria-pressed={saleMode===mode} onClick={()=>setSaleMode(mode)} key={mode}>{mode[0]+mode.slice(1).toLowerCase()}</button>)}</div><button type="button" className="sale-gear" onClick={()=>setSettingsOpen(true)} aria-label="Sale settings">⚙</button></header>
  <section className="sale-meta"><button type="button" onClick={()=>{setNumberDraft(manualNumber||autoNumber);setInvoiceOpen(true)}}><small>Invoice No.</small><strong>{shownNumber}⌄</strong></button><button type="button" onClick={()=>dateRef.current?.showPicker()}><small>Date</small><strong>{new Date(`${issueDate}T00:00:00`).toLocaleDateString("en-IN")}⌄</strong><input ref={dateRef} aria-label="Invoice date" type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)}/></button></section>
  <section className="sale-body"><label>Customer *<button type="button" className="sale-customer-trigger" onClick={()=>setCustomerOpen(true)}>{customers.find(x=>x.id===partyId)?.name??"Search or select customer"}<b>›</b></button></label>{preferences.billingName!==false&&<label>Billing Name (Optional)<input value={billingName} onChange={e=>setBillingName(e.target.value)} placeholder="Name shown while entering this sale"/></label>}
  <button type="button" className="sale-add-items" onClick={()=>setItemsOpen(true)}>＋ Add Items (Optional)</button>{lines.map((line,i)=><article className="sale-line" key={`${line.sourceId}-${i}`}><div><strong>{line.itemName}</strong><button type="button" onClick={()=>setLines(old=>old.filter((_,n)=>n!==i))}>Remove</button></div><label>Qty<input type="number" min=".0001" step=".0001" value={line.quantity} onChange={e=>patch(i,"quantity",e.target.value)}/></label><label>Rate<input type="number" min="0" step=".01" value={line.rate} onChange={e=>patch(i,"rate",e.target.value)}/></label>{preferences.transactionDiscount!==false&&<label>Discount %<input type="number" min="0" max="100" value={line.discountValue} onChange={e=>{patch(i,"discountType","PERCENTAGE");patch(i,"discountValue",e.target.value)}}/></label>}<label>Tax %<input type="number" min="0" value={line.taxRate} onChange={e=>patch(i,"taxRate",e.target.value)}/></label></article>)}
  <div className="sale-total"><span>Total Amount<small>Final tax and total are validated by the server</small></span><strong>₹ {money.format(total)}</strong></div>{error&&<p role="alert" className="sale-error">{error}</p>}</section>
  <footer className="sale-actions"><button type="button" disabled={pending} onClick={()=>submit(true)}>Save &amp; New</button><button type="button" disabled={pending} onClick={()=>submit(false)}>{pending?"Saving…":"Save"}</button><button type="button" disabled={pending} onClick={()=>setMoreOpen(true)} aria-label="More sale options">⋮</button></footer>
  {invoiceOpen&&<div className="sale-overlay"><section className="sale-dialog" role="dialog" aria-modal="true" aria-labelledby="invoice-title"><header><h2 id="invoice-title">Change Invoice No.</h2><button onClick={()=>setInvoiceOpen(false)} aria-label="Close">×</button></header><h3>Invoice Prefix</h3><div className="invoice-prefix-segments"><button type="button" aria-pressed={prefixMode==="NONE"} onClick={()=>setPrefixMode("NONE")}>None</button><button type="button" aria-pressed={prefixMode==="PREFIX"} onClick={()=>{setPrefixMode("PREFIX");setPrefixDraft(seriesPrefix);setPrefixOpen(true)}}>Add Prefix</button></div><label>Invoice No.<input value={numberDraft} onChange={e=>setNumberDraft(e.target.value)} maxLength={100}/></label><button className="account-primary" onClick={()=>{const value=numberDraft.trim(),prefix=prefixMode==="PREFIX"?seriesPrefix:"";setManualNumber(prefix&& !value.startsWith(prefix)?prefix+value:value);setInvoiceOpen(false)}}>SAVE</button></section></div>}
  {customerOpen&&<div className="sale-overlay"><section className="sale-dialog party-selector" role="dialog" aria-modal="true"><header><h2>Select Customer</h2><button onClick={()=>setCustomerOpen(false)}>×</button></header><input autoFocus aria-label="Search saved parties" placeholder="Search parties" value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)}/><div className="party-selector-heading"><b>Showing Saved Parties</b><Link href="/workspace/account/customers">Add new party</Link></div>{customers.filter(x=>`${x.name} ${x.phone??""}`.toLowerCase().includes(customerQuery.toLowerCase())).map(x=><button className="party-row" key={x.id} onClick={()=>{setParty(x.id);setError("");setCustomerOpen(false)}}><span><b>{x.name}</b>{x.phone&&<small>{x.phone}</small>}</span><span>{x.balance??"—"}　›</span></button>)}</section></div>}
  {prefixOpen&&<div className="sale-overlay"><section className="sale-dialog prefix-dialog"><header><h2>Add Prefix</h2><button onClick={()=>setPrefixOpen(false)}>×</button></header><label>Prefix Name<input autoFocus placeholder="e.g., INV" value={prefixDraft} onChange={e=>setPrefixDraft(e.target.value)} maxLength={30}/></label><div className="dialog-actions"><button onClick={()=>setPrefixOpen(false)}>Cancel</button><button onClick={()=>startTransition(async()=>{const value=prefixDraft.trim();const row=await updateSalesInvoicePrefixAction(branchId,value?`${value.replace(/-+$/,'')}-`:"");setSeriesPrefix(row.prefix);setPrefixMode(row.prefix?"PREFIX":"NONE");setPrefixOpen(false)})}>Save</button></div></section></div>}
  {itemsOpen&&<div className="sale-overlay"><section className="sale-dialog sale-items" role="dialog" aria-modal="true"><header><h2>Add Items</h2><button onClick={()=>setItemsOpen(false)} aria-label="Close">×</button></header><h3>Products</h3>{options.products.map(x=><button key={x.id} onClick={()=>addItem("PRODUCT",x)}>{x.name}<small>₹{x.salePrice??"0"}</small></button>)}<h3>Services</h3>{options.services.map(x=><button key={x.id} onClick={()=>addItem("SERVICE",x)}>{x.name}<small>₹{x.sellingRate??"0"}</small></button>)}</section></div>}
  {settingsOpen&&<div className="sale-overlay drawer"><aside className="sale-settings" role="dialog" aria-modal="true"><header><h2>Settings</h2><button onClick={()=>setSettingsOpen(false)} aria-label="Close">×</button></header><label><span>Sale Prefix<small>Uses this branch’s canonical invoice numbering series.</small></span><input type="checkbox" checked={prefixMode==="PREFIX"} onChange={e=>setPrefixMode(e.target.checked?"PREFIX":"NONE")}/></label><label><span>Transaction SMS<small>No SMS delivery is enabled.</small></span><input type="checkbox" disabled/></label><Link href="/workspace/account/settings/custom-fields">Additional Fields <b>›</b></Link><Link href="/workspace/account/settings/transactions">Additional Charges <b>›</b></Link><h3>Billing Type</h3><label><span>Full Sale</span><input type="radio" checked readOnly/></label><label className="disabled"><span>Mobile POS<small>Coming Soon</small></span><input type="radio" disabled/></label><Link className="more-settings" href="/workspace/account/settings/transactions">⚙ More Settings</Link></aside></div>}
  {moreOpen&&<div className="sale-overlay"><section className="sale-dialog"><header><h2>Sale Options</h2><button onClick={()=>setMoreOpen(false)} aria-label="Close">×</button></header><Link href="/workspace/account/settings/transactions">Transaction Settings</Link><Link href="/workspace/account/settings/print-templates">Print Settings</Link></section></div>}
 </main>
}
