package com.salespunch360.mobile.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.CompanyViewModel
import com.salespunch360.mobile.data.*

@Composable fun SettingsScreen(vm:CompanyViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val c=state.context?.company;if(state.loading&&c==null){LoadingScreen("Loading company settings…");return};if(c==null){RetryScreen(state.message?:"Settings unavailable.",vm::load);return};var attendance by remember(c){mutableStateOf(c.attendanceEnabled)};var gps by remember(c){mutableStateOf(c.gpsTrackingEnabled)};var checkout by remember(c){mutableStateOf(c.checkoutRequiredBeforeNextCheckIn)};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Company settings",style=MaterialTheme.typography.headlineSmall);Text("Saved and enforced by the SalesPunch360 server.")};item{SettingSwitch("Attendance enabled",attendance){attendance=it};SettingSwitch("GPS tracking enabled",gps){gps=it};SettingSwitch("Checkout before next check-in",checkout){checkout=it};Button({vm.saveOperations(OperationsSettings(attendance,gps,checkout))},enabled=!state.saving,modifier=Modifier.fillMaxWidth()){Text(if(state.saving)"Saving…" else "Save settings")}};state.message?.let{item{ContentCard("Status",it)}}}}

@Composable private fun SettingSwitch(label:String,checked:Boolean,change:(Boolean)->Unit){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,Modifier.weight(1f));Switch(checked,change)}}

@Composable fun GeofenceScreen(vm:CompanyViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val c=state.context?.company;if(state.loading&&c==null){LoadingScreen("Loading geofence settings…");return};if(c==null){RetryScreen(state.message?:"Geofence unavailable.",vm::load);return};var attendance by remember(c){mutableStateOf(c.attendanceGeofenceEnabled)};var customer by remember(c){mutableStateOf(c.customerCheckInGeofenceEnabled)};var lat by remember(c){mutableStateOf(c.attendanceReferenceLatitude?:"")};var lng by remember(c){mutableStateOf(c.attendanceReferenceLongitude?:"")};var ar by remember(c){mutableStateOf(c.attendanceGeofenceRadiusMeters?.toString()?:"")};var cr by remember(c){mutableStateOf(c.customerCheckInGeofenceRadiusMeters?.toString()?:"")};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Geofence",style=MaterialTheme.typography.headlineSmall);Text("The server uses the existing Haversine policy and validates radii from 10–100000 metres.")};item{SettingSwitch("Attendance start enforcement",attendance){attendance=it};OutlinedTextField(lat,{lat=it},label={Text("Reference latitude")},modifier=Modifier.fillMaxWidth());OutlinedTextField(lng,{lng=it},label={Text("Reference longitude")},modifier=Modifier.fillMaxWidth());OutlinedTextField(ar,{ar=it},label={Text("Attendance radius (m)")},modifier=Modifier.fillMaxWidth());HorizontalDivider();SettingSwitch("Customer check-in enforcement",customer){customer=it};Text("Customer reference coordinates remain protected on each customer record.");OutlinedTextField(cr,{cr=it},label={Text("Customer radius (m)")},modifier=Modifier.fillMaxWidth());Button({vm.saveGeofence(GeofenceSettings(attendance,lat.ifBlank{null},lng.ifBlank{null},ar.toIntOrNull(),customer,cr.toIntOrNull()))},enabled=!state.saving,modifier=Modifier.fillMaxWidth()){Text(if(state.saving)"Saving…" else "Save geofence")}};state.message?.let{item{ContentCard("Status",it)}}}}

@Composable fun SubscriptionScreen(vm:CompanyViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val r=state.context;if(state.loading&&r==null){LoadingScreen("Loading subscription…");return};if(r==null){RetryScreen(state.message?:"Subscription unavailable.",vm::load);return};val c=r.company;val e=r.entitlement;LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Subscription",style=MaterialTheme.typography.headlineSmall);StatusChip(e.state);ContentCard("Access",listOfNotNull("Company status: ${c.subscriptionStatus}",c.trialEndsAt?.let{"Trial ends: ${it.take(10)}"},e.subscription?.let{"${it.billingPeriod} through ${it.endsAt.take(10)}"}).joinToString(" · "));if(c.teamStructure==TeamStructure.MANAGERS_AND_SALES)ContentCard("Manager seats","${e.managerUsage} used of ${e.managerLimit}");ContentCard("Sales seats","${e.salesUsage} used of ${e.salesLimit}");ContentCard("Billing",r.paymentMessage){Text("Prices are read from the database; no payment action is available.")}};items(r.prices.filter{c.teamStructure==TeamStructure.MANAGERS_AND_SALES||it.role=="SALES"}){p->ContentCard("${p.role.replace('_',' ')} · ${p.period.replace('_',' ')}","${p.currency} ${p.amount}")}}}
