package com.salespunch360.mobile.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.EmployeesViewModel
import com.salespunch360.mobile.data.*

private enum class RoleFilter{ALL,MANAGER,SALES};private enum class ActiveFilter{ALL,ACTIVE,INACTIVE}
@Composable fun EmployeesScreen(vm:EmployeesViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val context=state.context;var search by remember{mutableStateOf("")};var role by remember{mutableStateOf(RoleFilter.ALL)};var active by remember{mutableStateOf(ActiveFilter.ALL)};var adding by remember{mutableStateOf(false)};var confirm by remember{mutableStateOf<Employee?>(null)}
 if(context==null&&state.loading){LoadingScreen("Loading employees…");return};if(context==null){RetryScreen(state.error?:"Employees couldn't be loaded.",vm::refresh);return};val managersEnabled=context.teamStructure==TeamStructure.MANAGERS_AND_SALES;val visible=context.employees.filter{it.name.contains(search,true)||it.email.contains(search,true)||it.phone?.contains(search,true)==true}.filter{role==RoleFilter.ALL||it.role.name==role.name}.filter{active==ActiveFilter.ALL||if(active==ActiveFilter.ACTIVE)isActiveEmployee(it) else !it.isActive}
 Box(Modifier.fillMaxSize()){LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(bottom=88.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Spacer(Modifier.height(8.dp));SeatSummary(context);if(state.emailVerified==false){Spacer(Modifier.height(8.dp));EmailVerificationCard(state.verificationSending,vm::resendVerification,vm::refresh)};Spacer(Modifier.height(8.dp));OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),singleLine=true,label={Text("Search employees")},leadingIcon={Icon(Icons.Default.Search,null)});FilterRow(managersEnabled,role,{role=it},active,{active=it});state.error?.let{MessageBanner(it,vm::dismiss)};state.notice?.let{Surface(Modifier.fillMaxWidth(),color=MaterialTheme.colorScheme.primaryContainer,shape=MaterialTheme.shapes.medium){Text(it,Modifier.padding(12.dp))}}};if(visible.isEmpty())item{ContentCard("No employees found",if(context.employees.isEmpty())"Add your first team member to get started." else "Try changing your search or filters.")};items(visible,key={it.id}){employee->EmployeeCard(employee,managersEnabled,state.mutating){confirm=employee}};if(state.loading)item{LinearProgressIndicator(Modifier.fillMaxWidth())}}
  val e=context.entitlement;val verifiedForCreation=state.emailVerified!=false;val hasAvailableSeat=hasSeat(e.salesUsage,e.salesLimit)||(managersEnabled&&hasSeat(e.managerUsage,e.managerLimit));val canAdd=verifiedForCreation&&e.operationalWritesAllowed&&hasAvailableSeat;val addLabel=when{!verifiedForCreation->"Verify email first";!hasAvailableSeat->"No seats available";!e.operationalWritesAllowed->"Employee changes unavailable";else->"Add employee"};ExtendedFloatingActionButton(text={Text(addLabel)},icon={Icon(Icons.Default.PersonAdd,null)},onClick={if(canAdd)adding=true},modifier=Modifier.align(androidx.compose.ui.Alignment.BottomEnd).padding(20.dp))
 }
 if(adding)AddEmployeeDialog(context,state.mutating,{adding=false}){vm.create(it){adding=false}};confirm?.let{employee->AlertDialog(onDismissRequest={confirm=null},title={Text("${employeeAction(employee)} for ${employee.name}?")},text={Text(if(isActiveEmployee(employee))"They will be signed out and unable to use the application." else "This uses an available ${employee.role.name.lowercase()} seat.")},confirmButton={Button({vm.setActive(employee,!isActiveEmployee(employee));confirm=null},enabled=!state.mutating){Text(employeeAction(employee))}},dismissButton={TextButton({confirm=null}){Text("Cancel")}})}
}
@Composable private fun SeatSummary(context:EmployeeContext){val e=context.entitlement;ContentCard("Team seats",if(context.teamStructure==TeamStructure.SALES_ONLY)"Sales ${e.salesUsage} / ${limit(e.salesLimit)}" else "Managers ${e.managerUsage} / ${limit(e.managerLimit)}   ·   Sales ${e.salesUsage} / ${limit(e.salesLimit)}"){if(!e.operationalWritesAllowed)Text("Employee creation and reactivation are currently unavailable.",color=MaterialTheme.colorScheme.error)}}
@Composable private fun EmailVerificationCard(sending:Boolean,onResend:()->Unit,onRefresh:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Verify your email",style=MaterialTheme.typography.titleMedium);Text("Verify your email address before adding Managers or Sales employees.",style=MaterialTheme.typography.bodyMedium);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onResend,enabled=!sending){if(sending)CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp)else Text("Resend email")};TextButton(onRefresh,enabled=!sending){Text("I've verified")}}}}}
private fun limit(value:Int?)=value?.toString()?:"Unlimited"
private fun hasSeat(usage:Int,limit:Int?)=limit==null||usage<limit
@Composable private fun FilterRow(managers:Boolean,role:RoleFilter,onRole:(RoleFilter)->Unit,active:ActiveFilter,onActive:(ActiveFilter)->Unit){Column{if(managers)SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){RoleFilter.entries.forEachIndexed{i,item->SegmentedButton(selected=role==item,onClick={onRole(item)},shape=SegmentedButtonDefaults.itemShape(i,RoleFilter.entries.size)){Text(item.name.lowercase().replaceFirstChar{it.uppercase()})}}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){ActiveFilter.entries.forEach{FilterChip(active==it,{onActive(it)},{Text(it.name.lowercase().replaceFirstChar{c->c.uppercase()})})}}}}
@Composable private fun EmployeeCard(employee:Employee,managers:Boolean,busy:Boolean,onManage:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Row{Column(Modifier.weight(1f)){Text(employee.name,style=MaterialTheme.typography.titleMedium,maxLines=1,overflow=TextOverflow.Ellipsis);Text(employee.email,maxLines=1,overflow=TextOverflow.Ellipsis)};StatusChip(employeeStatus(employee))};Text(employee.role.name.lowercase().replaceFirstChar{it.uppercase()}+(employee.employeeCode?.let{" · $it"}?:""),style=MaterialTheme.typography.labelMedium);employee.phone?.let{Text(it)};if(managers&&employee.role==MobileRole.SALES)Text("Manager: ${employee.manager?.let{it.name+if(!it.isActive||!it.salesAccessActive)" (unavailable)" else ""}?:"Unassigned"}");TextButton(onManage,enabled=!busy,contentPadding=PaddingValues(horizontal=0.dp)){Text(employeeAction(employee))}}}}

@Composable private fun AddEmployeeDialog(context:EmployeeContext,busy:Boolean,dismiss:()->Unit,submit:(CreateEmployeeRequest)->Unit){val managersEnabled=context.teamStructure==TeamStructure.MANAGERS_AND_SALES;var role by remember{mutableStateOf(MobileRole.SALES)};var managerType by remember{mutableStateOf(ManagerType.FIELD_MANAGER)};var name by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var code by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var confirm by remember{mutableStateOf("")};var visible by remember{mutableStateOf(false)};var managerId by remember{mutableStateOf<String?>(null)};val managers=selectableManagers(context.employees);val valid=name.trim().length>=2&&android.util.Patterns.EMAIL_ADDRESS.matcher(email.trim()).matches()&&password.length>=12&&password==confirm
 val roleHasSeat=if(role==MobileRole.MANAGER)hasSeat(context.entitlement.managerUsage,context.entitlement.managerLimit)else hasSeat(context.entitlement.salesUsage,context.entitlement.salesLimit);AlertDialog(onDismissRequest={if(!busy)dismiss()},title={Text("Add employee")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){if(managersEnabled)SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf(MobileRole.SALES,MobileRole.MANAGER).forEachIndexed{i,item->SegmentedButton(selected=role==item,onClick={role=item;managerId=null},enabled=if(item==MobileRole.MANAGER)hasSeat(context.entitlement.managerUsage,context.entitlement.managerLimit)else hasSeat(context.entitlement.salesUsage,context.entitlement.salesLimit),shape=SegmentedButtonDefaults.itemShape(i,2)){Text(if(item==MobileRole.SALES)"Sales" else "Manager")}}};if(managersEnabled&&role==MobileRole.MANAGER){Text("Manager Type",style=MaterialTheme.typography.labelLarge);SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){listOf(ManagerType.FIELD_MANAGER,ManagerType.MANAGER_ONLY).forEachIndexed{i,item->SegmentedButton(selected=managerType==item,onClick={managerType=item},shape=SegmentedButtonDefaults.itemShape(i,2)){Text(if(item==ManagerType.FIELD_MANAGER)"Field Manager" else "Manager Only")}}}};OutlinedTextField(name,{name=it},label={Text("Full name")},singleLine=true);OutlinedTextField(email,{email=it},label={Text("Email")},singleLine=true,keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Email));OutlinedTextField(phone,{phone=it},label={Text("Phone (optional)")},singleLine=true,keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Phone));OutlinedTextField(code,{code=it},label={Text("Employee code (optional)")},singleLine=true);if(managersEnabled&&role==MobileRole.SALES)ManagerPicker(managers,managerId){managerId=it};OutlinedTextField(password,{password=it},label={Text("Password")},singleLine=true,visualTransformation=if(visible)VisualTransformation.None else PasswordVisualTransformation(),trailingIcon={IconButton({visible=!visible}){Icon(if(visible)Icons.Default.VisibilityOff else Icons.Default.Visibility,if(visible)"Hide password" else "Show password")}},supportingText={Text("At least 12 characters")});OutlinedTextField(confirm,{confirm=it},label={Text("Confirm password")},singleLine=true,visualTransformation=PasswordVisualTransformation(),isError=confirm.isNotEmpty()&&password!=confirm)}},confirmButton={Button({submit(CreateEmployeeRequest(role,name.trim(),email.trim(),phone.ifBlank{null},code.ifBlank{null},password,confirm,managerId,if(role==MobileRole.MANAGER)managerType else null))},enabled=valid&&!busy&&roleHasSeat&&context.entitlement.operationalWritesAllowed){if(busy)CircularProgressIndicator(Modifier.size(20.dp))else Text("Create")}},dismissButton={TextButton(dismiss,enabled=!busy){Text("Cancel")}})
}
@Composable private fun ManagerPicker(managers:List<Employee>,selected:String?,choose:(String?)->Unit){var expanded by remember{mutableStateOf(false)};Box{OutlinedButton({expanded=true},Modifier.fillMaxWidth()){Text(managers.firstOrNull{it.id==selected}?.name?:"No Manager assigned")};DropdownMenu(expanded,{expanded=false}){DropdownMenuItem({Text("No Manager assigned")},{choose(null);expanded=false});managers.forEach{manager->DropdownMenuItem({Text(manager.name)},{choose(manager.id);expanded=false})}}}}
