package com.salespunch360.mobile.ui
import android.Manifest
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import java.io.ByteArrayOutputStream
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import android.content.pm.PackageManager
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.FieldViewModel
import com.salespunch360.mobile.data.*
import com.salespunch360.mobile.location.currentDeviceLocation
import com.salespunch360.mobile.location.locationFailureMessage
import kotlinx.coroutines.launch

private fun compressedBitmap(source:Bitmap):ByteArray{val scale=minOf(1f,720f/maxOf(source.width,source.height));val result=if(scale<1f)Bitmap.createScaledBitmap(source,(source.width*scale).toInt(),(source.height*scale).toInt(),true)else source;return ByteArrayOutputStream().use{result.compress(Bitmap.CompressFormat.WEBP_LOSSY,58,it);if(result!==source)result.recycle();source.recycle();it.toByteArray()}}
private fun compressedPhoto(bytes:ByteArray):ByteArray?=BitmapFactory.decodeByteArray(bytes,0,bytes.size)?.let(::compressedBitmap)
@Composable fun FieldScreen(vm:FieldViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val context=state.context;var type by remember{mutableStateOf("NEW")};var subjectId by remember{mutableStateOf<String?>(null)};var subjectLabel by remember{mutableStateOf<String?>(null)};var firstCustomer by remember{mutableStateOf(false)};var showForm by remember{mutableStateOf(false)};var checkout by remember{mutableStateOf<FieldVisit?>(null)};var permissionAction by remember{mutableStateOf<(() -> Unit)?>(null)};val androidContext=LocalContext.current;val scope=rememberCoroutineScope();val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){if(it[Manifest.permission.ACCESS_FINE_LOCATION]==true)permissionAction?.invoke()else vm.locationError("Precise location is required.")}
 if(context==null&&state.loading){LoadingScreen("Loading check-ins…");return};if(context==null){RetryScreen(state.message?:"Check-ins couldn't be loaded.",vm::refresh);return};val open=context.visits.filter{it.checkedOutAt==null}
 LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{SingleChoiceSegmentedButtonRow{listOf("NEW" to "New Check-in","FOLLOW_UP" to "Follow-up Check-in","CUSTOMER" to "Customer Check-in").forEachIndexed{i,(value,label)->SegmentedButton(selected=type==value,onClick={type=value;subjectId=null;subjectLabel=null},shape=SegmentedButtonDefaults.itemShape(i,3)){Text(label)}}}};item{when(type){"NEW"->Button({showForm=true},Modifier.fillMaxWidth()){Text("New Check-in")};"CUSTOMER"->Column{context.customers.forEach{c->OutlinedButton({subjectId=c.id;subjectLabel=c.name;firstCustomer=c.checkInReferenceSetAt==null;showForm=true},Modifier.fillMaxWidth()){Text(c.name)}}};else->Column{state.leads.forEach{l->OutlinedButton({subjectId=l.id;subjectLabel=l.title;showForm=true},Modifier.fillMaxWidth()){Text(l.title)}}}}};state.message?.let{item{MessageBanner(it,vm::clear)}};if(open.isNotEmpty())item{ContentCard("Checkout required","Complete the current checkout before another check-in."){open.forEach{v->Button({checkout=v},Modifier.fillMaxWidth()){Text("Checkout · ${v.customer?.name?:v.contactName?:"Prospect"}")}}}};item{Text("Visit history",style=MaterialTheme.typography.titleLarge)};items(context.visits,key={it.id}){v->OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(v.customer?.name?:v.contactName?:"Field prospect");Text(v.checkedInAt);Text(if(v.checkedOutAt==null)"Awaiting checkout" else "Completed")}}}}
 if(showForm)CheckInDialog(type,subjectId,subjectLabel,firstCustomer,state.busy,{showForm=false}){name,phone,notes,photo->permissionAction={scope.launch{runCatching{currentDeviceLocation(androidContext)}.onSuccess{vm.checkIn(type,subjectId,name,phone,it,notes,photo);showForm=false}.onFailure{vm.locationError(locationFailureMessage(it))}}};permission.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))}
 checkout?.let{visit->CheckoutDialog(visit,state.busy,{checkout=null}){sentiment,remarks->permissionAction={scope.launch{runCatching{currentDeviceLocation(androidContext)}.onSuccess{vm.checkout(visit.id,it,sentiment,remarks);checkout=null}.onFailure{vm.locationError(locationFailureMessage(it))}}};permission.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))}}
}
@Composable private fun CheckInDialog(type:String,subjectId:String?,label:String?,firstCustomer:Boolean,busy:Boolean,dismiss:()->Unit,submit:(String?,String?,String?,ByteArray?)->Unit){var name by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")};var photo by remember{mutableStateOf<ByteArray?>(null)};val context=LocalContext.current;val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri->photo=uri?.let{context.contentResolver.openInputStream(it)?.use{stream->compressedPhoto(stream.readBytes())}}};val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicturePreview()){bitmap->photo=bitmap?.let(::compressedBitmap)};val cameraPermission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){if(it)camera.launch(null)};val required=type=="NEW"||(type=="CUSTOMER"&&firstCustomer);AlertDialog(onDismissRequest=dismiss,title={Text(when(type){"NEW"->"New Check-in";"FOLLOW_UP"->"Follow-up Check-in";else->"Customer Check-in"})},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){label?.let{Text(it)};if(type=="NEW"){OutlinedTextField(name,{name=it},label={Text("Name")});OutlinedTextField(phone,{phone=it},label={Text("Phone (optional)")})};OutlinedTextField(notes,{notes=it},label={Text("Notes (optional)")});Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton({if(ContextCompat.checkSelfPermission(context,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.launch(null)else cameraPermission.launch(Manifest.permission.CAMERA)}){Text("Camera")};OutlinedButton({picker.launch("image/*")}){Text("Gallery")}};Text(if(photo==null)"No photo selected" else "Photo ready (≤720px)");Text(if(required)"Photo required" else "Photo optional",style=MaterialTheme.typography.bodySmall)}},confirmButton={Button({submit(name.ifBlank{null},phone.ifBlank{null},notes.ifBlank{null},photo)},enabled=!busy&&(if(type=="NEW")name.isNotBlank() else subjectId!=null)&&(!required||photo!=null)){Icon(Icons.Default.LocationOn,null);Text(" Check in")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
@Composable private fun CheckoutDialog(visit:FieldVisit,busy:Boolean,dismiss:()->Unit,submit:(VisitSentiment,String?)->Unit){var sentiment by remember{mutableStateOf<VisitSentiment?>(null)};var remarks by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Checkout")},text={Column{VisitSentiment.entries.forEach{item->Row{RadioButton(sentiment==item,{sentiment=item});Text(item.name)}};OutlinedTextField(remarks,{remarks=it.take(2000)},label={Text("Remarks (optional)")})}},confirmButton={Button({sentiment?.let{submit(it,remarks.ifBlank{null})}},enabled=!busy&&sentiment!=null){Text("Checkout with GPS")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
