package com.salespunch360.mobile.ui
import android.Manifest
import android.graphics.Bitmap
import android.os.Build
import java.io.ByteArrayOutputStream
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import android.content.pm.PackageManager
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.FieldViewModel
import com.salespunch360.mobile.data.*
import com.salespunch360.mobile.location.currentDeviceLocation
import com.salespunch360.mobile.location.locationFailureMessage
import kotlinx.coroutines.launch

private fun compressedBitmap(source:Bitmap):ByteArray{val scale=minOf(1f,720f/maxOf(source.width,source.height));val result=if(scale<1f)Bitmap.createScaledBitmap(source,(source.width*scale).toInt(),(source.height*scale).toInt(),true)else source;val format=if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.R)Bitmap.CompressFormat.WEBP_LOSSY else @Suppress("DEPRECATION") Bitmap.CompressFormat.WEBP;return ByteArrayOutputStream().use{result.compress(format,58,it);if(result!==source)result.recycle();source.recycle();it.toByteArray()}}

@Composable fun CustomersScreen(openCheckIns:()->Unit,vm:FieldViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val context=state.context;if(context==null&&state.loading){LoadingScreen("Loading customers…");return};if(context==null){RetryScreen(state.message?:"Customers couldn't be loaded.",vm::refresh);return};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Customers",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=SalesInk)};if(context.customers.isEmpty())item{OutlinedCard(Modifier.fillMaxWidth()){Box(Modifier.fillMaxWidth().padding(vertical=32.dp,horizontal=16.dp)){Text("No customers are assigned to you.",color=SalesMuted)}}};items(context.customers,key={it.id}){c->OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(c.name,fontWeight=FontWeight.Bold,color=SalesInk);c.contactPerson?.let{Text(it,color=SalesMuted)};c.phone?.let{Text(it,color=SalesMuted)};c.address?.let{Text(it,style=MaterialTheme.typography.bodySmall,color=SalesMuted)};Text(if(c.checkInReferenceSetAt==null)"First customer visit" else "Customer location established",style=MaterialTheme.typography.labelSmall,color=SalesMuted);TextButton(openCheckIns,contentPadding=PaddingValues(0.dp)){Text("Start customer check-in")}}}}}}

@Composable fun FieldScreen(initialFollowUpTask:FollowUpTask?=null,onInitialFollowUpConsumed:()->Unit={},initialLead:LeadSummary?=null,onInitialLeadConsumed:()->Unit={},vm:FieldViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val context=state.context;var type by remember{mutableStateOf("NEW")};var subjectId by remember{mutableStateOf<String?>(null)};var subjectLabel by remember{mutableStateOf<String?>(null)};var followUpTaskId by remember{mutableStateOf<String?>(null)};var firstCustomer by remember{mutableStateOf(false)};var showForm by remember{mutableStateOf(false)};var checkout by remember{mutableStateOf<FieldVisit?>(null)};var permissionAction by remember{mutableStateOf<(() -> Unit)?>(null)};val androidContext=LocalContext.current;val scope=rememberCoroutineScope();val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){if(it[Manifest.permission.ACCESS_FINE_LOCATION]==true)permissionAction?.invoke()else vm.locationError("Precise location is required.")}
 LaunchedEffect(initialFollowUpTask?.id){initialFollowUpTask?.let{type="FOLLOW_UP";subjectId=it.leadId;subjectLabel=it.subjectName;followUpTaskId=it.id;showForm=true;onInitialFollowUpConsumed()}}
 LaunchedEffect(initialLead?.id){initialLead?.let{type="FOLLOW_UP";subjectId=it.id;subjectLabel=it.title;followUpTaskId=null;showForm=true;onInitialLeadConsumed()}}
 if(context==null&&state.loading){LoadingScreen("Loading check-ins…");return};if(context==null){RetryScreen(state.message?:"Check-ins couldn't be loaded.",vm::refresh);return};val open=context.visits.filter{it.checkedOutAt==null}
 LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Check-ins",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=SalesInk)};item{SingleChoiceSegmentedButtonRow{listOf("NEW" to "New","FOLLOW_UP" to "Follow-up","CUSTOMER" to "Customer").forEachIndexed{i,(value,label)->SegmentedButton(selected=type==value,onClick={type=value;subjectId=null;subjectLabel=null;followUpTaskId=null},shape=SegmentedButtonDefaults.itemShape(i,3)){Text(label)}}}};item{when(type){"NEW"->Button({followUpTaskId=null;showForm=true},Modifier.fillMaxWidth()){Text("Add Check-in")};"CUSTOMER"->Column{context.customers.forEach{c->OutlinedButton({subjectId=c.id;subjectLabel=c.name;followUpTaskId=null;firstCustomer=c.checkInReferenceSetAt==null;showForm=true},Modifier.fillMaxWidth()){Text(c.name)}}};else->Column{state.leads.forEach{l->OutlinedButton({subjectId=l.id;subjectLabel=l.title;followUpTaskId=null;showForm=true},Modifier.fillMaxWidth()){Text(l.title)}}}}};state.message?.let{item{MessageBanner(it,vm::clear)}};if(open.isNotEmpty())item{ContentCard("Checkout required","Complete the current checkout before another check-in."){open.forEach{v->Button({checkout=v},Modifier.fillMaxWidth()){Text("Checkout · ${v.customer?.name?:v.contactName?:"Prospect"}")}}}};item{Text("Visit history",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};items(context.visits,key={it.id}){v->OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(v.customer?.name?:v.contactName?:"Field prospect",fontWeight=FontWeight.Bold);Text(formatFieldTime(v.checkedInAt),color=SalesMuted);Text(if(v.checkedOutAt==null)"Awaiting checkout" else "Completed${v.checkoutSentiment?.let{" · ${it.name}"}?:""}",color=SalesMuted);v.checkedOutAt?.let{Text("Out ${formatFieldTime(it)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}}}}}
 if(showForm)CheckInDialog(type,subjectId,subjectLabel,firstCustomer,state.busy,{showForm=false}){name,phone,notes,photo->permissionAction={scope.launch{runCatching{currentDeviceLocation(androidContext)}.onSuccess{vm.checkIn(type,subjectId,name,phone,it,notes,photo,followUpTaskId);showForm=false;followUpTaskId=null}.onFailure{vm.locationError(locationFailureMessage(it))}}};permission.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))}
 checkout?.let{visit->CheckoutDialog(visit,state.busy,{checkout=null}){sentiment,remarks->permissionAction={scope.launch{runCatching{currentDeviceLocation(androidContext)}.onSuccess{vm.checkout(visit.id,it,sentiment,remarks);checkout=null}.onFailure{vm.locationError(locationFailureMessage(it))}}};permission.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))}}
}
private fun formatFieldTime(value:String):String=runCatching{java.time.OffsetDateTime.parse(value).atZoneSameInstant(java.time.ZoneId.systemDefault()).format(java.time.format.DateTimeFormatter.ofPattern("d MMM yyyy, h:mm a"))}.getOrDefault(value)
@Composable private fun CheckInDialog(type:String,subjectId:String?,label:String?,firstCustomer:Boolean,busy:Boolean,dismiss:()->Unit,submit:(String?,String?,String?,ByteArray?)->Unit){var name by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")};var photo by remember{mutableStateOf<ByteArray?>(null)};val context=LocalContext.current;val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicturePreview()){bitmap->photo=bitmap?.let(::compressedBitmap)};val cameraPermission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){if(it)camera.launch(null)};val required=type=="NEW"||(type=="CUSTOMER"&&firstCustomer);AlertDialog(onDismissRequest=dismiss,title={Column{Text("ADD CHECK-IN",style=MaterialTheme.typography.labelMedium,color=SalesBlue);Text(when(type){"NEW"->"New";"FOLLOW_UP"->"Follow-up";else->"Customer"})}},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){StatusChip("Location ready");label?.let{Text(it)};if(type=="NEW"){OutlinedTextField(name,{name=it},label={Text("Name")});OutlinedTextField(phone,{phone=it},label={Text("Phone")})};Text("Photo",fontWeight=FontWeight.Bold);Text(if(required)"Required" else "Optional",style=MaterialTheme.typography.bodySmall,color=SalesMuted);OutlinedButton({if(ContextCompat.checkSelfPermission(context,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.launch(null)else cameraPermission.launch(Manifest.permission.CAMERA)},Modifier.fillMaxWidth()){Text("Take / Choose Photo")};if(photo!=null)Text("Photo ready",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text("Notes",fontWeight=FontWeight.Bold);Text("Optional",style=MaterialTheme.typography.bodySmall,color=SalesMuted);OutlinedTextField(notes,{notes=it},placeholder={Text("Add visit details")},modifier=Modifier.fillMaxWidth())}},confirmButton={Button({submit(name.ifBlank{null},phone.ifBlank{null},notes.ifBlank{null},photo)},enabled=!busy&&(if(type=="NEW")name.isNotBlank() else subjectId!=null)&&(!required||photo!=null)){Icon(Icons.Default.LocationOn,null);Text(" Check in")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
@Composable private fun CheckoutDialog(visit:FieldVisit,busy:Boolean,dismiss:()->Unit,submit:(VisitSentiment,String?)->Unit){var sentiment by remember{mutableStateOf<VisitSentiment?>(null)};var remarks by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Checkout")},text={Column{VisitSentiment.entries.forEach{item->Row{RadioButton(sentiment==item,{sentiment=item});Text(item.name)}};OutlinedTextField(remarks,{remarks=it.take(2000)},label={Text("Remarks (optional)")})}},confirmButton={Button({sentiment?.let{submit(it,remarks.ifBlank{null})}},enabled=!busy&&sentiment!=null){Text("Checkout with GPS")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
