@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.FollowUpsViewModel
import com.salespunch360.mobile.data.FollowUpTask
import java.time.OffsetDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
@Composable fun FollowUpsScreen(startCheckIn:(FollowUpTask)->Unit,viewLead:(String)->Unit,vm:FollowUpsViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;var visitDetails by remember{mutableStateOf<FollowUpTask?>(null)};LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(vertical=14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Follow-ups",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=SalesInk);HorizontalDivider(Modifier.padding(top=8.dp,bottom=10.dp),color=SalesLine);LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf("TODAY" to "Due Today","OVERDUE" to "Overdue","PENDING" to "Pending","COMPLETED" to "Completed","CANCELLED" to "Cancelled")){(value,label)->FilterChip(state.filter==value,{vm.select(value)},{Text(label)})}}};state.message?.let{item{MessageBanner(it,vm::clear)}};if(state.loading&&state.tasks.isEmpty())item{LinearProgressIndicator(Modifier.fillMaxWidth())};if(!state.loading&&state.tasks.isEmpty())item{OutlinedCard(Modifier.fillMaxWidth()){Box(Modifier.fillMaxWidth().padding(vertical=28.dp,horizontal=16.dp)){Text("No tasks in this view.",color=SalesMuted)}}};items(state.tasks,key={it.id}){task->FollowUpTaskCard(task,state.busyTaskId==task.id,startCheckIn,viewLead,{visitDetails=task},{vm.cancel(task)})}};visitDetails?.let{task->VisitDetailsDialog(task){visitDetails=null}}}
@Composable private fun FollowUpTaskCard(task:FollowUpTask,busy:Boolean,startCheckIn:(FollowUpTask)->Unit,viewLead:(String)->Unit,viewVisit:()->Unit,cancel:()->Unit){var confirmCancel by remember(task.id){mutableStateOf(false)};OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Row{Text(task.subjectName,Modifier.weight(1f),fontWeight=FontWeight.Bold,color=SalesInk);StatusChip(task.status)};Text("Lead: ${task.leadTitle} · Assigned: ${task.assignedUserName?:"—"}",style=MaterialTheme.typography.bodyMedium,color=SalesInk);Text("Due: ${task.dueDate.take(10)} · Last action: ${task.lastAction}",style=MaterialTheme.typography.bodyMedium,color=SalesMuted);task.notes?.takeIf{it.isNotBlank()}?.let{Text(it,style=MaterialTheme.typography.bodyMedium)};task.createdByUserName?.let{creator->Text("Task created by $creator${task.createdAt?.let{" · ${followUpTime(it)}"}?:""}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};HorizontalDivider(color=SalesLine);Text("Task created by ${task.createdByUserName?:"—"}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text("→ Assigned to ${task.assignedUserName?:"—"}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);if(task.completedVisitId!=null){Text("→ Follow-up check-in done by ${task.completedVisitUserName?:task.assignedUserName?:"—"}${task.checkedInAt?.let{" · ${followUpTime(it)}"}?:""}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);task.checkedOutAt?.let{Text("→ Checkout completed · ${followUpTime(it)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}};task.completedAt?.let{Text("→ Task completed · ${followUpTime(it)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};if(task.status=="CANCELLED")Text("→ Cancelled",style=MaterialTheme.typography.bodySmall,color=SalesMuted);FlowRow(horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton({viewLead(task.leadId)},enabled=!busy){Text("View Lead")};if(task.completedVisitId!=null)OutlinedButton(viewVisit,enabled=!busy){Text("View Visit")};if(task.canStartCheckIn)Button({startCheckIn(task)},enabled=!busy){Text("Start Follow-up Check-in")};if(task.canCancel)OutlinedButton({confirmCancel=true},enabled=!busy){Text(if(busy)"Cancelling…" else "Cancel")}}}};if(confirmCancel)AlertDialog(onDismissRequest={confirmCancel=false},title={Text("Cancel follow-up?")},text={Text("This pending follow-up will be marked as cancelled.")},confirmButton={Button({confirmCancel=false;cancel()}){Text("Cancel Follow-up")}},dismissButton={TextButton({confirmCancel=false}){Text("Keep")}})}
@Composable private fun VisitDetailsDialog(task:FollowUpTask,dismiss:()->Unit){AlertDialog(onDismissRequest=dismiss,title={Text("Visit Details")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(task.subjectName,fontWeight=FontWeight.Bold);Text("Lead: ${task.leadTitle}");Text("Sales: ${task.completedVisitUserName?:task.assignedUserName?:"—"}");task.checkedInAt?.let{Text("Check-in: ${followUpTime(it)}")};task.checkedOutAt?.let{Text("Checkout: ${followUpTime(it)}")};Text(if(task.checkedOutAt==null)"Checkout pending" else "Checkout completed",color=SalesMuted)}},confirmButton={TextButton(dismiss){Text("Close")}})}
private fun followUpTime(value:String):String=runCatching{OffsetDateTime.parse(value).atZoneSameInstant(ZoneId.of("Asia/Kolkata")).format(DateTimeFormatter.ofPattern("d MMM yyyy, h:mm a"))}.getOrDefault(value)
