@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.LeadsViewModel
import com.salespunch360.mobile.data.*

@OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
@Composable fun LeadsScreen(vm:LeadsViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;var search by remember{mutableStateOf("")};var stage by remember{mutableStateOf<LeadStage?>(null)};var selected by remember{mutableStateOf<LeadSummary?>(null)};if(state.loading&&state.leads.isEmpty()){LoadingScreen("Loading leads…");return};val visible=state.leads.filter{stage==null||it.stage==stage}.filter{it.title.contains(search,true)||it.companyName?.contains(search,true)==true||it.customer?.name?.contains(search,true)==true};LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(vertical=12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{OutlinedTextField(search,{search=it},Modifier.fillMaxWidth(),label={Text("Search leads")},singleLine=true,leadingIcon={Icon(Icons.Default.Search,null)});LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{FilterChip(stage==null,{stage=null},{Text("All")})};items(LeadStage.entries){item->FilterChip(stage==item,{stage=item},{Text(item.name.lowercase().replaceFirstChar{it.uppercase()})})}};state.message?.let{MessageBanner(it,vm::clear)}};if(visible.isEmpty())item{ContentCard("No leads found","Try another search or pipeline filter.")};items(visible,key={it.id}){lead->OutlinedCard({selected=lead;vm.open(lead.id)},Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Row{Text(lead.title,Modifier.weight(1f),style=MaterialTheme.typography.titleMedium,maxLines=1,overflow=TextOverflow.Ellipsis);StatusChip(lead.stage.name)};Text(lead.customer?.name?:lead.companyName?:lead.contactName?:"Prospect");Text("Assigned to ${lead.assignedUser.name}",style=MaterialTheme.typography.bodySmall);lead.followUpAt?.let{Text("Follow-up $it",style=MaterialTheme.typography.labelMedium)}}}}};selected?.let{summary->val lead=state.detail?.takeIf{it.id==summary.id}?:summary;LeadDialog(lead,state.detailLoading,state.busy,{selected=null;vm.close()},{target,reason->vm.transition(lead,target,reason);selected=null},{at,notes->vm.followUp(lead,at,notes);selected=null})}}
@Composable private fun LeadDialog(lead:LeadSummary,detailLoading:Boolean,busy:Boolean,dismiss:()->Unit,transition:(LeadStage,String?)->Unit,follow:(String?,String?)->Unit){var lostReason by remember{mutableStateOf("")};var followDate by remember{mutableStateOf("")};var notes by remember{mutableStateOf(lead.notes?:"")};val terminal=lead.stage in listOf(LeadStage.WON,LeadStage.LOST);AlertDialog(onDismissRequest=dismiss,title={Text(lead.title)},text={Column(Modifier.heightIn(max=560.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("${lead.stage.name} · ${lead.source}");lead.customer?.let{Text("Customer: ${it.name}")};lead.companyName?.let{Text(it)};lead.phone?.let{Text(it)};lead.followUpAt?.let{Text("Next follow-up: $it")};Text("Activity",style=MaterialTheme.typography.titleSmall);if(detailLoading)LinearProgressIndicator(Modifier.fillMaxWidth()) else if(lead.activities.isEmpty())Text("No recorded activity.",style=MaterialTheme.typography.bodySmall) else lead.activities.forEach{activity->Column(Modifier.fillMaxWidth().padding(vertical=3.dp)){Text(activity.type.replace('_',' ').lowercase().replaceFirstChar{it.uppercase()},style=MaterialTheme.typography.labelLarge);Text(listOfNotNull(activity.actorUser.name,activity.fromStage?.let{from->"$from → ${activity.toStage}"},activity.createdAt).joinToString(" · "),style=MaterialTheme.typography.bodySmall)}};if(!terminal){Text("Move pipeline",style=MaterialTheme.typography.titleSmall);FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){LeadStage.entries.filter{it!=lead.stage}.forEach{target->AssistChip({if(target!=LeadStage.LOST||lostReason.isNotBlank())transition(target,lostReason.ifBlank{null})},{Text(target.name)})}};OutlinedTextField(lostReason,{lostReason=it},label={Text("Lost reason (required for Lost)")});OutlinedTextField(followDate,{followDate=it},label={Text("Follow-up date · YYYY-MM-DD")});OutlinedTextField(notes,{if(it.length<=5000)notes=it},label={Text("Follow-up notes")},minLines=2);Button({follow(if(followDate.isBlank())null else "${followDate}T09:00:00+05:30",notes.ifBlank{null})},enabled=!busy&&(followDate.isBlank()||Regex("\\d{4}-\\d{2}-\\d{2}").matches(followDate))){Text("Save follow-up")}}else Text("This lead is terminal. Company Admin can reopen it where policy allows.")}},confirmButton={},dismissButton={TextButton(dismiss){Text("Close")}})}
