@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.LeadsViewModel
import com.salespunch360.mobile.data.*

@Composable fun LeadsScreen(initialLeadId:String?=null,onInitialLeadConsumed:()->Unit={},onCheckIn:(LeadSummary)->Unit={},vm:LeadsViewModel=viewModel()){
 val state=vm.state.collectAsStateWithLifecycle().value;var selectedStage by remember{mutableStateOf<LeadStage?>(null)};var appliedStage by remember{mutableStateOf<LeadStage?>(null)};var pendingView by remember{mutableStateOf(false)};var stageMenu by remember{mutableStateOf(false)};var detailLead by remember{mutableStateOf<LeadSummary?>(null)};var followLead by remember{mutableStateOf<LeadSummary?>(null)};var transitionLead by remember{mutableStateOf<LeadSummary?>(null)};var deleteLead by remember{mutableStateOf<LeadSummary?>(null)};var phoneVisit by remember{mutableStateOf<PendingLeadVisit?>(null)}
 LaunchedEffect(initialLeadId,state.leads){initialLeadId?.let{id->state.leads.firstOrNull{it.id==id}?.let{detailLead=it;onInitialLeadConsumed()}}}
 if(state.loading&&state.leads.isEmpty()){LoadingScreen("Loading leads…");return};detailLead?.let{lead->LeadDetails(lead,{detailLead=null},{followLead=lead},{onCheckIn(lead)});return};val visible=state.leads.filter{appliedStage==null||it.stage==appliedStage}
 LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(vertical=14.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Text("Leads",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=SalesInk);HorizontalDivider(Modifier.padding(top=8.dp,bottom=10.dp),color=SalesLine);LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{SummaryChip("All Leads",state.leads.size,!pendingView&&appliedStage==null){pendingView=false;selectedStage=null;appliedStage=null}};item{SummaryChip("Pending",state.pending.count,pendingView){pendingView=true}};items(LeadStage.entries){s->SummaryChip(stageLabel(s),state.leads.count{it.stage==s},!pendingView&&appliedStage==s){pendingView=false;selectedStage=s;appliedStage=s}}};if(!pendingView){Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Box(Modifier.weight(1f)){OutlinedButton({stageMenu=true},Modifier.fillMaxWidth()){Text(selectedStage?.let(::stageLabel)?:"All stages",Modifier.weight(1f));Text("⌄")};DropdownMenu(stageMenu,{stageMenu=false}){DropdownMenuItem({Text("All stages")},{selectedStage=null;stageMenu=false});LeadStage.entries.forEach{s->DropdownMenuItem({Text(stageLabel(s))},{selectedStage=s;stageMenu=false})}}};Button({appliedStage=selectedStage}){Text("Filter")}}};state.message?.let{Spacer(Modifier.height(8.dp));MessageBanner(it,vm::clear)}}
  if(pendingView){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Pending",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text(state.pending.count.toString(),color=SalesMuted)}};if(state.pending.visits.isEmpty())item{OutlinedCard(Modifier.fillMaxWidth()){Box(Modifier.padding(24.dp)){Text("No check-ins are waiting for a phone number.",color=SalesMuted)}}};items(state.pending.visits,key={"pending-${it.id}"}){visit->PendingVisitCard(visit,state.busy){phoneVisit=visit}}}else{if(visible.isEmpty())item{OutlinedCard(Modifier.fillMaxWidth()){Box(Modifier.fillMaxWidth().padding(24.dp)){Text("No leads in this stage.",color=SalesMuted)}}};LeadStage.entries.filter{appliedStage==null||it==appliedStage}.forEach{pipelineStage->val stageLeads=visible.filter{it.stage==pipelineStage};item(key="heading-$pipelineStage"){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(stageLabel(pipelineStage),style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold,color=SalesInk);Text(stageLeads.size.toString(),color=SalesMuted)}};items(stageLeads,key={it.id}){lead->LeadCard(lead,state.busy,{detailLead=lead},{followLead=lead},{onCheckIn(lead)},{transitionLead=lead},{deleteLead=lead})}}}
 }
 followLead?.let{lead->FollowUpDialog(lead,state.busy,{followLead=null}){at,notes->vm.followUp(lead,at,notes);followLead=null}};transitionLead?.let{lead->TransitionDialog(lead,state.busy,{transitionLead=null}){target,reason->vm.transition(lead,target,reason);transitionLead=null}};deleteLead?.let{lead->DeleteLeadDialog(lead,state.busy,{deleteLead=null}){vm.delete(lead);deleteLead=null}};phoneVisit?.let{visit->PendingPhoneDialog(visit,state.busy,{phoneVisit=null}){phone->vm.addPendingPhone(visit,phone);phoneVisit=null}}
}
@Composable private fun LeadDetails(lead:LeadSummary,back:()->Unit,followUp:()->Unit,checkIn:()->Unit){LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{TextButton(back,contentPadding=PaddingValues(0.dp)){Text("← Back")};Text("Lead Details",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold,color=SalesInk);HorizontalDivider(Modifier.padding(top=8.dp),color=SalesLine)};item{OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row{Text(lead.title,Modifier.weight(1f),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);StatusChip(stageLabel(lead.stage))};Text(lead.customer?.name?:lead.companyName?:"Prospect",color=SalesInk);Text("Assigned: ${lead.assignedUser.name}",color=SalesMuted);Text("Source: ${lead.source}",color=SalesMuted);Text("${lead.visitCount} check-in / visit${if(lead.visitCount==1)"" else "s"}",color=SalesMuted);lead.estimatedValue?.let{Text("${lead.currencyCode} $it",color=SalesMuted)};lead.updatedAt?.let{Text("Updated ${friendlyLeadDate(it)}",color=SalesMuted);};OutlinedButton(followUp,Modifier.fillMaxWidth()){Text("+ Add Follow-up")};if(lead.canAddCheckIn&&lead.stage !in listOf(LeadStage.WON,LeadStage.LOST))Button(checkIn,Modifier.fillMaxWidth()){Text("+ Add Check-in")}}}}}}
@Composable private fun PendingVisitCard(visit:PendingLeadVisit,busy:Boolean,addPhone:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(visit.customerName?:visit.contactName?:"Field prospect",fontWeight=FontWeight.Bold);Text("${visit.userName} · ${friendlyLeadDateTime(visit.checkedInAt)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text(if(visit.checkedOutAt!=null)"Checked out ${friendlyLeadDateTime(visit.checkedOutAt)}" else "Checkout pending",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text(visit.checkInAddress?:"%.5f, %.5f".format(visit.checkInLatitude,visit.checkInLongitude),style=MaterialTheme.typography.bodySmall,color=SalesMuted);visit.visitNotes?.takeIf{it.isNotBlank()}?.let{Text(it)};if(visit.canAddPhone)OutlinedButton(addPhone,enabled=!busy,modifier=Modifier.fillMaxWidth()){Text("Add phone to create Lead")}}}}
@Composable private fun PendingPhoneDialog(visit:PendingLeadVisit,busy:Boolean,dismiss:()->Unit,save:(String)->Unit){var phone by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Add phone")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(visit.customerName?:visit.contactName?:"Pending check-in",fontWeight=FontWeight.Bold);OutlinedTextField(phone,{phone=it},label={Text("Add phone to create Lead")},singleLine=true)}},confirmButton={Button({save(phone.trim())},enabled=!busy&&phone.isNotBlank()){Text(if(busy)"Adding…" else "Add phone")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
@Composable private fun SummaryChip(label:String,count:Int,selected:Boolean,onClick:()->Unit){FilterChip(selected,onClick,{Column{Text(label,fontWeight=FontWeight.SemiBold);Text(count.toString(),style=MaterialTheme.typography.bodySmall)}})}
@Composable private fun LeadCard(lead:LeadSummary,busy:Boolean,onDetails:()->Unit,onFollowUp:()->Unit,onCheckIn:()->Unit,onTransition:()->Unit,onDelete:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Row{TextButton(onDetails,Modifier.weight(1f),contentPadding=PaddingValues(0.dp)){Text(lead.title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis)};StatusChip(stageLabel(lead.stage))};Text(lead.customer?.name?:lead.companyName?:"Prospect",color=SalesInk);Text("${lead.assignedUser.name} · ${lead.source}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text("${lead.visitCount} check-in / visit${if(lead.visitCount==1)"" else "s"}",style=MaterialTheme.typography.bodySmall,fontWeight=FontWeight.SemiBold,color=SalesMuted);lead.estimatedValue?.let{Text("${lead.currencyCode} $it",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};OutlinedButton(onFollowUp,enabled=!busy,modifier=Modifier.fillMaxWidth()){Text("+ Add Follow-up")};lead.updatedAt?.let{Text("Updated ${friendlyLeadDate(it)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};if(lead.canAddCheckIn)Button(onCheckIn,enabled=!busy&&lead.stage !in listOf(LeadStage.WON,LeadStage.LOST),modifier=Modifier.fillMaxWidth()){Text("+ Add Check-in")};if(lead.canDelete)OutlinedButton(onDelete,enabled=!busy,modifier=Modifier.fillMaxWidth(),colors=ButtonDefaults.outlinedButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("Delete Lead")};if(lead.stage !in listOf(LeadStage.WON,LeadStage.LOST))OutlinedButton(onTransition,enabled=!busy,modifier=Modifier.fillMaxWidth()){Text("Choose next step...")}}}}
@Composable private fun DeleteLeadDialog(lead:LeadSummary,busy:Boolean,dismiss:()->Unit,confirm:()->Unit){AlertDialog(onDismissRequest=dismiss,title={Text("Delete this Lead?")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("This will permanently delete this Lead and all check-ins, visit history and stored photos related to this Lead.");Text("This action cannot be undone.",fontWeight=FontWeight.Bold)}},confirmButton={Button(confirm,enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("Delete Permanently")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
@Composable private fun FollowUpDialog(lead:LeadSummary,busy:Boolean,dismiss:()->Unit,save:(String?,String?)->Unit){var date by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Add Follow-up")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(lead.title,fontWeight=FontWeight.Bold);OutlinedTextField(date,{date=it},label={Text("Due date · YYYY-MM-DD")},singleLine=true);OutlinedTextField(notes,{if(it.length<=5000)notes=it},label={Text("Notes (optional)")},minLines=2)}},confirmButton={Button({save(if(date.isBlank())null else "${date}T09:00:00+05:30",notes.ifBlank{null})},enabled=!busy&&Regex("\\d{4}-\\d{2}-\\d{2}").matches(date)){Text("Add Follow-up")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
@Composable private fun TransitionDialog(lead:LeadSummary,busy:Boolean,dismiss:()->Unit,confirm:(LeadStage,String?)->Unit){var target by remember{mutableStateOf<LeadStage?>(null)};var lostReason by remember{mutableStateOf("")};AlertDialog(onDismissRequest=dismiss,title={Text("Choose next step...")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Current stage: ${stageLabel(lead.stage)}");FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){LeadStage.entries.filter{it!=lead.stage}.forEach{s->FilterChip(target==s,{target=s},{Text(stageLabel(s))})}};if(target==LeadStage.LOST)OutlinedTextField(lostReason,{lostReason=it},label={Text("Lost reason")})}},confirmButton={Button({target?.let{confirm(it,lostReason.ifBlank{null})}},enabled=!busy&&target!=null&&(target!=LeadStage.LOST||lostReason.isNotBlank())){Text("Confirm")}},dismissButton={TextButton(dismiss){Text("Cancel")}})}
private fun stageLabel(stage:LeadStage)=when(stage){LeadStage.NEW->"Lead";LeadStage.QUALIFIED->"Qualified";LeadStage.PROPOSAL->"Prospecting";LeadStage.NEGOTIATION->"Quote Given";LeadStage.WON->"Won";LeadStage.LOST->"Lost"}
private fun friendlyLeadDate(value:String)=runCatching{java.time.OffsetDateTime.parse(value).atZoneSameInstant(java.time.ZoneId.of("Asia/Kolkata")).format(java.time.format.DateTimeFormatter.ofPattern("M/d/yyyy"))}.getOrElse{value.take(10)}
private fun friendlyLeadDateTime(value:String)=runCatching{java.time.OffsetDateTime.parse(value).atZoneSameInstant(java.time.ZoneId.of("Asia/Kolkata")).format(java.time.format.DateTimeFormatter.ofPattern("M/d/yyyy, h:mm a"))}.getOrElse{value}
