@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.ReportsViewModel
import com.salespunch360.mobile.data.MobileRole
import kotlinx.serialization.json.*
private fun reportTypes(role:MobileRole)=when(role){MobileRole.SALES->listOf("check-ins" to "Check-in Report","advanced-check-ins" to "Advanced Check-in","attendance" to "My Attendance","gps" to "My Travel / Distance","leads" to "Lead Report","targets" to "My Performance");MobileRole.MANAGER->listOf("check-ins" to "Check-in Report","advanced-check-ins" to "Advanced Check-in","attendance" to "Attendance Report","gps" to "GPS Route Report","geofence" to "Geofence Report","leads" to "Lead Report","targets" to "Target Analysis");else->listOf("check-ins" to "Check-in Report","advanced-check-ins" to "Advanced Check-in","attendance" to "Attendance Report","gps" to "GPS Route Report","geofence" to "Geofence Report","leads" to "Lead Report","targets" to "Target Analysis","expenses" to "Expense Report")}
@Composable fun ReportsScreen(initialType:String?=null,showMenu:Boolean=true,role:MobileRole=MobileRole.SALES,vm:ReportsViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;val types=remember(role){reportTypes(role)};var expanded by remember{mutableStateOf(showMenu)};LaunchedEffect(initialType){vm.load(initialType?:state.type)};val report=state.report;val rows=report?.get("rows")?.jsonArray?:report?.get("targets")?.jsonArray?:JsonArray(emptyList());LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(vertical=12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text(if(showMenu)"Reports" else types.firstOrNull{it.first==(initialType?:state.type)}?.second?:"Report",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(showMenu){OutlinedButton({expanded=!expanded},Modifier.fillMaxWidth()){Text(if(expanded)"Reports ▲" else "Reports ▼")};if(expanded)types.forEach{(id,label)->TextButton({vm.load(id)},Modifier.fillMaxWidth()){Text(label,Modifier.fillMaxWidth())}}}};item{ReportFilters(state,vm)};if(state.loading)item{LinearProgressIndicator(Modifier.fillMaxWidth())};state.message?.let{item{ContentCard("Report unavailable",it)}};report?.let{r->item{SummaryCards(r["summary"]?.jsonObject);if(state.type=="gps")GpsSummary(r)};if(state.type=="gps"){val events=r["events"]?.jsonArray?:JsonArray(emptyList());items(events.size){EventCard(events[it].jsonObject)}}else if(rows.isEmpty())item{ContentCard("No report records","No records match the selected filters.")}else items(rows.size){ReportRow(rows[it].jsonObject)};val pages=r["totalPages"]?.jsonPrimitive?.intOrNull?:1;if(pages>1)item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){OutlinedButton({vm.load(page=(state.page-1).coerceAtLeast(1))},enabled=state.page>1){Text("Previous")};Text("Page ${state.page} of $pages");Button({vm.load(page=state.page+1)},enabled=state.page<pages){Text("Next")}}}}}}
@Composable private fun SummaryCards(summary:JsonObject?){if(summary==null)return;FlowRow(horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){summary.entries.filterNot{it.key in setOf("firstVisits","repeatVisits")&&it.value.jsonPrimitive.intOrNull==0}.forEach{(k,v)->StatusChip("${prettyLabel(k)} ${value(v)}")}}}
@Composable private fun GpsSummary(r:JsonObject){val sessions=r["sessions"]?.jsonArray?.size?:0;val points=r["points"]?.jsonArray?.size?:0;val metres=r["routeDistanceMeters"]?.jsonPrimitive?.doubleOrNull?:0.0;ContentCard("Stored route","$sessions attendance session${if(sessions==1)"" else "s"} · $points accepted GPS points · ${"%.2f".format(metres/1000)} km"){Text("Route segments: ${r["segments"]?.jsonArray?.size?:0}. Separate attendance sessions are never joined.",style=MaterialTheme.typography.bodySmall)}}
@Composable private fun EventCard(row:JsonObject){ContentCard(prettyLabel(row.text("type")?:"Event"),listOfNotNull(row.text("at"),row.text("customer"),row.text("detail"),coords(row,"latitude","longitude")).joinToString(" · "))}
@Composable private fun ReportRow(row:JsonObject){val title=row.objText("user","name")?:row.objText("assignedUser","name")?:row.objText("employee","name")?:row.objText("customer","name")?:row.text("title")?:"Report record";val hidden=setOf("id","companyId","branchId","userId","customerId","assignedUserId","user","customer","assignedUser");OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(title,fontWeight=FontWeight.Bold);row.entries.filter{it.key !in hidden&&!it.value.isNullish()}.forEach{(k,v)->Text("${prettyLabel(k)}: ${value(v)}",style=MaterialTheme.typography.bodySmall)}}}}
@Composable private fun ReportFilters(state:com.salespunch360.mobile.ReportsState,vm:ReportsViewModel){val employees=state.report?.get("employees")?.jsonArray?:JsonArray(emptyList());val customers=state.report?.get("customers")?.jsonArray?:JsonArray(emptyList());Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){DateField(if(state.type=="gps")"Date" else "Start",state.start,vm::setStart,Modifier.weight(1f));if(state.type!="gps")DateField("End",state.end,vm::setEnd,Modifier.weight(1f))};CycleFilter("Employee",state.employeeId,employees,vm::setEmployee);if(state.type.contains("check-ins"))CycleFilter("Customer",state.customerId,customers,vm::setCustomer);if(state.type.contains("check-ins")){ChoiceRow("Status",state.status,listOf("ALL","ACTIVE","COMPLETED"),vm::setStatus);ChoiceRow("Sentiment",state.sentiment,listOf("ALL","POSITIVE","NEUTRAL","NEGATIVE"),vm::setSentiment)};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.load()}){Text("Apply")};OutlinedButton(vm::reset){Text("Reset")}}}}
@Composable private fun CycleFilter(label:String,selected:String?,options:JsonArray,change:(String?)->Unit){if(options.isEmpty())return;val name=options.firstOrNull{it.jsonObject.text("id")==selected}?.jsonObject?.text("name")?:"All permitted ${label.lowercase()}s";OutlinedButton({val i=options.indexOfFirst{it.jsonObject.text("id")==selected};change(if(i+1>=options.size)null else options[i+1].jsonObject.text("id"))},Modifier.fillMaxWidth()){Text("$label: $name")}}
@Composable private fun ChoiceRow(label:String,current:String,options:List<String>,change:(String)->Unit){Column{Text(label,style=MaterialTheme.typography.labelMedium);FlowRow(horizontalArrangement=Arrangement.spacedBy(4.dp)){options.forEach{FilterChip(current==it,{change(it)},{Text(prettyLabel(it))})}}}}
private fun JsonObject.text(key:String)=this[key]?.jsonPrimitive?.contentOrNull;private fun JsonObject.objText(key:String,child:String)=this[key]?.jsonObject?.get(child)?.jsonPrimitive?.contentOrNull
private fun coords(o:JsonObject,a:String,b:String)=if(o[a]?.jsonPrimitive?.doubleOrNull!=null&&o[b]?.jsonPrimitive?.doubleOrNull!=null)"${o[a]?.jsonPrimitive?.content}, ${o[b]?.jsonPrimitive?.content}" else null
private fun JsonElement.isNullish()=this is JsonNull||(this is JsonPrimitive&&contentOrNull.isNullOrBlank())
private fun value(v:JsonElement):String=when(v){is JsonPrimitive->v.content;is JsonObject->v.entries.joinToString{(k,x)->"${prettyLabel(k)} ${value(x)}"};is JsonArray->"${v.size} item${if(v.size==1)"" else "s"}";else->"—"}
private fun prettyLabel(s:String)=s.replace('_',' ').replace(Regex("([a-z])([A-Z])"),"$1 $2").lowercase().replaceFirstChar{it.uppercase()}
