@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.ReportsViewModel
import kotlinx.serialization.json.*
private val reportTypes=listOf("attendance" to "Attendance","check-ins" to "Visits","advanced-check-ins" to "Advanced visits","leads" to "Pipeline","gps" to "GPS routes","geofence" to "Geofence")
@OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
@Composable fun ReportsScreen(vm:ReportsViewModel=viewModel()){val state=vm.state.collectAsStateWithLifecycle().value;LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(vertical=12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{ReportFilters(state,vm)};item{SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()){reportTypes.take(3).forEachIndexed{i,item->SegmentedButton(selected=state.type==item.first,onClick={vm.load(item.first)},shape=SegmentedButtonDefaults.itemShape(i,3)){Text(item.second)}}};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){reportTypes.drop(3).forEach{item->FilterChip(state.type==item.first,{vm.load(item.first)},{Text(item.second)})}}};if(state.loading)item{LinearProgressIndicator(Modifier.fillMaxWidth())};state.message?.let{item{ContentCard("Report unavailable",it)}};state.report?.let{report->item{Text("Asia/Kolkata reporting period",style=MaterialTheme.typography.labelMedium);SummaryCards(report["summary"]?.jsonObject)};val rows=report["rows"]?.jsonArray?:JsonArray(emptyList());if(rows.isEmpty())item{ContentCard("No report records","No records match the authoritative default reporting period.")}else items(rows.size){index->ReportRow(rows[index].jsonObject)}}}}
@Composable private fun SummaryCards(summary:JsonObject?){if(summary==null)return;FlowRow(horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){summary.entries.take(8).forEach{(label,value)->StatusChip("${label.replaceFirstChar{it.uppercase()}} ${display(value)}")}}}
@Composable private fun ReportRow(row:JsonObject){val user=row["user"]?.jsonObject?.get("name")?.jsonPrimitive?.contentOrNull?:row["assignedUser"]?.jsonObject?.get("name")?.jsonPrimitive?.contentOrNull;val customer=row["customer"]?.jsonObject?.get("name")?.jsonPrimitive?.contentOrNull;ContentCard(user?:row["title"]?.jsonPrimitive?.contentOrNull?:customer?:"Report record",listOfNotNull(customer,row["stage"]?.jsonPrimitive?.contentOrNull,row["startedAt"]?.jsonPrimitive?.contentOrNull?:row["checkedInAt"]?.jsonPrimitive?.contentOrNull,row["routeDistanceMeters"]?.jsonPrimitive?.contentOrNull?.let{"Server distance: $it m"}).joinToString(" · ").ifBlank{"Authoritative report record"})}
private fun display(value:JsonElement):String=when(value){is JsonPrimitive->value.content;is JsonObject->value.entries.joinToString{"${it.key}:${display(it.value)}"};else->"—"}

@Composable private fun ReportFilters(state:com.salespunch360.mobile.ReportsState,vm:ReportsViewModel){val employees=state.report?.get("employees")?.jsonArray?:JsonArray(emptyList());val selected=employees.firstOrNull{it.jsonObject["id"]?.jsonPrimitive?.contentOrNull==state.employeeId}?.jsonObject?.get("name")?.jsonPrimitive?.contentOrNull?:"All permitted employees";Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(state.start,vm::setStart,label={Text("Start YYYY-MM-DD")},modifier=Modifier.weight(1f));OutlinedTextField(state.end,vm::setEnd,label={Text("End YYYY-MM-DD")},modifier=Modifier.weight(1f))};if(employees.isNotEmpty())TextButton({val index=employees.indexOfFirst{it.jsonObject["id"]?.jsonPrimitive?.contentOrNull==state.employeeId};vm.setEmployee(if(index+1>=employees.size)null else employees[index+1].jsonObject["id"]?.jsonPrimitive?.contentOrNull)}){Text("Employee: $selected")};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.load()}){Text("Apply")};OutlinedButton(vm::reset){Text("Reset")}};Text("Dates are interpreted by the server in Asia/Kolkata.",style=MaterialTheme.typography.labelSmall)}}
