@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package com.salespunch360.mobile.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.Alignment
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.salespunch360.mobile.data.*
import kotlinx.coroutines.launch

private const val MANUAL_PAYMENT_MOBILE="9611278818"

@Composable fun SubscriptionScreen(){
 val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();var data by remember{mutableStateOf<MobileBillingContext?>(null)};var error by remember{mutableStateOf<String?>(null)};var loading by remember{mutableStateOf(true)};var loadingMore by remember{mutableStateOf(false)}
 fun reload(){loading=true;error=null;scope.launch{runCatching{api.billing()}.onSuccess{data=it}.onFailure{error="Unable to load subscription."};loading=false}}
 LaunchedEffect(Unit){runCatching{api.billing()}.onSuccess{data=it}.onFailure{error="Unable to load subscription."};loading=false}
 when{loading->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()};error!=null->RetryScreen(error!!,::reload);else->SubscriptionContent(data!!,::reload,loadingMore){if(!loadingMore&&data?.hasMoreOrders==true){loadingMore=true;scope.launch{runCatching{api.billing((data?.orderPage?:1)+1)}.onSuccess{next->data=next.copy(orders=data!!.orders+next.orders)}.onFailure{error="Unable to load more payment history."};loadingMore=false}}}}
}

@Composable private fun SubscriptionContent(data:MobileBillingContext,reload:()->Unit,loadingMore:Boolean,loadMore:()->Unit){
 var checkout by remember{mutableStateOf<BillingQuote?>(null)};var editing by remember{mutableStateOf<String?>(null)};var showOrders by remember{mutableStateOf(false)}
 if(checkout!=null){CheckoutCard(checkout!!){checkout=null;reload()};return}
 val pending=data.orders.firstOrNull{it.status=="PENDING"}
 LazyColumn(Modifier.fillMaxSize().padding(horizontal=14.dp),contentPadding=PaddingValues(vertical=12.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){
  item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text("Subscription",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);pending?.let{StatusChip("Payment Pending")}}}
  if(pending!=null)item{Surface(Modifier.fillMaxWidth(),shape=MaterialTheme.shapes.medium,color=MaterialTheme.colorScheme.secondaryContainer){Text("Ref ${pending.id.take(8).uppercase()} · ₹${pending.totalAmount}",Modifier.padding(10.dp),style=MaterialTheme.typography.bodySmall)}}
  if(data.hasSales)item{
   CompactSalesSummary(data.sales,data.teamStructure,!data.isPlus,{editing=if(editing=="ADD_TEAM")null else "ADD_TEAM"},{editing=if(editing=="SALES")null else "SALES"})
   if(editing=="ADD_TEAM")AddTeamPurchase(data){checkout=it}
   if(editing=="SALES"&&!data.isPlus)SalesPurchase(data){checkout=it}
  }
  if(data.hasAccount)item{
   CompactAccountSummary(data.account,data.isPlus,{editing=if(editing=="ADD_ACCOUNT")null else "ADD_ACCOUNT"},{editing=if(data.isPlus){if(editing=="PLUS")null else "PLUS"}else if(editing=="ACCOUNT")null else "ACCOUNT"})
   if(editing=="ADD_ACCOUNT"&&data.isPlus)AccountIncreasePurchase(data){checkout=it}
   if(editing=="ACCOUNT"&&!data.isPlus)AccountPurchase(data){checkout=it}
   if(editing=="PLUS"&&data.isPlus)SalesPurchase(data){checkout=it}
  }
  item{OutlinedButton({showOrders=!showOrders},Modifier.fillMaxWidth()){Text(if(showOrders)"Hide Payment History" else "Payment History")}}
  if(showOrders)items(data.orders,key={it.id}){o->OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Order ${o.id.take(8).uppercase()}",fontWeight=FontWeight.Bold);StatusChip(o.status)};Text("${periodLabel(o.billingPeriod)} · ${o.currency} ${o.totalAmount}");Text("Created ${o.createdAt.replace('T',' ').take(19)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){if(o.adminSeats>0)StatusChip("Admin ${o.adminSeats}");if(o.managerSeats>0)StatusChip("Manager ${o.managerSeats}");if(o.salesSeats>0)StatusChip("Sales ${o.salesSeats}");if(o.accountPackages>0)StatusChip("Account packages ${o.accountPackages}")};Text("Provider: ${o.provider.replace('_',' ')}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}}}
  if(showOrders&&data.hasMoreOrders)item{OutlinedButton(loadMore,enabled=!loadingMore,modifier=Modifier.fillMaxWidth()){Text(if(loadingMore)"Loading…" else "Load More (${data.orderPage} / ${data.orderTotalPages})")}}
 }
}

@Composable private fun CompactSalesSummary(s:MobileSalesSubscription?,structure:TeamStructure,showRenew:Boolean,addTeam:()->Unit,renew:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Sales Subscription",fontWeight=FontWeight.Bold);StatusChip(s?.status?:"INACTIVE")};s?.endsAt?.let{Text("Valid until ${it.take(10)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){SeatPill("Admin",s?.adminUsage?:0,s?.adminLimit?:0);if(structure!=TeamStructure.SALES_ONLY)SeatPill("Manager",s?.managerUsage?:0,s?.managerLimit?:0);SeatPill("Sales",s?.salesUsage?:0,s?.salesLimit?:0)};if(s?.status=="ACTIVE")Button(addTeam,Modifier.fillMaxWidth()){Text("Add Team / Increase Seats")};if(showRenew)OutlinedButton(renew,Modifier.fillMaxWidth()){Text(if(s?.status=="ACTIVE")"Renew / Change Sales Plan" else "Choose Sales Plan")}}}}
@Composable private fun CompactAccountSummary(a:MobileAccountSubscription?,plus:Boolean,increase:()->Unit,manage:()->Unit){OutlinedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Account Subscription",fontWeight=FontWeight.Bold);StatusChip(a?.status?:"INACTIVE")};a?.endsAt?.let{Text("Valid until ${it.take(10)} · ${a.packageCount} package${if(a.packageCount==1)"" else "s"}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)};FlowRow(horizontalArrangement=Arrangement.spacedBy(6.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){SeatPill("Account Admin",a?.accountAdminUsage?:0,a?.accountAdminLimit?:0);SeatPill("Accountant",a?.accountantUsage?:0,a?.accountantLimit?:0);SeatPill("Project Manager",a?.projectManagerUsage?:0,a?.projectManagerLimit?:0);SeatPill("Data Entry",a?.dataEntryUsage?:0,a?.dataEntryLimit?:0)};if(plus&&a?.status=="ACTIVE")Button(increase,Modifier.fillMaxWidth()){Text("Increase Account Packages")};if(plus)OutlinedButton(manage,Modifier.fillMaxWidth()){Text(if(a?.status=="ACTIVE")"Renew / Change Plus" else "Choose Plus Plan")}else Button(manage,Modifier.fillMaxWidth()){Text("Add / Renew Account Seats")}}}}
@Composable private fun SeatPill(label:String,used:Int,limit:Int){Surface(shape=MaterialTheme.shapes.small,color=SalesPale){Text("$label  $used / $limit",Modifier.padding(horizontal=8.dp,vertical=5.dp),style=MaterialTheme.typography.labelSmall)}}

@Composable private fun AddTeamPurchase(data:MobileBillingContext,onQuote:(BillingQuote)->Unit){
 val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();val s=data.sales?:return
 val period=data.orders.firstOrNull{it.status=="PAID"&&(it.adminSeats+it.managerSeats+it.salesSeats)>0}?.billingPeriod?:"SIX_MONTH"
 var addAdmins by remember{mutableStateOf("0")};var addManagers by remember{mutableStateOf("0")};var addSales by remember{mutableStateOf("0")};var busy by remember{mutableStateOf(false)}
 val addAdminCount=addAdmins.toIntOrNull()?:0;val addManagerCount=if(data.teamStructure==TeamStructure.SALES_ONLY)0 else addManagers.toIntOrNull()?:0;val addSalesCount=addSales.toIntOrNull()?:0
 val adminTarget=s.adminLimit+addAdminCount;val managerTarget=if(data.teamStructure==TeamStructure.SALES_ONLY)0 else s.managerLimit+addManagerCount;val salesTarget=s.salesLimit+addSalesCount;val accountPackages=if(data.isPlus)(data.account?.packageCount?:1).coerceAtLeast(1)else 0;val hasAddition=addAdminCount+addManagerCount+addSalesCount>0
 ContentCard("Add Team / Increase Seats","Add seats now without renewing. Only added seats are prorated to the current expiry."){
  Text("Current period: ${periodLabel(period)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);s.endsAt?.let{Text("Current expiry: ${it.take(10)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}
  NumberField("Add Additional Admin",addAdmins){addAdmins=it};Text("New Additional Admin total: $adminTarget",style=MaterialTheme.typography.labelMedium)
  if(data.teamStructure!=TeamStructure.SALES_ONLY){NumberField("Add Manager",addManagers){addManagers=it};Text("New Manager total: $managerTarget",style=MaterialTheme.typography.labelMedium)}
  NumberField("Add Sales",addSales){addSales=it};Text("New Sales total: $salesTarget",style=MaterialTheme.typography.labelMedium)
  if(data.isPlus)Text("Account packages stay unchanged at $accountPackages.",style=MaterialTheme.typography.bodySmall,color=SalesMuted)
  Text("Retention is not used for Add Team. Renewal and seat reductions are handled separately.",style=MaterialTheme.typography.bodySmall,color=SalesMuted)
  Button({busy=true;scope.launch{runCatching{api.billingQuote(BillingQuoteRequest(billingPeriod=period,adminSeats=adminTarget,managerSeats=managerTarget,salesSeats=salesTarget,accountPackages=accountPackages))}.onSuccess(onQuote);busy=false}},enabled=!busy&&hasAddition,modifier=Modifier.fillMaxWidth()){Text(if(busy)"Calculating…" else "Review Prorated Price")}
 }
}

@Composable private fun AccountIncreasePurchase(data:MobileBillingContext,onQuote:(BillingQuote)->Unit){
 val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();val s=data.sales?:return;val a=data.account?:return
 if(!data.isPlus||s.status!="ACTIVE"||a.status!="ACTIVE")return
 val period=data.orders.firstOrNull{it.status=="PAID"&&it.provider=="PLUS_COMBINED"}?.billingPeriod?:data.orders.firstOrNull{it.status=="PAID"&&(it.adminSeats+it.managerSeats+it.salesSeats)>0}?.billingPeriod?:"SIX_MONTH"
 val currentPackages=a.packageCount.coerceAtLeast(1);var addPackages by remember{mutableStateOf("0")};var busy by remember{mutableStateOf(false)};val addCount=(addPackages.toIntOrNull()?:0).coerceIn(0,(100-currentPackages).coerceAtLeast(0));val targetPackages=currentPackages+addCount;val managerTarget=if(data.teamStructure==TeamStructure.SALES_ONLY)0 else s.managerLimit
 ContentCard("Increase Account Packages","Add Account capacity now without renewing Plus. Only added Account packages are prorated to the current expiry."){
  Text("Current packages: $currentPackages",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text("Current period: ${periodLabel(period)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted);a.endsAt?.let{Text("Current expiry: ${it.take(10)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}
  NumberField("Add Account Packages",addPackages){addPackages=it};Text("New Account package total: $targetPackages",style=MaterialTheme.typography.labelMedium);Text(packageContents(targetPackages),style=MaterialTheme.typography.bodySmall,color=SalesMuted);Text("Sales seat limits stay unchanged.",style=MaterialTheme.typography.bodySmall,color=SalesMuted)
  Button({busy=true;scope.launch{runCatching{api.billingQuote(BillingQuoteRequest(billingPeriod=period,adminSeats=s.adminLimit,managerSeats=managerTarget,salesSeats=s.salesLimit,accountPackages=targetPackages))}.onSuccess(onQuote);busy=false}},enabled=!busy&&addCount>0,modifier=Modifier.fillMaxWidth()){Text(if(busy)"Calculating…" else "Review Prorated Price")}
 }
}

@Composable private fun SalesPurchase(data:MobileBillingContext,onQuote:(BillingQuote)->Unit){
 val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();var period by remember{mutableStateOf("SIX_MONTH")};val s=data.sales;var admins by remember(s){mutableStateOf((s?.adminLimit?:s?.adminUsage?:0).toString())};var managers by remember(s,data.teamStructure){mutableStateOf((if(data.teamStructure==TeamStructure.SALES_ONLY)0 else s?.managerLimit?:s?.managerUsage?:0).toString())};var sales by remember(s){mutableStateOf((s?.salesLimit?:s?.salesUsage?:1).toString())};var accounts by remember(data.account){mutableIntStateOf((data.account?.packageCount?:1).coerceAtLeast(1))};var busy by remember{mutableStateOf(false)};var retained by remember{mutableStateOf(setOf<String>())}
 ContentCard(if(data.isPlus)"Renew / Change Plus" else "Renew / Change Sales Plan",if(data.isPlus)"Choose the next billing period, Account packages and Sales seats." else "Use this flow for renewal or next-term seat changes."){PeriodSelector(period){period=it};if(data.isPlus){PackageSelector(accounts){accounts=it};Text("(${packageContents(accounts)})",style=MaterialTheme.typography.bodySmall,color=SalesMuted);HorizontalDivider();Text("Sales",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};NumberField("Additional Admin Seats",admins){admins=it};if(data.teamStructure!=TeamStructure.SALES_ONLY)NumberField("Manager Seats",managers){managers=it};NumberField("Sales Seats",sales){sales=it};val reduced=listOf(MobileRole.ADMIN to (admins.toIntOrNull()?:0),MobileRole.MANAGER to (managers.toIntOrNull()?:0),MobileRole.SALES to (sales.toIntOrNull()?:0)).filter{(role,count)->data.salesSeatUsers.count{it.salesRole==role}>count};if(reduced.isNotEmpty()){Text("Renewal retention",fontWeight=FontWeight.Bold);Text("Choose users to retain for a next-term reduction. Leave it empty to use server fallback retention rules.",style=MaterialTheme.typography.bodySmall,color=SalesMuted);reduced.forEach{(role,count)->Text("${role.name.replace('_',' ')}: retain up to $count",style=MaterialTheme.typography.labelMedium);data.salesSeatUsers.filter{it.salesRole==role}.forEach{u->Row(verticalAlignment=Alignment.CenterVertically){Checkbox(u.id in retained,{checked->retained=if(checked)retained+u.id else retained-u.id});Text(u.name)}}}};Button({busy=true;scope.launch{runCatching{api.billingQuote(BillingQuoteRequest(billingPeriod=period,adminSeats=admins.toIntOrNull()?:0,managerSeats=managers.toIntOrNull()?:0,salesSeats=sales.toIntOrNull()?:0,accountPackages=if(data.isPlus)accounts else 0,retainAdminUserIds=retained.filter{id->data.salesSeatUsers.any{it.id==id&&it.salesRole==MobileRole.ADMIN}},retainManagerUserIds=retained.filter{id->data.salesSeatUsers.any{it.id==id&&it.salesRole==MobileRole.MANAGER}},retainSalesUserIds=retained.filter{id->data.salesSeatUsers.any{it.id==id&&it.salesRole==MobileRole.SALES}}))}.onSuccess(onQuote);busy=false}},enabled=!busy&&(sales.toIntOrNull()?:0)+(managers.toIntOrNull()?:0)>0,modifier=Modifier.fillMaxWidth()){Text(if(busy)"Calculating…" else "Review Checkout")}}
}

@Composable private fun AccountPurchase(data:MobileBillingContext,onQuote:(BillingQuote)->Unit){val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();var period by remember{mutableStateOf("SIX_MONTH")};var quantity by remember{mutableIntStateOf(1)};var busy by remember{mutableStateOf(false)};val six=data.prices.firstOrNull{it.role=="ACCOUNT_PACKAGE"&&it.period=="SIX_MONTH"}?.amount?:"400.00";val year=data.prices.firstOrNull{it.role=="ACCOUNT_PACKAGE"&&it.period=="YEARLY"}?.amount?:"700.00";ContentCard("Account Packages","6 Months ₹$six · Yearly ₹$year per package."){PeriodSelector(period){period=it};PackageSelector(quantity){quantity=it};Text("(${packageContents(quantity)})",style=MaterialTheme.typography.bodySmall,color=SalesMuted);Button({busy=true;scope.launch{runCatching{api.billingQuote(BillingQuoteRequest(kind="ACCOUNT_PACKAGE",billingPeriod=period,quantity=quantity))}.onSuccess(onQuote);busy=false}},enabled=!busy,modifier=Modifier.fillMaxWidth()){Text(if(busy)"Calculating…" else "Review Checkout")}}}
@Composable private fun PeriodSelector(period:String,change:(String)->Unit){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("SIX_MONTH" to "6 Month","YEARLY" to "Yearly").forEach{(value,label)->FilterChip(selected=period==value,onClick={change(value)},label={Text(label)})}}}
@Composable private fun PackageSelector(value:Int,change:(Int)->Unit){var expanded by remember{mutableStateOf(false)};Column(verticalArrangement=Arrangement.spacedBy(4.dp)){Text("Account Packages",fontWeight=FontWeight.SemiBold);Box{OutlinedButton({expanded=true},Modifier.fillMaxWidth()){Text(value.toString(),Modifier.fillMaxWidth())};DropdownMenu(expanded,{expanded=false}){(1..100).forEach{count->DropdownMenuItem(text={Text(count.toString())},onClick={change(count);expanded=false})}}}}}
@Composable private fun NumberField(label:String,value:String,change:(String)->Unit){OutlinedTextField(value,{change(it.filter(Char::isDigit).take(5))},label={Text(label)},singleLine=true,modifier=Modifier.fillMaxWidth())}
private fun packageContents(count:Int)="$count package${if(count==1)"" else "s"} = $count Account Admin, $count Accountant, $count Project Manager, $count Data Entry"
private fun periodLabel(value:String)=when(value){"SIX_MONTH"->"6 Month";"YEARLY"->"Yearly";else->value.replace('_',' ')}

@Composable private fun CheckoutCard(q:BillingQuote,back:()->Unit){
 val context=LocalContext.current;val api=remember{ApiClient(SecureSession(context))};val scope=rememberCoroutineScope();var pending by remember{mutableStateOf<ManualOrderResponse?>(null)};var busy by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)}
 pending?.let{order->LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Payment Pending",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);ContentCard("Manual Payment","Order ref ${order.id.take(8).uppercase()}"){Text("₹${order.totalAmount}",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Awaiting Super Admin payment verification.",style=MaterialTheme.typography.bodySmall);Text("WhatsApp / Call $MANUAL_PAYMENT_MOBILE",fontWeight=FontWeight.Bold)};Button(back,Modifier.fillMaxWidth()){Text("Back to Subscription")}}};return}
 LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{TextButton(back){Text("← Subscription")};Text("Checkout",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);ContentCard("Review","${q.kind.replace('_',' ')} · ${periodLabel(q.billingPeriod)}"){q.salesSubtotal?.let{if(it!="0.00")Text("Sales subtotal ₹$it")};q.accountSubtotal?.let{if(it!="0.00")Text("Account subtotal ₹$it")};if(q.prorated){Text("Only mid-term additions are charged for the remaining time.",style=MaterialTheme.typography.bodySmall,color=SalesMuted);q.coTermEndsAt?.let{Text("Existing expiry stays ${it.take(10)}",style=MaterialTheme.typography.bodySmall,color=SalesMuted)}};Text("Total payable",style=MaterialTheme.typography.bodySmall);Text("₹${q.totalAmount}",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold)}}
  item{ContentCard("Manual Payment","After creating the request, WhatsApp / call $MANUAL_PAYMENT_MOBILE. Super Admin activates the subscription after verification."){error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({busy=true;error=null;scope.launch{val key="android_"+java.util.UUID.randomUUID().toString().replace("-","");val request=ManualOrderRequest(kind=q.kind,billingPeriod=q.billingPeriod,adminSeats=q.adminSeats,managerSeats=q.managerSeats,salesSeats=q.salesSeats,accountPackages=q.accountPackages,quantity=if(q.kind=="ACCOUNT_PACKAGE")q.quantity else null,retainAdminUserIds=q.retainAdminUserIds,retainManagerUserIds=q.retainManagerUserIds,retainSalesUserIds=q.retainSalesUserIds,idempotencyKey=key);runCatching{api.createManualOrder(request)}.onSuccess{pending=it}.onFailure{error="Unable to create payment request."};busy=false}},enabled=!busy,modifier=Modifier.fillMaxWidth()){Text(if(busy)"Creating…" else "Manual Payment")}}}
 }
}
