import Link from "next/link";
import { AccountCard, AccountPageHeader } from "@/components/account/account-shell";
import { requirePermission } from "@/lib/auth/authorization";
import { resolveAccountBranchContext } from "@/lib/account/branch-context";
import { accountBranchDashboard } from "@/lib/account/branch-dashboard";
import { enabledModulesForCompany } from "@/lib/account/modules";
import { formatInr } from "@/lib/account/presentation";
import { db } from "@/lib/db";
import { dashboardCardVisibility } from "@/lib/account/dashboard-policy";
type Query={branchId?:string;scope?:string};
export default async function Page({searchParams}:{searchParams:Promise<Query>}){const rawActor=await requirePermission("ACCOUNT_DASHBOARD"),actor={...rawActor,companyId:rawActor.companyId!},query=await searchParams,resolved=await resolveAccountBranchContext(actor,{branchId:query.branchId,scope:query.scope}),now=new Date(),year=await db.financialYear.findFirst({where:{companyId:actor.companyId,status:"OPEN"},orderBy:{startDate:"desc"},select:{name:true,startDate:true}}),from=year?.startDate??new Date(Date.UTC(now.getUTCFullYear(),3,1)),[data,modules]=await Promise.all([accountBranchDashboard(actor,resolved.context,from,now),enabledModulesForCompany(actor.companyId)]),title=resolved.context.mode==="COMPANY"?"Company Consolidated Dashboard":`${resolved.context.branchName} Dashboard`,period=year?.name??from.toLocaleDateString("en-IN");if(data.projectOnly)return <><AccountPageHeader title={title} subtitle={`Authorized Projects · ${period}`}/><section className="account-stat-grid"><AccountCard><small>Assigned projects</small><strong>{data.projects}</strong></AccountCard><AccountCard><small>Project value</small><strong>{formatInr(data.projectValue)}</strong></AccountCard></section></>;
 const visible=dashboardCardVisibility(modules),trendMax=Math.max(1,...data.salesTrend.map(point=>Number(point.total)));return <><AccountPageHeader title={title} subtitle={`Current Financial Year · ${period}`}/><div className="account-dashboard-modern">{visible.sales&&<AccountCard className="account-sale-overview"><small>SALE OVERVIEW · CURRENT MONTH</small><h2>Sales revenue</h2><strong>{formatInr(data.currentMonthSales)}</strong><p>{data.salesGrowthPercent===null?"Previous-period comparison becomes available after the first recorded month.":`${data.salesGrowthPercent.gte(0)?"↑":"↓"} ${data.salesGrowthPercent.abs().toString()}% from previous month`}</p><div className="account-mini-chart" aria-label="Six month sales trend">{data.salesTrend.map(point=><span key={point.month}><i style={{height:`${Math.max(3,Number(point.total)/trendMax*100)}%`}}/><small>{point.month.slice(5)}</small></span>)}</div></AccountCard>}<section className="account-dashboard-pair">{visible.expenses&&<AccountCard><small>EXPENSES</small><h2>{formatInr(data.currentMonthExpenses)}</h2><p>Posted this month</p></AccountCard>}<AccountCard><small>CASH &amp; BANK</small><h2>{formatInr(data.cashBank)}</h2><p>Ledger-backed balance</p></AccountCard></section>{visible.inventory&&<AccountCard className="account-inventory-overview"><small>INVENTORY</small><h2>{formatInr(data.stockValue)}</h2><div className="account-breakdown-row"><span>Items <strong>{data.itemCount}</strong></span><span>Low stock <strong>{data.lowStockItems}</strong></span></div><Link href="/workspace/account/inventory">See all items →</Link></AccountCard>}<AccountCard className="account-reports-overview"><small>REPORTS</small><h2>Understand your business</h2><p>Open ledger-backed financial, sales, tax and inventory reports.</p><Link href="/workspace/account/reports">See Reports →</Link></AccountCard>{visible.expenses&&<AccountCard><small>EXPENSE BREAKDOWN · CURRENT MONTH</small><h2>Top categories</h2>{data.expenseBreakdown.length?data.expenseBreakdown.map(row=><div className="account-breakdown-row" key={row.categoryId}><span>{row.category}</span><strong>{formatInr(row.amount)}</strong></div>):<p>No posted expenses this month.</p>}<Link href="/workspace/account/reports/profit-loss">See expense report →</Link></AccountCard>}</div>{resolved.context.mode==="COMPANY"&&(visible.sales||visible.expenses)&&<AccountCard><h2>Branch comparison</h2><div className="account-table-wrap"><table><thead><tr><th>Branch</th>{visible.sales&&<th>Sales</th>}{visible.expenses&&<th>Expenses</th>}{visible.sales&&visible.expenses&&<th>Operating contribution</th>}</tr></thead><tbody>{data.branchComparison.map(row=><tr key={row.id}><td>{row.name}</td>{visible.sales&&<td>{formatInr(row.sales)}</td>}{visible.expenses&&<td>{formatInr(row.expenses)}</td>}{visible.sales&&visible.expenses&&<td>{formatInr(row.operatingContribution)}</td>}</tr>)}</tbody></table></div></AccountCard>}</>}
