import { AccountCard, AccountPageHeader } from "@/components/account/account-shell";
import { requirePermission } from "@/lib/auth/authorization";
import { resolveAccountBranchContext } from "@/lib/account/branch-context";
import { accountBranchDashboard } from "@/lib/account/branch-dashboard";
import { enabledModulesForCompany } from "@/lib/account/modules";
import { formatInr } from "@/lib/account/presentation";
import { db } from "@/lib/db";
import { dashboardCardVisibility } from "@/lib/account/dashboard-policy";
type Query={branchId?:string;scope?:string};
export default async function Page({searchParams}:{searchParams:Promise<Query>}){const rawActor=await requirePermission("ACCOUNT_DASHBOARD"),actor={...rawActor,companyId:rawActor.companyId!},query=await searchParams,resolved=await resolveAccountBranchContext(actor,{branchId:query.branchId,scope:query.scope}),now=new Date(),year=await db.financialYear.findFirst({where:{companyId:actor.companyId,status:"OPEN"},orderBy:{startDate:"desc"},select:{name:true,startDate:true}}),from=year?.startDate??new Date(Date.UTC(now.getUTCFullYear(),3,1)),[data,modules]=await Promise.all([accountBranchDashboard(actor,resolved.context,from,now),enabledModulesForCompany(actor.companyId)]),title=resolved.context.mode==="COMPANY"?"Company Consolidated Dashboard":`${resolved.context.branchName} Dashboard`,period=year?.name??from.toLocaleDateString("en-IN");if(data.projectOnly)return <><AccountPageHeader title={title} subtitle={`Authorized Projects · ${period}`}/><section className="account-stat-grid"><AccountCard><small>Assigned projects</small><strong>{data.projects}</strong></AccountCard><AccountCard><small>Project value</small><strong>{formatInr(data.projectValue)}</strong></AccountCard></section></>;
 const visible=dashboardCardVisibility(modules),cards=[...(visible.sales?[["Tax-exclusive Sales Revenue",data.sales] as const,["Receivables",data.receivables] as const]:[]),...(visible.purchases?[["Tax-exclusive Purchases",data.purchases] as const,["Vendor Payables",data.payables] as const]:[]),["Cash / Bank",data.cashBank] as const,["Profit (A14 ledger)",data.profit] as const,...(visible.expenses?[["Posted Expenses",data.expenses] as const]:[]),...(visible.projects?[["Active Projects",data.projects] as const,["Project Value",data.projectValue] as const]:[]),...(visible.inventory?[["Inventory Value",data.stockValue] as const,["Warehouses",data.warehouses] as const]:[])];return <><AccountPageHeader title={title} subtitle={`Current Financial Year · ${period}`}/><section className="account-stat-grid">{cards.map(([label,value])=><AccountCard key={label}><small>{label}</small><strong>{typeof value==="number"?value:formatInr(value)}</strong></AccountCard>)}</section>{resolved.context.mode==="COMPANY"&&(visible.sales||visible.expenses)&&<AccountCard><h2>Branch comparison</h2><div className="account-table-wrap"><table><thead><tr><th>Branch</th>{visible.sales&&<th>Sales</th>}{visible.expenses&&<th>Expenses</th>}{visible.sales&&visible.expenses&&<th>Operating contribution</th>}</tr></thead><tbody>{data.branchComparison.map(row=><tr key={row.id}><td>{row.name}</td>{visible.sales&&<td>{formatInr(row.sales)}</td>}{visible.expenses&&<td>{formatInr(row.expenses)}</td>}{visible.sales&&visible.expenses&&<td>{formatInr(row.operatingContribution)}</td>}</tr>)}</tbody></table></div></AccountCard>}</>}
