package com.salespunch360.mobile

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.salespunch360.mobile.account.*
import com.salespunch360.mobile.data.*
import java.io.IOException
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.*

class AccountSalesViewModel(app:Application):AndroidViewModel(app){private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(AccountSalesState());val state:StateFlow<AccountSalesState> = _state;private var searchJob:Job?=null
 init{refresh()}
 fun refresh(){searchJob?.cancel();searchJob=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);try{val raw=api.accountSalesOptions();val options=SalesOptions(raw["allowedDocumentTypes"]?.jsonArray?.map{it.jsonPrimitive.content}.orEmpty(),raw.array("branches").map{it.option()},raw.array("customers").map{it.option()},raw.array("products").map{it.option()},raw.array("services").map{it.option("sellingRate")},raw.array("workPackages").map{it.option("sellingRate")},raw.array("warehouses").map{it.option()},raw.array("projects").map{it.option()},raw.array("sourceDocuments"));val rows=loadRows();_state.value=_state.value.copy(loading=false,options=options,rows=rows)}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}}}
 fun search(value:String){_state.value=_state.value.copy(query=value);reloadRows()};fun filter(type:String?){_state.value=_state.value.copy(typeFilter=type);reloadRows()}
 private fun reloadRows(){searchJob?.cancel();searchJob=viewModelScope.launch{_state.value=_state.value.copy(loading=true);try{_state.value=_state.value.copy(loading=false,rows=loadRows())}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}}}
 private suspend fun loadRows()=api.accountSalesDocuments(_state.value.typeFilter,_state.value.query).map{it.jsonObject}.map{SalesDocumentRow(it.str("id"),it.str("type"),it.str("documentNumber"),it.str("partyName"),it.str("issueDate").take(10),it.str("status"),it.str("grandTotal"))}
 fun newDocument(type:String){val o=_state.value.options;_state.value=_state.value.copy(editor=SalesEditorDraft(type=type,branchId=o.branches.firstOrNull()?.id.orEmpty()),detail=null,error=null,message=null)}
 fun editDraft(value:SalesEditorDraft){_state.value=_state.value.copy(editor=value)};fun closeEditor(){_state.value=_state.value.copy(editor=null)}
 fun addLine(){_state.value.editor?.let{editDraft(it.copy(lines=it.lines+SalesLineDraft()))}};fun updateLine(index:Int,line:SalesLineDraft){_state.value.editor?.let{editDraft(it.copy(lines=it.lines.mapIndexed{i,x->if(i==index)line else x}))}};fun removeLine(index:Int){_state.value.editor?.let{if(it.lines.size>1)editDraft(it.copy(lines=it.lines.filterIndexed{i,_->i!=index}))}}
 fun save(){val draft=_state.value.editor?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);try{val payload=buildJsonObject{put("type",draft.type);put("branchId",draft.branchId);put("partyId",draft.customerId);draft.sourceDocumentId.takeIf{it.isNotBlank()}?.let{put("sourceDocumentId",it)};put("issueDate",draft.issueDate);draft.dueDate.takeIf{it.isNotBlank()}?.let{put("dueDate",it)};put("taxMode",draft.taxMode);draft.stateOfSupplyCode.takeIf{it.isNotBlank()}?.let{put("stateOfSupplyCode",it)};draft.projectId.takeIf{it.isNotBlank()}?.let{put("projectId",it)};put("notes",draft.notes);put("tcsRate",draft.tcsRate);putJsonArray("lines"){draft.lines.forEach{line->add(buildJsonObject{put("lineType",line.lineType);line.sourceId.takeIf{it.isNotBlank()}?.let{put("sourceId",it)};line.itemName.takeIf{it.isNotBlank()}?.let{put("itemName",it)};put("description",line.description);put("quantity",line.quantity);line.rate.takeIf{it.isNotBlank()}?.let{put("rate",it)};line.discountType.takeIf{it.isNotBlank()}?.let{put("discountType",it);put("discountValue",line.discountValue)};line.taxRate.takeIf{it.isNotBlank()}?.let{put("taxRate",it)};line.warehouseId.takeIf{it.isNotBlank()}?.let{put("warehouseId",it)};line.sourceCommercialLineId.takeIf{it.isNotBlank()}?.let{put("sourceCommercialLineId",it)};put("stockReturnQuantity",line.stockReturnQuantity)})}}};val created=api.createAccountSalesDocument(payload);_state.value=_state.value.copy(saving=false,editor=null,detail=api.accountSalesDocument(created.str("id")),message="Draft created with server totals.");refresh()}catch(e:Exception){_state.value=_state.value.copy(saving=false,error=errorText(e))}}}
 fun open(id:String)=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);try{_state.value=_state.value.copy(loading=false,detail=api.accountSalesDocument(id))}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}};fun closeDetail(){_state.value=_state.value.copy(detail=null)}
 fun requestPost(id:String){_state.value=_state.value.copy(postingId=id)};fun cancelPost(){_state.value=_state.value.copy(postingId=null)};fun confirmPost(){val id=_state.value.postingId?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,postingId=null);try{api.postAccountSalesDocument(id);_state.value=_state.value.copy(saving=false,detail=api.accountSalesDocument(id),message="Document posted successfully.");refresh()}catch(e:Exception){_state.value=_state.value.copy(saving=false,error=errorText(e))}}}
 private fun errorText(e:Exception)=when{e is IOException->"You're offline. Financial changes were not submitted.";e is ApiException&&e.status==403->"You are not authorized for this action.";e is ApiException&&e.code=="INVALID_INPUT"->"Check the document fields and line items.";else->"The server could not complete this Account action."}
}
