package com.salespunch360.mobile
import android.app.Application;import androidx.lifecycle.AndroidViewModel;import androidx.lifecycle.viewModelScope;import com.salespunch360.mobile.data.*;import java.io.IOException;import kotlinx.coroutines.flow.*;import kotlinx.coroutines.launch;import kotlinx.coroutines.Job;import kotlinx.coroutines.CancellationException;import kotlinx.serialization.json.*
data class JournalLineDraft(val ledgerId:String="",val costCentreId:String="",val debit:String="0",val credit:String="0",val description:String="")
data class JournalDraft(val requestKey:String=java.util.UUID.randomUUID().toString(),val opening:Boolean=false,val financialYearId:String="",val branchId:String="",val date:String=java.time.LocalDate.now().toString(),val reference:String="",val narration:String="",val lines:List<JournalLineDraft> = listOf(JournalLineDraft(debit="1"),JournalLineDraft(credit="1")))
data class AccountingState(val journalRows:List<JsonObject> = emptyList(),val journalPage:Int=1,val hasMore:Boolean=false,val branchFilter:String="",val fromFilter:String="",val toFilter:String="",val loading:Boolean=false,val saving:Boolean=false,val query:String="",val data:JsonObject=buildJsonObject{},val journal:JsonObject?=null,val draft:JournalDraft?=null,val editor:String?=null,val error:String?=null,val message:String?=null)
class AccountAccountingViewModel(app:Application):AndroidViewModel(app){private var historyJob:Job?=null;private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(AccountingState());val state:StateFlow<AccountingState> = _state;init{load()};fun load()=viewModelScope.launch{try{_state.value=_state.value.copy(loading=true,error=null);_state.value=_state.value.copy(loading=false,data=api.accountingOverview());history()}catch(e:Exception){fail(e)}};fun search(q:String){_state.value=_state.value.copy(query=q,journalRows=emptyList(),journalPage=1,hasMore=false)};fun editor(kind:String?){_state.value=_state.value.copy(editor=kind)};fun newJournal(opening:Boolean=false){val d=_state.value.data;_state.value=_state.value.copy(draft=JournalDraft(opening=opening,financialYearId=d["financialYears"]?.jsonArray?.firstOrNull()?.jsonObject?.get("id")?.jsonPrimitive?.content.orEmpty(),branchId=d["branches"]?.jsonArray?.firstOrNull()?.jsonObject?.get("id")?.jsonPrimitive?.content.orEmpty()))};fun draft(v:JournalDraft){_state.value=_state.value.copy(draft=v)};fun close(){if(_state.value.saving)return;_state.value=_state.value.copy(draft=null,journal=null,editor=null)};fun openJournal(id:String)=viewModelScope.launch{try{_state.value=_state.value.copy(journal=api.journal(id))}catch(e:Exception){fail(e)}}
 fun saveJournal()=viewModelScope.launch{if(_state.value.saving)return@launch;val d=_state.value.draft?:return@launch;_state.value=_state.value.copy(saving=true,error=null);try{val payload=buildJsonObject{put("financialYearId",d.financialYearId);put("branchId",d.branchId);put("entryDate",d.date);put("sourceType",if(d.opening)"OPENING_BALANCE" else "MANUAL_JOURNAL");put("sourceId",d.requestKey);put("postingPurpose","PRIMARY");d.reference.takeIf{it.isNotBlank()}?.let{put("reference",it)};d.narration.takeIf{it.isNotBlank()}?.let{put("narration",it)};putJsonArray("lines"){d.lines.forEach{l->add(buildJsonObject{put("ledgerAccountId",l.ledgerId);l.costCentreId.takeIf{it.isNotBlank()}?.let{put("costCentreId",it)};put("debit",l.debit);put("credit",l.credit);l.description.takeIf{it.isNotBlank()}?.let{put("description",it)}})}}};api.accountingAction(if(d.opening)"opening" else "journals",payload);_state.value=_state.value.copy(saving=false,draft=null,message="Journal posted after server validation.");load()}catch(e:Exception){fail(e)}}
 fun reverse(id:String,date:String,reason:String)=viewModelScope.launch{if(_state.value.saving)return@launch;_state.value=_state.value.copy(saving=true,error=null);try{api.reverseJournal(id,buildJsonObject{put("entryDate",date);put("reason",reason)});_state.value=_state.value.copy(saving=false,journal=null,message="Journal reversed by server.");load()}catch(e:Exception){fail(e)}}
 fun save(kind:String,p:JsonObject)=viewModelScope.launch{if(_state.value.saving)return@launch;_state.value=_state.value.copy(saving=true,error=null);try{when(kind){"ledgers"->api.accountingAction("ledgers",p);"cost-centres"->api.accountingAction("cost-centres",p);"period-locks"->api.accountingAction("period-locks",p);"financial-years"->api.createFinancialYear(p);"close-year"->api.closeFinancialYear(p)};_state.value=_state.value.copy(saving=false);editor(null);load()}catch(e:Exception){fail(e)}}
 fun history(branch:String=_state.value.branchFilter,from:String=_state.value.fromFilter,to:String=_state.value.toFilter,more:Boolean=false){historyJob?.cancel();historyJob=viewModelScope.launch{val snapshot=_state.value;val page=if(more)snapshot.journalPage+1 else 1;_state.value=snapshot.copy(loading=true,error=null,branchFilter=branch,fromFilter=from,toFilter=to);try{val result=api.journalHistory(snapshot.query,page,branch,from,to);val rows=result["items"]?.jsonArray?.map{it.jsonObject}.orEmpty();_state.value=_state.value.copy(loading=false,journalPage=page,hasMore=result["hasMore"]?.jsonPrimitive?.booleanOrNull==true,journalRows=if(more)snapshot.journalRows+rows else rows)}catch(e:CancellationException){throw e}catch(e:Exception){fail(e)}}}
 private fun fail(e:Exception){_state.value=_state.value.copy(loading=false,saving=false,error=when{e is IOException->"Offline. No accounting action was confirmed.";e is ApiException&&e.status==403->"Permission or subscription entitlement denied this action.";e is ApiException && e.serverMessage!=null->e.serverMessage;else->"Authoritative accounting validation rejected this action."})}}
