package com.salespunch360.mobile

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.salespunch360.mobile.account.*
import com.salespunch360.mobile.data.*
import java.io.IOException
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.*

class AccountSalesViewModel(app:Application):AndroidViewModel(app){private val session=SecureSession(app);private val api=ApiClient(session);private val amendments=SaleAmendmentClient(session);private val _state=MutableStateFlow(AccountSalesState());val state:StateFlow<AccountSalesState> = _state;private var searchJob:Job?=null;private val creationIdentity=CommercialCreationIdentity()
 init{refresh()}
 fun refresh(){searchJob?.cancel();searchJob=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);try{val raw=api.accountSalesOptions();val options=SalesOptions(types=raw["allowedDocumentTypes"]?.jsonArray?.map{it.jsonPrimitive.content}.orEmpty(),branches=raw.array("branches").map{it.option()},customers=raw.array("customers").map{it.option()},products=raw.array("products").map{it.option()},services=raw.array("services").map{it.option("sellingRate")},workPackages=raw.array("workPackages").map{it.option("sellingRate")},warehouses=raw.array("warehouses").map{it.option()},projects=raw.array("projects").map{it.option()},units=raw.array("units").map{it.option()},sourceDocuments=raw.array("sourceDocuments"),numberingSeries=raw.array("numberingSeries").map{NumberingPreview(it.str("branchId"),it.str("prefix"),it.str("suffix"),it.str("padding").toIntOrNull()?:2,it.str("nextSequence").toLongOrNull()?:1)});val rows=loadRows();_state.value=_state.value.copy(loading=false,options=options,rows=rows)}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}}}
 fun search(value:String){_state.value=_state.value.copy(query=value);reloadRows()};fun filter(type:String?){_state.value=_state.value.copy(typeFilter=type);reloadRows()}
 private fun reloadRows(){searchJob?.cancel();searchJob=viewModelScope.launch{_state.value=_state.value.copy(loading=true);try{_state.value=_state.value.copy(loading=false,rows=loadRows())}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}}}
 private suspend fun loadRows()=api.accountSalesDocuments(_state.value.typeFilter,_state.value.query).map{it.jsonObject}.map{SalesDocumentRow(it.str("id"),it.str("type"),it.str("documentNumber"),it.str("partyName"),it.str("issueDate").take(10),it.str("status"),it.str("grandTotal"),it.str("outstanding"),it.str("paymentStatus"))}
 fun newDocument(type:String){if(_state.value.saving)return;creationIdentity.reset();val o=_state.value.options;_state.value=_state.value.copy(editor=SalesEditorDraft(type=type,branchId=o.branches.firstOrNull()?.id.orEmpty()),detail=null,error=null,message=null)}
 fun updateInvoicePrefix(prefix:String){val draft=_state.value.editor?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);runCatching{api.saveSalesInvoicePrefix(draft.branchId,prefix)}.onSuccess{row->val preview=NumberingPreview(row.str("branchId"),row.str("prefix"),row.str("suffix"),row.str("padding").toIntOrNull()?:2,row.str("nextSequence").toLongOrNull()?:1);_state.value=_state.value.copy(saving=false,options=_state.value.options.copy(numberingSeries=_state.value.options.numberingSeries.filterNot{it.branchId==draft.branchId}+preview),message="Invoice prefix saved.")}.onFailure{_state.value=_state.value.copy(saving=false,error=errorText(it as Exception))}}}
 fun createSaleCustomer(fields:JsonObject,done:(String)->Unit){val draft=_state.value.editor?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);runCatching{api.saveAccountMaster("customers",null,buildJsonObject{put("branchId",draft.branchId);fields.forEach{(key,value)->put(key,value)}})}.onSuccess{customer->_state.value=applyCreatedSaleCustomer(_state.value,SalesOption(customer.id,customer.name,customer.branchId,phone=customer.phone));done(customer.id);refresh()}.onFailure{_state.value=_state.value.copy(saving=false,error=errorText(it as Exception))}}}
 fun editDraft(value:SalesEditorDraft){if(_state.value.saving)return;_state.value=_state.value.copy(editor=value)};fun closeEditor(){if(_state.value.saving)return;_state.value=_state.value.copy(editor=null)}
 fun addLine(){_state.value.editor?.let{editDraft(it.copy(lines=it.lines+SalesLineDraft()))}};fun updateLine(index:Int,line:SalesLineDraft){_state.value.editor?.let{editDraft(it.copy(lines=it.lines.mapIndexed{i,x->if(i==index)line else x}))}};fun removeLine(index:Int){_state.value.editor?.let{if(it.lines.size>1)editDraft(it.copy(lines=it.lines.filterIndexed{i,_->i!=index}))}}
 private fun payload(draft:SalesEditorDraft)=buildJsonObject{put("type",draft.type);put("branchId",draft.branchId);put("partyId",draft.customerId);draft.sourceDocumentId.takeIf{it.isNotBlank()}?.let{put("sourceDocumentId",it)};put("issueDate",draft.issueDate);draft.dueDate.takeIf{it.isNotBlank()}?.let{put("dueDate",it)};put("taxMode",draft.taxMode);draft.stateOfSupplyCode.takeIf{it.isNotBlank()}?.let{put("stateOfSupplyCode",it)};draft.projectId.takeIf{it.isNotBlank()}?.let{put("projectId",it)};put("notes",draft.notes);put("tcsRate",draft.tcsRate);if(draft.type=="SALES_INVOICE"&&draft.editingSourceId.isBlank()){put("receivedAmount",if(draft.receivedEnabled)draft.receivedAmount.ifBlank{"0"} else "0");put("paymentType",draft.paymentType)};putJsonArray("lines"){draft.lines.forEach{line->add(buildJsonObject{put("lineType",line.lineType);line.sourceId.takeIf{it.isNotBlank()}?.let{put("sourceId",it)};line.itemName.takeIf{it.isNotBlank()}?.let{put("itemName",it)};put("description",line.description);line.unitName.takeIf{it.isNotBlank()}?.let{put("unitName",it)};line.unitSymbol.takeIf{it.isNotBlank()}?.let{put("unitSymbol",it)};put("quantity",line.quantity);line.rate.takeIf{it.isNotBlank()}?.let{put("rate",it)};line.discountType.takeIf{it.isNotBlank()}?.let{put("discountType",it);put("discountValue",line.discountValue)};line.taxRate.takeIf{it.isNotBlank()}?.let{put("taxRate",it)};line.warehouseId.takeIf{it.isNotBlank()}?.let{put("warehouseId",it)};line.sourceCommercialLineId.takeIf{it.isNotBlank()}?.let{put("sourceCommercialLineId",it)};put("stockReturnQuantity",line.stockReturnQuantity)})}}}
 fun save(saveAndNew:Boolean=false){if(_state.value.saving)return;val draft=_state.value.editor?:return;_state.value=_state.value.copy(saving=true,error=null);viewModelScope.launch{try{val raw=payload(draft);val body=if(draft.editingSourceId.isBlank())creationIdentity.payload(raw) else raw;val created=if(draft.editingSourceId.isNotBlank())amendments.replace(draft.editingSourceId,body) else api.createAccountSalesDocument(body);creationIdentity.reset();val submitted=draft.type=="SALES_INVOICE";if(saveAndNew&&draft.editingSourceId.isBlank()){_state.value=_state.value.copy(saving=false,editor=SalesEditorDraft(type=draft.type,branchId=draft.branchId),detail=null,message=if(submitted)"Sale submitted. Ready for a new sale." else "Document saved. Ready for a new document.")}else{_state.value=_state.value.copy(saving=false,editor=null,detail=if(created["lines"] is JsonArray)created else null,message=if(draft.editingSourceId.isNotBlank())"Sale updated successfully." else if(submitted)"Sale submitted successfully." else "Document saved.");if(created["lines"] !is JsonArray)open(created.str("id"))};refresh()}catch(e:Exception){_state.value=_state.value.copy(saving=false,error=errorText(e))}}}
 fun open(id:String)=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);try{_state.value=_state.value.copy(loading=false,detail=api.accountSalesDocument(id))}catch(e:Exception){_state.value=_state.value.copy(loading=false,error=errorText(e))}};fun closeDetail(){_state.value=_state.value.copy(detail=null)}
 fun editSavedSale(){val doc=_state.value.detail?:return;if(doc.str("type")!="SALES_INVOICE"||doc.str("status")!="POSTED")return;val financial=doc["financial"]?.jsonObject;val base=doc.str("payableAmount").ifBlank{doc.str("grandTotal")};if(financial?.str("outstanding")!=base)return;val lines=doc.array("lines").map{line->SalesLineDraft(lineType=line.str("lineType"),sourceId=line.str("productId").ifBlank{line.str("serviceId").ifBlank{line.str("workPackageId")}},itemName=line.str("itemName"),description=line.str("description"),unitName=line.str("unitName"),unitSymbol=line.str("unitSymbol"),quantity=line.str("quantity"),rate=line.str("rate"),discountType=line.str("discountType"),discountValue=line.str("discountValue"),taxRate=line.str("taxRate"),warehouseId=line.str("warehouseId"),stockReturnQuantity="0")};_state.value=_state.value.copy(detail=null,editor=SalesEditorDraft(type="SALES_INVOICE",branchId=doc.str("branchId"),customerId=doc.str("partyId"),editingSourceId=doc.str("id"),issueDate=doc.str("issueDate").take(10),taxMode=doc.str("taxMode").ifBlank{"EXCLUSIVE"},stateOfSupplyCode=doc.str("stateOfSupplyCode"),notes=doc.str("notes"),lines=lines.ifEmpty{listOf(SalesLineDraft())}))}
 fun deleteSavedSale(){val doc=_state.value.detail?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);try{amendments.delete(doc.str("id"));_state.value=_state.value.copy(saving=false,detail=null,message="Sale deleted with accounting and stock reversal.");refresh()}catch(e:Exception){_state.value=_state.value.copy(saving=false,error=errorText(e))}}}
 fun requestPost(id:String){_state.value=_state.value.copy(postingId=id)};fun cancelPost(){_state.value=_state.value.copy(postingId=null)};fun confirmPost(){val id=_state.value.postingId?:return;viewModelScope.launch{_state.value=_state.value.copy(saving=true,postingId=null);try{api.postAccountSalesDocument(id);_state.value=_state.value.copy(saving=false,detail=api.accountSalesDocument(id),message="Document posted successfully.");refresh()}catch(e:Exception){_state.value=_state.value.copy(saving=false,error=errorText(e))}}}
 private fun errorText(e:Exception)=when{e is IOException->"Connection interrupted. Your inputs were kept; retry the same request when online.";e is ApiException&&e.status==403->"You are not authorized for this action.";e is ApiException&&e.code?.contains("SALE_HAS_PAYMENTS_OR_ADJUSTMENTS")==true->"This Sale has a payment or adjustment. Reverse that first before Edit/Delete.";e is ApiException&&e.code=="INVALID_INPUT"->"Check the document fields and line items.";else->"The server could not complete this Account action."}
}
