package com.salespunch360.mobile
import android.app.Application;import androidx.lifecycle.AndroidViewModel;import androidx.lifecycle.viewModelScope;import com.salespunch360.mobile.account.*;import com.salespunch360.mobile.data.*;import java.io.IOException;import kotlinx.coroutines.flow.*;import kotlinx.coroutines.launch;import kotlinx.serialization.json.*
data class ExpenseState(val loading:Boolean=false,val saving:Boolean=false,val query:String="",val status:String?=null,val rows:List<JsonObject> = emptyList(),val options:JsonObject=buildJsonObject{},val detail:JsonObject?=null,val editing:JsonObject?=null,val error:String?=null,val message:String?=null,val downloaded:Pair<String,ByteArray>?=null)
class AccountExpenseViewModel(app:Application):AndroidViewModel(app){private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(ExpenseState());val state:StateFlow<ExpenseState> = _state;init{refresh()};fun refresh()=viewModelScope.launch{_state.value=_state.value.copy(loading=true,error=null);try{_state.value=_state.value.copy(loading=false,options=api.expenseOptions(),rows=api.expenses(_state.value.query,_state.value.status).map{it.jsonObject})}catch(e:Exception){fail(e)}};fun search(v:String){_state.value=_state.value.copy(query=v);refresh()};fun filter(v:String?){_state.value=_state.value.copy(status=v);refresh()};fun create(){_state.value=_state.value.copy(editing=buildJsonObject{})};fun edit(x:JsonObject){_state.value=_state.value.copy(editing=x)};fun dismiss(){_state.value=_state.value.copy(editing=null,detail=null)};fun open(id:String)=viewModelScope.launch{try{_state.value=_state.value.copy(detail=api.expense(id))}catch(e:Exception){fail(e)}}
 fun save(payload:JsonObject)=viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);try{val id=_state.value.editing?.get("id")?.jsonPrimitive?.contentOrNull;val x=api.saveExpense(id,payload);_state.value=_state.value.copy(saving=false,editing=null,message="Expense saved with authoritative server totals.");open(x.str("id"));refresh()}catch(e:Exception){fail(e)}}
 fun action(id:String,action:String,status:String?=null,reason:String?=null,date:String?=null)=viewModelScope.launch{_state.value=_state.value.copy(saving=true,error=null);try{api.expenseAction(id,buildJsonObject{put("action",action);status?.let{put("status",it)};reason?.let{put("reason",it)};date?.let{put("entryDate",it)}});_state.value=_state.value.copy(saving=false,message="Expense action confirmed by server.",detail=api.expense(id));refresh()}catch(e:Exception){fail(e)}}
 fun recurring(payload:JsonObject)=viewModelScope.launch{try{api.saveRecurringExpense(payload);_state.value=_state.value.copy(message="Recurring expense schedule saved by server.")}catch(e:Exception){fail(e)}}
 fun download(id:String,name:String)=viewModelScope.launch{try{_state.value=_state.value.copy(downloaded=name to api.expenseAttachment(id))}catch(e:Exception){fail(e)}};fun consumedDownload(){_state.value=_state.value.copy(downloaded=null)}
 fun attach(id:String,name:String,mime:String,bytes:ByteArray)=viewModelScope.launch{try{api.uploadExpenseAttachment(id,name,mime,bytes);_state.value=_state.value.copy(detail=api.expense(id),message="Attachment uploaded.")}catch(e:Exception){fail(e)}}
 private fun fail(e:Exception){_state.value=_state.value.copy(loading=false,saving=false,error=when{e is IOException->"You're offline. No expense change was confirmed.";e is ApiException&&e.status==403->"Permission or subscription entitlement does not allow this action.";else->"The server rejected the expense action."})}}
