package com.salespunch360.mobile
import android.app.Application;import androidx.lifecycle.AndroidViewModel;import androidx.lifecycle.viewModelScope;import com.salespunch360.mobile.data.*;import java.io.IOException;import kotlinx.coroutines.flow.*;import kotlinx.coroutines.launch;import kotlinx.serialization.json.*
data class JournalLineDraft(val ledgerId:String="",val costCentreId:String="",val debit:String="0",val credit:String="0",val description:String="")
data class JournalDraft(val opening:Boolean=false,val financialYearId:String="",val branchId:String="",val date:String=java.time.LocalDate.now().toString(),val reference:String="",val narration:String="",val lines:List<JournalLineDraft> = listOf(JournalLineDraft(debit="1"),JournalLineDraft(credit="1")))
data class AccountingState(val loading:Boolean=false,val saving:Boolean=false,val query:String="",val data:JsonObject=buildJsonObject{},val journal:JsonObject?=null,val draft:JournalDraft?=null,val editor:String?=null,val error:String?=null,val message:String?=null)
class AccountAccountingViewModel(app:Application):AndroidViewModel(app){private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(AccountingState());val state:StateFlow<AccountingState> = _state;init{load()};fun load()=viewModelScope.launch{try{_state.value=_state.value.copy(loading=true,error=null);_state.value=_state.value.copy(loading=false,data=api.accountingOverview())}catch(e:Exception){fail(e)}};fun search(q:String){_state.value=_state.value.copy(query=q)};fun editor(kind:String?){_state.value=_state.value.copy(editor=kind)};fun newJournal(opening:Boolean=false){val d=_state.value.data;_state.value=_state.value.copy(draft=JournalDraft(opening,financialYearId=d["financialYears"]?.jsonArray?.firstOrNull()?.jsonObject?.get("id")?.jsonPrimitive?.content.orEmpty(),branchId=d["branches"]?.jsonArray?.firstOrNull()?.jsonObject?.get("id")?.jsonPrimitive?.content.orEmpty()))};fun draft(v:JournalDraft){_state.value=_state.value.copy(draft=v)};fun close(){_state.value=_state.value.copy(draft=null,journal=null,editor=null)};fun openJournal(id:String)=viewModelScope.launch{try{_state.value=_state.value.copy(journal=api.journal(id))}catch(e:Exception){fail(e)}}
 fun saveJournal()=viewModelScope.launch{val d=_state.value.draft?:return@launch;try{val payload=buildJsonObject{put("financialYearId",d.financialYearId);put("branchId",d.branchId);put("entryDate",d.date);put("sourceType",if(d.opening)"OPENING_BALANCE" else "MANUAL_JOURNAL");put("sourceId",java.util.UUID.randomUUID().toString());put("postingPurpose","PRIMARY");d.reference.takeIf{it.isNotBlank()}?.let{put("reference",it)};d.narration.takeIf{it.isNotBlank()}?.let{put("narration",it)};putJsonArray("lines"){d.lines.forEach{l->add(buildJsonObject{put("ledgerAccountId",l.ledgerId);l.costCentreId.takeIf{it.isNotBlank()}?.let{put("costCentreId",it)};put("debit",l.debit);put("credit",l.credit);l.description.takeIf{it.isNotBlank()}?.let{put("description",it)}})}}};api.accountingAction(if(d.opening)"opening" else "journals",payload);_state.value=_state.value.copy(draft=null,message="Journal posted after server validation.");load()}catch(e:Exception){fail(e)}}
 fun reverse(id:String,date:String,reason:String)=viewModelScope.launch{try{api.reverseJournal(id,buildJsonObject{put("entryDate",date);put("reason",reason)});_state.value=_state.value.copy(journal=null,message="Journal reversed by server.");load()}catch(e:Exception){fail(e)}}
 fun save(kind:String,p:JsonObject)=viewModelScope.launch{try{when(kind){"ledgers"->api.accountingAction("ledgers",p);"cost-centres"->api.accountingAction("cost-centres",p);"period-locks"->api.accountingAction("period-locks",p);"financial-years"->api.createFinancialYear(p);"close-year"->api.closeFinancialYear(p)};editor(null);load()}catch(e:Exception){fail(e)}}
 private fun fail(e:Exception){_state.value=_state.value.copy(loading=false,saving=false,error=when{e is IOException->"Offline. No accounting action was confirmed.";e is ApiException&&e.status==403->"Permission or subscription entitlement denied this action.";else->"Authoritative accounting validation rejected this action."})}}
