package com.salespunch360.mobile
import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.salespunch360.mobile.data.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
data class LeadsState(val loading:Boolean=true,val leads:List<LeadSummary> = emptyList(),val pending:PendingLeadsContext=PendingLeadsContext(),val detail:LeadSummary?=null,val detailLoading:Boolean=false,val busy:Boolean=false,val message:String?=null)
class LeadsViewModel(app:Application):AndroidViewModel(app){private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(LeadsState());val state:StateFlow<LeadsState> = _state;init{refresh()};fun refresh()=viewModelScope.launch{_state.value=_state.value.copy(loading=true);_state.value=try{LeadsState(false,api.leads(),api.pendingLeads())}catch(e:Exception){_state.value.copy(loading=false,message=apiMessage(e,"Leads couldn't be loaded."))}};fun open(id:String)=viewModelScope.launch{_state.value=_state.value.copy(detailLoading=true,detail=null);_state.value=try{_state.value.copy(detail=api.lead(id),detailLoading=false)}catch(e:Exception){_state.value.copy(detailLoading=false,message=apiMessage(e,"Lead details couldn't be loaded."))}};fun close(){_state.value=_state.value.copy(detail=null,detailLoading=false)};fun transition(lead:LeadSummary,stage:LeadStage,reason:String?){mutate{api.transitionLead(lead.id,lead.version,stage,reason)}};fun followUp(lead:LeadSummary,at:String?,notes:String?){mutate{api.updateFollowUp(lead.id,at,notes)}};fun delete(lead:LeadSummary){mutate{api.deleteLead(lead.id)}};fun addPendingPhone(visit:PendingLeadVisit,phone:String){mutate("Phone added. Lead created."){api.addPendingPhone(visit.id,phone)}};fun clear(){_state.value=_state.value.copy(message=null)};private fun mutate(success:String="Lead updated.",action:suspend()->Unit){if(_state.value.busy)return;viewModelScope.launch{_state.value=_state.value.copy(busy=true);try{action();_state.value=LeadsState(false,api.leads(),api.pendingLeads(),message=success)}catch(e:Exception){_state.value=_state.value.copy(busy=false,message=apiMessage(e,"Lead update wasn't accepted."))}}}}
