package com.salespunch360.mobile
import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.salespunch360.mobile.account.*
import com.salespunch360.mobile.data.*
import java.util.UUID
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.*
data class ProjectMaterialState(val loading:Boolean=true,val saving:Boolean=false,val projects:List<JsonObject> = emptyList(),val warehouses:List<JsonObject> = emptyList(),val products:List<JsonObject> = emptyList(),val budgetLines:List<JsonObject> = emptyList(),val movements:List<JsonObject> = emptyList(),val action:String="ISSUE",val projectId:String="",val destinationProjectId:String="",val warehouseId:String="",val productId:String="",val budgetLineId:String="",val sourceMovementId:String="",val quantity:String="",val reason:String="",val notes:String="",val error:String?=null,val message:String?=null)
class ProjectMaterialViewModel(app:Application):AndroidViewModel(app){private val api=ApiClient(SecureSession(app));private val _state=MutableStateFlow(ProjectMaterialState());val state:StateFlow<ProjectMaterialState> = _state;init{refresh()}fun update(f:(ProjectMaterialState)->ProjectMaterialState){_state.value=f(_state.value)}fun refresh()=viewModelScope.launch{runCatching{api.projectMaterialContext()}.onSuccess{c->_state.value=_state.value.copy(loading=false,projects=c.array("projects"),warehouses=c.array("warehouses"),products=c.array("products"),budgetLines=c.array("budgetLines"),movements=c.array("movements"))}.onFailure{_state.value=_state.value.copy(loading=false,error="Unable to load Project material.")}}fun post()=viewModelScope.launch{val s=_state.value;if(s.quantity.toDoubleOrNull()?.let{it>0}!=true){_state.value=s.copy(error="Enter a positive quantity.");return@launch};_state.value=s.copy(saving=true,error=null);val payload=buildJsonObject{put("movementDate",java.time.LocalDate.now().toString());put("idempotencyKey",UUID.randomUUID().toString());put("quantity",s.quantity);put("notes",s.notes);when(s.action){"ISSUE"->{put("projectId",s.projectId);put("warehouseId",s.warehouseId);put("productId",s.productId);put("projectBudgetLineId",s.budgetLineId)};"CONSUME"->{put("projectId",s.projectId);put("sourceMovementId",s.sourceMovementId)};"RETURN"->{put("projectId",s.projectId);put("sourceMovementId",s.sourceMovementId);put("warehouseId",s.warehouseId);put("reason",s.reason)};"TRANSFER"->{put("sourceProjectId",s.projectId);put("destinationProjectId",s.destinationProjectId);put("sourceMovementId",s.sourceMovementId);put("reason",s.reason)}}};runCatching{api.postProjectMaterial(s.action,payload)}.onSuccess{_state.value=s.copy(saving=false,quantity="",message="Material movement posted.");refresh()}.onFailure{_state.value=s.copy(saving=false,error="The server rejected this material movement.")}}}
