-- Forward-only A11-A14 runtime closure. Nullable line references preserve posted history.
ALTER TYPE "PurchaseClassification" ADD VALUE IF NOT EXISTS 'FIXED_ASSET';
ALTER TABLE "commercial_document_lines" ADD COLUMN "warehouseId" UUID, ADD COLUMN "batchId" UUID, ADD COLUMN "serialNumberId" UUID, ADD COLUMN "stockReturnQuantity" DECIMAL(18,4) NOT NULL DEFAULT 0, ADD COLUMN "cessRate" DECIMAL(7,4) NOT NULL DEFAULT 0;
ALTER TABLE "commercial_document_lines" ADD CONSTRAINT "commercial_line_stock_return_valid" CHECK ("stockReturnQuantity" >= 0 AND "stockReturnQuantity" <= "quantity");
ALTER TABLE "commercial_document_lines" ADD CONSTRAINT "commercial_line_warehouse_company_fk" FOREIGN KEY ("companyId","warehouseId") REFERENCES "warehouses"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "commercial_document_lines" ADD CONSTRAINT "commercial_line_batch_company_fk" FOREIGN KEY ("companyId","batchId") REFERENCES "inventory_batches"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "commercial_document_lines" ADD CONSTRAINT "commercial_line_serial_company_fk" FOREIGN KEY ("companyId","serialNumberId") REFERENCES "inventory_serial_numbers"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "inventory_batches" ADD CONSTRAINT "inventory_batches_company_fk" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "inventory_serial_numbers" ADD CONSTRAINT "inventory_serial_company_fk" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_batch_fk" FOREIGN KEY ("companyId","batchId") REFERENCES "inventory_batches"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_serial_fk" FOREIGN KEY ("companyId","serialNumberId") REFERENCES "inventory_serial_numbers"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_creator_fk" FOREIGN KEY ("companyId","createdById") REFERENCES "users"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_customer_fk" FOREIGN KEY ("companyId","customerId") REFERENCES "customers"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE INDEX "inventory_batches_expiry_idx" ON "inventory_batches"("companyId","expiryDate"); CREATE INDEX "inventory_serial_expiry_idx" ON "inventory_serial_numbers"("companyId","expiryDate"); CREATE INDEX "stock_movements_serial_state_idx" ON "stock_movements"("companyId","serialNumberId","movementDate"); CREATE INDEX "commercial_lines_warehouse_product_idx" ON "commercial_document_lines"("companyId","warehouseId","productId");
ALTER TABLE "assets" ADD CONSTRAINT "assets_purchase_document_fk" FOREIGN KEY ("companyId","purchaseDocumentId") REFERENCES "commercial_documents"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_purchase_line_fk" FOREIGN KEY ("companyId","purchaseDocumentLineId") REFERENCES "commercial_document_lines"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_assignee_fk" FOREIGN KEY ("companyId","assignedUserId") REFERENCES "users"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_creator_fk" FOREIGN KEY ("companyId","createdById") REFERENCES "users"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_asset_ledger_fk" FOREIGN KEY ("companyId","assetLedgerId") REFERENCES "ledger_accounts"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_accumulated_ledger_fk" FOREIGN KEY ("companyId","accumulatedDepreciationLedgerId") REFERENCES "ledger_accounts"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "assets" ADD CONSTRAINT "assets_depreciation_expense_ledger_fk" FOREIGN KEY ("companyId","depreciationExpenseLedgerId") REFERENCES "ledger_accounts"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "asset_assignment_history" ADD CONSTRAINT "asset_assignment_user_fk" FOREIGN KEY ("companyId","assignedToId") REFERENCES "users"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE "asset_assignment_history" ADD CONSTRAINT "asset_assignment_actor_fk" FOREIGN KEY ("companyId","assignedById") REFERENCES "users"("companyId","id") ON DELETE RESTRICT ON UPDATE RESTRICT;
CREATE INDEX "assets_purchase_document_idx" ON "assets"("companyId","purchaseDocumentId"); CREATE INDEX "assets_assignee_idx" ON "assets"("companyId","assignedUserId");
INSERT INTO "ledger_accounts" ("id","companyId","code","name","accountClass","normalBalance","systemKey","isSystem","isActive","allowPosting","createdAt","updatedAt") SELECT gen_random_uuid(),c.id,v.code,v.name,v.class::"LedgerAccountClass",v.normal::"NormalBalanceSide",v.key,true,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "companies" c CROSS JOIN (VALUES ('1460','Inventory Asset','ASSET','DEBIT','INVENTORY_ASSET'),('1470','CGST ITC','ASSET','DEBIT','CGST_ITC'),('1471','SGST ITC','ASSET','DEBIT','SGST_ITC'),('1472','IGST ITC','ASSET','DEBIT','IGST_ITC'),('1473','CESS ITC','ASSET','DEBIT','CESS_ITC'),('2110','CGST Payable','LIABILITY','CREDIT','CGST_PAYABLE'),('2111','SGST Payable','LIABILITY','CREDIT','SGST_PAYABLE'),('2112','IGST Payable','LIABILITY','CREDIT','IGST_PAYABLE'),('2113','CESS Payable','LIABILITY','CREDIT','CESS_PAYABLE'),('2120','TDS Payable','LIABILITY','CREDIT','TDS_PAYABLE'),('2130','TCS Payable','LIABILITY','CREDIT','TCS_PAYABLE'),('5200','Cost of Goods Sold','EXPENSE','DEBIT','COGS')) v(code,name,class,normal,key) WHERE c."productEdition" IN ('SALESPUNCH360_ACCOUNT','SALESPUNCH360_PLUS') ON CONFLICT ("companyId","systemKey") DO NOTHING;
