import type { CommercialDocumentType } from "@prisma/client";
import { canUsePermission } from "@/lib/auth/permissions";
import { assertOperationalWrite } from "@/lib/billing/entitlement";
import { commercialDocumentPolicies, commercialEditorOptionsForActor, createCommercialDocumentForActor, createSettlementForActor, getCommercialDocumentForActor, listCommercialDocumentsForActor, postCommercialDocumentForActor } from "@/lib/account/commercial";
import type { MobileAppPrincipal } from "./auth";

const SALES_TYPES = new Set<CommercialDocumentType>(["SALES_INVOICE","PROFORMA_INVOICE","SALES_ORDER","DELIVERY_CHALLAN","CREDIT_NOTE"]);
export function mobileAccountActor(user:MobileAppPrincipal){if(!user.authorizedWorkspaces.includes("ACCOUNT")||!user.accountRole)throw new Error("MOBILE_FORBIDDEN");return{id:user.id,name:user.name,companyId:user.companyId,role:user.role,isActive:true,salesRole:user.salesRole,accountRole:user.accountRole,salesAccessActive:user.authorizedWorkspaces.includes("SALES"),accountAccessActive:true,managerType:user.managerType,branchAccessScope:user.branchAccessScope,branchIds:user.branchIds};}
function permit(user:MobileAppPrincipal,permission:Parameters<typeof canUsePermission>[2]){const actor=mobileAccountActor(user);if(!canUsePermission(actor,user.productEdition,permission))throw new Error("MOBILE_FORBIDDEN");return actor;}
export async function mobileSalesOptions(user:MobileAppPrincipal){const actor=permit(user,"ACCOUNT_LEDGER_VIEW"),options=await commercialEditorOptionsForActor(actor);return{...options,allowedDocumentTypes:options.allowedDocumentTypes.filter(type=>SALES_TYPES.has(type))};}
export async function mobileSalesList(user:MobileAppPrincipal,type?:string|null,q?:string|null){const actor=permit(user,"ACCOUNT_LEDGER_VIEW"),rows=await listCommercialDocumentsForActor(actor);return rows.filter(row=>SALES_TYPES.has(row.type)&&(!type||row.type===type)&&(!q||row.documentNumber.toLowerCase().includes(q.toLowerCase())||row.partyName.toLowerCase().includes(q.toLowerCase()))).slice(0,200);}
export async function mobileSalesDetail(user:MobileAppPrincipal,id:string){const row=await getCommercialDocumentForActor(permit(user,"ACCOUNT_LEDGER_VIEW"),id);if(!SALES_TYPES.has(row.type))throw new Error("MOBILE_FORBIDDEN");return row;}
export async function mobileCreateSales(user:MobileAppPrincipal,raw:unknown){const type=(raw as{type?:CommercialDocumentType})?.type;if(!type||!SALES_TYPES.has(type))throw new Error("INVALID_INPUT");const policy=commercialDocumentPolicies[type],actor=permit(user,policy.permission);await assertOperationalWrite(user.companyId);return createCommercialDocumentForActor(actor,raw);}
export async function mobilePostSales(user:MobileAppPrincipal,id:string){const actor=permit(user,"ACCOUNT_JOURNAL_POST");await assertOperationalWrite(user.companyId);const row=await getCommercialDocumentForActor(actor,id);if(!SALES_TYPES.has(row.type))throw new Error("MOBILE_FORBIDDEN");return postCommercialDocumentForActor(actor,{documentId:id});}
export async function mobileCustomerReceipt(user:MobileAppPrincipal,raw:unknown){const actor=permit(user,"ACCOUNT_SETTLEMENT_ENTRY");await assertOperationalWrite(user.companyId);if((raw as{type?:string})?.type!=="CUSTOMER_RECEIPT")throw new Error("INVALID_INPUT");return createSettlementForActor(actor,raw);}
