import type {QuotationStatus} from "@prisma/client";import{canUsePermission,type Permission}from"@/lib/auth/permissions";import{assertOperationalWrite}from"@/lib/billing/entitlement";import{createQuotationForActor,createQuotationRevisionForActor,createQuotationShareForActor,getQuotationForActor,getCustomerQuotationForActor,listQuotationsForActor,quotationEditorOptionsForActor,quotationTransitions,transitionQuotationForActor,updateQuotationDraftForActor}from"@/lib/quotations/service";import{mobileAccountActor}from"./account-transactions";import type{MobileAppPrincipal}from"./auth";
function actor(user:MobileAppPrincipal,permission:Permission){const a=mobileAccountActor(user);if(!canUsePermission(a,user.productEdition,permission))throw new Error("MOBILE_FORBIDDEN");return a as never}async function write(user:MobileAppPrincipal,p:Permission){const a=actor(user,p);await assertOperationalWrite(user.companyId);return a}
export async function mobileQuotationOptions(user:MobileAppPrincipal){return quotationEditorOptionsForActor(actor(user,"ACCOUNT_QUOTATION_VIEW"))}
export async function mobileQuotationList(user:MobileAppPrincipal,q?:string|null,status?:string|null){const rows=await listQuotationsForActor(actor(user,"ACCOUNT_QUOTATION_VIEW"));return rows.filter(x=>(!q||x.documentNumber.toLowerCase().includes(q.toLowerCase())||x.revisions[0]?.customerName.toLowerCase().includes(q.toLowerCase()))&&(!status||x.status===status)).slice(0,200)}
export async function mobileQuotationDetail(user:MobileAppPrincipal,id:string){const row=await getQuotationForActor(actor(user,"ACCOUNT_QUOTATION_VIEW"),id);return{...row,allowedTransitions:quotationTransitions[row.status]}}
export async function mobileCreateQuotation(user:MobileAppPrincipal,raw:unknown){return createQuotationForActor(await write(user,"ACCOUNT_QUOTATION_EDIT"),raw)}
export async function mobileUpdateQuotation(user:MobileAppPrincipal,id:string,raw:unknown){return updateQuotationDraftForActor(await write(user,"ACCOUNT_QUOTATION_EDIT"),id,raw)}
export async function mobileReviseQuotation(user:MobileAppPrincipal,id:string,raw:unknown){return createQuotationRevisionForActor(await write(user,"ACCOUNT_QUOTATION_EDIT"),id,raw)}
export async function mobileTransitionQuotation(user:MobileAppPrincipal,id:string,to:QuotationStatus,note?:string){const p:Permission=to==="APPROVED"||to==="REJECTED"?"ACCOUNT_QUOTATION_APPROVE":to==="SENT"?"ACCOUNT_QUOTATION_SHARE":"ACCOUNT_QUOTATION_EDIT";return transitionQuotationForActor(await write(user,p),id,to,note)}
export async function mobileShareQuotation(user:MobileAppPrincipal,id:string,expiresAt?:string){return{token:await createQuotationShareForActor(await write(user,"ACCOUNT_QUOTATION_SHARE"),id,expiresAt?new Date(expiresAt):undefined)}}

export async function mobileCustomerQuotation(user:MobileAppPrincipal,id:string){return getCustomerQuotationForActor(actor(user,"ACCOUNT_QUOTATION_VIEW"),id)}
