import {deliverFieldEvent} from '@/lib/push/service';import {db} from '@/lib/db';import {assertOperationalWrite} from '@/lib/billing/entitlement';import {evaluateGeofence} from '@/lib/geofence/policy';import {assertAttendanceStartFresh,assertCaptureTime,shouldAcceptLocationPoint} from '@/lib/attendance/policy';import {haversineDistanceMeters} from '@/lib/location/geo';import {operationalBranchContext,resolveOperationalWriteBranch}from '@/lib/branches/operational-scope';import {mobileFieldWorkEnabled,type MobilePrincipal} from './auth';
type Point={latitude:number;longitude:number;accuracyMeters?:number;capturedAt:Date};
export async function mobileAttendanceAction(user:MobilePrincipal,action:'START'|'END',location?:Point,requestedBranchId?:string){
  if(!mobileFieldWorkEnabled(user))throw new Error('MOBILE_FORBIDDEN');
  if(action==='START')await assertOperationalWrite(user.companyId);
  const branches=await operationalBranchContext(user,requestedBranchId),branchId=action==='START'?await resolveOperationalWriteBranch(user,requestedBranchId):branches.branchId;
  const attendance=await db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "users" WHERE "id"=${user.id}::uuid FOR UPDATE`;const company=await tx.company.findUnique({where:{id:user.companyId},select:{attendanceEnabled:true,gpsTrackingEnabled:true,attendanceGeofenceEnabled:true,attendanceReferenceLatitude:true,attendanceReferenceLongitude:true,attendanceGeofenceRadiusMeters:true}});if(!company?.attendanceEnabled)throw new Error('ATTENDANCE_DISABLED');const open=await tx.attendance.findFirst({where:{companyId:user.companyId,branchId:branches.branchId,userId:user.id,endedAt:null},select:{id:true,startedAt:true}});
    if(action==='END'){if(!open)throw new Error('NO_OPEN_ATTENDANCE');const saved=company.gpsTrackingEnabled?location:undefined;return tx.attendance.update({where:{id:open.id},data:{endedAt:new Date(),endLatitude:saved?.latitude,endLongitude:saved?.longitude,endAccuracyMeters:saved?.accuracyMeters},select:{id:true,startedAt:true,endedAt:true}})}
    if(open)throw new Error('ALREADY_OPEN');if((company.gpsTrackingEnabled||company.attendanceGeofenceEnabled)&&!location)throw new Error('GPS_REQUIRED');if(location)assertAttendanceStartFresh(location.capturedAt);if(company.attendanceGeofenceEnabled){if(!location||company.attendanceReferenceLatitude==null||company.attendanceReferenceLongitude==null||company.attendanceGeofenceRadiusMeters==null)throw new Error('GEOFENCE_REQUIRED');const verdict=evaluateGeofence(location,{latitude:company.attendanceReferenceLatitude,longitude:company.attendanceReferenceLongitude},company.attendanceGeofenceRadiusMeters);if(!verdict.allowed)throw new Error(verdict.type)}const saved=company.gpsTrackingEnabled||company.attendanceGeofenceEnabled?location:undefined;return tx.attendance.create({data:{companyId:user.companyId,branchId:branchId as string,userId:user.id,startLatitude:saved?.latitude,startLongitude:saved?.longitude,startAccuracyMeters:saved?.accuracyMeters},select:{id:true,startedAt:true,endedAt:true}})
  });await deliverFieldEvent({eventType:action==='START'?'ATTENDANCE_STARTED':'ATTENDANCE_ENDED',actorUserId:user.id,attendanceId:attendance.id,occurredAt:action==='START'?attendance.startedAt:attendance.endedAt!}).catch(()=>undefined);return attendance
}
export async function mobileUploadPoint(user:MobilePrincipal,point:Point&{clientPointId:string;capturedAt:Date}){if(!mobileFieldWorkEnabled(user))throw new Error('MOBILE_FORBIDDEN');const now=new Date();assertCaptureTime(point.capturedAt,now);return db.$transaction(async tx=>{const existing=await tx.locationPoint.findFirst({where:{companyId:user.companyId,userId:user.id,clientPointId:point.clientPointId},select:{id:true}});if(existing)return{acknowledged:true,duplicate:true};const company=await tx.company.findUnique({where:{id:user.companyId},select:{gpsTrackingEnabled:true}});if(!company?.gpsTrackingEnabled)throw new Error('GPS_DISABLED');const attendance=await tx.attendance.findFirst({where:{companyId:user.companyId,userId:user.id,endedAt:null},select:{id:true,branchId:true}});if(!attendance)throw new Error('NO_OPEN_ATTENDANCE');await tx.$queryRaw`SELECT "id" FROM "attendances" WHERE "id"=${attendance.id}::uuid FOR UPDATE`;const previous=await tx.locationPoint.findFirst({where:{attendanceId:attendance.id},orderBy:{sequenceNumber:'desc'},select:{latitude:true,longitude:true,capturedAt:true,sequenceNumber:true}});const distance=previous?haversineDistanceMeters(previous,point):0;if(!shouldAcceptLocationPoint(previous,point,distance))throw new Error('THROTTLED');await tx.locationPoint.create({data:{companyId:user.companyId,branchId:attendance.branchId,userId:user.id,attendanceId:attendance.id,clientPointId:point.clientPointId,latitude:point.latitude,longitude:point.longitude,accuracyMeters:point.accuracyMeters,capturedAt:point.capturedAt,receivedAt:now,sequenceNumber:(previous?.sequenceNumber??0)+1}});return{acknowledged:true,duplicate:false}})}
