import {Prisma} from '@prisma/client';
import {db} from '@/lib/db';
import {branchDetails} from '@/lib/branches/management';
import type {MobilePrincipal} from './auth';
import {MobileCompanyError} from './company';

function primary(p:MobilePrincipal){if(p.salesRole!=='PRIMARY_ADMIN')throw new MobileCompanyError('FORBIDDEN',403);return p.companyId}
const details=(raw:unknown)=>branchDetails.parse(raw);
export async function mobileBranches(p:MobilePrincipal){const companyId=primary(p);return db.branch.findMany({where:{companyId},select:{id:true,name:true,code:true,addressLine1:true,city:true,state:true,postalCode:true,country:true,phone:true,email:true,isPrimary:true,isActive:true},orderBy:[{isPrimary:'desc'},{name:'asc'}]})}
export async function mobileCreateBranch(p:MobilePrincipal,raw:unknown){const companyId=primary(p),data=details(raw);try{return await db.branch.create({data:{...data,companyId,isPrimary:false}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new MobileCompanyError('DUPLICATE_BRANCH_CODE',409);throw error}}
export async function mobileEditBranch(p:MobilePrincipal,raw:unknown){const companyId=primary(p);if(!raw||typeof raw!=='object')throw new MobileCompanyError('INVALID_INPUT');const input=raw as Record<string,unknown>,branchId=String(input.branchId??''),data=details({name:input.name,code:input.code,addressLine1:input.addressLine1,city:input.city,state:input.state,postalCode:input.postalCode,country:input.country,phone:input.phone,email:input.email});const changed=await db.branch.updateMany({where:{id:branchId,companyId},data});if(changed.count!==1)throw new MobileCompanyError('NOT_FOUND',404);return{ok:true}}
export async function mobileSetBranchActive(p:MobilePrincipal,branchId:string,active:boolean){const companyId=primary(p);await db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "branches" WHERE "id"=${branchId}::uuid AND "companyId"=${companyId}::uuid FOR UPDATE`;const branch=await tx.branch.findFirst({where:{id:branchId,companyId},select:{id:true,isPrimary:true}});if(!branch)throw new MobileCompanyError('NOT_FOUND',404);if(branch.isPrimary&&!active)throw new MobileCompanyError('PRIMARY_BRANCH_PROTECTED',409);if(!active){const [access,...operations]=await Promise.all([tx.userBranchAccess.count({where:{branchId,user:{companyId,isActive:true,branchAccessScope:'SELECTED_BRANCHES'}}}),tx.attendance.count({where:{companyId,branchId}}),tx.customer.count({where:{companyId,branchId}}),tx.customerVisit.count({where:{companyId,branchId}}),tx.lead.count({where:{companyId,branchId}}),tx.followUpTask.count({where:{companyId,branchId}}),tx.locationPoint.count({where:{companyId,branchId}}),tx.geofenceEvent.count({where:{companyId,branchId}}),tx.salesTarget.count({where:{companyId,branchId}}),tx.dailyTravelApproval.count({where:{companyId,branchId}})]);if(access||operations.some(Boolean))throw new MobileCompanyError('BRANCH_IN_USE',409)}await tx.branch.update({where:{id:branch.id},data:{isActive:active}})});return{ok:true}}
