import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({find:vi.fn(),update:vi.fn(),entitlement:vi.fn(),prices:vi.fn()}));
vi.mock('@/lib/db',()=>({db:{company:{findUnique:mocks.find,updateMany:mocks.update}}}));
vi.mock('@/lib/billing/entitlement',()=>({effectiveEntitlement:mocks.entitlement}));
vi.mock('@/lib/billing/service',()=>({currentPrices:mocks.prices}));
import {mobileCompanyContext,mobileUpdateCompany} from './company';import type {MobilePrincipal} from './auth';
const principal=(role:MobilePrincipal['salesRole'],companyId='company-a'):MobilePrincipal=>({id:'actor',name:'Actor',email:'a@example.com',salesRole:role,managerType:role==='MANAGER'?'FIELD_MANAGER':null,companyId});
const company={name:'Acme',teamStructure:'SALES_ONLY',subscriptionStatus:'TRIAL',trialStartedAt:new Date(),trialEndsAt:new Date(),attendanceEnabled:true,gpsTrackingEnabled:false,checkoutRequiredBeforeNextCheckIn:true,attendanceGeofenceEnabled:false,attendanceReferenceLatitude:null,attendanceReferenceLongitude:null,attendanceGeofenceRadiusMeters:null,customerCheckInGeofenceEnabled:false,customerCheckInGeofenceRadiusMeters:null};
beforeEach(()=>{vi.clearAllMocks();mocks.find.mockResolvedValue(company);mocks.entitlement.mockResolvedValue({state:'TRIAL',trialActive:true,paidActive:false,managerLimit:0,salesLimit:5,managerUsage:0,salesUsage:1,operationalWritesAllowed:true,subscription:null});mocks.prices.mockResolvedValue([]);mocks.update.mockResolvedValue({count:1})});
describe('mobile company administration boundary',()=>{
 it('reads settings, trial and seats only for the authenticated company admin tenant',async()=>{const result=await mobileCompanyContext(principal('PRIMARY_ADMIN'));expect(mocks.find).toHaveBeenCalledWith(expect.objectContaining({where:{id:'company-a'}}));expect(mocks.entitlement).toHaveBeenCalledWith('company-a');expect(result.company.teamStructure).toBe('SALES_ONLY')});
 it.each(['ADMIN','MANAGER','SALES'] as const)('forbids %s reads and mutations',async role=>{await expect(mobileCompanyContext(principal(role))).rejects.toMatchObject({code:'FORBIDDEN',status:403});await expect(mobileUpdateCompany(principal(role),{section:'operations',data:{}})).rejects.toMatchObject({code:'FORBIDDEN'});expect(mocks.update).not.toHaveBeenCalled()});
 it('derives companyId from the principal and rejects forged settings fields',async()=>{await expect(mobileUpdateCompany(principal('PRIMARY_ADMIN'),{companyId:'company-b',section:'operations',data:{attendanceEnabled:true,gpsTrackingEnabled:false,checkoutRequiredBeforeNextCheckIn:true,companyId:'company-b'}})).rejects.toThrow();expect(mocks.update).not.toHaveBeenCalled()});
 it('updates existing geofence fields with the server schema and tenant scope',async()=>{await mobileUpdateCompany(principal('PRIMARY_ADMIN'),{section:'geofence',data:{attendanceGeofenceEnabled:false,customerCheckInGeofenceEnabled:true,customerCheckInGeofenceRadiusMeters:50}});expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({where:{id:'company-a'},data:expect.objectContaining({customerCheckInGeofenceRadiusMeters:50})}))});
});
