import {Prisma} from '@prisma/client';
import {db} from '@/lib/db';
import {assignCustomerSchema,createCustomerSchema} from '@/lib/customers/validation';
import {operationalBranchContext,resolveOperationalWriteBranch} from '@/lib/branches/operational-scope';
import type {MobilePrincipal} from './auth';
import {MobileCompanyError} from './company';

function admin(p:MobilePrincipal){if(p.salesRole!=='PRIMARY_ADMIN'&&p.salesRole!=='ADMIN')throw new MobileCompanyError('FORBIDDEN',403);return p.companyId}
async function createLead(tx:Prisma.TransactionClient,companyId:string,branchId:string,actorId:string,customer:{id:string;name:string;phone:string|null},assignedUserId:string){const existing=await tx.lead.findFirst({where:{companyId,branchId,customerId:customer.id},select:{id:true}});if(existing)return existing;const lead=await tx.lead.create({data:{companyId,branchId,customerId:customer.id,assignedUserId,createdByUserId:actorId,title:customer.name,contactName:customer.name,phone:customer.phone,source:'MANUAL',stage:'NEW'}});await tx.leadActivity.create({data:{companyId,leadId:lead.id,actorUserId:actorId,type:'CREATED',newAssignedUserId:assignedUserId,toStage:'NEW'}});return lead}

export async function mobileCustomerAdminContext(p:MobilePrincipal){const companyId=admin(p),scope=await operationalBranchContext(p);const [customers,assignees,branches]=await Promise.all([
 db.customer.findMany({where:{companyId,branchId:{in:scope.branchIds},assignedUserId:null},select:{id:true,branchId:true,name:true,phone:true,contactPerson:true,email:true,address:true,assignedUserId:true},orderBy:{name:'asc'},take:100}),
 db.user.findMany({where:{companyId,isActive:true,salesAccessActive:true,OR:[{salesRole:'SALES'},{salesRole:'MANAGER',managerType:'FIELD_MANAGER'}]},select:{id:true,name:true,salesRole:true,branchAccessScope:true,branchAccesses:{select:{branchId:true}}},orderBy:{name:'asc'}}),
 db.branch.findMany({where:{companyId,id:{in:scope.branchIds},isActive:true},select:{id:true,name:true,code:true,isPrimary:true},orderBy:[{isPrimary:'desc'},{name:'asc'}]})
]);return{customers,assignees,branches}}

export async function mobileCreateCustomer(p:MobilePrincipal,raw:unknown){const companyId=admin(p),data=createCustomerSchema.parse(raw),branchId=await resolveOperationalWriteBranch(p,data.branchId);return db.$transaction(async tx=>{let assigneeId:string|undefined;if(data.assignedUserId){const assignee=await tx.user.findFirst({where:{id:data.assignedUserId,companyId,isActive:true,salesAccessActive:true,OR:[{salesRole:'SALES'},{salesRole:'MANAGER',managerType:'FIELD_MANAGER'}]},select:{id:true}});if(!assignee)throw new MobileCompanyError('INVALID_ASSIGNMENT',400);await resolveOperationalWriteBranch({id:assignee.id,companyId},branchId,tx);assigneeId=assignee.id}const customer=await tx.customer.create({data:{name:data.name,phone:data.phone,companyId,branchId,assignedUserId:assigneeId}});if(assigneeId)await createLead(tx,companyId,branchId,p.id,customer,assigneeId);return customer})}

export async function mobileAssignCustomer(p:MobilePrincipal,raw:unknown){const companyId=admin(p),data=assignCustomerSchema.parse(raw),scope=await operationalBranchContext(p);return db.$transaction(async tx=>{const assignee=await tx.user.findFirst({where:{id:data.assignedUserId,companyId,isActive:true,salesAccessActive:true,OR:[{salesRole:'SALES'},{salesRole:'MANAGER',managerType:'FIELD_MANAGER'}]},select:{id:true}});if(!assignee)throw new MobileCompanyError('INVALID_ASSIGNMENT',400);const customer=await tx.customer.findFirst({where:{id:data.customerId,companyId,branchId:{in:scope.branchIds},assignedUserId:null},select:{id:true,name:true,phone:true,branchId:true}});if(!customer)throw new MobileCompanyError('CUSTOMER_NOT_FOUND',404);await resolveOperationalWriteBranch({id:assignee.id,companyId},customer.branchId,tx);await tx.customer.update({where:{id:customer.id},data:{assignedUserId:assignee.id}});await createLead(tx,companyId,customer.branchId,p.id,customer,assignee.id);return{ok:true}})}
