import {effectiveEntitlement} from '@/lib/billing/entitlement';
import {profileComplete} from '@/lib/company/profile';
import {db} from '@/lib/db';
import {createManagerForCompany,createSalesEmployeeForCompany,deactivateEmployeeForCompany,getEmployeeManagementContextForCompany,reactivateEmployeeForCompany} from '@/lib/employees/service';
import {mobileCan,type MobilePrincipal} from './auth';

export class MobileEmployeeError extends Error{constructor(public code:string,public status=400){super(code)}}
function admin(principal:MobilePrincipal){if(!mobileCan(principal,'SALES_USER_ADMIN'))throw new MobileEmployeeError('FORBIDDEN',403);return principal.companyId}
export async function mobileEmployeeContext(principal:MobilePrincipal){const companyId=admin(principal);const [context,entitlement,company]=await Promise.all([getEmployeeManagementContextForCompany(companyId),effectiveEntitlement(companyId),db.company.findUnique({where:{id:companyId},select:{name:true,teamStructure:true,addressLine1:true,city:true,state:true,postalCode:true,country:true,primaryContactName:true,primaryPhone:true,contactEmail:true}})]);return{employees:context.employees,teamStructure:context.teamStructure,profileComplete:Boolean(company&&profileComplete(company as unknown as Record<string,unknown>)),entitlement:{state:entitlement.state,operationalWritesAllowed:entitlement.operationalWritesAllowed,managerLimit:entitlement.managerLimit,salesLimit:entitlement.salesLimit,managerUsage:entitlement.managerUsage,salesUsage:entitlement.salesUsage}}}
export async function mobileCreateEmployee(principal:MobilePrincipal,raw:unknown){const companyId=admin(principal);if(!raw||typeof raw!=='object')throw new MobileEmployeeError('INVALID_INPUT');const {role,...input}=raw as Record<string,unknown>;if(role==='MANAGER')return createManagerForCompany(companyId,input,principal.id);if(role==='SALES')return createSalesEmployeeForCompany(companyId,input,principal.id);throw new MobileEmployeeError('INVALID_ROLE')}
export async function mobileSetEmployeeActive(principal:MobilePrincipal,raw:unknown){const companyId=admin(principal);if(!raw||typeof raw!=='object')throw new MobileEmployeeError('INVALID_INPUT');const {employeeId,isActive}=raw as Record<string,unknown>;if(typeof isActive!=='boolean')throw new MobileEmployeeError('INVALID_INPUT');const input={employeeId};if(isActive)await reactivateEmployeeForCompany(companyId,input,principal.id);else await deactivateEmployeeForCompany(companyId,input,principal.id);return{ok:true}}
