import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({context:vi.fn(),entitlement:vi.fn(),manager:vi.fn(),sales:vi.fn(),deactivate:vi.fn(),reactivate:vi.fn()}));
vi.mock('@/lib/employees/service',()=>({getEmployeeManagementContextForCompany:mocks.context,createManagerForCompany:mocks.manager,createSalesEmployeeForCompany:mocks.sales,deactivateEmployeeForCompany:mocks.deactivate,reactivateEmployeeForCompany:mocks.reactivate}));
vi.mock('@/lib/billing/entitlement',()=>({effectiveEntitlement:mocks.entitlement}));
import {mobileCreateEmployee,mobileEmployeeContext,mobileSetEmployeeActive} from './employees';
import type {MobilePrincipal} from './auth';
const principal=(role:MobilePrincipal['salesRole'],companyId='company-a'):MobilePrincipal=>({id:'actor',name:'Admin',email:'admin@example.com',salesRole:role,managerType:role==='MANAGER'?'FIELD_MANAGER':null,companyId});
beforeEach(()=>{vi.clearAllMocks();mocks.context.mockResolvedValue({teamStructure:'MANAGERS_AND_SALES',employees:[{id:'employee',name:'Sam',email:'sam@example.com',phone:null,employeeCode:null,role:'SALES',isActive:true,managerId:null,manager:null}]});mocks.entitlement.mockResolvedValue({state:'TRIAL',operationalWritesAllowed:true,managerLimit:1,salesLimit:5,managerUsage:0,salesUsage:1});mocks.manager.mockResolvedValue({id:'manager',name:'Morgan',email:'m@example.com',role:'MANAGER',isActive:true});mocks.sales.mockResolvedValue({id:'sales',name:'Sam',email:'s@example.com',role:'SALES',isActive:true})});
describe('mobile employee administration',()=>{
 it('lists only through the authenticated company boundary without sensitive fields',async()=>{const result=await mobileEmployeeContext(principal('PRIMARY_ADMIN'));expect(mocks.context).toHaveBeenCalledWith('company-a');expect(JSON.stringify(result)).not.toMatch(/password|session|hash/i)});
 it.each(['MANAGER','SALES'] as const)('rejects %s employee administration',async role=>{await expect(mobileEmployeeContext(principal(role))).rejects.toMatchObject({code:'FORBIDDEN',status:403});expect(mocks.context).not.toHaveBeenCalled()});
 it('allows Additional Admin through canonical SALES_USER_ADMIN',async()=>{await mobileEmployeeContext(principal('ADMIN'));expect(mocks.context).toHaveBeenCalledWith('company-a')});
 it('passes Manager and Sales creation to authoritative services with server companyId',async()=>{await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'MANAGER',name:'M'});await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'SALES',name:'S',managerId:'manager'});expect(mocks.manager).toHaveBeenCalledWith('company-a',{name:'M'},'actor');expect(mocks.sales).toHaveBeenCalledWith('company-a',{name:'S',managerId:'manager'},'actor')});
 it('never accepts a client companyId as tenant scope',async()=>{await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'SALES',name:'S',companyId:'company-b'});expect(mocks.sales).toHaveBeenCalledWith('company-a',{name:'S',companyId:'company-b'},'actor')});
 it('uses authoritative scoped lifecycle services for activation changes',async()=>{await mobileSetEmployeeActive(principal('PRIMARY_ADMIN'),{employeeId:'employee',isActive:false});await mobileSetEmployeeActive(principal('PRIMARY_ADMIN'),{employeeId:'employee',isActive:true});expect(mocks.deactivate).toHaveBeenCalledWith('company-a',{employeeId:'employee'},'actor');expect(mocks.reactivate).toHaveBeenCalledWith('company-a',{employeeId:'employee'},'actor')});
});
