import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({context:vi.fn(),entitlement:vi.fn(),manager:vi.fn(),sales:vi.fn(),admins:vi.fn(),company:vi.fn(),branches:vi.fn(),setActive:vi.fn()}));
vi.mock('@/lib/employees/service',()=>({getEmployeeManagementContextForCompany:mocks.context,createManagerForCompany:mocks.manager,createSalesEmployeeForCompany:mocks.sales}));
vi.mock('@/lib/billing/entitlement',()=>({effectiveEntitlement:mocks.entitlement}));
vi.mock('@/lib/users/additional-admin',()=>({createAdditionalAdminForCompany:vi.fn(),listAdditionalAdminsForCompany:mocks.admins}));
vi.mock('@/lib/db',()=>({db:{company:{findUnique:mocks.company},branch:{findMany:mocks.branches}}}));
vi.mock('./employee-admin',()=>({mobileSetAnyEmployeeActive:mocks.setActive,mobileEditEmployee:vi.fn(),mobileChangeEmployeeRole:vi.fn()}));
import {mobileCreateEmployee,mobileEmployeeContext,mobileSetEmployeeActive} from './employees';
import type {MobilePrincipal} from './auth';
const principal=(role:MobilePrincipal['salesRole'],companyId='company-a'):MobilePrincipal=>({id:'actor',name:'Admin',email:'admin@example.com',salesRole:role,managerType:role==='MANAGER'?'FIELD_MANAGER':null,companyId});
beforeEach(()=>{vi.clearAllMocks();mocks.context.mockResolvedValue({teamStructure:'MANAGERS_AND_SALES',employees:[{id:'employee',name:'Sam',email:'sam@example.com',phone:null,employeeCode:null,designation:null,dateOfJoining:null,salesRole:'SALES',isActive:true,salesAccessActive:true,managerId:null,manager:null,managerType:null,branchAccessScope:'ALL_BRANCHES',branchAccesses:[],travelAllowanceEnabled:false,travelRatePerKm:null}]});mocks.admins.mockResolvedValue([]);mocks.company.mockResolvedValue({name:'Company',teamStructure:'MANAGERS_AND_SALES'});mocks.branches.mockResolvedValue([]);mocks.entitlement.mockResolvedValue({state:'TRIAL',operationalWritesAllowed:true,adminLimit:0,managerLimit:1,salesLimit:5,adminUsage:0,managerUsage:0,salesUsage:1});mocks.manager.mockResolvedValue({id:'employee',name:'Morgan',email:'m@example.com',role:'MANAGER',isActive:true});mocks.sales.mockResolvedValue({id:'employee',name:'Sam',email:'s@example.com',role:'SALES',isActive:true});mocks.setActive.mockResolvedValue({ok:true})});
describe('mobile employee administration',()=>{
 it('lists only through the authenticated company boundary without sensitive fields',async()=>{const result=await mobileEmployeeContext(principal('PRIMARY_ADMIN'));expect(mocks.context).toHaveBeenCalledWith('company-a');expect(JSON.stringify(result)).not.toMatch(/password|session|hash/i)});
 it.each(['MANAGER','SALES'] as const)('rejects %s employee administration',async role=>{await expect(mobileEmployeeContext(principal(role))).rejects.toMatchObject({code:'FORBIDDEN',status:403});expect(mocks.context).not.toHaveBeenCalled()});
 it('blocks Additional Admin from employee administration',async()=>{await expect(mobileEmployeeContext(principal('ADMIN'))).rejects.toMatchObject({code:'FORBIDDEN',status:403});expect(mocks.context).not.toHaveBeenCalled()});
 it('passes Manager and Sales creation to authoritative services with server companyId',async()=>{await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'MANAGER',name:'M'});await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'SALES',name:'S',managerId:'manager'});expect(mocks.manager).toHaveBeenCalledWith('company-a',{name:'M'},'actor');expect(mocks.sales).toHaveBeenCalledWith('company-a',{name:'S',managerId:'manager'},'actor')});
 it('never accepts a client companyId as tenant scope',async()=>{await mobileCreateEmployee(principal('PRIMARY_ADMIN'),{role:'SALES',name:'S',companyId:'company-b'});expect(mocks.sales).toHaveBeenCalledWith('company-a',{name:'S',companyId:'company-b'},'actor')});
 it('uses authoritative scoped lifecycle services for activation changes',async()=>{await mobileSetEmployeeActive(principal('PRIMARY_ADMIN'),{employeeId:'employee',isActive:false});await mobileSetEmployeeActive(principal('PRIMARY_ADMIN'),{employeeId:'employee',isActive:true});expect(mocks.setActive).toHaveBeenNthCalledWith(1,expect.objectContaining({companyId:'company-a',id:'actor'}),'employee',false);expect(mocks.setActive).toHaveBeenNthCalledWith(2,expect.objectContaining({companyId:'company-a',id:'actor'}),'employee',true)});
});
