import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({customers:vi.fn(),history:vi.fn(),checkIn:vi.fn(),fieldCheckIn:vi.fn(),checkout:vi.fn()}));
vi.mock('@/lib/customers/service',()=>({searchCustomersForCompany:mocks.customers}));vi.mock('@/lib/visits/service',()=>({getOwnVisitHistoryForUser:mocks.history,checkInForUser:mocks.checkIn,fieldCheckInForUser:mocks.fieldCheckIn,checkoutForUser:mocks.checkout}));
import {mobileCheckIn,mobileCheckout,mobileFieldCheckIn,mobileFieldContext} from './field';import type {MobilePrincipal} from './auth';
const user=(role:MobilePrincipal['salesRole'],companyId='company-a'):MobilePrincipal=>({id:'user-a',name:'Field',email:'field@example.com',salesRole:role,managerType:role==='MANAGER'?'FIELD_MANAGER':null,companyId});
beforeEach(()=>{vi.clearAllMocks();mocks.checkIn.mockResolvedValue({id:'visit-a',checkedInAt:new Date()});mocks.fieldCheckIn.mockResolvedValue({id:'visit-b',checkedInAt:new Date(),leadId:'lead'});mocks.customers.mockResolvedValue([{id:'customer-a',companyId:'company-a',name:'Acme',contactPerson:null,phone:null,email:null,address:null,latitude:null,longitude:null,createdAt:new Date(),updatedAt:new Date()}]);mocks.history.mockResolvedValue([])});
describe('mobile field boundary',()=>{
 it('scopes customers and visit history to authenticated identity',async()=>{await mobileFieldContext(user('SALES'));expect(mocks.customers).toHaveBeenCalledWith('company-a','','user-a');expect(mocks.history).toHaveBeenCalledWith(expect.objectContaining({id:'user-a',companyId:'company-a'}))});
 it('allows Field Manager and Sales but rejects Company Admin and Manager Only field operations',async()=>{await mobileFieldContext(user('MANAGER'));await expect(mobileFieldContext(user('PRIMARY_ADMIN'))).rejects.toMatchObject({code:'FORBIDDEN',status:403});await expect(mobileFieldContext({...user('MANAGER'),managerType:'MANAGER_ONLY'})).rejects.toMatchObject({code:'FORBIDDEN',status:403})});
 it('passes server principal to authoritative check-in and checkout services',async()=>{const location={latitude:1,longitude:2,accuracyMeters:5};await mobileCheckIn(user('SALES'),{customerId:'c',location});await mobileCheckout(user('SALES'),{visitId:'v',location,sentiment:'NEUTRAL'});expect(mocks.checkIn).toHaveBeenCalledWith(expect.objectContaining({companyId:'company-a',id:'user-a'}),expect.anything());expect(mocks.checkout).toHaveBeenCalledWith(expect.objectContaining({companyId:'company-a',id:'user-a'}),expect.anything())});
 it('passes multipart photo inputs to the same authoritative service',async()=>{const photo=new File(['x'],'photo.webp',{type:'image/webp'});await mobileFieldCheckIn(user('SALES'),{visitType:'NEW',name:'Prospect',location:{latitude:1,longitude:2,accuracyMeters:5}},photo);expect(mocks.fieldCheckIn).toHaveBeenCalledWith(expect.objectContaining({id:'user-a'}),expect.anything(),photo)});
 it('does not expose tenant metadata from customer rows',async()=>{const result=await mobileFieldContext(user('SALES'));expect(JSON.stringify(result)).not.toMatch(/companyId|password|session/i)});
});
