import {beforeEach,describe,expect,it,vi} from 'vitest';
const COMPANY='11111111-1111-4111-8111-111111111111',FOREIGN='22222222-2222-4222-8222-222222222222',USER='33333333-3333-4333-8333-333333333333';
const mocks=vi.hoisted(()=>({read:vi.fn(),mutation:vi.fn(),transaction:vi.fn(),raw:vi.fn(),company:vi.fn(),count:vi.fn(),subscription:vi.fn(),find:vi.fn(),many:vi.fn(),create:vi.fn(),update:vi.fn(),updateMany:vi.fn(),hash:vi.fn(),clear:vi.fn(),activate:vi.fn(),deactivate:vi.fn(),suspend:vi.fn()}));
vi.mock('@/lib/auth/authorization',()=>({requirePermission:mocks.read,requirePermissionForMutation:mocks.mutation}));
vi.mock('@/lib/auth/password',()=>({hashPassword:mocks.hash}));
vi.mock('@/lib/auth/session-generation',()=>({clearUserAuthentication:mocks.clear}));
vi.mock('@/lib/auth/lifecycle',()=>({activateSalesAccessInTransaction:mocks.activate,deactivateIdentityWithLock:mocks.deactivate,suspendSalesAccessInTransaction:mocks.suspend}));
vi.mock('@/lib/db',()=>({db:{user:{findMany:mocks.many},$transaction:mocks.transaction}}));
import {createAdditionalAdmin,editAdditionalAdmin,listAdditionalAdmins,resetAdditionalAdminPassword,restoreAdditionalAdminSales,setAdditionalAdminActive} from './additional-admin';
const input={name:'Admin User',email:'admin@example.com',phone:'',password:'StrongPassword123!',confirmPassword:'StrongPassword123!'};
function tx(){return {$queryRaw:mocks.raw,company:{findUnique:mocks.company},companySubscription:{findFirst:mocks.subscription},user:{count:mocks.count,findFirst:mocks.find,create:mocks.create,update:mocks.update,updateMany:mocks.updateMany}}}
beforeEach(()=>{vi.clearAllMocks();mocks.mutation.mockResolvedValue({id:'actor',companyId:COMPANY,salesRole:'PRIMARY_ADMIN'});mocks.read.mockResolvedValue({id:'actor',companyId:COMPANY,salesRole:'PRIMARY_ADMIN'});mocks.company.mockResolvedValue({productEdition:'SALESPUNCH360'});mocks.count.mockResolvedValue(0);mocks.subscription.mockResolvedValue({adminSeats:1});mocks.hash.mockResolvedValue('hash');mocks.create.mockImplementation(({data})=>Promise.resolve(data));mocks.find.mockResolvedValue({id:USER,isActive:true,salesAccessActive:true,role:'FIELD_ADMIN'});mocks.updateMany.mockResolvedValue({count:1});mocks.transaction.mockImplementation(async work=>work(tx()))});
describe('Additional Admin canonical service',()=>{
 it('lets only Primary Admin create and serializes seat checks on the company',async()=>{await createAdditionalAdmin(input);expect(mocks.raw).toHaveBeenCalled();expect(mocks.count).toHaveBeenCalledWith({where:{companyId:COMPANY,isActive:true,salesAccessActive:true,salesRole:'ADMIN'}});expect(mocks.create).toHaveBeenCalledWith({data:expect.objectContaining({salesRole:'ADMIN',role:'FIELD_ADMIN',branchAccessScope:'ALL_BRANCHES',accountRole:null,accountAccessActive:false,managerId:null,managerType:null})})});
 it('denies an Additional Admin actor',async()=>{mocks.mutation.mockResolvedValue({id:'actor',companyId:COMPANY,salesRole:'ADMIN'});await expect(createAdditionalAdmin(input)).rejects.toThrow('NOT_AUTHORIZED');expect(mocks.raw).not.toHaveBeenCalled()});
 it('requires a paid Admin seat, including during a zero-Admin trial',async()=>{mocks.subscription.mockResolvedValue(null);await expect(createAdditionalAdmin(input)).rejects.toThrow('SEAT_LIMIT');expect(mocks.create).not.toHaveBeenCalled()});
 it('rejects cross-company, Primary, Manager, Sales and legacy-only targets canonically',async()=>{for(let invalidRole=0;invalidRole<4;invalidRole+=1){mocks.find.mockResolvedValueOnce(null);await expect(editAdditionalAdmin({userId:USER,name:'X',email:'x@example.com',phone:''})).rejects.toThrow('NOT_FOUND')}expect(mocks.find).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:COMPANY,salesRole:'ADMIN'})}))});
 it('scopes the initial user row lock by company before the authoritative read',async()=>{await editAdditionalAdmin({userId:USER,name:'X',email:'x@example.com',phone:''});const call=mocks.raw.mock.calls[0];expect(call[0].join(' ')).toContain('"id"=');expect(call[0].join(' ')).toContain('"companyId"=');expect(call).toContain(USER);expect(call).toContain(COMPANY)});
 it('cannot intentionally lock a foreign UUID outside the actor company',async()=>{mocks.find.mockResolvedValue(null);await expect(editAdditionalAdmin({userId:USER,name:'X',email:'x@example.com',phone:''})).rejects.toThrow('NOT_FOUND');const call=mocks.raw.mock.calls[0];expect(call).toContain(COMPANY);expect(call).not.toContain(FOREIGN)});
 it('explicitly vetoes canonical ADMIN plus legacy SUPER_ADMIN and excludes it from reads',async()=>{mocks.find.mockResolvedValue({id:USER,isActive:true,salesAccessActive:true,role:'SUPER_ADMIN'});await expect(editAdditionalAdmin({userId:USER,name:'X',email:'x@example.com',phone:''})).rejects.toThrow('NOT_FOUND');await listAdditionalAdmins();expect(mocks.many).toHaveBeenCalledWith(expect.objectContaining({where:{companyId:COMPANY,salesRole:'ADMIN',role:{not:'SUPER_ADMIN'}}}))});
 it('edits only contact fields and preserves dual-workspace and role fields',async()=>{await editAdditionalAdmin({userId:USER,name:'Changed',email:'changed@example.com',phone:'+91123'});const data=mocks.updateMany.mock.calls[0][0].data;expect(data).toEqual({name:'Changed',email:'changed@example.com',phone:'+91123'});for(const key of ['salesRole','role','accountRole','accountAccessActive','branchAccessScope','managerId'])expect(data).not.toHaveProperty(key)});
 it('deactivates and reactivates only validated Additional Admin targets',async()=>{await setAdditionalAdminActive({userId:USER},false);expect(mocks.deactivate).toHaveBeenCalled();mocks.find.mockResolvedValue({id:USER,isActive:false,salesAccessActive:false,role:'FIELD_ADMIN'});await setAdditionalAdminActive({userId:USER},true);expect(mocks.activate).toHaveBeenCalled()});
 it('requires an available seat to restore Sales access',async()=>{mocks.find.mockResolvedValue({id:USER,isActive:true,salesAccessActive:false,role:'FIELD_ADMIN'});mocks.count.mockResolvedValue(1);await expect(restoreAdditionalAdminSales({userId:USER})).rejects.toThrow('SEAT_LIMIT');expect(mocks.activate).not.toHaveBeenCalled()});
 it('resets password, increments session generation and revokes authentication',async()=>{await resetAdditionalAdminPassword({userId:USER,password:input.password,confirmPassword:input.password});expect(mocks.update).toHaveBeenCalledWith({where:{id:USER},data:{passwordHash:'hash',sessionVersion:{increment:1}}});expect(mocks.clear).toHaveBeenCalledWith(expect.anything(),USER)});
});
