import {Prisma} from '@prisma/client';
import {z} from 'zod';
import {db} from '@/lib/db';
import {requirePermission,requirePermissionForMutation} from '@/lib/auth/authorization';
import {hashPassword} from '@/lib/auth/password';
import {strongPasswordSchema} from '@/lib/auth/validation';
import {projectLegacyRole} from './role-projection';
import {clearUserAuthentication} from '@/lib/auth/session-generation';
import {activateSalesAccessInTransaction,deactivateIdentityWithLock,suspendSalesAccessInTransaction} from '@/lib/auth/lifecycle';
import {getTrialStatus}from '@/lib/trial/status';
import {hasSalesWorkspace} from '@/lib/product/edition';

const optionalPhone=z.preprocess(v=>typeof v==='string'&&v.trim()===''?null:v,z.string().trim().min(1).max(30).nullable().optional());
export const createAdditionalAdminSchema=z.object({name:z.string().trim().min(1).max(120),email:z.string().trim().toLowerCase().email().max(320),phone:optionalPhone,password:strongPasswordSchema,confirmPassword:z.string()}).strict().refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords do not match'});
export const editAdditionalAdminSchema=z.object({userId:z.string().uuid(),name:z.string().trim().min(1).max(120),email:z.string().trim().toLowerCase().email().max(320),phone:optionalPhone}).strict();
export const additionalAdminIdSchema=z.object({userId:z.string().uuid()}).strict();
export const resetAdditionalAdminPasswordSchema=z.object({userId:z.string().uuid(),password:strongPasswordSchema,confirmPassword:z.string()}).strict().refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords do not match'});

async function primary(mutation:boolean){const actor=mutation?await requirePermissionForMutation('SALES_USER_ADMIN'):await requirePermission('SALES_USER_ADMIN');if(!actor.companyId||actor.salesRole!=='PRIMARY_ADMIN')throw new Error('NOT_AUTHORIZED');return{...actor,companyId:actor.companyId}}
async function lockCompany(tx:Prisma.TransactionClient,id:string){await tx.$queryRaw`SELECT 1 FROM "companies" WHERE "id"=${id}::uuid FOR UPDATE`;const c=await tx.company.findUnique({where:{id},select:{productEdition:true,subscriptionStatus:true,trialStartedAt:true,trialEndsAt:true,teamStructure:true}});if(!c)throw new Error('NOT_FOUND');return c}
async function target(tx:Prisma.TransactionClient,companyId:string,userId:string){
 await tx.$queryRaw`SELECT 1 FROM "users" WHERE "id"=${userId}::uuid AND "companyId"=${companyId}::uuid FOR UPDATE`;
 const u=await tx.user.findFirst({where:{id:userId,companyId,salesRole:'ADMIN',role:{not:'SUPER_ADMIN'}},select:{id:true,isActive:true,salesAccessActive:true,role:true,accountRole:true,accountAccessActive:true}});
 if(!u||u.role==='SUPER_ADMIN')throw new Error('NOT_FOUND');return u
}
async function ensureSeat(tx:Prisma.TransactionClient,companyId:string,company?:{subscriptionStatus:"TRIAL"|"ACTIVE"|"EXPIRED"|"SUSPENDED";trialStartedAt:Date|null;trialEndsAt:Date|null;teamStructure:"MANAGERS_AND_SALES"|"SALES_ONLY"}){const now=new Date();if(company&&getTrialStatus(company).effectiveStatus==='TRIAL')throw new Error('SEAT_LIMIT');const [used,sub]=await Promise.all([tx.user.count({where:{companyId,isActive:true,salesAccessActive:true,salesRole:'ADMIN'}}),tx.companySubscription.findFirst({where:{companyId,status:'ACTIVE',startsAt:{lte:now},endsAt:{gt:now}},orderBy:{endsAt:'desc'}})]);if(used>=(sub?.adminSeats??0))throw new Error('SEAT_LIMIT')}
export async function listAdditionalAdmins(){const a=await primary(false);return db.user.findMany({where:{companyId:a.companyId,salesRole:'ADMIN',role:{not:'SUPER_ADMIN'}},select:{id:true,name:true,email:true,phone:true,isActive:true,salesAccessActive:true,accountRole:true,accountAccessActive:true},orderBy:{name:'asc'}})}
export async function createAdditionalAdmin(raw:unknown){const a=await primary(true),d=createAdditionalAdminSchema.parse(raw),passwordHash=await hashPassword(d.password);return db.$transaction(async tx=>{const company=await lockCompany(tx,a.companyId);await ensureSeat(tx,a.companyId,company);return tx.user.create({data:{companyId:a.companyId,name:d.name,email:d.email,phone:d.phone,passwordHash,salesRole:'ADMIN',role:projectLegacyRole({salesRole:'ADMIN',accountRole:null}),isActive:true,salesAccessActive:hasSalesWorkspace(company.productEdition),accountRole:null,accountAccessActive:false,branchAccessScope:'ALL_BRANCHES',managerId:null,managerType:null}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function editAdditionalAdmin(raw:unknown){const a=await primary(true),d=editAdditionalAdminSchema.parse(raw);return db.$transaction(async tx=>{await target(tx,a.companyId,d.userId);const r=await tx.user.updateMany({where:{id:d.userId,companyId:a.companyId,salesRole:'ADMIN'},data:{name:d.name,email:d.email,phone:d.phone}});if(r.count!==1)throw new Error('NOT_FOUND')})}
export async function setAdditionalAdminActive(raw:unknown,active:boolean){const a=await primary(true),d=additionalAdminIdSchema.parse(raw);return db.$transaction(async tx=>{const company=await lockCompany(tx,a.companyId);const u=await target(tx,a.companyId,d.userId);if(active){if(!u.isActive){await ensureSeat(tx,a.companyId,company);await tx.user.update({where:{id:u.id},data:{isActive:true}})}if(!u.salesAccessActive){await ensureSeat(tx,a.companyId,company);await activateSalesAccessInTransaction(tx,u.id)}}else if(u.isActive){if(u.accountRole)await suspendSalesAccessInTransaction(tx,u.id);else await deactivateIdentityWithLock(tx,u.id)}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function restoreAdditionalAdminSales(raw:unknown){const a=await primary(true),d=additionalAdminIdSchema.parse(raw);return db.$transaction(async tx=>{const company=await lockCompany(tx,a.companyId);const u=await target(tx,a.companyId,d.userId);if(!u.isActive)throw new Error('IDENTITY_INACTIVE');if(!u.salesAccessActive){await ensureSeat(tx,a.companyId,company);await activateSalesAccessInTransaction(tx,u.id)}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function suspendAdditionalAdminSales(raw:unknown){const a=await primary(true),d=additionalAdminIdSchema.parse(raw);return db.$transaction(async tx=>{const u=await target(tx,a.companyId,d.userId);if(u.salesAccessActive)await suspendSalesAccessInTransaction(tx,u.id)})}
export async function resetAdditionalAdminPassword(raw:unknown){const a=await primary(true),d=resetAdditionalAdminPasswordSchema.parse(raw),passwordHash=await hashPassword(d.password);return db.$transaction(async tx=>{const u=await target(tx,a.companyId,d.userId);await tx.user.update({where:{id:u.id},data:{passwordHash,sessionVersion:{increment:1}}});await clearUserAuthentication(tx,u.id)})}
