import{beforeEach,describe,expect,it,vi}from"vitest";
const m=vi.hoisted(()=>({owner:vi.fn(),transaction:vi.fn(),candidates:vi.fn(),revoke:vi.fn()}));
vi.mock("@/lib/company/owner-authorization",()=>({requirePrimaryOwner:m.owner}));vi.mock("@/lib/auth/session-generation",()=>({revokeUserAuthenticationWithLock:m.revoke}));vi.mock("@/lib/db",()=>({db:{$transaction:m.transaction,user:{findMany:m.candidates}}}));
import{listPrimaryAdminTransferCandidates,transferPrimaryAdmin}from"./primary-admin";
const companyId="1d8b93fd-eed3-48f0-b117-047574625ada",actorId="0202cd71-0a78-44c8-86a2-dcee7e899209",targetId="4f0ef50d-d8a6-4b31-8d8d-cb87c1c6ed60";
const actor={id:actorId,companyId,role:"COMPANY_ADMIN",salesRole:"PRIMARY_ADMIN",accountRole:"ACCOUNT_ADMIN",isActive:true,salesAccessActive:true,accountAccessActive:true,branchAccessScope:"ALL_BRANCHES"};
function tx(target={...actor,id:targetId,salesRole:"ADMIN"}){const x={$queryRaw:vi.fn(),user:{findFirst:vi.fn().mockResolvedValueOnce(actor).mockResolvedValueOnce(target),findMany:vi.fn().mockResolvedValue([{id:actorId}]),updateMany:vi.fn().mockResolvedValue({count:1}),count:vi.fn().mockResolvedValue(1)},userBranchAccess:{deleteMany:vi.fn()}};m.transaction.mockImplementation(async f=>f(x));return x}
beforeEach(()=>{vi.clearAllMocks();m.owner.mockResolvedValue({actor,company:{productEdition:"SALESPUNCH360_PLUS"}})});
describe("product-aware Primary ownership transfer",()=>{it("requires a complete Plus admin, keeps Account roles, forces all branches, and revokes both identities",async()=>{const x=tx();await expect(transferPrimaryAdmin({targetUserId:targetId})).resolves.toEqual({primaryAdminId:targetId});expect(x.user.updateMany).toHaveBeenCalledTimes(2);expect(x.user.updateMany.mock.calls[0][0].data).toMatchObject({salesRole:"ADMIN",branchAccessScope:"ALL_BRANCHES"});expect(x.user.updateMany.mock.calls[1][0].data).toMatchObject({salesRole:"PRIMARY_ADMIN",branchAccessScope:"ALL_BRANCHES"});expect(m.revoke).toHaveBeenCalledTimes(2)});it("rejects self transfer",async()=>{await expect(transferPrimaryAdmin({targetUserId:actorId})).rejects.toThrow("SELF_TRANSFER")});it("lists Account-only eligible Account Admins without Sales access",async()=>{m.owner.mockResolvedValue({actor:{...actor,salesAccessActive:false},company:{productEdition:"SALESPUNCH360_ACCOUNT"}});m.candidates.mockResolvedValue([]);await listPrimaryAdminTransferCandidates();expect(m.candidates).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({accountRole:"ACCOUNT_ADMIN",accountAccessActive:true})}))})});
