import {describe,expect,it} from "vitest";
import {createProductUserSchema,editProductUserSchema} from "./product-user-management";
import {assertEditableProductUser,roleChangeRequiresAuthenticationRevocation,validateUserRoleAssignment} from "./product-role-policy";
const id="11111111-1111-4111-8111-111111111111";
const base={salesRole:null,accountRole:null,managerType:null};
describe("product-aware Company users",()=>{
 it("accepts Sales-only, Account-only, and Plus dual identities",()=>{expect(validateUserRoleAssignment("SALESPUNCH360",{...base,salesRole:"SALES"})).toBeTruthy();expect(validateUserRoleAssignment("SALESPUNCH360_ACCOUNT",{...base,accountRole:"ACCOUNTANT"})).toBeTruthy();expect(validateUserRoleAssignment("SALESPUNCH360_PLUS",{salesRole:"MANAGER",accountRole:"ACCOUNTANT",managerType:"FIELD_MANAGER"})).toBeTruthy()});
 it("rejects cross-product roles and invalid manager types",()=>{expect(()=>validateUserRoleAssignment("SALESPUNCH360",{...base,accountRole:"DATA_ENTRY"})).toThrow("ACCOUNT_ROLE_NOT_ENTITLED");expect(()=>validateUserRoleAssignment("SALESPUNCH360_ACCOUNT",{...base,salesRole:"SALES"})).toThrow("SALES_ROLE_NOT_ENTITLED");expect(()=>validateUserRoleAssignment("SALESPUNCH360_PLUS",{...base,salesRole:"MANAGER"})).toThrow("MANAGER_TYPE_REQUIRED");expect(()=>validateUserRoleAssignment("SALESPUNCH360_PLUS",{...base,salesRole:"SALES",managerType:"FIELD_MANAGER"})).toThrow("MANAGER_TYPE_NOT_ALLOWED")});
 it("uses scalar enums so two roles in either domain are impossible",()=>{const input={name:"User",email:"u@example.com",password:"Password1234",confirmPassword:"Password1234",salesRole:["MANAGER","SALES"],accountRole:["ACCOUNTANT","DATA_ENTRY"],managerType:null,managerId:null,branchAccessScope:"ALL_BRANCHES",branchIds:[]};expect(createProductUserSchema.safeParse(input).success).toBe(false)});
 it("protects Primary Admin and cross-tenant edits",()=>{expect(()=>assertEditableProductUser("a",{companyId:"a",salesRole:"PRIMARY_ADMIN"})).toThrow("PRIMARY_PROTECTED");expect(()=>assertEditableProductUser("a",{companyId:"b",salesRole:"SALES"})).toThrow("NOT_FOUND")});
 it("preserves the other workspace while revoking stale authentication",()=>{const before={salesRole:"MANAGER" as const,accountRole:"ACCOUNTANT" as const,managerType:"FIELD_MANAGER" as const,managerId:null,salesAccessActive:true,accountAccessActive:true,branchAccessScope:"ALL_BRANCHES",branchIds:[id]};const after={...before,salesAccessActive:false};expect(after.accountAccessActive).toBe(true);expect(roleChangeRequiresAuthenticationRevocation(before,after)).toBe(true);expect(editProductUserSchema.safeParse({userId:id,name:"User",email:"u@example.com",...after}).success).toBe(true)});
});
