import {Prisma} from '@prisma/client';
import {beforeEach,describe,expect,it,vi} from 'vitest';

const events:string[]=[];
const mocks=vi.hoisted(()=>({permission:vi.fn(),transaction:vi.fn(),existing:vi.fn(),prices:vi.fn(),company:vi.fn(),raw:vi.fn(),activeSubscription:vi.fn(),usage:vi.fn(),retainedCount:vi.fn(),orderCreate:vi.fn(),auditCreate:vi.fn()}));
vi.mock('@/lib/auth/authorization',()=>({requirePermissionForMutation:mocks.permission,requirePermission:vi.fn(),requireRole:vi.fn()}));
vi.mock('@/lib/billing/seat-reduction',()=>({applyDueSeatReductions:vi.fn()}));
vi.mock('@/lib/db',()=>({db:{billingOrder:{findUnique:mocks.existing},billingPrice:{findMany:mocks.prices},$transaction:mocks.transaction}}));
import {createBillingOrder} from './service';

const salesIds=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];
const request=(managerSeats=0,retainSalesUserIds:string[]=[],salesSeats=2)=>({billingPeriod:'MONTHLY',adminSeats:1,managerSeats,salesSeats,retainAdminUserIds:[],retainManagerUserIds:[],retainSalesUserIds,idempotencyKey:'order-key-123456789'});
const prices=['ADMIN','MANAGER','SALES'].map(role=>({role,period:'MONTHLY',currency:'INR',amount:new Prisma.Decimal(100)}));
function tx(){return{$queryRaw:mocks.raw,company:{findUnique:mocks.company},companySubscription:{findFirst:mocks.activeSubscription},user:{groupBy:mocks.usage,count:mocks.retainedCount},billingOrder:{create:mocks.orderCreate},billingAuditEvent:{create:mocks.auditCreate}}}

beforeEach(()=>{vi.clearAllMocks();events.length=0;mocks.permission.mockResolvedValue({id:'primary',companyId:'company'});mocks.existing.mockResolvedValue(null);mocks.prices.mockResolvedValue(prices);mocks.raw.mockImplementation(async()=>{events.push('company-lock');return[]});mocks.company.mockImplementation(async()=>{events.push('company-reread');return{id:'company',teamStructure:'MANAGERS_AND_SALES'}});mocks.activeSubscription.mockImplementation(async()=>{events.push('paid-state');return null});mocks.usage.mockImplementation(async()=>{events.push('usage');return[]});mocks.retainedCount.mockImplementation(async()=>{events.push('retained-users');return 2});mocks.orderCreate.mockImplementation(async({data})=>{events.push('order-write');return{id:'order',...data}});mocks.auditCreate.mockImplementation(async()=>{events.push('audit-write');return{id:'audit'}});mocks.transaction.mockImplementation(work=>work(tx()))});

describe('billing order company serialization',()=>{
 it('rereads paid state and canonical usage after the company lock and before order/audit writes',async()=>{await createBillingOrder(request());expect(events).toEqual(['company-lock','company-reread','paid-state','usage','order-write','audit-write']);expect(mocks.activeSubscription).toHaveBeenCalledWith({where:{companyId:'company',status:'ACTIVE',startsAt:{lte:expect.any(Date)},endsAt:{gt:expect.any(Date)}},select:{id:true}});expect(mocks.usage).toHaveBeenCalledWith({by:['salesRole'],where:{companyId:'company',isActive:true,salesAccessActive:true,salesRole:{in:['ADMIN','MANAGER','SALES']}},_count:true})});
 it('rejects the usage 2 to 3 race with an empty retention snapshot before writes',async()=>{mocks.activeSubscription.mockImplementation(async()=>{events.push('paid-state');return{id:'paid'}});mocks.usage.mockImplementation(async()=>{events.push('usage');return[{salesRole:'SALES',_count:3}]});await expect(createBillingOrder(request())).rejects.toThrow('SEAT_SELECTION_REQUIRED');expect(events).toEqual(['company-lock','company-reread','paid-state','usage']);expect(mocks.orderCreate).not.toHaveBeenCalled();expect(mocks.auditCreate).not.toHaveBeenCalled()});
 it('creates a renewal when the final usage is three and both retained Sales users are currently valid',async()=>{mocks.activeSubscription.mockImplementation(async()=>{events.push('paid-state');return{id:'paid'}});mocks.usage.mockImplementation(async()=>{events.push('usage');return[{salesRole:'SALES',_count:3}]});await expect(createBillingOrder(request(0,salesIds))).resolves.toBeTruthy();expect(events).toEqual(['company-lock','company-reread','paid-state','usage','retained-users','order-write','audit-write']);expect(mocks.retainedCount).toHaveBeenCalledWith({where:{companyId:'company',salesRole:'SALES',isActive:true,salesAccessActive:true,id:{in:salesIds}}})});
 it('rejects Manager seats for SALES_ONLY before authoritative seat reads or writes',async()=>{mocks.company.mockImplementation(async()=>{events.push('company-reread');return{id:'company',teamStructure:'SALES_ONLY'}});await expect(createBillingOrder(request(1))).rejects.toThrow('MANAGERS_DISABLED');expect(events).toEqual(['company-lock','company-reread']);expect(mocks.orderCreate).not.toHaveBeenCalled()});
 it('allows zero Manager seats for SALES_ONLY after authoritative seat validation',async()=>{mocks.company.mockImplementation(async()=>{events.push('company-reread');return{id:'company',teamStructure:'SALES_ONLY'}});await expect(createBillingOrder(request())).resolves.toBeTruthy();expect(events.at(-2)).toBe('order-write')});
});
