import {beforeEach,describe,expect,it,vi} from 'vitest';import {Prisma} from '@prisma/client';
const events:string[]=[];
const mocks=vi.hoisted(()=>({transaction:vi.fn(),role:vi.fn(),raw:vi.fn(),companyFind:vi.fn(),orderFind:vi.fn(),paymentFind:vi.fn(),subscriptionFind:vi.fn(),subscriptionMany:vi.fn(),paymentCreate:vi.fn(),orderUpdate:vi.fn(),subscriptionCreate:vi.fn(),companyUpdate:vi.fn(),auditMany:vi.fn(),groupBy:vi.fn(),userCount:vi.fn(),audit:vi.fn(),reduce:vi.fn()}));
vi.mock('@/lib/db',()=>({db:{$transaction:mocks.transaction}}));vi.mock('@/lib/auth/authorization',()=>({requireGlobalSuperAdmin:mocks.role,requireGlobalSuperAdminForMutation:mocks.role,requirePermission:vi.fn(),requirePermissionForMutation:vi.fn()}));vi.mock('./seat-reduction',()=>({applyDueSeatReductions:mocks.reduce}));
import {activateVerifiedPayment,manualOverride} from './service';
const capturedAt=new Date('2026-09-08T12:00:00Z'),retainedSales=['11111111-1111-4111-8111-111111111111'],order={id:'order',companyId:'company',status:'PENDING',totalAmount:new Prisma.Decimal(600),currency:'INR',billingPeriod:'SIX_MONTH',adminSeats:1,managerSeats:1,salesSeats:1,retainAdminUserIds:[],retainManagerUserIds:[],retainSalesUserIds:[]};
function tx(){return {$queryRaw:mocks.raw,company:{findUnique:mocks.companyFind,update:mocks.companyUpdate},billingOrder:{findUnique:mocks.orderFind,update:mocks.orderUpdate},paymentTransaction:{findUnique:mocks.paymentFind,create:mocks.paymentCreate},companySubscription:{findFirst:mocks.subscriptionFind,findMany:mocks.subscriptionMany,create:mocks.subscriptionCreate},billingAuditEvent:{createMany:mocks.auditMany,create:mocks.audit},user:{groupBy:mocks.groupBy,count:mocks.userCount}}}
beforeEach(()=>{vi.clearAllMocks();events.length=0;mocks.role.mockResolvedValue({id:'super'});mocks.paymentFind.mockResolvedValue(null);mocks.orderFind.mockImplementation(({select})=>{events.push(select?'tenant-order-read':'authoritative-order-read');return select?{companyId:'company'}:order});mocks.raw.mockImplementation((strings:TemplateStringsArray)=>{events.push(strings.join(' ').includes('billing_orders')?'order-lock':'company-lock');return []});mocks.companyFind.mockImplementation(()=>{events.push('company-read');return {id:'company',teamStructure:'MANAGERS_AND_SALES'}});mocks.subscriptionFind.mockImplementation(()=>{events.push('subscription-read');return null});mocks.subscriptionMany.mockImplementation(()=>{events.push('subscription-read');return[]});mocks.paymentCreate.mockResolvedValue({id:'payment',companyId:'company'});mocks.subscriptionCreate.mockImplementation(({data})=>{events.push('subscription-write');return {id:'subscription',...data}});mocks.groupBy.mockImplementation(()=>{events.push('usage-count');return [{salesRole:'ADMIN',_count:1},{salesRole:'MANAGER',_count:1},{salesRole:'SALES',_count:1}]});mocks.userCount.mockResolvedValue(1);mocks.transaction.mockImplementation(work=>work(tx()))});
describe('billing company serialization',()=>{
 it('payment locks company then order, validates canonical usage, and only then writes',async()=>{await activateVerifiedPayment({orderId:'order',provider:'TEST',providerPaymentId:'provider-payment',amount:'600',currency:'INR',capturedAt});expect(events).toEqual(expect.arrayContaining(['tenant-order-read','company-lock','company-read','order-lock','authoritative-order-read','usage-count','subscription-read','subscription-write']));expect(events.indexOf('company-lock')).toBeLessThan(events.indexOf('order-lock'));expect(events.indexOf('order-lock')).toBeLessThan(events.indexOf('authoritative-order-read'));expect(events.indexOf('authoritative-order-read')).toBeLessThan(events.indexOf('usage-count'));expect(events.indexOf('usage-count')).toBeLessThan(events.indexOf('subscription-write'));expect(mocks.subscriptionCreate).toHaveBeenCalledWith({data:expect.objectContaining({adminSeats:1,managerSeats:1,salesSeats:1,sourceOrderId:'order'})})});
 it('rejects a stale Manager-seat payment for SALES_ONLY after company then order locks and before every write',async()=>{mocks.companyFind.mockImplementation(()=>{events.push('company-read');return{id:'company',teamStructure:'SALES_ONLY'}});await expect(activateVerifiedPayment({orderId:'order',provider:'TEST',providerPaymentId:'blocked',amount:'600',currency:'INR',capturedAt})).rejects.toThrow('MANAGERS_DISABLED');expect(events).toEqual(['tenant-order-read','company-lock','company-read','order-lock','authoritative-order-read']);expect(mocks.paymentCreate).not.toHaveBeenCalled();expect(mocks.orderUpdate).not.toHaveBeenCalled();expect(mocks.subscriptionCreate).not.toHaveBeenCalled();expect(mocks.companyUpdate).not.toHaveBeenCalled();expect(mocks.auditMany).not.toHaveBeenCalled()});
 it('allows a zero-Manager payment for SALES_ONLY',async()=>{mocks.companyFind.mockImplementation(()=>{events.push('company-read');return{id:'company',teamStructure:'SALES_ONLY'}});mocks.orderFind.mockImplementation(({select})=>{events.push(select?'tenant-order-read':'authoritative-order-read');return select?{companyId:'company'}:{...order,managerSeats:0}});await expect(activateVerifiedPayment({orderId:'order',provider:'TEST',providerPaymentId:'zero-manager',amount:'600',currency:'INR',capturedAt})).resolves.toBeTruthy();expect(mocks.paymentCreate).toHaveBeenCalledTimes(1);expect(mocks.subscriptionCreate).toHaveBeenCalledWith({data:expect.objectContaining({managerSeats:0})})});
 it('rejects stale retention before every financial write when current usage exceeds the locked order',async()=>{mocks.groupBy.mockImplementation(()=>{events.push('usage-count');return[{salesRole:'SALES',_count:2}]});await expect(activateVerifiedPayment({orderId:'order',provider:'TEST',providerPaymentId:'stale-retention',amount:'600',currency:'INR',capturedAt})).rejects.toThrow('SEAT_REDUCTION_SELECTION_REQUIRED');expect(events.slice(0,6)).toEqual(['tenant-order-read','company-lock','company-read','order-lock','authoritative-order-read','usage-count']);expect(mocks.paymentCreate).not.toHaveBeenCalled();expect(mocks.orderUpdate).not.toHaveBeenCalled();expect(mocks.subscriptionCreate).not.toHaveBeenCalled();expect(mocks.companyUpdate).not.toHaveBeenCalled();expect(mocks.auditMany).not.toHaveBeenCalled()});
 it('activates when over-limit usage has a valid locked retained snapshot',async()=>{mocks.orderFind.mockImplementation(({select})=>{events.push(select?'tenant-order-read':'authoritative-order-read');return select?{companyId:'company'}:{...order,retainSalesUserIds:retainedSales}});mocks.groupBy.mockImplementation(()=>{events.push('usage-count');return[{salesRole:'SALES',_count:2}]});mocks.groupBy.mockImplementationOnce(()=>{events.push('usage-count');return[{salesRole:'SALES',_count:2}]});await expect(activateVerifiedPayment({orderId:'order',provider:'TEST',providerPaymentId:'valid-retention',amount:'600',currency:'INR',capturedAt})).resolves.toBeTruthy();expect(mocks.subscriptionCreate).toHaveBeenCalledTimes(1)});
 it('manual override locks and confirms company before canonical three-role usage',async()=>{await manualOverride({companyId:'11111111-1111-4111-8111-111111111111',status:'ACTIVE',billingPeriod:'SIX_MONTH',adminSeats:1,managerSeats:1,salesSeats:1,endsAt:'2027-01-01T00:00:00.000Z',reason:'approved support correction'});expect(events.indexOf('company-lock')).toBeLessThan(events.indexOf('usage-count'));expect(mocks.groupBy).toHaveBeenCalledWith({by:['salesRole'],where:{companyId:'11111111-1111-4111-8111-111111111111',isActive:true,salesAccessActive:true,salesRole:{in:['ADMIN','MANAGER','SALES']}},_count:true})});
 it('rejects a lower entitlement under the same company serialization',async()=>{await expect(manualOverride({companyId:'11111111-1111-4111-8111-111111111111',status:'ACTIVE',billingPeriod:'SIX_MONTH',adminSeats:0,managerSeats:1,salesSeats:1,endsAt:'2027-01-01T00:00:00.000Z',reason:'approved support correction'})).rejects.toThrow('SEATS_BELOW_USAGE');expect(events.slice(0,3)).toEqual(['company-lock','company-read','usage-count']);expect(mocks.subscriptionCreate).not.toHaveBeenCalled()});
 it('rejects Manager seats for SALES_ONLY before usage or subscription writes',async()=>{mocks.companyFind.mockImplementation(()=>{events.push('company-read');return {id:'company',teamStructure:'SALES_ONLY'}});await expect(manualOverride({companyId:'11111111-1111-4111-8111-111111111111',status:'ACTIVE',billingPeriod:'SIX_MONTH',adminSeats:1,managerSeats:1,salesSeats:1,endsAt:'2027-01-01T00:00:00.000Z',reason:'approved support correction'})).rejects.toThrow('MANAGERS_DISABLED');expect(events).toEqual(['company-lock','company-read']);expect(mocks.subscriptionCreate).not.toHaveBeenCalled()});
 it('allows zero Managers for SALES_ONLY',async()=>{mocks.companyFind.mockImplementation(()=>{events.push('company-read');return {id:'company',teamStructure:'SALES_ONLY'}});mocks.groupBy.mockResolvedValue([{salesRole:'ADMIN',_count:1},{salesRole:'SALES',_count:1}]);await expect(manualOverride({companyId:'11111111-1111-4111-8111-111111111111',status:'ACTIVE',billingPeriod:'SIX_MONTH',adminSeats:1,managerSeats:0,salesSeats:1,endsAt:'2027-01-01T00:00:00.000Z',reason:'approved support correction'})).resolves.toBeTruthy();expect(mocks.subscriptionCreate).toHaveBeenCalled()});
 it('allows positive Managers for MANAGERS_AND_SALES',async()=>{await expect(manualOverride({companyId:'11111111-1111-4111-8111-111111111111',status:'ACTIVE',billingPeriod:'SIX_MONTH',adminSeats:1,managerSeats:1,salesSeats:1,endsAt:'2027-01-01T00:00:00.000Z',reason:'approved support correction'})).resolves.toBeTruthy()});

});
