import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { requireGlobalSuperAdminForMutation, requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";
import { TELECALLER_PRICE_SCHEDULE_INR, type TelecallerBillingPeriod } from "./sales-pricing";
import { ACCOUNT_PACKAGE_ORDER_PROVIDER } from "./account-package";

export const TELECALLER_ORDER_PROVIDER = "TELECALLER_PACKAGE" as const;

type TelecallerSubscriptionRow = {id:string;companyId:string;status:"ACTIVE"|"EXPIRED"|"CANCELLED";billingPeriod:TelecallerBillingPeriod;seats:number;startsAt:Date;endsAt:Date;sourceOrderId:string|null};
export type TelecallerBillingOrderRow = {id:string;companyId:string;companyName?:string;createdByUserId:string;createdByName?:string;billingPeriod:TelecallerBillingPeriod;addedSeats:number;targetSeats:number;unitPrice:Prisma.Decimal;subtotal:Prisma.Decimal;totalAmount:Prisma.Decimal;status:"PENDING"|"PAID"|"FAILED"|"CANCELLED"|"EXPIRED";paymentReference:string|null;coTermStartsAt:Date;coTermEndsAt:Date;paidAt:Date|null;expiresAt:Date|null;createdAt:Date};
const telecallerDesignationSql=Prisma.sql`upper(replace(coalesce(designation,''),' ',''))='TELECALLER'`;

async function activeSubscription(tx:Prisma.TransactionClient|typeof db,companyId:string,now=new Date()){
 const rows=await tx.$queryRaw<TelecallerSubscriptionRow[]>(Prisma.sql`SELECT id,"companyId",status,"billingPeriod",seats,"startsAt","endsAt","sourceOrderId" FROM "telecaller_subscriptions" WHERE "companyId"=${companyId}::uuid AND status='ACTIVE' AND "startsAt"<=${now} AND "endsAt">${now} ORDER BY "endsAt" DESC LIMIT 1`);return rows[0]??null;
}
async function activeTelecallerUsage(tx:Prisma.TransactionClient|typeof db,companyId:string,excludeUserId?:string){const rows=await tx.$queryRaw<{count:bigint}[]>(Prisma.sql`SELECT COUNT(*)::bigint AS count FROM "users" WHERE "companyId"=${companyId}::uuid AND "isActive"=TRUE AND "salesRole"='SALES'::"SalesRole" AND ${telecallerDesignationSql} ${excludeUserId?Prisma.sql`AND id<>${excludeUserId}::uuid`:Prisma.empty}`);return Number(rows[0]?.count??0)}
async function currentSalesTerm(tx:Prisma.TransactionClient|typeof db,companyId:string,now=new Date()){
 const rows=await tx.companySubscription.findMany({where:{companyId,status:"ACTIVE",startsAt:{lte:now},endsAt:{gt:now}},orderBy:{endsAt:"desc"},select:{id:true,billingPeriod:true,startsAt:true,endsAt:true,adminSeats:true,managerSeats:true,salesSeats:true,sourceOrder:{select:{provider:true}}}});
 return rows.find(r=>r.sourceOrder?.provider!==ACCOUNT_PACKAGE_ORDER_PROVIDER&&(r.adminSeats>0||r.managerSeats>0||r.salesSeats>0))??null;
}
export async function assertActiveTelecallerEntitlement(companyId:string){const subscription=await activeSubscription(db,companyId);if(!subscription)throw new Error("TELECALLER_SUBSCRIPTION_REQUIRED");return subscription}
export async function assertTelecallerSeatAvailable(companyId:string,excludeUserId?:string){const subscription=await activeSubscription(db,companyId);if(!subscription)throw new Error("TELECALLER_SUBSCRIPTION_REQUIRED");const used=await activeTelecallerUsage(db,companyId,excludeUserId);if(used>=subscription.seats)throw new Error("TELECALLER_SEAT_LIMIT");return{subscription,used,available:Math.max(0,subscription.seats-used)}}
export async function getTelecallerBillingOverview(){const actor=await requirePermission("SALES_BILLING");if(!actor.companyId)throw new Error("NOT_AUTHORIZED");return getTelecallerBillingOverviewForCompany(actor.companyId)}
export async function getTelecallerBillingOverviewForCompany(companyId:string){const now=new Date();await db.$executeRaw(Prisma.sql`UPDATE "telecaller_billing_orders" SET status='EXPIRED',"updatedAt"=NOW() WHERE "companyId"=${companyId}::uuid AND status='PENDING' AND "expiresAt" IS NOT NULL AND "expiresAt"<=NOW()`);await db.$executeRaw(Prisma.sql`UPDATE "telecaller_subscriptions" SET status='EXPIRED',"updatedAt"=NOW() WHERE "companyId"=${companyId}::uuid AND status='ACTIVE' AND "endsAt"<=NOW()`);const[subscription,used,orders]=await Promise.all([activeSubscription(db,companyId,now),activeTelecallerUsage(db,companyId),db.$queryRaw<TelecallerBillingOrderRow[]>(Prisma.sql`SELECT id,"companyId","createdByUserId","billingPeriod","addedSeats","targetSeats","unitPrice",subtotal,"totalAmount",status,"paymentReference","coTermStartsAt","coTermEndsAt","paidAt","expiresAt","createdAt" FROM "telecaller_billing_orders" WHERE "companyId"=${companyId}::uuid ORDER BY "createdAt" DESC LIMIT 20`)]);return{subscription,used,limit:subscription?.seats??0,available:Math.max(0,(subscription?.seats??0)-used),orders,prices:TELECALLER_PRICE_SCHEDULE_INR}}
export async function createTelecallerBillingOrder(_input:{addedSeats:number;billingPeriod:TelecallerBillingPeriod}){await requirePermissionForMutation("SALES_BILLING");throw new Error("TELECALLER_BILLING_MERGED_WITH_SALES")}
export async function listTelecallerBillingOrdersForAdmin(){await requireGlobalSuperAdminForMutation();return db.$queryRaw<TelecallerBillingOrderRow[]>(Prisma.sql`SELECT o.id,o."companyId",c.name AS "companyName",o."createdByUserId",u.name AS "createdByName",o."billingPeriod",o."addedSeats",o."targetSeats",o."unitPrice",o.subtotal,o."totalAmount",o.status,o."paymentReference",o."coTermStartsAt",o."coTermEndsAt",o."paidAt",o."expiresAt",o."createdAt" FROM "telecaller_billing_orders" o JOIN "companies" c ON c.id=o."companyId" JOIN "users" u ON u.id=o."createdByUserId" ORDER BY CASE o.status WHEN 'PENDING' THEN 0 ELSE 1 END,o."createdAt" DESC LIMIT 300`)}
export async function confirmTelecallerManualPayment(orderId:string,paymentReference:string){const admin=await requireGlobalSuperAdminForMutation(),reference=paymentReference.trim();if(!reference||reference.length>200)throw new Error("INVALID_PAYMENT_REFERENCE");return db.$transaction(async tx=>{const rows=await tx.$queryRaw<TelecallerBillingOrderRow[]>(Prisma.sql`SELECT id,"companyId","createdByUserId","billingPeriod","addedSeats","targetSeats","unitPrice",subtotal,"totalAmount",status,"paymentReference","coTermStartsAt","coTermEndsAt","paidAt","expiresAt","createdAt" FROM "telecaller_billing_orders" WHERE id=${orderId}::uuid FOR UPDATE`),order=rows[0];if(!order)throw new Error("ORDER_NOT_FOUND");if(order.paymentReference==='UNIFIED_SALES_ORDER')throw new Error("ORDER_MANAGED_BY_SALES_BILLING");if(order.status==="PAID")return order;if(order.status!=="PENDING")throw new Error("ORDER_NOT_PENDING");if(order.expiresAt&&order.expiresAt<=new Date())throw new Error("ORDER_EXPIRED");const duplicate=await tx.$queryRaw<{id:string}[]>(Prisma.sql`SELECT id FROM "telecaller_billing_orders" WHERE "paymentReference"=${reference} AND id<>${order.id}::uuid LIMIT 1`);if(duplicate.length)throw new Error("PAYMENT_REFERENCE_IN_USE");const term=await currentSalesTerm(tx,order.companyId);if(!term)throw new Error("SALES_SUBSCRIPTION_REQUIRED");const current=await activeSubscription(tx,order.companyId);if(current&&Math.abs(current.endsAt.getTime()-term.endsAt.getTime())<1000){await tx.$executeRaw(Prisma.sql`UPDATE "telecaller_subscriptions" SET seats=GREATEST(seats,${order.targetSeats}),"billingPeriod"=${term.billingPeriod}::text,"endsAt"=${term.endsAt},"updatedAt"=NOW() WHERE id=${current.id}::uuid`)}else{const subscriptionId=randomUUID();await tx.$executeRaw(Prisma.sql`INSERT INTO "telecaller_subscriptions" (id,"companyId",status,"billingPeriod",seats,"startsAt","endsAt","sourceOrderId","createdAt","updatedAt") VALUES (${subscriptionId}::uuid,${order.companyId}::uuid,'ACTIVE',${term.billingPeriod}::text,${order.targetSeats},NOW(),${term.endsAt},${order.id}::uuid,NOW(),NOW())`)}await tx.$executeRaw(Prisma.sql`UPDATE "telecaller_billing_orders" SET status='PAID',"paymentReference"=${reference},"coTermEndsAt"=${term.endsAt},"paidAt"=NOW(),"updatedAt"=NOW() WHERE id=${order.id}::uuid`);await tx.billingAuditEvent.create({data:{companyId:order.companyId,actorUserId:admin.id,type:"MANUAL_PAYMENT_CONFIRMED",entityId:order.id,reason:"Legacy Telecaller payment confirmed and co-termed to Sales",metadata:{kind:"TELECALLER_LEGACY",reference,targetSeats:order.targetSeats,salesEndsAt:term.endsAt.toISOString()}}});return{...order,status:"PAID" as const,paymentReference:reference,coTermEndsAt:term.endsAt,paidAt:new Date()}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
