import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";
import { costCentreSchema, ledgerAccountSchema, periodLockSchema, postingSchema, reversalSchema } from "./validation";
const D=Prisma.Decimal;
async function actor(permission:"ACCOUNT_LEDGER_VIEW"|"ACCOUNT_JOURNAL_POST"|"ACCOUNT_JOURNAL_REVERSE"|"ACCOUNT_OPENING_BALANCE"|"ACCOUNT_PERIOD_LOCK"|"ACCOUNT_CHART_ADMIN",mutation=true){const a=mutation?await requirePermissionForMutation(permission):await requirePermission(permission);return{...a,companyId:a.companyId!};}
export async function accountingOverview(){const a=await actor("ACCOUNT_LEDGER_VIEW",false);return db.company.findUniqueOrThrow({where:{id:a.companyId},select:{ledgerAccounts:{orderBy:{code:"asc"}},costCentres:{orderBy:{code:"asc"}},journalEntries:{orderBy:[{entryDate:"desc"},{createdAt:"desc"}],take:100,include:{lines:true}},financialYears:{where:{isActive:true},orderBy:{startDate:"desc"}},branches:{where:{isActive:true},orderBy:{name:"asc"}},accountingPeriodLocks:true}});}
export async function createLedgerAccount(raw:unknown){const a=await actor("ACCOUNT_CHART_ADMIN"),d=ledgerAccountSchema.parse(raw);if(d.parentId&&!await db.ledgerAccount.findFirst({where:{id:d.parentId,companyId:a.companyId,isActive:true,allowPosting:false}}))throw new Error("INVALID_PARENT_ACCOUNT");return db.ledgerAccount.create({data:{companyId:a.companyId,...d}});}
export async function createCostCentre(raw:unknown){const a=await actor("ACCOUNT_CHART_ADMIN"),d=costCentreSchema.parse(raw);return db.costCentre.create({data:{companyId:a.companyId,...d}});}
function assertBalanced(lines:{debit:string;credit:string}[]){const debit=lines.reduce((n,l)=>n.add(l.debit),new D(0)),credit=lines.reduce((n,l)=>n.add(l.credit),new D(0));if(!debit.equals(credit)||debit.isZero())throw new Error("UNBALANCED_JOURNAL");}
async function lockCompany(tx:Prisma.TransactionClient,companyId:string){await tx.$queryRaw`SELECT 1 FROM "companies" WHERE "id"=${companyId}::uuid FOR UPDATE`;}
async function validateContext(tx:Prisma.TransactionClient,a:{companyId:string;branchAccessScope?:string;branchIds?:string[]},d:{financialYearId:string;branchId:string;entryDate:Date}){if(a.branchAccessScope==="SELECTED_BRANCHES"&&!(a.branchIds??[]).includes(d.branchId))throw new Error("INVALID_BRANCH");const [fy,branch,lock]=await Promise.all([tx.financialYear.findFirst({where:{id:d.financialYearId,companyId:a.companyId,isActive:true,startDate:{lte:d.entryDate},endDate:{gte:d.entryDate}}}),tx.branch.findFirst({where:{id:d.branchId,companyId:a.companyId,isActive:true}}),tx.accountingPeriodLock.findFirst({where:{companyId:a.companyId,financialYearId:d.financialYearId}})]);if(!fy)throw new Error("INVALID_FINANCIAL_YEAR");if(!branch)throw new Error("INVALID_BRANCH");if(lock?.lockedThrough&&d.entryDate<=lock.lockedThrough)throw new Error("PERIOD_LOCKED");}
async function number(tx:Prisma.TransactionClient,companyId:string,branchId:string){await tx.numberingSeries.upsert({where:{companyId_branchId_seriesKey:{companyId,branchId,seriesKey:"MANUAL_JOURNAL"}},create:{companyId,branchId,seriesKey:"MANUAL_JOURNAL",prefix:"JV-",padding:6},update:{}});const [r]=await tx.$queryRaw<Array<{prefix:string;suffix:string;padding:number,n:bigint}>>(Prisma.sql`UPDATE numbering_series SET "nextSequence"="nextSequence"+1,"updatedAt"=NOW() WHERE "companyId"=${companyId}::uuid AND "branchId"=${branchId}::uuid AND "seriesKey"='MANUAL_JOURNAL' AND "isActive"=TRUE RETURNING prefix,suffix,padding,"nextSequence"-1 n`);if(!r)throw new Error("NUMBERING_UNAVAILABLE");return`${r.prefix}${r.n.toString().padStart(r.padding,"0")}${r.suffix}`;}
async function postInTx(tx:Prisma.TransactionClient,a:{id:string;companyId:string;branchAccessScope?:string;branchIds?:string[]},raw:unknown,event:"JOURNAL_POSTED"|"OPENING_BALANCE_POSTED"="JOURNAL_POSTED"){const d=postingSchema.parse(raw);assertBalanced(d.lines);await lockCompany(tx,a.companyId);await validateContext(tx,a,d);const accountIds=[...new Set(d.lines.map(x=>x.ledgerAccountId))],costIds=[...new Set(d.lines.flatMap(x=>x.costCentreId?[x.costCentreId]:[]))];const [accounts,costs]=await Promise.all([tx.ledgerAccount.findMany({where:{companyId:a.companyId,id:{in:accountIds},isActive:true,allowPosting:true}}),tx.costCentre.findMany({where:{companyId:a.companyId,id:{in:costIds},isActive:true}})]);if(accounts.length!==accountIds.length)throw new Error("INVALID_LEDGER_ACCOUNT");if(costs.length!==costIds.length)throw new Error("INVALID_COST_CENTRE");const journalNumber=await number(tx,a.companyId,d.branchId);const j=await tx.journalEntry.create({data:{companyId:a.companyId,financialYearId:d.financialYearId,branchId:d.branchId,journalNumber,entryDate:d.entryDate,status:"POSTED",reference:d.reference,narration:d.narration,sourceType:d.sourceType,sourceId:d.sourceId,postingPurpose:d.postingPurpose,createdById:a.id,postedById:a.id,postedAt:new Date(),lines:{create:d.lines.map((l,i)=>({companyId:a.companyId,lineNumber:i+1,ledgerAccountId:l.ledgerAccountId,costCentreId:l.costCentreId,debit:new D(l.debit),credit:new D(l.credit),description:l.description}))}}});await tx.accountingAuditEvent.create({data:{companyId:a.companyId,actorUserId:a.id,eventType:event,entityType:"JOURNAL_ENTRY",entityId:j.id}});return j;}
export async function postJournal(raw:unknown){const a=await actor("ACCOUNT_JOURNAL_POST");return db.$transaction(tx=>postInTx(tx,a,raw),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function postOpeningBalances(raw:unknown){const a=await actor("ACCOUNT_OPENING_BALANCE");return db.$transaction(async tx=>{const input=postingSchema.parse(raw);if(input.sourceType!=="OPENING_BALANCE")throw new Error("INVALID_SOURCE");return postInTx(tx,a,input,"OPENING_BALANCE_POSTED");},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function setPeriodLock(raw:unknown){const a=await actor("ACCOUNT_PERIOD_LOCK"),d=periodLockSchema.parse(raw);return db.$transaction(async tx=>{await lockCompany(tx,a.companyId);const fy=await tx.financialYear.findFirst({where:{id:d.financialYearId,companyId:a.companyId,isActive:true}});if(!fy||d.lockedThrough&&(d.lockedThrough<fy.startDate||d.lockedThrough>fy.endDate))throw new Error("INVALID_LOCK_DATE");const row=await tx.accountingPeriodLock.upsert({where:{companyId_financialYearId:{companyId:a.companyId,financialYearId:d.financialYearId}},create:{companyId:a.companyId,financialYearId:d.financialYearId,lockedThrough:d.lockedThrough,updatedById:a.id},update:{lockedThrough:d.lockedThrough,updatedById:a.id}});await tx.accountingAuditEvent.create({data:{companyId:a.companyId,actorUserId:a.id,eventType:d.lockedThrough?"PERIOD_LOCKED":"PERIOD_UNLOCKED",entityType:"FINANCIAL_YEAR",entityId:d.financialYearId,reason:d.reason}});return row;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function reverseJournal(raw:unknown){const a=await actor("ACCOUNT_JOURNAL_REVERSE"),d=reversalSchema.parse(raw);return db.$transaction(async tx=>{await lockCompany(tx,a.companyId);const original=await tx.journalEntry.findFirst({where:{id:d.journalEntryId,companyId:a.companyId,status:"POSTED",reversedBy:null},include:{lines:true}});if(!original)throw new Error("JOURNAL_NOT_REVERSIBLE");await validateContext(tx,a,{financialYearId:original.financialYearId,branchId:original.branchId,entryDate:d.entryDate});const journalNumber=await number(tx,a.companyId,original.branchId);const reversal=await tx.journalEntry.create({data:{companyId:a.companyId,financialYearId:original.financialYearId,branchId:original.branchId,journalNumber,entryDate:d.entryDate,status:"POSTED",sourceType:"REVERSAL",sourceId:original.id,postingPurpose:"REVERSAL",reversalOfId:original.id,reversalReason:d.reason,narration:`Reversal: ${d.reason}`,createdById:a.id,postedById:a.id,postedAt:new Date(),lines:{create:original.lines.map(l=>({companyId:a.companyId,lineNumber:l.lineNumber,ledgerAccountId:l.ledgerAccountId,costCentreId:l.costCentreId,debit:l.credit,credit:l.debit,description:l.description}))}}});await tx.journalEntry.update({where:{id:original.id},data:{status:"REVERSED"}});await tx.accountingAuditEvent.create({data:{companyId:a.companyId,actorUserId:a.id,eventType:"JOURNAL_REVERSED",entityType:"JOURNAL_ENTRY",entityId:original.id,reason:d.reason,metadata:{reversalId:reversal.id}}});return reversal;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
