import type { Metadata } from "next";
import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { updateOperationsAction } from "@/app/actions/attendance";
import { getCompanyOperations } from "@/lib/attendance/service";
import { getGeofenceSettings } from "@/lib/geofence/service";
import { updateGeofenceAction } from "@/app/actions/geofence";

export const metadata: Metadata = { title: "Operational settings" };

export default async function SettingsPage() {
  const [settings, geofence] = await Promise.all([getCompanyOperations(), getGeofenceSettings()]);
  if (!settings) return null;
  return <main className="settings-shell"><header className="employees-header"><Link href="/workspace">← Workspace</Link><BrandLogo href="/workspace" /></header><section className="settings-content"><p className="eyebrow">Company administration</p><h1>Operational settings</h1><p className="muted">Control attendance, location collection, and customer-visit flow.</p><form action={updateOperationsAction} className="settings-card"><label><div><strong>Attendance</strong><span>Allow active Managers and Sales employees to start work sessions.</span></div><input type="checkbox" name="attendanceEnabled" defaultChecked={settings.attendanceEnabled} /></label><label><div><strong>GPS Tracking</strong><span>Collect continuous route points only while attendance is open.</span></div><input type="checkbox" name="gpsTrackingEnabled" defaultChecked={settings.gpsTrackingEnabled} /></label><label><div><strong>Checkout required</strong><span>Require employees to finish a customer visit before another check-in.</span></div><input type="checkbox" name="checkoutRequiredBeforeNextCheckIn" defaultChecked={settings.checkoutRequiredBeforeNextCheckIn} /></label><button className="primary-button">Save settings</button></form><form action={updateGeofenceAction} className="settings-card geofence-settings"><h2>Geofence enforcement</h2><p className="muted">The server calculates straight-line Haversine distance. Radius must be 10–100000 meters.</p><label><div><strong>Attendance start geofence</strong><span>Require attendance starts near the single company reference point.</span></div><input type="checkbox" name="attendanceGeofenceEnabled" defaultChecked={geofence?.attendanceGeofenceEnabled}/></label><div className="settings-fields"><label>Reference latitude<input name="attendanceReferenceLatitude" type="number" step="any" defaultValue={geofence?.attendanceReferenceLatitude??""}/></label><label>Reference longitude<input name="attendanceReferenceLongitude" type="number" step="any" defaultValue={geofence?.attendanceReferenceLongitude??""}/></label><label>Radius meters<input name="attendanceGeofenceRadiusMeters" type="number" min="10" max="100000" defaultValue={geofence?.attendanceGeofenceRadiusMeters??""}/></label></div><label><div><strong>Customer check-in geofence</strong><span>Centers come from each Customer’s protected reference coordinates.</span></div><input type="checkbox" name="customerCheckInGeofenceEnabled" defaultChecked={geofence?.customerCheckInGeofenceEnabled}/></label><div className="settings-fields"><label>Customer radius meters<input name="customerCheckInGeofenceRadiusMeters" type="number" min="10" max="100000" defaultValue={geofence?.customerCheckInGeofenceRadiusMeters??""}/></label></div><button className="primary-button">Save geofence settings</button></form><p className="privacy-note">Visit check-in and checkout always require current GPS, independently of continuous GPS Tracking.</p></section></main>;
}
