import {Prisma} from "@prisma/client";import {db} from "@/lib/db";import {AuthorizationError,requireRole} from "@/lib/auth/authorization";import {indiaDateBoundary} from "@/lib/reports/validation";import {visibleUserWhere} from "@/lib/reports/policy";import type {ReportActor} from "@/lib/reports/scope";import {canonicalPeriod,createTargetSchema,editTargetSchema} from "./validation";import {targetProgress} from "./metrics";import {assertOperationalWrite} from "@/lib/billing/entitlement";
async function actor(provided?:ReportActor):Promise<ReportActor>{if(provided)return provided;const u=await requireRole("COMPANY_ADMIN","MANAGER","SALES");if(!u.companyId)throw new AuthorizationError();return {...u,companyId:u.companyId}}
async function assertAssignee(a:ReportActor,id:string){if(a.role==="SALES")throw new AuthorizationError();const u=await db.user.findFirst({where:{id,isActive:true,...visibleUserWhere(a),NOT:{role:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true}});if(!u)throw new AuthorizationError();return u}
export async function targetOptions(provided?:ReportActor){const a=await actor(provided);return db.user.findMany({where:{...visibleUserWhere(a),isActive:true,NOT:{role:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true,name:true,role:true},orderBy:{name:"asc"}})}
export async function createTarget(raw:unknown,provided?:ReportActor){const a=await actor(provided);await assertOperationalWrite(a.companyId);const d=createTargetSchema.parse(raw);await assertAssignee(a,d.assignedUserId);const dates=canonicalPeriod(d.periodType,d.startDate,d.endDate);return db.salesTarget.create({data:{companyId:a.companyId,createdByUserId:a.id,assignedUserId:d.assignedUserId,metric:d.metric,periodType:d.periodType,...dates,targetValue:new Prisma.Decimal(d.targetValue),currencyCode:d.currencyCode}})}
export async function editTarget(raw:unknown,provided?:ReportActor){const a=await actor(provided);await assertOperationalWrite(a.companyId);const d=editTargetSchema.parse(raw);await assertAssignee(a,d.assignedUserId);const current=await db.salesTarget.findFirst({where:{id:d.targetId,companyId:a.companyId,assignedUser:visibleUserWhere(a)},select:{id:true,version:true}});if(!current)throw new AuthorizationError();if(current.version!==d.version)throw new Error("STALE");const dates=canonicalPeriod(d.periodType,d.startDate,d.endDate);const changed=await db.salesTarget.updateMany({where:{id:d.targetId,companyId:a.companyId,version:d.version},data:{assignedUserId:d.assignedUserId,metric:d.metric,periodType:d.periodType,...dates,targetValue:new Prisma.Decimal(d.targetValue),currencyCode:d.currencyCode,version:{increment:1}}});if(changed.count!==1)throw new Error("STALE")}
export async function listTargets(raw:Record<string,string|undefined>={},provided?:ReportActor,exportMode=false){
 const a=await actor(provided),metric=raw.metric==="LEADS_CREATED_COUNT"||raw.metric==="WON_LEADS_COUNT"||raw.metric==="WON_LEADS_VALUE"?raw.metric:undefined;
 const where:Prisma.SalesTargetWhereInput={companyId:a.companyId,assignedUser:visibleUserWhere(a),metric,assignedUserId:raw.employeeId,...(raw.start&&raw.end?{startDate:{lte:new Date(`${raw.end}T00:00:00Z`)},endDate:{gte:new Date(`${raw.start}T00:00:00Z`)}}:{})};
 if(exportMode&&await db.salesTarget.count({where})>10000)throw new Error("ROW_LIMIT");
 const targets=await db.salesTarget.findMany({where,include:{assignedUser:{select:{name:true,role:true,isActive:true}}},orderBy:[{startDate:"desc"},{id:"desc"}],take:exportMode?10000:100});
 const enriched=await Promise.all(targets.map(async t=>{const startText=t.startDate.toISOString().slice(0,10),endText=t.endDate.toISOString().slice(0,10),start=indiaDateBoundary(startText),endExclusive=indiaDateBoundary(endText,true);const wonWhere={companyId:a.companyId,assignedUserId:t.assignedUserId,stage:"WON" as const,wonAt:{gte:start,lt:endExclusive}},createdWhere={companyId:a.companyId,assignedUserId:t.assignedUserId,createdAt:{gte:start,lt:endExclusive}};const useCreated=t.metric==="LEADS_CREATED_COUNT";const [leads,count,sum]=await Promise.all([db.lead.findMany({where:useCreated?createdWhere:wonWhere,select:{id:true,title:true,wonAt:true,estimatedValue:true},orderBy:[{createdAt:"desc"},{id:"desc"}],take:100}),db.lead.count({where:useCreated?createdWhere:wonWhere}),db.lead.aggregate({where:wonWhere,_sum:{estimatedValue:true}})]);const actual=t.metric==="WON_LEADS_VALUE"?(sum._sum.estimatedValue||new Prisma.Decimal(0)):new Prisma.Decimal(count);return {...t,...targetProgress(t.targetValue,actual,start,endExclusive),leads}}));
 return {actor:a,targets:raw.status?enriched.filter(t=>t.status===raw.status):enriched,options:await targetOptions(a)};
}

function indiaMonth(now=new Date()){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit"}).formatToParts(now),y=Number(parts.find(p=>p.type==="year")?.value),m=Number(parts.find(p=>p.type==="month")?.value);const startText=`${y}-${String(m).padStart(2,"0")}-01`,last=new Date(Date.UTC(y,m,0)).getUTCDate(),endText=`${y}-${String(m).padStart(2,"0")}-${String(last).padStart(2,"0")}`;return{startText,endText,start:indiaDateBoundary(startText),endExclusive:indiaDateBoundary(endText,true),startDate:new Date(`${startText}T00:00:00Z`),endDate:new Date(`${endText}T00:00:00Z`)}};

export async function monthlyTargetRows(provided?:ReportActor){
 const a=await actor(provided),month=indiaMonth(),users=await db.user.findMany({where:{...visibleUserWhere(a),isActive:true,NOT:{role:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true,name:true,role:true,managerType:true},orderBy:[{name:"asc"},{id:"asc"}]});
 users.sort((x,y)=>x.id===a.id?-1:y.id===a.id?1:x.name.localeCompare(y.name));
 const rows=await Promise.all(users.map(async u=>{
  const [leadTarget,wonTarget,created,won]=await Promise.all([
   db.salesTarget.findFirst({where:{companyId:a.companyId,assignedUserId:u.id,metric:"LEADS_CREATED_COUNT",periodType:"MONTHLY",startDate:{lte:month.startDate}},orderBy:{startDate:"desc"}}),
   db.salesTarget.findFirst({where:{companyId:a.companyId,assignedUserId:u.id,metric:"WON_LEADS_COUNT",periodType:"MONTHLY",startDate:{lte:month.startDate}},orderBy:{startDate:"desc"}}),
   db.lead.count({where:{companyId:a.companyId,assignedUserId:u.id,createdAt:{gte:month.start,lt:month.endExclusive}}}),
   db.lead.count({where:{companyId:a.companyId,assignedUserId:u.id,stage:"WON",wonAt:{gte:month.start,lt:month.endExclusive}}})
  ]);
  return{...u,leadTarget:Number(leadTarget?.targetValue??0),wonTarget:Number(wonTarget?.targetValue??0),created,won,hasTarget:Boolean(leadTarget||wonTarget)};
 }));
 return{actor:a,month,rows};
}
export async function saveMonthlyTargets(raw:{assignedUserId:string;leadTarget:number;wonTarget:number},provided?:ReportActor){
 const a=await actor(provided);if(a.role==="SALES")throw new AuthorizationError();await assertOperationalWrite(a.companyId);await assertAssignee(a,raw.assignedUserId);
 const leadTarget=Math.max(0,Math.trunc(Number(raw.leadTarget))),wonTarget=Math.max(0,Math.trunc(Number(raw.wonTarget)));if(!Number.isFinite(leadTarget)||!Number.isFinite(wonTarget))throw new Error("INVALID_TARGET");
 const month=indiaMonth(),key=(metric:"LEADS_CREATED_COUNT"|"WON_LEADS_COUNT")=>({companyId_assignedUserId_metric_startDate_endDate:{companyId:a.companyId,assignedUserId:raw.assignedUserId,metric,startDate:month.startDate,endDate:month.endDate}});
 await db.$transaction([
  db.salesTarget.upsert({where:key("LEADS_CREATED_COUNT"),update:{targetValue:new Prisma.Decimal(leadTarget),createdByUserId:a.id,version:{increment:1}},create:{companyId:a.companyId,createdByUserId:a.id,assignedUserId:raw.assignedUserId,metric:"LEADS_CREATED_COUNT",periodType:"MONTHLY",startDate:month.startDate,endDate:month.endDate,targetValue:new Prisma.Decimal(leadTarget),currencyCode:"INR"}}),
  db.salesTarget.upsert({where:key("WON_LEADS_COUNT"),update:{targetValue:new Prisma.Decimal(wonTarget),createdByUserId:a.id,version:{increment:1}},create:{companyId:a.companyId,createdByUserId:a.id,assignedUserId:raw.assignedUserId,metric:"WON_LEADS_COUNT",periodType:"MONTHLY",startDate:month.startDate,endDate:month.endDate,targetValue:new Prisma.Decimal(wonTarget),currencyCode:"INR"}})
 ]);
}
