import { operationalBranchContext, resolveOperationalWriteBranch } from "@/lib/branches/operational-scope";
import {Prisma} from "@prisma/client";import {db} from "@/lib/db";import {AuthorizationError,requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";import {indiaDateBoundary} from "@/lib/reports/validation";import {visibleUserWhere} from "@/lib/reports/policy";import type {ReportActor} from "@/lib/reports/scope";import {canonicalPeriod,createTargetSchema,editTargetSchema,targetListFilterSchema} from "./validation";import {targetProgress} from "./metrics";import {assertOperationalWrite} from "@/lib/billing/entitlement";
async function actor(mutation=false):Promise<ReportActor>{const u=await (mutation?requirePermissionForMutation("SALES_TARGETS"):requirePermission("SALES_TARGETS"));if(!u.companyId||!u.salesRole)throw new AuthorizationError();return{id:u.id,name:u.name,salesRole:u.salesRole,managerType:u.managerType,companyId:u.companyId,branchAccessScope:u.branchAccessScope,branchIds:u.branchIds}}
async function assertAssignee(a:ReportActor,id:string){if(a.salesRole==="SALES")throw new AuthorizationError();const u=await db.user.findFirst({where:{id,isActive:true,salesAccessActive:true,...visibleUserWhere(a),NOT:{salesRole:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true}});if(!u)throw new AuthorizationError();return u}
async function targetOptionsForActor(a:ReportActor){return db.user.findMany({where:{...visibleUserWhere(a),isActive:true,salesAccessActive:true,NOT:{salesRole:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true,name:true,salesRole:true},orderBy:{name:"asc"}})}
export async function createTarget(raw:unknown){return createTargetForActor(await actor(true),raw)}
export async function createTargetForActor(a:ReportActor,raw:unknown){await assertOperationalWrite(a.companyId);const d=createTargetSchema.parse(raw);await assertAssignee(a,d.assignedUserId);const branchId=await resolveOperationalWriteBranch(a,d.branchId);await resolveOperationalWriteBranch({id:d.assignedUserId,companyId:a.companyId},branchId);const dates=canonicalPeriod(d.periodType,d.startDate,d.endDate);return db.salesTarget.create({data:{companyId:a.companyId,branchId,createdByUserId:a.id,assignedUserId:d.assignedUserId,metric:d.metric,periodType:d.periodType,...dates,targetValue:new Prisma.Decimal(d.targetValue),currencyCode:d.currencyCode}})}
export async function editTarget(raw:unknown){return editTargetForActor(await actor(true),raw)}
export async function editTargetForActor(a:ReportActor,raw:unknown){await assertOperationalWrite(a.companyId);const d=editTargetSchema.parse(raw);await assertAssignee(a,d.assignedUserId);const branches=await operationalBranchContext(a,d.branchId);const current=await db.salesTarget.findFirst({where:{id:d.targetId,companyId:a.companyId,branchId:branches.branchId,assignedUser:visibleUserWhere(a)},select:{id:true,version:true}});if(!current)throw new AuthorizationError();if(current.version!==d.version)throw new Error("STALE");const dates=canonicalPeriod(d.periodType,d.startDate,d.endDate);const changed=await db.salesTarget.updateMany({where:{id:d.targetId,companyId:a.companyId,version:d.version},data:{assignedUserId:d.assignedUserId,metric:d.metric,periodType:d.periodType,...dates,targetValue:new Prisma.Decimal(d.targetValue),currencyCode:d.currencyCode,version:{increment:1}}});if(changed.count!==1)throw new Error("STALE")}
export async function listTargets(raw:Record<string,string|undefined>={},exportMode=false){return listTargetsForActor(await actor(),raw,exportMode)}
export async function listTargetsForActor(a:ReportActor,raw:Record<string,string|undefined>={},exportMode=false){
 const input=targetListFilterSchema.parse(raw),branches=await operationalBranchContext(a,input.branchId),metric=input.metric==="LEADS_CREATED_COUNT"||input.metric==="WON_LEADS_COUNT"||input.metric==="WON_LEADS_VALUE"?input.metric:undefined;
 const where:Prisma.SalesTargetWhereInput={companyId:a.companyId,branchId:branches.branchId,assignedUser:visibleUserWhere(a),metric,assignedUserId:input.employeeId,...(input.start&&input.end?{startDate:{lte:new Date(`${input.end}T00:00:00Z`)},endDate:{gte:new Date(`${input.start}T00:00:00Z`)}}:{})};
 if(exportMode&&await db.salesTarget.count({where})>10000)throw new Error("ROW_LIMIT");
 const targets=await db.salesTarget.findMany({where,include:{assignedUser:{select:{name:true,salesRole:true,isActive:true}}},orderBy:[{startDate:"desc"},{id:"desc"}],take:exportMode?10000:100});
 if(!targets.length)return{actor:a,targets:[],options:await targetOptionsForActor(a)};
 const periods=targets.map(t=>({target:t,start:indiaDateBoundary(t.startDate.toISOString().slice(0,10)),endExclusive:indiaDateBoundary(t.endDate.toISOString().slice(0,10),true)})),values=Prisma.join(periods.map(({target,start,endExclusive})=>Prisma.sql`(${target.id}::uuid,${target.branchId}::uuid,${target.assignedUserId}::uuid,${target.metric}::text,${start},${endExclusive})`));
 const actualRows=await db.$queryRaw<{id:string;count:bigint;value:Prisma.Decimal}[]>(Prisma.sql`WITH target_scope(id,"branchId","assignedUserId",metric,"startAt","endAt") AS (VALUES ${values}) SELECT t.id,COUNT(l.id)::bigint AS count,COALESCE(SUM(l."estimatedValue") FILTER (WHERE t.metric='WON_LEADS_VALUE'),0) AS value FROM target_scope t LEFT JOIN leads l ON l."companyId"=${a.companyId}::uuid AND l."branchId"=t."branchId" AND l."assignedUserId"=t."assignedUserId" AND ((t.metric='LEADS_CREATED_COUNT' AND l."createdAt">=t."startAt" AND l."createdAt"<t."endAt") OR (t.metric<>'LEADS_CREATED_COUNT' AND l.stage='WON' AND l."wonAt">=t."startAt" AND l."wonAt"<t."endAt")) GROUP BY t.id`),actuals=new Map(actualRows.map(row=>[row.id,{count:Number(row.count),value:new Prisma.Decimal(row.value)}]));
 const enriched=periods.map(({target,start,endExclusive})=>{const aggregate=actuals.get(target.id)??{count:0,value:new Prisma.Decimal(0)},actual=target.metric==="WON_LEADS_VALUE"?aggregate.value:new Prisma.Decimal(aggregate.count);return{...target,...targetProgress(target.targetValue,actual,start,endExclusive),leads:[]}});
 return {actor:a,targets:input.status?enriched.filter(t=>t.status===input.status):enriched,options:await targetOptionsForActor(a)};
}

function indiaMonth(now=new Date()){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit"}).formatToParts(now),y=Number(parts.find(p=>p.type==="year")?.value),m=Number(parts.find(p=>p.type==="month")?.value);const startText=`${y}-${String(m).padStart(2,"0")}-01`,last=new Date(Date.UTC(y,m,0)).getUTCDate(),endText=`${y}-${String(m).padStart(2,"0")}-${String(last).padStart(2,"0")}`;return{startText,endText,start:indiaDateBoundary(startText),endExclusive:indiaDateBoundary(endText,true),startDate:new Date(`${startText}T00:00:00Z`),endDate:new Date(`${endText}T00:00:00Z`)}};

export async function monthlyTargetRows(){return monthlyTargetRowsForActor(await actor())}
export async function monthlyTargetRowsForActor(a:ReportActor){
 const branches=await operationalBranchContext(a),month=indiaMonth(),users=await db.user.findMany({where:{...visibleUserWhere(a),isActive:true,salesAccessActive:true,NOT:{salesRole:"MANAGER",managerType:"MANAGER_ONLY"}},select:{id:true,name:true,salesRole:true,managerType:true},orderBy:[{name:"asc"},{id:"asc"}]});
 users.sort((x,y)=>x.id===a.id?-1:y.id===a.id?1:x.name.localeCompare(y.name));
 const userIds=users.map(user=>user.id),[targets,checkInGroups,wonGroups]=userIds.length?await Promise.all([db.salesTarget.findMany({where:{companyId:a.companyId,branchId:branches.branchId,assignedUserId:{in:userIds},metric:{in:["LEADS_CREATED_COUNT","WON_LEADS_COUNT"]},periodType:"MONTHLY",startDate:{lte:month.startDate}},orderBy:[{startDate:"desc"},{id:"desc"}]}),db.customerVisit.groupBy({by:["userId"],where:{companyId:a.companyId,branchId:branches.branchId,userId:{in:userIds},checkedInAt:{gte:month.start,lt:month.endExclusive}},_count:{_all:true}}),db.lead.groupBy({by:["assignedUserId"],where:{companyId:a.companyId,branchId:branches.branchId,assignedUserId:{in:userIds},stage:"WON",wonAt:{gte:month.start,lt:month.endExclusive}},_count:{_all:true}})]):[[],[],[]],targetMap=new Map<string,typeof targets[number]>();for(const target of targets){const key=`${target.assignedUserId}:${target.metric}`;if(!targetMap.has(key))targetMap.set(key,target)}const createdMap=new Map(checkInGroups.map(group=>[group.userId,group._count._all])),wonMap=new Map(wonGroups.map(group=>[group.assignedUserId,group._count._all]));
 const rows=users.map(u=>{const leadTarget=targetMap.get(`${u.id}:LEADS_CREATED_COUNT`),wonTarget=targetMap.get(`${u.id}:WON_LEADS_COUNT`);return{...u,leadTarget:Number(leadTarget?.targetValue??0),wonTarget:Number(wonTarget?.targetValue??0),created:createdMap.get(u.id)??0,won:wonMap.get(u.id)??0,hasTarget:Boolean(leadTarget||wonTarget)}});
 return{actor:a,month,rows};
}
export async function saveMonthlyTargets(raw:{assignedUserId:string;leadTarget:number;wonTarget:number;branchId?:string}){return saveMonthlyTargetsForActor(await actor(true),raw)}
export async function saveMonthlyTargetsForActor(a:ReportActor,raw:{assignedUserId:string;leadTarget:number;wonTarget:number;branchId?:string}){
 if(a.salesRole==="SALES")throw new AuthorizationError();await assertOperationalWrite(a.companyId);await assertAssignee(a,raw.assignedUserId);const branchId=await resolveOperationalWriteBranch(a,raw.branchId);await resolveOperationalWriteBranch({id:raw.assignedUserId,companyId:a.companyId},branchId);
 const leadTarget=Math.max(0,Math.trunc(Number(raw.leadTarget))),wonTarget=Math.max(0,Math.trunc(Number(raw.wonTarget)));if(!Number.isFinite(leadTarget)||!Number.isFinite(wonTarget))throw new Error("INVALID_TARGET");
 const month=indiaMonth(),key=(metric:"LEADS_CREATED_COUNT"|"WON_LEADS_COUNT")=>({companyId_assignedUserId_metric_startDate_endDate:{companyId:a.companyId,assignedUserId:raw.assignedUserId,metric,startDate:month.startDate,endDate:month.endDate}});
 await db.$transaction([
  db.salesTarget.upsert({where:key("LEADS_CREATED_COUNT"),update:{targetValue:new Prisma.Decimal(leadTarget),createdByUserId:a.id,version:{increment:1}},create:{companyId:a.companyId,branchId,createdByUserId:a.id,assignedUserId:raw.assignedUserId,metric:"LEADS_CREATED_COUNT",periodType:"MONTHLY",startDate:month.startDate,endDate:month.endDate,targetValue:new Prisma.Decimal(leadTarget),currencyCode:"INR"}}),
  db.salesTarget.upsert({where:key("WON_LEADS_COUNT"),update:{targetValue:new Prisma.Decimal(wonTarget),createdByUserId:a.id,version:{increment:1}},create:{companyId:a.companyId,branchId,createdByUserId:a.id,assignedUserId:raw.assignedUserId,metric:"WON_LEADS_COUNT",periodType:"MONTHLY",startDate:month.startDate,endDate:month.endDate,targetValue:new Prisma.Decimal(wonTarget),currencyCode:"INR"}})
 ]);
}
