import Link from "next/link";
import { WorkspacePageHeader } from "@/components/workspace/workspace-page-header";
import { getEmployeeManagementContext } from "@/lib/employees/service";
import { getProductUserManagementContext } from "@/lib/users/product-user-management";
import { listAdditionalAdmins } from "@/lib/users/additional-admin";
import { effectiveEntitlement } from "@/lib/billing/entitlement";
import { getTelecallerBillingOverviewForCompany } from "@/lib/billing/telecaller";
import { webWorkspaceContext } from "@/lib/auth/web-workspace";
import { isTelecallerDesignation } from "@/lib/telecalling/policy";
import { setTelecallerActiveAction } from "@/app/actions/telecaller-team";
import { accountGroups, accountRoleLabel, salesGroups, salesRoleLabel, type DirectoryUser } from "./directory-policy";

const accountRoles = ["ACCOUNT_ADMIN", "ACCOUNTANT", "PROJECT_MANAGER", "DATA_ENTRY"] as const;
type GroupProps={title:string;users:DirectoryUser[];empty:string;addHref?:string;addLabel?:string;canManage:boolean;canAdd:boolean;domain:"sales"|"account";hideTitle?:boolean};
const tabStyle=(active:boolean)=>({color:active?"var(--blue)":"var(--muted)",borderBottom:active?"3px solid var(--blue)":"3px solid transparent",fontWeight:active?800:600,padding:"10px 8px",textDecoration:"none"} as const);
export function EmployeeCard({user,domain,canManage}:{user:DirectoryUser;domain:"sales"|"account";canManage:boolean}){const telecaller=domain==="sales"&&isTelecallerDesignation(user.designation),active=user.isActive&&(domain==="sales"?(user.salesAccessActive||telecaller):user.accountAccessActive),label=domain==="sales"?salesRoleLabel(user):accountRoleLabel(user.accountRole!);return <article className={`employee-card ${active?"":"inactive"}`}><div className="employee-summary"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div className="employee-identity"><h3>{user.name}</h3><p>{user.email}</p><p>{label} · {active?"Active":"Inactive"}</p></div></div>{canManage&&!telecaller&&<Link href={`/workspace/employees/${domain}/edit/${user.id}`}>Edit User</Link>}</article>}
export function EmployeeGroup({title,users,empty,addHref,addLabel,canManage,canAdd,domain,hideTitle=false}:GroupProps){return <section className="billing-card">{!hideTitle&&<h2>{title}</h2>}<div className="employee-list">{users.map(user=><EmployeeCard key={user.id} user={user} domain={domain} canManage={canManage}/>)}{!users.length&&<p className="muted">{empty}</p>}</div>{canAdd&&addHref?<p><Link className="primary-button" href={addHref}>+ {addLabel}</Link></p>:addHref&&<p className="muted">No seat available. <Link href={domain==="sales"&&addLabel?.includes("Telecaller")?"/workspace/billing/telecaller":"/workspace/billing"}>Manage Subscription</Link></p>}</section>}
function TelecallerGroup({users,canManage,canAdd,hideTitle=false}:{users:DirectoryUser[];canManage:boolean;canAdd:boolean;hideTitle?:boolean}){return <section className="billing-card">{!hideTitle&&<h2>Telecallers</h2>}<div className="employee-list">{users.map(user=><article className={`employee-card ${user.isActive?"":"inactive"}`} key={user.id}><div className="employee-summary"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div className="employee-identity"><h3>{user.name}</h3><p>{user.email}</p><p>Telecaller · {user.isActive?"Active":"Inactive"}</p></div></div>{canManage?<form action={setTelecallerActiveAction}><input type="hidden" name="userId" value={user.id}/><input type="hidden" name="active" value={user.isActive?"false":"true"}/><button className="secondary-button">{user.isActive?"Deactivate":"Reactivate"}</button></form>:null}</article>)}{!users.length&&<p className="muted">No Telecallers added.</p>}</div>{canManage&&canAdd?<p><Link className="primary-button" href="/workspace/employees/sales/new/telecaller">+ Add Telecaller</Link></p>:canManage?<p className="muted">No Telecaller seat available. <Link href="/workspace/billing/telecaller">Manage Telecaller Subscription</Link></p>:null}</section>}
export default async function EmployeesPage({searchParams}:{searchParams:Promise<{domain?:string;filter?:string}>}){const context=await getProductUserManagementContext(),params=await searchParams,workspace=await webWorkspaceContext(context.actor),domain=workspace?.effectiveWorkspace==="ACCOUNT"?"account":"sales";
if(domain==="account"){if(!context.canManageAccountUsers)return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title="Account Employees" backHref="/workspace/account"/><p className="muted">You do not have permission to manage Account employees.</p></section></main>;const groups=accountGroups(context.users as DirectoryUser[]),filter=(params.filter??"all").toUpperCase(),valid=filter==="ALL"||filter==="INACTIVE"||accountRoles.includes(filter as typeof accountRoles[number])?filter:"ALL";return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title="Account Employees" backHref="/workspace/account"/><nav className="employee-filters" style={{display:"flex",gap:8,overflowX:"auto"}}><Link style={tabStyle(valid==="ALL")} href="/workspace/employees">All</Link>{accountRoles.map(role=><Link key={role} style={tabStyle(valid===role)} href={`/workspace/employees?filter=${role.toLowerCase()}`}>{accountRoleLabel(role)}</Link>)}<Link style={tabStyle(valid==="INACTIVE")} href="/workspace/employees?filter=inactive">Inactive</Link></nav><div className="account-role-stats">{accountRoles.map(role=><div key={role}><strong>{context.accountUsage[role]} / {context.accountLimits[role]}</strong><span>{accountRoleLabel(role)} · {Math.max(0,context.accountLimits[role]-context.accountUsage[role])} available</span></div>)}</div>{valid==="INACTIVE"?<EmployeeGroup title="Inactive Account Employees" hideTitle users={groups.inactive} empty="No inactive users." canManage={context.canManageAccountUsers} canAdd={false} domain="account"/>:valid!=="ALL"?(()=>{const role=valid as typeof accountRoles[number];return <EmployeeGroup title={`${accountRoleLabel(role)}s`} hideTitle users={groups[role]} empty={`No ${accountRoleLabel(role)}s added.`} canManage={context.canManageAccountUsers} canAdd={context.accountUsage[role]<context.accountLimits[role]} addHref={`/workspace/employees/account/new/${role.toLowerCase().replaceAll("_","-")}`} addLabel={`Add ${accountRoleLabel(role)}`} domain="account"/>})():accountRoles.map(role=><EmployeeGroup key={role} title={`${accountRoleLabel(role)}s`} users={groups[role]} empty={`No ${accountRoleLabel(role)}s added.`} canManage={context.canManageAccountUsers} canAdd={context.accountUsage[role]<context.accountLimits[role]} addHref={`/workspace/employees/account/new/${role.toLowerCase().replaceAll("_","-")}`} addLabel={`Add ${accountRoleLabel(role)}`} domain="account"/>)}</section></main>}
if(!context.canManageSalesUsers)return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title="Sales Employees" backHref="/workspace"/><p className="muted">You do not have permission to manage Sales employees.</p></section></main>;
const[employeeContext,admins,seats,telecallerSeats]=await Promise.all([getEmployeeManagementContext(),listAdditionalAdmins(),effectiveEntitlement(context.actor.companyId!),getTelecallerBillingOverviewForCompany(context.actor.companyId!)]),all=[...admins.map(user=>({...user,salesRole:"ADMIN" as const,managerType:null,designation:null})),...employeeContext.employees] as DirectoryUser[],groups=salesGroups(all),filter=(params.filter??"all").toLowerCase(),canManage=context.actor.salesRole==="PRIMARY_ADMIN",usage={ADMIN:seats.adminUsage,MANAGER:seats.managerUsage,SALES:seats.salesUsage},limits={ADMIN:seats.adminLimit,MANAGER:seats.managerLimit,SALES:seats.salesLimit},group=(title:string,users:DirectoryUser[],role:"ADMIN"|"MANAGER"|"SALES",href:string,label:string,hideTitle=false)=><EmployeeGroup title={title} hideTitle={hideTitle} users={users} empty={`No ${title} added.`} canManage={canManage} canAdd={canManage&&usage[role]<limits[role]} addHref={href} addLabel={label} domain="sales"/>,managers=[...groups.salesManagers,...groups.officeManagers],activeTelecallers=groups.telecallers.filter(x=>x.isActive).length;
const tabs=[["all","All"],["administrators","Administrators"],["managers","Managers"],["sales","Sales"],["telecallers","Telecallers"],["inactive","Inactive"]] as const;
return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title="Sales Employees" backHref="/workspace"/><div className="employee-stats employee-stats-four"><div><strong>{seats.adminUsage} / {seats.adminLimit}</strong><span>Active Admins</span></div><div><strong>{seats.managerUsage} / {seats.managerLimit}</strong><span>Active Managers</span></div><div><strong>{seats.salesUsage} / {seats.salesLimit}</strong><span>Active Sales</span></div><div><strong>{activeTelecallers} / {telecallerSeats.limit}</strong><span>Active Telecallers</span></div><div><strong>{groups.inactive.length}</strong><span>Inactive</span></div></div><nav className="employee-filters" style={{display:"flex",gap:8,overflowX:"auto"}}>{tabs.map(([key,label])=><Link key={key} style={tabStyle(filter===key)} href={key==="all"?"/workspace/employees":`/workspace/employees?filter=${key}`}>{label}</Link>)}</nav>{filter==="administrators"?group("Additional Admins",groups.admins,"ADMIN","/workspace/employees/sales/new/additional-admin","Add Additional Admin",true):filter==="managers"?group("Manager",managers,"MANAGER","/workspace/employees/sales/new/manager","Add Manager",true):filter==="sales"?group("Sales Employees",groups.sales,"SALES","/workspace/employees/sales/new/sales","Add Sales Employee",true):filter==="telecallers"?<TelecallerGroup users={groups.telecallers} canManage={canManage} canAdd={telecallerSeats.available>0} hideTitle/>:filter==="inactive"?<EmployeeGroup title="Inactive Employees" hideTitle users={groups.inactive} empty="No inactive users." canManage={canManage} canAdd={false} domain="sales"/>:<>{group("Additional Admins",groups.admins,"ADMIN","/workspace/employees/sales/new/additional-admin","Add Additional Admin")}{group("Manager",managers,"MANAGER","/workspace/employees/sales/new/manager","Add Manager")}{group("Sales Employees",groups.sales,"SALES","/workspace/employees/sales/new/sales","Add Sales Employee")}<TelecallerGroup users={groups.telecallers} canManage={canManage} canAdd={telecallerSeats.available>0}/></>}</section></main>}