"use client";
import { useActionState, useState } from "react";
import type { AccountRole, ManagerType, SalesRole } from "@prisma/client";
import { manageAccountUser, type ProductUserState } from "@/app/actions/product-users";
type User={id:string;name:string;email:string;isActive:boolean;salesRole:SalesRole|null;accountRole:AccountRole|null;managerType:ManagerType|null;managerId:string|null;salesAccessActive:boolean;accountAccessActive:boolean;branchAccessScope:"ALL_BRANCHES"|"SELECTED_BRANCHES";branchAccesses:{branchId:string}[]};
type Branch={id:string;name:string;code:string;isPrimary:boolean};
const roles=[["ACCOUNT_ADMIN","Account Admin"],["ACCOUNTANT","Accountant"],["PROJECT_MANAGER","Project Manager"],["DATA_ENTRY","Data Entry"]] as const;
export function ProductUserManager({users,branches,limits,usage}:{users:User[];branches:Branch[];limits:Record<AccountRole,number>;usage:Record<AccountRole,number>}){
 const[state,action,pending]=useActionState<ProductUserState,FormData>(manageAccountUser,{}),[creating,setCreating]=useState<AccountRole|null>(null);
 const label=(role:AccountRole)=>roles.find(([value])=>value===role)?.[1]??role;
 return <section className="employee-domain-section"><h2>Account Employees</h2><div className="account-role-stats">{roles.map(([role,name])=><div key={role}><strong>{usage[role]} / {limits[role]}</strong><span>{name}</span></div>)}</div><div className="account-role-actions">{roles.map(([role,name])=><button key={role} type="button" disabled={usage[role]>=limits[role]} onClick={()=>setCreating(current=>current===role?null:role)}>Add {name}</button>)}</div>
 {state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.success&&<p className="form-success" role="status">{state.success}</p>}
 {creating&&<form action={action} className="employee-form create-form"><input type="hidden" name="operation" value="create-account"/><input type="hidden" name="accountRole" value={creating}/><div className="form-title"><h3>Add {label(creating)}</h3><button type="button" className="close-button" onClick={()=>setCreating(null)}>Close</button></div><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Branch scope<select name="branchAccessScope" defaultValue="ALL_BRANCHES"><option value="ALL_BRANCHES">All Branches</option><option value="SELECTED_BRANCHES">Selected Branches</option></select></label>{branches.map(b=><label key={b.id}><input type="checkbox" name="branchIds" value={b.id}/>{b.name} ({b.code})</label>)}<label>Password<input name="password" type="password" minLength={12} required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} required/></label><button className="primary-button" disabled={pending}>{pending?"Creating…":`Add ${label(creating)}`}</button></form>}
 <div className="employee-list">{users.filter(user=>user.accountRole).map(user=><article className="employee-card" key={user.id}><div className="employee-summary"><div className="employee-identity"><h2>{user.name}</h2><p>{user.email}</p><p>{label(user.accountRole!)} · {!user.isActive?"Inactive identity":user.accountAccessActive?"Active":"Account access suspended"}</p></div></div><details><summary>Manage Account access</summary><form action={action} className="employee-form"><input type="hidden" name="operation" value="edit-account"/><input type="hidden" name="userId" value={user.id}/><label>Account role<select name="accountRole" defaultValue={user.accountRole??""}><option value="">No Account role</option>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><input type="checkbox" name="accountAccessActive" defaultChecked={user.accountAccessActive}/>Account workspace active</label><label>Branch scope<select name="branchAccessScope" defaultValue={user.branchAccessScope}><option value="ALL_BRANCHES">All Branches</option><option value="SELECTED_BRANCHES">Selected Branches</option></select></label>{branches.map(b=><label key={b.id}><input type="checkbox" name="branchIds" value={b.id} defaultChecked={user.branchAccesses.some(a=>a.branchId===b.id)}/>{b.name} ({b.code})</label>)}<button disabled={pending}>{pending?"Saving…":"Save Account access"}</button></form></details></article>)}</div></section>;
}
