"use client";
import { useActionState, useState } from "react";
import type { AccountRole, ManagerType, ProductEdition, SalesRole } from "@prisma/client";
import { manageAccountUser, type ProductUserState } from "@/app/actions/product-users";
type User={id:string;name:string;email:string;isActive:boolean;salesRole:SalesRole|null;accountRole:AccountRole|null;managerType:ManagerType|null;managerId:string|null;salesAccessActive:boolean;accountAccessActive:boolean;branchAccessScope:"ALL_BRANCHES"|"SELECTED_BRANCHES";branchAccesses:{branchId:string}[]};
type Branch={id:string;name:string;code:string;isPrimary:boolean};
const roles=[["ACCOUNT_ADMIN","Account Admin"],["ACCOUNTANT","Accountant"],["PROJECT_MANAGER","Project Manager"],["DATA_ENTRY","Data Entry"]] as const;
export function ProductUserManager({edition,users}: {edition:ProductEdition;users:User[];branches:Branch[]}) {
 const [state,action,pending]=useActionState<ProductUserState,FormData>(manageAccountUser,{}),[creating,setCreating]=useState(false);
 return <section className="employee-list"><header className="employee-actions"><div><h2>Account users</h2><p className="muted">Account roles are managed independently; Sales roles and Branch access are preserved.</p></div><button onClick={()=>setCreating(v=>!v)}>Add Account user</button></header>
 {state.error&&<p className="form-error">{state.error}</p>}{state.success&&<p className="form-success">{state.success}</p>}
 {creating&&<form action={action} className="employee-form create-form"><input type="hidden" name="operation" value="create-account"/><h3>Create Account user</h3><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Account role<select name="accountRole">{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Password<input name="password" type="password" minLength={12} required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} required/></label><button disabled={pending}>Create user</button></form>}
 {users.map(user=><article className="employee-card" key={user.id}><div className="employee-summary"><div className="employee-identity"><h2>{user.name}</h2><p>{user.email}</p><p>{user.salesRole&&`Sales: ${user.salesRole}${user.managerType?` (${user.managerType})`:""} · `}Account: {user.accountRole??"None"}</p></div></div><details><summary>Manage Account access</summary><form action={action} className="employee-form"><input type="hidden" name="operation" value="edit-account"/><input type="hidden" name="userId" value={user.id}/><label>Account role<select name="accountRole" defaultValue={user.accountRole??""}><option value="">No Account role</option>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><input type="checkbox" name="accountAccessActive" defaultChecked={user.accountAccessActive}/>Account workspace active</label><button disabled={pending}>Save Account access</button></form></details></article>)}
 <p className="muted">Roles shown are limited by {edition}.</p></section>;
}
