import { AssetStatus, AssetType, DepreciationMethod, Prisma } from "@prisma/client";
import { z } from "zod";
import { db } from "@/lib/db";
import { AuthorizationError, requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";
import { requireAccountModules } from "./modules";
import { allocateDocumentNumberInTx } from "./numbering";
import type { ProjectActor } from "./projects";
const input=z.object({branchId:z.string().uuid(),name:z.string().trim().min(1).max(240),assetType:z.nativeEnum(AssetType),category:z.string().max(120).optional(),purchaseDate:z.coerce.date(),purchaseValue:z.string().regex(/^\d{1,16}(\.\d{1,2})?$/),vendorId:z.string().uuid().optional(),purchaseDocumentId:z.string().uuid().optional(),purchaseDocumentLineId:z.string().uuid().optional(),description:z.string().max(5000).optional(),serialNumber:z.string().max(160).optional(),registrationNumber:z.string().max(80).optional(),makeModel:z.string().max(160).optional(),manufactureYear:z.coerce.number().int().min(1900).max(2200).optional(),location:z.string().max(240).optional(),depreciationMethod:z.nativeEnum(DepreciationMethod).default("NONE"),usefulLifeMonths:z.coerce.number().int().positive().optional(),salvageValue:z.string().regex(/^\d{1,16}(\.\d{1,2})?$/).default("0"),depreciationStartDate:z.coerce.date().optional(),assetLedgerId:z.string().uuid().optional(),accumulatedDepreciationLedgerId:z.string().uuid().optional(),depreciationExpenseLedgerId:z.string().uuid().optional()}).strict();
async function actor(write=false){const a=(write?await requirePermissionForMutation("ACCOUNT_ACCOUNTS"):await requirePermission("ACCOUNT_ACCOUNTS")) as ProjectActor;await requireAccountModules(a,"ASSETS");if(!["ACCOUNT_ADMIN","ACCOUNTANT"].includes(a.accountRole??""))throw new AuthorizationError();return a;}
const allowed=(a:ProjectActor,id:string)=>a.branchAccessScope!=="SELECTED_BRANCHES"||a.branchIds?.includes(id);
export async function createAsset(raw:unknown){const a=await actor(true),d=input.parse(raw);if(!allowed(a,d.branchId))throw new AuthorizationError();return db.$transaction(async tx=>{if(!await tx.branch.findFirst({where:{id:d.branchId,companyId:a.companyId,isActive:true}}))throw new AuthorizationError();if(d.vendorId&&!await tx.vendor.findFirst({where:{id:d.vendorId,companyId:a.companyId}}))throw new AuthorizationError();if(d.purchaseDocumentId&&!await tx.commercialDocument.findFirst({where:{id:d.purchaseDocumentId,companyId:a.companyId,type:"PURCHASE_BILL",status:"POSTED"}}))throw new AuthorizationError();const assetNumber=await allocateDocumentNumberInTx(tx,{companyId:a.companyId!,branchId:d.branchId,seriesKey:"ASSET",defaults:{prefix:"AST-",padding:6}}),row=await tx.asset.create({data:{...d,companyId:a.companyId!,assetNumber,purchaseValue:new Prisma.Decimal(d.purchaseValue),salvageValue:new Prisma.Decimal(d.salvageValue),createdById:a.id}});await tx.accountOperationalAudit.create({data:{companyId:a.companyId!,actorUserId:a.id,eventType:"ASSET_CREATED",entityType:"ASSET",entityId:row.id}});return row;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
async function scoped(a:ProjectActor,id:string){const row=await db.asset.findFirst({where:{id,companyId:a.companyId,...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})}});if(!row)throw new AuthorizationError();return row;}
export async function assignAsset(assetId:string,userId:string,notes?:string){const a=await actor(true),asset=await scoped(a,assetId);if(!["ACTIVE","ASSIGNED"].includes(asset.status))throw new Error("ASSET_NOT_ASSIGNABLE");return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "assets" WHERE "id"=${assetId}::uuid FOR UPDATE`;const user=await tx.user.findFirst({where:{id:userId,companyId:a.companyId,isActive:true}});if(!user)throw new AuthorizationError();await tx.assetAssignmentHistory.updateMany({where:{companyId:a.companyId,assetId,returnedAt:null},data:{returnedAt:new Date()}});const history=await tx.assetAssignmentHistory.create({data:{companyId:a.companyId!,assetId,assignedToId:userId,assignedById:a.id,notes}});await tx.asset.update({where:{id:assetId},data:{assignedUserId:userId,status:"ASSIGNED"}});await tx.accountOperationalAudit.create({data:{companyId:a.companyId!,actorUserId:a.id,eventType:"ASSET_ASSIGNED",entityType:"ASSET",entityId:assetId,metadata:{userId}}});return history;});}
export async function returnAsset(assetId:string,notes?:string){const a=await actor(true);await scoped(a,assetId);return db.$transaction(async tx=>{const changed=await tx.assetAssignmentHistory.updateMany({where:{companyId:a.companyId,assetId,returnedAt:null},data:{returnedAt:new Date(),...(notes?{notes}:{})}});if(changed.count!==1)throw new Error("ASSET_NOT_ASSIGNED");await tx.asset.update({where:{id:assetId},data:{assignedUserId:null,status:"ACTIVE"}});await tx.accountOperationalAudit.create({data:{companyId:a.companyId!,actorUserId:a.id,eventType:"ASSET_RETURNED",entityType:"ASSET",entityId:assetId}});});}
export async function setAssetStatus(assetId:string,status:AssetStatus){const a=await actor(true);await scoped(a,assetId);if(status==="ASSIGNED")throw new Error("USE_ASSIGNMENT_FLOW");return db.asset.update({where:{id:assetId},data:{status,...(status!=="ACTIVE"?{assignedUserId:null}:{})}});}
