import { compactSource } from "@/lib/testing/compact-source";
import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const material=compactSource(readFileSync("src/lib/account/project-material-service.ts","utf8")).replace(/\s+/g,""),commercial=compactSource(readFileSync("src/lib/account/commercial.ts","utf8")),projects=compactSource(readFileSync("src/lib/account/projects.ts","utf8")).replace(/\s+/g,""),page=readFileSync("src/app/workspace/account/projects/page.tsx","utf8"),nav=readFileSync("src/components/account/account-bottom-nav.tsx","utf8"),android=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/NativeAccountApp.kt","utf8"),sale=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/sales/SalesDocumentEditor.kt","utf8"),item=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/inventory/AddItemScreen.kt","utf8");
describe("B6-B12 unified Account acceptance contracts",()=>{
 it("uses canonical Android prefix and party APIs",()=>{expect(sale).toContain('onPrefix("")');expect(sale).toContain("onCreateCustomer")});
 it("has the dedicated Android item editor and central settings links",()=>{for(const x of["Product","Services","Item Name *","Select Unit","Cancel","Save","Add Item Settings","Service Reminders · Coming Soon","/workspace/account/inventory/item-settings"])expect(item).toContain(x);expect(sale).toContain('navigate("/workspace/account/settings")')});
 it("shows footer only for exact roots",()=>{expect(nav).toContain("item.href===pathname");expect(android).toContain("bottom.any{it.path==state.selectedPath}")});
 it("renders exactly the five project metrics and four primary actions",()=>{for(const x of["Active Projects","Projects Closed","Total Project Value","Received","Outstanding"])expect(page).toContain(x);for(const x of["Project Invoice","Move / Return Stock","Project Settings","View All"])expect(page).toContain(x);expect(page).toContain("+ Create New Project")});
 it("keeps regular and project invoices in the same commercial engine",()=>{expect(commercial).toContain('type:d.type');expect(commercial).toContain('projectId:["CREDIT_NOTE","DEBIT_NOTE"].includes(d.type)?source?.projectId:d.projectId');expect(commercial).toContain("authorizeProjectForCommercial")});
 it("routes project transfers through inventory with preserved cost and traceability",()=>{for(const x of['movementType:"TRANSFER_IN"','movementType:"TRANSFER_OUT"','sourceType:"PROJECT_TRANSFER_RETURN"','sourceType:"PROJECT_TRANSFER_ISSUE"',"unitCost:source.originalUnitCost","totalCost:total","purchaseDocumentId:source.purchaseDocumentId"])expect(material).toContain(x)});
 it("only consumes material into project cost",()=>{expect(material).toContain('sourceType:"PROJECT_MATERIAL_CONSUMPTION"');expect(material).toContain('ctx.account("PROJECT_MATERIAL_COST")');expect(material).toContain('ctx.account("PROJECT_MATERIAL_WIP")')});
 it("uses approved variations for final project value",()=>{expect(projects).toContain('status:"APPROVED"');expect(projects).toContain("finalProjectValue=project.projectValue.add(approvedVariations)")});
});
