import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import type { AccountBranchActor, AccountBranchContext } from "./branch-context";
import { documentOutstandingsBatch } from "./commercial";
import { profitAndLoss, type ReportLine } from "./financial-reports";
import { DASHBOARD_EXPENSE_TYPES } from "./dashboard-policy";
const D=Prisma.Decimal,Z=new D(0),sum=(v:Prisma.Decimal[])=>v.reduce((a,b)=>a.add(b),Z),incoming=new Set(["OPENING","PURCHASE","SALES_RETURN","TRANSFER_IN","ADJUSTMENT_IN"]);
export async function accountBranchDashboard(actor:AccountBranchActor,context:AccountBranchContext,from:Date,to:Date){const branch=context.mode==="BRANCH"?{branchId:context.branchId}:{},period={issueDate:{gte:from,lte:to}},projectScope=actor.accountRole==="PROJECT_MANAGER"?{projectManagerId:actor.id}:{};
 if(actor.accountRole==="PROJECT_MANAGER"){const p=await db.project.aggregate({where:{companyId:actor.companyId,...branch,...projectScope},_count:true,_sum:{projectValue:true}});return{projectOnly:true,projects:p._count,projectValue:p._sum.projectValue??Z,from,to,context} as const;}
 const [sr,pr,rd,pd,expense,projects,warehouses,moneyAccounts,stockRows,accounts,journalGroups,branches]=await Promise.all([db.commercialDocument.groupBy({by:["type"],where:{companyId:actor.companyId,status:"POSTED",type:{in:["SALES_INVOICE","CREDIT_NOTE"]},...branch,...period},_sum:{taxableTotal:true}}),db.commercialDocument.groupBy({by:["type"],where:{companyId:actor.companyId,status:"POSTED",type:{in:["PURCHASE_BILL","DEBIT_NOTE"]},...branch,...period},_sum:{taxableTotal:true}}),db.commercialDocument.findMany({where:{companyId:actor.companyId,status:"POSTED",type:"SALES_INVOICE",issueDate:{lte:to},...branch},select:{id:true,grandTotal:true,payableAmount:true}}),db.commercialDocument.findMany({where:{companyId:actor.companyId,status:"POSTED",type:"PURCHASE_BILL",issueDate:{lte:to},...branch},select:{id:true,grandTotal:true,payableAmount:true}}),db.expenseTransaction.aggregate({where:{companyId:actor.companyId,status:"POSTED",type:{in:[...DASHBOARD_EXPENSE_TYPES]},transactionDate:{gte:from,lte:to},...branch},_sum:{taxableAmount:true}}),db.project.aggregate({where:{companyId:actor.companyId,...branch,...projectScope,status:{in:["PLANNING","ACTIVE","ON_HOLD"]}},_count:true,_sum:{projectValue:true}}),db.warehouse.count({where:{companyId:actor.companyId,isActive:true,...branch}}),db.moneyAccount.findMany({where:{companyId:actor.companyId,isActive:true,...(context.mode==="BRANCH"?{branchId:context.branchId}:{})},select:{ledgerAccountId:true}}),db.stockMovement.groupBy({by:["movementType"],where:{companyId:actor.companyId,...branch,movementDate:{lte:to}},_sum:{totalCost:true}}),db.ledgerAccount.findMany({where:{companyId:actor.companyId,isActive:true,accountClass:{in:["INCOME","EXPENSE"]}},select:{id:true,code:true,name:true,accountClass:true}}),db.journalLine.groupBy({by:["ledgerAccountId"],where:{companyId:actor.companyId,journalEntry:{status:"POSTED",entryDate:{gte:from,lte:to},...branch}},_sum:{debit:true,credit:true}}),context.mode==="COMPANY"?db.branch.findMany({where:{companyId:actor.companyId,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}}):Promise.resolve([])]);
 const [rm,pm,moneyLines]=await Promise.all([documentOutstandingsBatch(actor.companyId,rd),documentOutstandingsBatch(actor.companyId,pd),db.journalLine.groupBy({by:["ledgerAccountId"],where:{companyId:actor.companyId,ledgerAccountId:{in:moneyAccounts.map(x=>x.ledgerAccountId)},journalEntry:{status:"POSTED",entryDate:{lte:to},...branch}},_sum:{debit:true,credit:true}})]),sales=sum(sr.map(x=>(x._sum.taxableTotal??Z).mul(x.type==="CREDIT_NOTE"?-1:1))),purchases=sum(pr.map(x=>(x._sum.taxableTotal??Z).mul(x.type==="DEBIT_NOTE"?-1:1)));
 const lines:ReportLine[]=accounts.map(a=>{const g=journalGroups.find(x=>x.ledgerAccountId===a.id);return{ledgerId:a.id,code:a.code,name:a.name,accountClass:a.accountClass,openingDebit:Z,openingCredit:Z,periodDebit:g?._sum.debit??Z,periodCredit:g?._sum.credit??Z}}),pnl=profitAndLoss(lines),cashBank=sum(moneyLines.map(x=>new D(x._sum.debit??0).sub(x._sum.credit??0))),stockValue=sum(stockRows.map(x=>(x._sum.totalCost??Z).mul(incoming.has(x.movementType)?1:-1)));
 const cmp=context.mode==="COMPANY"?await Promise.all([db.commercialDocument.groupBy({by:["branchId","type"],where:{companyId:actor.companyId,status:"POSTED",type:{in:["SALES_INVOICE","CREDIT_NOTE"]},...period},_sum:{taxableTotal:true}}),db.expenseTransaction.groupBy({by:["branchId"],where:{companyId:actor.companyId,status:"POSTED",type:{in:[...DASHBOARD_EXPENSE_TYPES]},transactionDate:{gte:from,lte:to}},_sum:{taxableAmount:true}})]):null;
 return{projectOnly:false as const,context,from,to,sales,purchases,receivables:sum([...rm.values()]),payables:sum([...pm.values()]),expenses:expense._sum.taxableAmount??Z,profit:pnl.profit,cashBank,projects:projects._count,projectValue:projects._sum.projectValue??Z,warehouses,stockValue,branchComparison:cmp?branches.map(b=>{const revenue=sum(cmp[0].filter(x=>x.branchId===b.id).map(x=>(x._sum.taxableTotal??Z).mul(x.type==="CREDIT_NOTE"?-1:1))),cost=cmp[1].find(x=>x.branchId===b.id)?._sum.taxableAmount??Z;return{id:b.id,name:b.name,sales:revenue,expenses:cost,operatingContribution:revenue.sub(cost)}}):[]};}
