import {CommercialDocumentType,Prisma,SettlementType} from "@prisma/client";
import {z} from "zod";
import {db} from "@/lib/db";
import {requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";
import type {Permission} from "@/lib/auth/permissions";
import {allocateDocumentNumberInTx} from "./numbering";
import {requireAccountModules,type ModuleKey} from "./modules";

const policies:Record<CommercialDocumentType,{modules:ModuleKey[];permission:Permission;party:"customer"|"vendor";prefix:string}>={
 SALES_ORDER:{modules:["SALES","SALES_ORDER"],permission:"ACCOUNT_SALES_ENTRY",party:"customer",prefix:"SO-"},PROFORMA_INVOICE:{modules:["SALES","PROFORMA_INVOICE"],permission:"ACCOUNT_SALES_ENTRY",party:"customer",prefix:"PI-"},SALES_INVOICE:{modules:["SALES"],permission:"ACCOUNT_SALES_ENTRY",party:"customer",prefix:"INV-"},DELIVERY_CHALLAN:{modules:["SALES","DELIVERY_CHALLAN"],permission:"ACCOUNT_SALES_ENTRY",party:"customer",prefix:"DC-"},CREDIT_NOTE:{modules:["SALES","CREDIT_NOTE"],permission:"ACCOUNT_SALES_ENTRY",party:"customer",prefix:"CN-"},
 PURCHASE_ORDER:{modules:["PURCHASES","PURCHASE_ORDER"],permission:"ACCOUNT_PURCHASE_ENTRY",party:"vendor",prefix:"PO-"},PURCHASE_BILL:{modules:["PURCHASES","PURCHASE_BILLS"],permission:"ACCOUNT_PURCHASE_ENTRY",party:"vendor",prefix:"PB-"},DEBIT_NOTE:{modules:["PURCHASES","DEBIT_NOTE"],permission:"ACCOUNT_PURCHASE_ENTRY",party:"vendor",prefix:"DN-"},SUBCONTRACT_PURCHASE:{modules:["PURCHASES","SUBCONTRACTORS"],permission:"ACCOUNT_PURCHASE_ENTRY",party:"vendor",prefix:"SC-"}};
const decimal=z.union([z.string(),z.number()]).transform(String);
const inputSchema=z.object({type:z.nativeEnum(CommercialDocumentType),branchId:z.string().uuid(),partyId:z.string().uuid(),issueDate:z.coerce.date(),dueDate:z.coerce.date().optional(),notes:z.string().max(5000).optional(),lines:z.array(z.object({description:z.string().trim().min(1).max(1000),quantity:decimal,rate:decimal,taxRate:decimal.default("0")})).min(1).max(500)}).strict();
function branchScope(a:{branchAccessScope?:string;branchIds?:string[]}){return a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{}}
export async function createCommercialDocument(raw:unknown){const d=inputSchema.parse(raw),p=policies[d.type],a=await requirePermissionForMutation(p.permission);await requireAccountModules(a,...p.modules);return db.$transaction(async tx=>{if(a.branchAccessScope==="SELECTED_BRANCHES"&&!a.branchIds?.includes(d.branchId))throw new Error("INVALID_BRANCH");if(!await tx.branch.findFirst({where:{companyId:a.companyId!,id:d.branchId,isActive:true}}))throw new Error("INVALID_BRANCH");const party=p.party==="customer"?await tx.customer.findFirst({where:{companyId:a.companyId!,id:d.partyId,isActive:true,isAccountCustomer:true},select:{name:true}}):await tx.vendor.findFirst({where:{companyId:a.companyId!,id:d.partyId,isActive:true},select:{name:true}});if(!party)throw new Error(`INVALID_${p.party.toUpperCase()}`);const lines=d.lines.map((x,position)=>{const quantity=new Prisma.Decimal(x.quantity),rate=new Prisma.Decimal(x.rate),taxRate=new Prisma.Decimal(x.taxRate);if(quantity.lte(0)||rate.lt(0)||taxRate.lt(0))throw new Error("INVALID_AMOUNT");const taxable=quantity.mul(rate).toDecimalPlaces(2),taxAmount=taxable.mul(taxRate).div(100).toDecimalPlaces(2);return{...x,position,taxable,taxAmount,total:taxable.add(taxAmount)}}),subtotal=lines.reduce((n,x)=>n.add(x.taxable),new Prisma.Decimal(0)),taxTotal=lines.reduce((n,x)=>n.add(x.taxAmount),new Prisma.Decimal(0)),grandTotal=subtotal.add(taxTotal),documentNumber=await allocateDocumentNumberInTx(tx,{companyId:a.companyId!,branchId:d.branchId,seriesKey:d.type,defaults:{prefix:p.prefix,padding:6}});return tx.commercialDocument.create({data:{companyId:a.companyId!,branchId:d.branchId,type:d.type,documentNumber,partyId:d.partyId,partyName:party.name,issueDate:d.issueDate,dueDate:d.dueDate,notes:d.notes,subtotal,taxTotal,grandTotal,balanceDue:grandTotal,createdById:a.id,lines:{create:lines.map(x=>({companyId:a.companyId!,...x}))}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
/** Reads deliberately ignore current module state so history and reports remain authoritative. */
export async function listCommercialDocuments(){const a=await requirePermission("ACCOUNT_LEDGER_VIEW");return db.commercialDocument.findMany({where:{companyId:a.companyId!,...branchScope(a)},include:{lines:true},orderBy:{createdAt:"desc"}})}
export async function getCommercialDocument(id:string){const a=await requirePermission("ACCOUNT_LEDGER_VIEW"),row=await db.commercialDocument.findFirst({where:{id,companyId:a.companyId!,...branchScope(a)},include:{lines:true,reminders:true}});if(!row)throw new Error("NOT_FOUND");return row}
const settlementModules:Record<SettlementType,ModuleKey[]>={CUSTOMER_RECEIPT:["SALES","CUSTOMER_RECEIPTS"],CUSTOMER_ADVANCE:["SALES","CUSTOMER_ADVANCES"],VENDOR_PAYMENT:["PURCHASES","VENDOR_PAYMENTS"],VENDOR_ADVANCE:["PURCHASES","VENDOR_ADVANCES"]};
export async function createSettlement(raw:unknown){const d=z.object({type:z.nativeEnum(SettlementType),branchId:z.string().uuid(),partyId:z.string().uuid(),amount:decimal,transactionDate:z.coerce.date(),reference:z.string().max(160).optional()}).strict().parse(raw),a=await requirePermissionForMutation("ACCOUNT_SETTLEMENT_ENTRY");await requireAccountModules(a,...settlementModules[d.type]);if(a.branchAccessScope==="SELECTED_BRANCHES"&&!a.branchIds?.includes(d.branchId))throw new Error("INVALID_BRANCH");const amount=new Prisma.Decimal(d.amount);if(amount.lte(0))throw new Error("INVALID_AMOUNT");return db.accountSettlement.create({data:{companyId:a.companyId!,createdById:a.id,...d,amount}})}
export async function schedulePaymentReminder(raw:unknown){const d=z.object({documentId:z.string().uuid(),remindAt:z.coerce.date(),message:z.string().trim().min(1).max(1000)}).strict().parse(raw),a=await requirePermissionForMutation("ACCOUNT_SALES_ENTRY");await requireAccountModules(a,"SALES","PAYMENT_REMINDERS");const document=await db.commercialDocument.findFirst({where:{id:d.documentId,companyId:a.companyId!,type:"SALES_INVOICE",...branchScope(a)}});if(!document)throw new Error("INVALID_INVOICE");return db.paymentReminder.create({data:{companyId:a.companyId!,...d}})}
export async function postCommercialDocument(raw:unknown){const d=z.object({documentId:z.string().uuid(),financialYearId:z.string().uuid(),receivableOrPayableAccountId:z.string().uuid(),incomeOrExpenseAccountId:z.string().uuid(),taxAccountId:z.string().uuid().optional()}).strict().parse(raw),a=await requirePermissionForMutation("ACCOUNT_JOURNAL_POST"),document=await db.commercialDocument.findFirst({where:{id:d.documentId,companyId:a.companyId!,status:"DRAFT",...branchScope(a)}});if(!document)throw new Error("DOCUMENT_NOT_POSTABLE");await requireAccountModules(a,...policies[document.type].modules);if(!["SALES_INVOICE","CREDIT_NOTE","PURCHASE_BILL","DEBIT_NOTE"].includes(document.type))throw new Error("NON_FINANCIAL_DOCUMENT");const debitMain=document.type==="SALES_INVOICE"||document.type==="DEBIT_NOTE",debitCounter=document.type==="PURCHASE_BILL"||document.type==="CREDIT_NOTE",money=(x:Prisma.Decimal)=>x.toFixed(2),lines=[{ledgerAccountId:d.receivableOrPayableAccountId,debit:debitMain?money(document.grandTotal):"0",credit:debitMain?"0":money(document.grandTotal),description:document.documentNumber},{ledgerAccountId:d.incomeOrExpenseAccountId,debit:debitCounter?money(document.subtotal):"0",credit:debitCounter?"0":money(document.subtotal),description:document.documentNumber}];if(document.taxTotal.gt(0)){if(!d.taxAccountId)throw new Error("TAX_ACCOUNT_REQUIRED");lines.push({ledgerAccountId:d.taxAccountId,debit:debitCounter?money(document.taxTotal):"0",credit:debitCounter?"0":money(document.taxTotal),description:document.documentNumber})}const {postJournal}=await import("@/lib/accounting/service"),journal=await postJournal({financialYearId:d.financialYearId,branchId:document.branchId,entryDate:document.issueDate,sourceType:document.type,sourceId:document.id,postingPurpose:"PRIMARY",lines});const changed=await db.commercialDocument.updateMany({where:{id:document.id,companyId:a.companyId!,status:"DRAFT"},data:{status:"POSTED",journalEntryId:journal.id}});if(changed.count!==1)throw new Error("STALE");return journal}
