import { beforeEach, describe, expect, it, vi } from "vitest";
import { Prisma } from "@prisma/client";

const COMPANY="11111111-1111-4111-8111-111111111111", BRANCH="22222222-2222-4222-8222-222222222222", PARTY="33333333-3333-4333-8333-333333333333", DOCUMENT="44444444-4444-4444-8444-444444444444";
const m=vi.hoisted(()=>({auth:vi.fn(),company:vi.fn(),modules:vi.fn(),enabled:vi.fn(),projects:vi.fn(),number:vi.fn(),post:vi.fn(),transaction:vi.fn(),branch:vi.fn(),customer:vi.fn(),settings:vi.fn(),documentCreate:vi.fn(),documentFind:vi.fn(),documentMany:vi.fn(),documentAggregate:vi.fn(),audit:vi.fn(),settlementFind:vi.fn(),settlementCreate:vi.fn(),fy:vi.fn(),ledgers:vi.fn(),lock:vi.fn(),raw:vi.fn(),execute:vi.fn(),findMany:vi.fn(),allocationAggregate:vi.fn(),applicationAggregate:vi.fn()}));
vi.mock("@/lib/auth/authorization",()=>({AuthorizationError:class extends Error{},requirePermission:m.auth,requirePermissionForMutation:m.auth}));
vi.mock("./modules",()=>({requireAccountModules:m.modules,enabledModulesForCompany:m.enabled}));
vi.mock("./projects",()=>({authorizeProjectForCommercial:vi.fn(),listOpenProjectOptionsForActor:m.projects}));
vi.mock("./numbering",()=>({allocateDocumentNumberInTx:m.number}));
vi.mock("@/lib/accounting/service",()=>({postJournalInTx:m.post}));
const tx={branch:{findFirst:m.branch},customer:{findFirst:m.customer},vendor:{findFirst:vi.fn()},accountSettings:{findUnique:m.settings},commercialDocument:{create:m.documentCreate,findFirst:m.documentFind,findMany:m.documentMany,aggregate:m.documentAggregate},commercialAuditEvent:{create:m.audit},accountSettlement:{findUnique:m.settlementFind,create:m.settlementCreate},financialYear:{findFirst:m.fy},ledgerAccount:{findMany:m.ledgers},accountingPeriodLock:{findFirst:m.lock},moneyAccount:{findFirst:vi.fn()},settlementAllocation:{aggregate:m.allocationAggregate},advanceApplication:{aggregate:m.applicationAggregate},$queryRaw:m.raw,$executeRaw:m.execute};
vi.mock("@/lib/db",()=>({db:{$transaction:m.transaction,company:{findUniqueOrThrow:m.company},commercialDocument:{findMany:m.documentMany},branch:{findMany:m.findMany},customer:{findMany:m.findMany},vendor:{findMany:m.findMany},accountProduct:{findMany:m.findMany},warehouse:{findMany:m.findMany},inventoryBatch:{findMany:m.findMany},inventorySerialNumber:{findMany:m.findMany},accountSettings:{findUnique:m.settings},accountService:{findMany:m.findMany},workPackage:{findMany:m.findMany}}}));
import {commercialEditorOptions,createCommercialDocument,createSettlement} from "./commercial";
const actor=(scope:"ALL_BRANCHES"|"SELECTED_BRANCHES"="ALL_BRANCHES")=>({id:"actor",companyId:COMPANY,accountRole:"ACCOUNT_ADMIN",branchAccessScope:scope,branchIds:scope==="SELECTED_BRANCHES"?[BRANCH]:[]});
const commercial=(type:string)=>({type,branchId:BRANCH,partyId:PARTY,issueDate:"2026-09-10",lines:[{lineType:"CUSTOM",itemName:"Work",quantity:"1",rate:"100"}]});
const settlement=(type:"CUSTOMER_RECEIPT"|"CUSTOMER_ADVANCE")=>({idempotencyKey:`key-${type}`,type,branchId:BRANCH,partyId:PARTY,paymentMode:"CASH",amount:"100",transactionDate:"2026-09-10",allocations:type==="CUSTOMER_RECEIPT"?[{documentId:DOCUMENT,amount:"100"}]:[]});
beforeEach(()=>{vi.clearAllMocks();m.auth.mockResolvedValue(actor());m.company.mockResolvedValue({productEdition:"SALESPUNCH360_PLUS"});m.enabled.mockResolvedValue(["SALES","SALES_ORDER","PROFORMA_INVOICE","DELIVERY_CHALLAN","CREDIT_NOTE","CUSTOMER_RECEIPTS","CUSTOMER_ADVANCES"]);m.projects.mockResolvedValue([]);m.number.mockResolvedValue("N-1");m.transaction.mockImplementation((fn:(client:typeof tx)=>unknown)=>fn(tx));m.branch.mockResolvedValue({id:BRANCH,gstin:null,gstStateCode:null});m.customer.mockResolvedValue({id:PARTY,name:"Customer",gstin:null,stateCode:null});m.settings.mockResolvedValue(null);m.documentCreate.mockResolvedValue({id:DOCUMENT});m.documentMany.mockResolvedValue([]);m.documentAggregate.mockResolvedValue({_sum:{grandTotal:0}});m.audit.mockResolvedValue({});m.settlementFind.mockResolvedValue(null);m.settlementCreate.mockResolvedValue({id:"settlement"});m.fy.mockResolvedValue({id:"fy"});m.ledgers.mockResolvedValue([{id:"cash",systemKey:"CASH"},{id:"ar",systemKey:"ACCOUNTS_RECEIVABLE"},{id:"adv",systemKey:"CUSTOMER_ADVANCES"}]);m.lock.mockResolvedValue(null);m.post.mockResolvedValue({id:"journal"});m.findMany.mockResolvedValue([]);m.allocationAggregate.mockResolvedValue({_sum:{amount:0}});m.applicationAggregate.mockResolvedValue({_sum:{amount:0}})});
describe("commercial Account Customer Branch options",()=>{
 it("limits selected-Branch customers to authorized Branch IDs",async()=>{m.auth.mockResolvedValue(actor("SELECTED_BRANCHES"));await commercialEditorOptions();expect(m.findMany).toHaveBeenCalledWith({where:{companyId:COMPANY,isActive:true,isAccountCustomer:true,branchId:{in:[BRANCH]}},select:{id:true,name:true}})});
 it("retains company-wide customers for ALL_BRANCHES",async()=>{await commercialEditorOptions();expect(m.findMany).toHaveBeenCalledWith({where:{companyId:COMPANY,isActive:true,isAccountCustomer:true},select:{id:true,name:true}})});
});
describe("commercial Sales document Customer Branch validation",()=>{
 it.each(["SALES_INVOICE","SALES_ORDER","PROFORMA_INVOICE","DELIVERY_CHALLAN"])("allows same-Branch %s Customer validation",async type=>{await createCommercialDocument(commercial(type));expect(m.customer).toHaveBeenCalledWith(expect.objectContaining({where:{companyId:COMPANY,id:PARTY,branchId:BRANCH,isActive:true,isAccountCustomer:true}}));expect(m.documentCreate).toHaveBeenCalled()});
 it.each(["SALES_INVOICE","SALES_ORDER","PROFORMA_INVOICE","DELIVERY_CHALLAN"])("rejects cross-Branch or cross-company Customer for %s safely",async type=>{m.customer.mockResolvedValue(null);await expect(createCommercialDocument(commercial(type))).rejects.toThrow("INVALID_CUSTOMER");expect(m.documentCreate).not.toHaveBeenCalled()});
 it("preserves Credit Note source, party, and Branch enforcement",async()=>{m.documentFind.mockResolvedValue({id:DOCUMENT,status:"POSTED",type:"SALES_INVOICE",branchId:BRANCH,partyId:PARTY,customerId:PARTY,vendorId:null,grandTotal:new Prisma.Decimal(100),taxableTotal:new Prisma.Decimal(100),taxTotal:new Prisma.Decimal(0),tdsAmount:new Prisma.Decimal(0),tcsAmount:new Prisma.Decimal(0),taxMode:"EXCLUSIVE",reverseCharge:false,taxCreditTreatment:"ELIGIBLE",lines:[]});await expect(createCommercialDocument({...commercial("CREDIT_NOTE"),sourceDocumentId:DOCUMENT,lines:[{lineType:"CUSTOM",itemName:"Return",quantity:"1",rate:"10",sourceCommercialLineId:DOCUMENT}]})).rejects.toThrow();expect(m.customer).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({branchId:BRANCH})}));expect(m.raw).toHaveBeenCalled()});
});
describe("Customer settlement Branch validation",()=>{
 it.each(["CUSTOMER_RECEIPT","CUSTOMER_ADVANCE"] as const)("rejects a crafted cross-Branch partyId for %s without leakage",async type=>{m.customer.mockResolvedValue(null);await expect(createSettlement(settlement(type))).rejects.toThrow("INVALID_PARTY");expect(m.customer).toHaveBeenCalledWith({where:{id:PARTY,companyId:COMPANY,branchId:BRANCH,isActive:true,isAccountCustomer:true}});expect(m.post).not.toHaveBeenCalled()});
 it("allows same-Branch Customer Advance",async()=>{await expect(createSettlement(settlement("CUSTOMER_ADVANCE"))).resolves.toEqual({id:"settlement"});expect(m.post).toHaveBeenCalled()});
 it("allows same-Branch Customer Receipt",async()=>{m.documentFind.mockResolvedValue({id:DOCUMENT,type:"SALES_INVOICE",status:"POSTED",partyId:PARTY,branchId:BRANCH,grandTotal:new Prisma.Decimal(100),payableAmount:null});m.documentMany.mockResolvedValue([]);await expect(createSettlement(settlement("CUSTOMER_RECEIPT"))).resolves.toEqual({id:"settlement"});expect(m.post).toHaveBeenCalled()});
});
