import ExcelJS from "exceljs";
import { Prisma } from "@prisma/client";
const D=Prisma.Decimal,Z=new D(0),sum=(xs:Prisma.Decimal[])=>xs.reduce((a,b)=>a.add(b),Z);
export const REPORT_EXPORT_LIMIT=10_000;
export type ReportLine={ledgerId:string;code:string;name:string;accountClass:"ASSET"|"LIABILITY"|"EQUITY"|"INCOME"|"EXPENSE";openingDebit:Prisma.Decimal;openingCredit:Prisma.Decimal;periodDebit:Prisma.Decimal;periodCredit:Prisma.Decimal};
export function trialBalance(lines:ReportLine[]){const rows=lines.map(l=>{const opening=l.openingDebit.sub(l.openingCredit),period=l.periodDebit.sub(l.periodCredit),closing=opening.add(period);return {...l,closingDebit:Prisma.Decimal.max(Z,closing),closingCredit:Prisma.Decimal.max(Z,closing.neg())};});return {rows,totals:{openingDebit:sum(rows.map(r=>r.openingDebit)),openingCredit:sum(rows.map(r=>r.openingCredit)),periodDebit:sum(rows.map(r=>r.periodDebit)),periodCredit:sum(rows.map(r=>r.periodCredit)),closingDebit:sum(rows.map(r=>r.closingDebit)),closingCredit:sum(rows.map(r=>r.closingCredit))}};}
export function profitAndLoss(lines:ReportLine[]){const income=sum(lines.filter(l=>l.accountClass==="INCOME").map(l=>l.periodCredit.sub(l.periodDebit))),expenses=sum(lines.filter(l=>l.accountClass==="EXPENSE").map(l=>l.periodDebit.sub(l.periodCredit)));return {income,expenses,profit:income.sub(expenses)};}
export function balanceSheet(lines:ReportLine[]){const balance=(classes:ReportLine["accountClass"][])=>sum(lines.filter(l=>classes.includes(l.accountClass)).map(l=>l.openingDebit.add(l.periodDebit).sub(l.openingCredit).sub(l.periodCredit))),assets=balance(["ASSET"]),liabilities=balance(["LIABILITY"]).neg(),equity=balance(["EQUITY"]).neg(),currentEarnings=profitAndLoss(lines).profit;return {assets,liabilities,equity,currentEarnings,liabilitiesAndEquity:liabilities.add(equity).add(currentEarnings),difference:assets.sub(liabilities).sub(equity).sub(currentEarnings)};}
export function runningLedger<T extends {debit:Prisma.Decimal;credit:Prisma.Decimal}>(opening:Prisma.Decimal,rows:T[]){let balance=opening;return rows.map(row=>({...row,runningBalance:(balance=balance.add(row.debit).sub(row.credit))}));}
export type AgingDocument={id:string;partyId:string;dueDate:Date|null;issueDate:Date;outstanding:Prisma.Decimal};
export function aging(rows:AgingDocument[],asOf:Date){const buckets={current:Z,"1_30":Z,"31_60":Z,"61_90":Z,"90_plus":Z};for(const row of rows.filter(r=>r.outstanding.gt(0))){const days=Math.max(0,Math.floor((asOf.getTime()-(row.dueDate??row.issueDate).getTime())/86400000));const key=days===0?"current":days<=30?"1_30":days<=60?"31_60":days<=90?"61_90":"90_plus";buckets[key]=buckets[key].add(row.outstanding);}return buckets;}
export function cashFlow(rows:Array<{sourceType:string;amount:Prisma.Decimal;direction:"IN"|"OUT"}>){const result={operating:Z,investing:Z,financing:Z,net:Z};for(const row of rows){if(row.sourceType==="MONEY_TRANSFER")continue;const signed=row.direction==="IN"?row.amount:row.amount.neg(),key=/ASSET/.test(row.sourceType)?"investing":/LOAN|CAPITAL|DRAWING/.test(row.sourceType)?"financing":"operating";result[key]=result[key].add(signed);result.net=result.net.add(signed);}return result;}
const csvCell=(v:unknown)=>{const s=String(v??"");return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s;};
export function exportCsv(columns:string[],rows:unknown[][]){if(rows.length>REPORT_EXPORT_LIMIT)throw new Error("REPORT_EXPORT_LIMIT_EXCEEDED");return `\uFEFF${[columns,...rows].map(r=>r.map(csvCell).join(",")).join("\r\n")}`;}
export async function exportExcel(input:{title:string;company:string;filter:string;columns:string[];rows:unknown[][]}){if(input.rows.length>REPORT_EXPORT_LIMIT)throw new Error("REPORT_EXPORT_LIMIT_EXCEEDED");const book=new ExcelJS.Workbook(),sheet=book.addWorksheet("Report");sheet.addRow([input.title]);sheet.addRow([input.company]);sheet.addRow([input.filter]);sheet.addRow([`Generated: ${new Date().toISOString()}`]);sheet.addRow([]);sheet.addRow(input.columns);input.rows.forEach(row=>sheet.addRow(row));sheet.getRow(1).font={bold:true,size:16};sheet.getRow(6).font={bold:true};sheet.columns.forEach(c=>{c.width=18});return Buffer.from(await book.xlsx.writeBuffer());}
export function exportPdf(input:{title:string;company:string;columns:string[];rows:unknown[][]}){if(input.rows.length>REPORT_EXPORT_LIMIT)throw new Error("REPORT_EXPORT_LIMIT_EXCEEDED");const clean=(v:unknown)=>String(v??"").replace(/[()\\]/g,c=>`\\${c}`).replace(/[^\x20-\x7e]/g,"?"),text=[input.title,input.company,input.columns.join(" | "),...input.rows.map(r=>r.join(" | "))],chunks:string[]=[];for(let i=0;i<text.length;i+=45)chunks.push(text.slice(i,i+45).map((x,n)=>`BT /F1 8 Tf 30 ${810-n*17} Td (${clean(x)}) Tj ET`).join("\n"));const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${chunks.map((_,i)=>`${3+i*2} 0 R`).join(" ")}] /Count ${chunks.length} >>`];chunks.forEach((_,i)=>objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${4+i*2} 0 R >> >> /Contents ${3+chunks.length*2+i} 0 R >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`));chunks.forEach(stream=>objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`));let output="%PDF-1.4\n";const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(output));output+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(output);output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output);}
