import { Prisma, StockMovementType } from "@prisma/client";
import { z } from "zod";
import { db } from "@/lib/db";
import { AuthorizationError, requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";
import { requireAccountModules } from "./modules";
import type { ProjectActor } from "./projects";
const D=Prisma.Decimal,Z=new D(0), qty=z.string().regex(/^\d{1,14}(\.\d{1,4})?$/), money=z.string().regex(/^\d{1,16}(\.\d{1,4})?$/);
const IN=new Set<StockMovementType>(["OPENING","PURCHASE","SALES_RETURN","TRANSFER_IN","ADJUSTMENT_IN"]);
export const signedQuantity=(type:StockMovementType, quantity:Prisma.Decimal)=>IN.has(type)?quantity:quantity.neg();
export function stockValuation(rows:Array<{movementType:StockMovementType;quantity:Prisma.Decimal;unitCost:Prisma.Decimal}>){let quantity=Z,value=Z;for(const row of rows){const q=signedQuantity(row.movementType,row.quantity);if(q.gte(0)){quantity=quantity.add(q);value=value.add(q.mul(row.unitCost));}else{const average=quantity.gt(0)?value.div(quantity):row.unitCost;quantity=quantity.add(q);value=value.add(q.mul(average));}}return {quantity,averageUnitCost:quantity.gt(0)?value.div(quantity).toDecimalPlaces(4):Z,stockValue:value.toDecimalPlaces(2)};}
export function chooseProductRate(input:{customerRate?:Prisma.Decimal|null;tierRate?:Prisma.Decimal|null;defaultRate?:Prisma.Decimal|null}){return input.customerRate??input.tierRate??input.defaultRate??Z;}
async function actor(write=false){const a=(write?await requirePermissionForMutation("ACCOUNT_STOCK"):await requirePermission("ACCOUNT_STOCK")) as ProjectActor;await requireAccountModules(a,"INVENTORY");if(a.accountRole==="PROJECT_MANAGER")throw new AuthorizationError();return a;}
const branchAllowed=(a:ProjectActor,id:string)=>a.branchAccessScope!=="SELECTED_BRANCHES"||a.branchIds?.includes(id);
async function warehouse(tx:Prisma.TransactionClient,a:ProjectActor,id:string){const row=await tx.warehouse.findFirst({where:{id,companyId:a.companyId,isActive:true}});if(!row||!branchAllowed(a,row.branchId))throw new AuthorizationError();return row;}
async function product(tx:Prisma.TransactionClient,a:ProjectActor,id:string){const row=await tx.accountProduct.findFirst({where:{id,companyId:a.companyId,isActive:true,trackInventory:true}});if(!row)throw new Error("INVALID_INVENTORY_PRODUCT");return row;}
async function balance(tx:Prisma.TransactionClient,companyId:string,warehouseId:string,productId:string,batchId?:string,serialNumberId?:string){const rows=await tx.stockMovement.findMany({where:{companyId,warehouseId,productId,...(batchId?{batchId}:{}),...(serialNumberId?{serialNumberId}:{})},select:{movementType:true,quantity:true}});return rows.reduce((n,r)=>n.add(signedQuantity(r.movementType,r.quantity)),Z);}
const movement=z.object({warehouseId:z.string().uuid(),productId:z.string().uuid(),quantity:qty,unitCost:money.default("0"),movementDate:z.coerce.date(),batchId:z.string().uuid().optional(),serialNumberId:z.string().uuid().optional(),reason:z.string().trim().min(1).max(1000).optional(),sourceType:z.string().max(80),sourceId:z.string().max(160),sourceLineId:z.string().uuid().optional()}).strict();
export async function createStockMovement(type:StockMovementType,raw:unknown){const a=await actor(true),d=movement.parse(raw);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`${a.companyId}:${d.warehouseId}:${d.productId}`}))`;const [w,p,settings]=await Promise.all([warehouse(tx,a,d.warehouseId),product(tx,a,d.productId),tx.accountSettings.findUnique({where:{companyId:a.companyId!}})]);const q=new D(d.quantity);if(p.trackingMode==="BATCH"&&!d.batchId)throw new Error("BATCH_REQUIRED");if(p.trackingMode==="SERIAL"&&(!d.serialNumberId||!q.equals(1)))throw new Error("SERIAL_QUANTITY_MISMATCH");if(d.batchId&&!await tx.inventoryBatch.findFirst({where:{id:d.batchId,companyId:a.companyId,productId:p.id}}))throw new AuthorizationError();if(d.serialNumberId&&!await tx.inventorySerialNumber.findFirst({where:{id:d.serialNumberId,companyId:a.companyId,productId:p.id}}))throw new AuthorizationError();if(!IN.has(type)&&!(settings?.negativeStockAllowed??false)&&(await balance(tx,a.companyId!,w.id,p.id,d.batchId,d.serialNumberId)).lt(q))throw new Error("INSUFFICIENT_STOCK");const unitCost=new D(d.unitCost);const row=await tx.stockMovement.create({data:{...d,companyId:a.companyId!,branchId:w.branchId,movementType:type,quantity:q,unitCost,totalCost:q.mul(unitCost).toDecimalPlaces(2),createdById:a.id}});await tx.accountOperationalAudit.create({data:{companyId:a.companyId!,actorUserId:a.id,eventType:`STOCK_${type}`,entityType:"STOCK_MOVEMENT",entityId:row.id,metadata:{reason:d.reason}}});return row;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export const createOpeningStock=(raw:unknown)=>createStockMovement("OPENING",raw);
export const adjustStock=(direction:"IN"|"OUT",raw:unknown)=>createStockMovement(direction==="IN"?"ADJUSTMENT_IN":"ADJUSTMENT_OUT",raw);
export async function transferStock(raw:unknown){const a=await actor(true),d=z.object({sourceWarehouseId:z.string().uuid(),destinationWarehouseId:z.string().uuid(),productId:z.string().uuid(),quantity:qty,unitCost:money,movementDate:z.coerce.date(),batchId:z.string().uuid().optional(),serialNumberId:z.string().uuid().optional(),reason:z.string().trim().min(1)}).parse(raw);if(d.sourceWarehouseId===d.destinationWarehouseId)throw new Error("SAME_WAREHOUSE");return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`${a.companyId}:${d.productId}:${[d.sourceWarehouseId,d.destinationWarehouseId].sort().join(":")}`}))`;const [source,destination,p,settings]=await Promise.all([warehouse(tx,a,d.sourceWarehouseId),warehouse(tx,a,d.destinationWarehouseId),product(tx,a,d.productId),tx.accountSettings.findUnique({where:{companyId:a.companyId!}})]);const q=new D(d.quantity);if(!(settings?.negativeStockAllowed??false)&&(await balance(tx,a.companyId!,source.id,p.id,d.batchId,d.serialNumberId)).lt(q))throw new Error("INSUFFICIENT_STOCK");const transferId=crypto.randomUUID(),unitCost=new D(d.unitCost),base={companyId:a.companyId!,productId:p.id,quantity:q,unitCost,totalCost:q.mul(unitCost).toDecimalPlaces(2),sourceType:"TRANSFER",sourceId:transferId,batchId:d.batchId,serialNumberId:d.serialNumberId,reason:d.reason,movementDate:d.movementDate,createdById:a.id};return Promise.all([tx.stockMovement.create({data:{...base,branchId:source.branchId,warehouseId:source.id,movementType:"TRANSFER_OUT"}}),tx.stockMovement.create({data:{...base,branchId:destination.branchId,warehouseId:destination.id,movementType:"TRANSFER_IN"}})]);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function inventorySnapshot(){const a=await actor(),warehouses=await db.warehouse.findMany({where:{companyId:a.companyId,isActive:true,...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})}}),rows=await db.stockMovement.findMany({where:{companyId:a.companyId,warehouseId:{in:warehouses.map(w=>w.id)}},orderBy:[{movementDate:"asc"},{createdAt:"asc"}]});const grouped=new Map<string,typeof rows>();for(const row of rows){const key=`${row.warehouseId}:${row.productId}`;grouped.set(key,[...(grouped.get(key)??[]),row]);}return [...grouped].map(([key,movements])=>({warehouseId:key.split(":")[0],productId:key.split(":")[1],...stockValuation(movements)}));}
export function itemProfitability(revenue:Prisma.Decimal,cogs:Prisma.Decimal){return {revenue,cogs,profit:revenue.sub(cogs),marginPercent:revenue.isZero()?Z:revenue.sub(cogs).div(revenue).mul(100)};}
