import {AccountModule,BusinessType,ProductEdition,type AccountRole} from "@prisma/client";import {z} from "zod";import {db} from "@/lib/db";import {AuthorizationError,requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";
export type ModuleKey=AccountModule;
export const IMPLEMENTED_ACCOUNT_MODULES=["QUOTATIONS_BOQ","SALES","SALES_ORDER","PROFORMA_INVOICE","DELIVERY_CHALLAN","CREDIT_NOTE","CUSTOMER_RECEIPTS","CUSTOMER_ADVANCES","PAYMENT_REMINDERS","PURCHASES","PURCHASE_ORDER","PURCHASE_BILLS","DEBIT_NOTE","VENDOR_PAYMENTS","VENDOR_ADVANCES","SUBCONTRACTORS","PROJECTS","PROJECT_COSTING","EXPENSES","INVENTORY","BARCODE","ASSETS","GST_ADVANCED"] as const satisfies readonly ModuleKey[];
export const FUTURE_ACCOUNT_MODULES=[] as const satisfies readonly ModuleKey[];
type Entry={name:string;description:string;parent?:ModuleKey;implemented:boolean};const e=(name:string,parent?:ModuleKey):Entry=>({name,description:`${name} workflows.`,parent,implemented:true});
export const ACCOUNT_MODULE_CATALOG:Record<ModuleKey,Entry>={QUOTATIONS_BOQ:e("Quotations / BOQ"),SALES:e("Sales"),SALES_ORDER:e("Sales Orders","SALES"),PROFORMA_INVOICE:e("Proforma Invoices","SALES"),DELIVERY_CHALLAN:e("Delivery Challans","SALES"),CREDIT_NOTE:e("Credit Notes","SALES"),CUSTOMER_RECEIPTS:e("Customer Receipts","SALES"),CUSTOMER_ADVANCES:e("Customer Advances","SALES"),PAYMENT_REMINDERS:e("Payment Reminders","SALES"),PURCHASES:e("Purchases"),PURCHASE_ORDER:e("Purchase Orders","PURCHASES"),PURCHASE_BILLS:e("Purchase Bills","PURCHASES"),DEBIT_NOTE:e("Debit Notes","PURCHASES"),VENDOR_PAYMENTS:e("Vendor Payments","PURCHASES"),VENDOR_ADVANCES:e("Vendor Advances","PURCHASES"),SUBCONTRACTORS:e("Subcontract Purchases","PURCHASES"),PROJECTS:e("Projects"),PROJECT_COSTING:e("Project Costing","PROJECTS"),INVENTORY:e("Inventory"),BARCODE:e("Barcode","INVENTORY"),EXPENSES:e("Expenses"),ASSETS:e("Assets"),GST_ADVANCED:e("Advanced GST")};
export const LEGACY_DEFAULT_ACCOUNT_MODULES=IMPLEMENTED_ACCOUNT_MODULES.filter(x=>x!=="PROJECTS"&&x!=="PROJECT_COSTING"&&x!=="EXPENSES"&&x!=="INVENTORY"&&x!=="BARCODE"&&x!=="ASSETS"&&x!=="GST_ADVANCED");
const common=["SALES","PROFORMA_INVOICE","CREDIT_NOTE","CUSTOMER_RECEIPTS","CUSTOMER_ADVANCES","PAYMENT_REMINDERS","PURCHASES","PURCHASE_BILLS","VENDOR_PAYMENTS"] as ModuleKey[],all=()=>[...IMPLEMENTED_ACCOUNT_MODULES];
export function recommendedModulesForBusinessType(raw:BusinessType|string):ModuleKey[]{const type=z.nativeEnum(BusinessType).parse(raw);if(type==="INTERIOR_CONSTRUCTION")return all().filter(x=>!["INVENTORY","BARCODE","ASSETS","GST_ADVANCED"].includes(x));if(type==="RETAIL_TRADING")return all().filter(x=>x!=="QUOTATIONS_BOQ"&&x!=="SUBCONTRACTORS"&&x!=="PROJECTS"&&x!=="PROJECT_COSTING");if(type==="SERVICE_BUSINESS")return ["QUOTATIONS_BOQ",...common];if(type==="MANUFACTURING")return all().filter(x=>x!=="SUBCONTRACTORS"&&x!=="PROJECTS"&&x!=="PROJECT_COSTING");return [...common,"SALES_ORDER","DELIVERY_CHALLAN","PURCHASE_ORDER","DEBIT_NOTE","VENDOR_ADVANCES"]}
export function validateEnabledModules(raw:unknown):ModuleKey[]{const selected=[...new Set(z.array(z.nativeEnum(AccountModule)).parse(raw))],future=selected.find(x=>!ACCOUNT_MODULE_CATALOG[x].implemented);if(future)throw new Error(`MODULE_NOT_AVAILABLE:${future}`);for(const key of selected){const parent=ACCOUNT_MODULE_CATALOG[key].parent;if(parent&&!selected.includes(parent))throw new Error(`MODULE_DEPENDENCY_REQUIRED:${key}:${parent}`)}return IMPLEMENTED_ACCOUNT_MODULES.filter(x=>selected.includes(x))}
export const editionHasAccount=(x:ProductEdition)=>x==="SALESPUNCH360_ACCOUNT"||x==="SALESPUNCH360_PLUS";
export async function enabledModulesForCompany(companyId:string){const company=await db.company.findUnique({where:{id:companyId},select:{productEdition:true,accountSettings:{select:{enabledModules:true}}}});if(!company||!editionHasAccount(company.productEdition))return [];return company.accountSettings?company.accountSettings.enabledModules:[...LEGACY_DEFAULT_ACCOUNT_MODULES]}
export async function requireAccountModules(actor:{companyId:string|null},...keys:ModuleKey[]){if(!actor.companyId)throw new AuthorizationError();const enabled=await enabledModulesForCompany(actor.companyId);for(const key of keys)if(!enabled.includes(key))throw new Error(`MODULE_DISABLED:${key}`)}
export async function getModuleSettings(){const a=await requirePermission("ACCOUNT_SETTINGS"),settings=await db.accountSettings.findUnique({where:{companyId:a.companyId!}});return{businessType:settings?.businessType??BusinessType.OTHER_MIXED,enabledModules:await enabledModulesForCompany(a.companyId!),catalog:IMPLEMENTED_ACCOUNT_MODULES.map(key=>({key,...ACCOUNT_MODULE_CATALOG[key]}))}}
export async function updateModuleSettings(raw:unknown){const a=await requirePermissionForMutation("ACCOUNT_SETTINGS");if(a.accountRole!=="ACCOUNT_ADMIN")throw new AuthorizationError();const d=z.object({businessType:z.nativeEnum(BusinessType),enabledModules:z.array(z.nativeEnum(AccountModule))}).strict().parse(raw),enabledModules=validateEnabledModules(d.enabledModules);return db.accountSettings.upsert({where:{companyId:a.companyId!},create:{companyId:a.companyId!,businessType:d.businessType,enabledModules},update:{businessType:d.businessType,enabledModules}})}
export const canAdministerModules=(role:AccountRole|null)=>role==="ACCOUNT_ADMIN";
