import {Prisma} from "@prisma/client";
export type OpeningParty="CUSTOMER"|"VENDOR";
const D=Prisma.Decimal;
export function openingOutstanding(amount:Prisma.Decimal.Value,allocations:Prisma.Decimal.Value[]){const remaining=allocations.reduce<Prisma.Decimal>((n,x)=>n.sub(x),new D(amount));if(remaining.lt(0))throw new Error("OPENING_ALLOCATION_EXCEEDS_OUTSTANDING");return remaining}
export function assertOpeningAllocation(target:{companyId:string;branchId:string;partyType:OpeningParty;partyId:string;amount:Prisma.Decimal.Value},request:{companyId:string;branchId:string;partyType:OpeningParty;partyId:string;amount:Prisma.Decimal.Value},already:Prisma.Decimal.Value[]){if(target.companyId!==request.companyId)throw new Error("INVALID_OPENING_TENANT");if(target.branchId!==request.branchId)throw new Error("INVALID_OPENING_BRANCH");if(target.partyType!==request.partyType||target.partyId!==request.partyId)throw new Error("INVALID_OPENING_PARTY");const amount=new D(request.amount);if(amount.lte(0)||amount.gt(openingOutstanding(target.amount,already)))throw new Error("OPENING_ALLOCATION_EXCEEDS_OUTSTANDING")}
export function openingAgeDays(effectiveDate:Date,asOf:Date){return Math.max(0,Math.floor((Date.UTC(asOf.getUTCFullYear(),asOf.getUTCMonth(),asOf.getUTCDate())-Date.UTC(effectiveDate.getUTCFullYear(),effectiveDate.getUTCMonth(),effectiveDate.getUTCDate()))/86400000))}

import {z} from "zod";import{db}from"@/lib/db";import{AuthorizationError,requirePermissionForMutation}from"@/lib/auth/authorization";
const registration=z.object({branchId:z.string().uuid(),partyType:z.enum(["CUSTOMER","VENDOR"]),partyId:z.string().uuid(),journalEntryId:z.string().uuid()}).strict();
export async function openingRegistrationOptions(){const actor=await requirePermissionForMutation("ACCOUNT_OPENING_BALANCE");if(actor.accountRole!=="ACCOUNT_ADMIN"&&actor.accountRole!=="ACCOUNTANT")throw new AuthorizationError();const branchIds=actor.branchAccessScope==="SELECTED_BRANCHES"?actor.branchIds??[]:undefined;const [branches,customers,vendors,journals]=await Promise.all([db.branch.findMany({where:{companyId:actor.companyId!,isActive:true,...(branchIds?{id:{in:branchIds}}:{})},select:{id:true,name:true},orderBy:{name:"asc"}}),db.customer.findMany({where:{companyId:actor.companyId!,isActive:true,isAccountCustomer:true,...(branchIds?{branchId:{in:branchIds}}:{})},select:{id:true,name:true,branchId:true},orderBy:{name:"asc"}}),db.vendor.findMany({where:{companyId:actor.companyId!,isActive:true},select:{id:true,name:true},orderBy:{name:"asc"}}),db.journalEntry.findMany({where:{companyId:actor.companyId!,status:"POSTED",sourceType:"OPENING_BALANCE",...(branchIds?{branchId:{in:branchIds}}:{})},select:{id:true,journalNumber:true,entryDate:true,branchId:true},orderBy:{entryDate:"desc"}})]);return{branches,customers,vendors,journals}}

/** Registers an already-posted opening journal as a settleable party target; it never posts accounting. */
export async function registerPartyOpeningBalance(raw:unknown){const actor=await requirePermissionForMutation("ACCOUNT_OPENING_BALANCE");if(actor.accountRole!=="ACCOUNT_ADMIN"&&actor.accountRole!=="ACCOUNTANT")throw new AuthorizationError();const input=registration.parse(raw);if(actor.branchAccessScope==="SELECTED_BRANCHES"&&!actor.branchIds?.includes(input.branchId))throw new AuthorizationError();return db.$transaction(async tx=>{const party=input.partyType==="CUSTOMER"?await tx.customer.findFirst({where:{id:input.partyId,companyId:actor.companyId!,branchId:input.branchId,isAccountCustomer:true}}):await tx.vendor.findFirst({where:{id:input.partyId,companyId:actor.companyId!,isActive:true}});if(!party)throw new Error("INVALID_OPENING_PARTY");await tx.$queryRaw`SELECT "id" FROM "journal_entries" WHERE "id"=${input.journalEntryId}::uuid AND "companyId"=${actor.companyId!}::uuid FOR UPDATE`;const journal=await tx.journalEntry.findFirst({where:{id:input.journalEntryId,companyId:actor.companyId!,branchId:input.branchId,status:"POSTED",sourceType:"OPENING_BALANCE"},include:{lines:{include:{ledgerAccount:true}}}});if(!journal)throw new Error("INVALID_OPENING_JOURNAL");const registered=await tx.partyOpeningBalance.findFirst({where:{companyId:actor.companyId!,journalEntryId:journal.id,partyType:input.partyType}});if(registered){if(registered.partyId===party.id)return registered;throw new Error("OPENING_JOURNAL_SIDE_ALREADY_REGISTERED")}const key=input.partyType==="CUSTOMER"?"ACCOUNTS_RECEIVABLE":"ACCOUNTS_PAYABLE",line=journal.lines.find(x=>x.ledgerAccount.systemKey===key),amount=input.partyType==="CUSTOMER"?line?.debit:line?.credit;if(!amount||amount.lte(0))throw new Error("OPENING_PARTY_LINE_REQUIRED");return tx.partyOpeningBalance.create({data:{companyId:actor.companyId!,branchId:input.branchId,partyType:input.partyType,partyId:party.id,partyName:party.name,effectiveDate:journal.entryDate,amount,journalEntryId:journal.id,createdById:actor.id}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function listOpeningOutstandings(input:{companyId:string;partyType:OpeningParty;partyId?:string;branchIds?:string[];asOf?:Date}){const rows=await db.partyOpeningBalance.findMany({where:{companyId:input.companyId,partyType:input.partyType,...(input.partyId?{partyId:input.partyId}:{}),...(input.branchIds?{branchId:{in:input.branchIds}}:{}),...(input.asOf?{effectiveDate:{lte:input.asOf}}:{})},orderBy:{effectiveDate:"asc"}});if(!rows.length)return[];const allocated=await db.openingBalanceAllocation.groupBy({by:["openingBalanceId"],where:{companyId:input.companyId,openingBalanceId:{in:rows.map(x=>x.id)}},_sum:{amount:true}}),byId=new Map(allocated.map(x=>[x.openingBalanceId,x._sum.amount??new D(0)]));return rows.map(row=>({...row,outstanding:openingOutstanding(row.amount,[byId.get(row.id)??0])})).filter(row=>row.outstanding.gt(0))}
