import {Prisma} from "@prisma/client";
export type OpeningParty="CUSTOMER"|"VENDOR";
const D=Prisma.Decimal;
export function openingOutstanding(amount:Prisma.Decimal.Value,allocations:Prisma.Decimal.Value[]){const remaining=allocations.reduce<Prisma.Decimal>((n,x)=>n.sub(x),new D(amount));if(remaining.lt(0))throw new Error("OPENING_ALLOCATION_EXCEEDS_OUTSTANDING");return remaining}
export function assertOpeningAllocation(target:{companyId:string;branchId:string;partyType:OpeningParty;partyId:string;amount:Prisma.Decimal.Value},request:{companyId:string;branchId:string;partyType:OpeningParty;partyId:string;amount:Prisma.Decimal.Value},already:Prisma.Decimal.Value[]){if(target.companyId!==request.companyId)throw new Error("INVALID_OPENING_TENANT");if(target.branchId!==request.branchId)throw new Error("INVALID_OPENING_BRANCH");if(target.partyType!==request.partyType||target.partyId!==request.partyId)throw new Error("INVALID_OPENING_PARTY");const amount=new D(request.amount);if(amount.lte(0)||amount.gt(openingOutstanding(target.amount,already)))throw new Error("OPENING_ALLOCATION_EXCEEDS_OUTSTANDING")}
export function openingAgeDays(effectiveDate:Date,asOf:Date){return Math.max(0,Math.floor((Date.UTC(asOf.getUTCFullYear(),asOf.getUTCMonth(),asOf.getUTCDate())-Date.UTC(effectiveDate.getUTCFullYear(),effectiveDate.getUTCMonth(),effectiveDate.getUTCDate()))/86400000))}

import {z} from "zod";import{db}from"@/lib/db";import{AuthorizationError,requirePermissionForMutation}from"@/lib/auth/authorization";
const registration=z.object({branchId:z.string().uuid(),partyType:z.enum(["CUSTOMER","VENDOR"]),partyId:z.string().uuid(),journalEntryId:z.string().uuid()}).strict();
/** Registers an already-posted opening journal as a settleable party target; it never posts accounting. */
export async function registerPartyOpeningBalance(raw:unknown){const actor=await requirePermissionForMutation("ACCOUNT_OPENING_BALANCE");if(actor.accountRole!=="ACCOUNT_ADMIN"&&actor.accountRole!=="ACCOUNTANT")throw new AuthorizationError();const input=registration.parse(raw);if(actor.branchAccessScope==="SELECTED_BRANCHES"&&!actor.branchIds?.includes(input.branchId))throw new AuthorizationError();return db.$transaction(async tx=>{const party=input.partyType==="CUSTOMER"?await tx.customer.findFirst({where:{id:input.partyId,companyId:actor.companyId!,branchId:input.branchId,isAccountCustomer:true}}):await tx.vendor.findFirst({where:{id:input.partyId,companyId:actor.companyId!}});if(!party)throw new Error("INVALID_OPENING_PARTY");const journal=await tx.journalEntry.findFirst({where:{id:input.journalEntryId,companyId:actor.companyId!,branchId:input.branchId,status:"POSTED",sourceType:"OPENING_BALANCE"},include:{lines:{include:{ledgerAccount:true}}}});if(!journal)throw new Error("INVALID_OPENING_JOURNAL");const key=input.partyType==="CUSTOMER"?"ACCOUNTS_RECEIVABLE":"ACCOUNTS_PAYABLE",line=journal.lines.find(x=>x.ledgerAccount.systemKey===key),amount=input.partyType==="CUSTOMER"?line?.debit:line?.credit;if(!amount||amount.lte(0))throw new Error("OPENING_PARTY_LINE_REQUIRED");return tx.partyOpeningBalance.upsert({where:{companyId_journalEntryId_partyType_partyId:{companyId:actor.companyId!,journalEntryId:journal.id,partyType:input.partyType,partyId:party.id}},create:{companyId:actor.companyId!,branchId:input.branchId,partyType:input.partyType,partyId:party.id,partyName:party.name,effectiveDate:journal.entryDate,amount,journalEntryId:journal.id,createdById:actor.id},update:{}})})}
