import {Prisma} from "@prisma/client";
import {z} from "zod";
import {db} from "@/lib/db";
import {AuthorizationError,requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";

export const partySettingsSchema=z.object({gstinEnabled:z.boolean(),groupingEnabled:z.boolean(),shippingAddressEnabled:z.boolean(),printShippingAddress:z.boolean()}).strict();
export type PartySettings=z.infer<typeof partySettingsSchema>;
export const DEFAULT_PARTY_SETTINGS:PartySettings={gstinEnabled:true,groupingEnabled:false,shippingAddressEnabled:true,printShippingAddress:false};
export function resolvePartySettings(raw:unknown):PartySettings{const root=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,candidate=root.partySettings;const parsed=partySettingsSchema.safeParse(candidate);return parsed.success?parsed.data:DEFAULT_PARTY_SETTINGS}
export async function getPartySettings(){const actor=await requirePermission("ACCOUNT_SETTINGS"),row=await db.accountSettings.findUnique({where:{companyId:actor.companyId!},select:{transactionDefaults:true}});return resolvePartySettings(row?.transactionDefaults)}
export async function updatePartySettings(raw:unknown){const actor=await requirePermissionForMutation("ACCOUNT_SETTINGS");if(actor.accountRole!=="ACCOUNT_ADMIN")throw new AuthorizationError();const input=partySettingsSchema.parse(raw),current=await db.accountSettings.findUnique({where:{companyId:actor.companyId!},select:{transactionDefaults:true}}),transactionDefaults={...((current?.transactionDefaults as Record<string,unknown>|null)??{}),partySettings:input} as Prisma.InputJsonValue;return db.$transaction(async tx=>{const row=await tx.accountSettings.upsert({where:{companyId:actor.companyId!},create:{companyId:actor.companyId!,transactionDefaults},update:{transactionDefaults}});for(const entityType of ["CUSTOMER","VENDOR"] as const)await tx.customFieldDefinition.upsert({where:{companyId_entityType_fieldKey:{companyId:actor.companyId!,entityType,fieldKey:"party_group"}},create:{companyId:actor.companyId!,entityType,fieldKey:"party_group",label:"Party Group",dataType:"TEXT",isRequired:false,isActive:input.groupingEnabled,position:20},update:{isActive:input.groupingEnabled}});await tx.accountingAuditEvent.create({data:{companyId:actor.companyId!,actorUserId:actor.id,eventType:"SETTINGS_CHANGED",entityType:"ACCOUNT_SETTINGS",entityId:actor.companyId!,metadata:{sections:["PARTY_SETTINGS"]}}});return row})}

export const PARTY_FIELD_SLOTS=["party_additional_1","party_additional_2","party_additional_3","party_date"] as const;
const additionalFieldSchema=z.object({key:z.enum(PARTY_FIELD_SLOTS),enabled:z.boolean(),label:z.string().trim().min(1).max(100),showInPrint:z.boolean(),dateFormat:z.enum(["DD/MM/YYYY"]).optional()}).strict();
export type PartyAdditionalField=z.infer<typeof additionalFieldSchema>;
export async function getPartyAdditionalFields(){const actor=await requirePermission("ACCOUNT_SETTINGS"),rows=await db.customFieldDefinition.findMany({where:{companyId:actor.companyId!,entityType:"CUSTOMER",fieldKey:{in:[...PARTY_FIELD_SLOTS]}},orderBy:{position:"asc"}});return PARTY_FIELD_SLOTS.map((key,index)=>{const row=rows.find(x=>x.fieldKey===key),meta=(row?.validation as {showInPrint?:boolean;dateFormat?:string}|null)??{};return{key,enabled:row?.isActive??false,label:row?.label??(key==="party_date"?"Date Field":`Additional Field ${index+1}`),showInPrint:meta.showInPrint??false,...(key==="party_date"?{dateFormat:"DD/MM/YYYY" as const}:{})}})}
export async function savePartyAdditionalFields(raw:unknown){const actor=await requirePermissionForMutation("ACCOUNT_SETTINGS");if(actor.accountRole!=="ACCOUNT_ADMIN")throw new AuthorizationError();const input=z.array(additionalFieldSchema).length(4).parse(raw);if(new Set(input.map(x=>x.key)).size!==4)throw new Error("PARTY_FIELD_SLOT_DUPLICATE");return db.$transaction(async tx=>{for(const entityType of ["CUSTOMER","VENDOR"] as const)for(const [position,field] of input.entries()){const data={label:field.label,dataType:field.key==="party_date"?"DATE" as const:"TEXT" as const,isRequired:false,isActive:field.enabled,position,validation:{showInPrint:field.showInPrint,...field.dateFormat?{dateFormat:field.dateFormat}:{}}};await tx.customFieldDefinition.upsert({where:{companyId_entityType_fieldKey:{companyId:actor.companyId!,entityType,fieldKey:field.key}},create:{companyId:actor.companyId!,entityType,fieldKey:field.key,...data},update:data})}await tx.accountingAuditEvent.create({data:{companyId:actor.companyId!,actorUserId:actor.id,eventType:"SETTINGS_CHANGED",entityType:"CUSTOM_FIELD",entityId:actor.companyId!,metadata:{sections:["PARTY_ADDITIONAL_FIELDS"]}}});return input})}
