import{describe,expect,it,vi}from"vitest";import{Prisma}from"@prisma/client";import{postProjectPurchaseMaterialsInTx}from"./commercial";
const D=(x:string)=>new Prisma.Decimal(x),actor={id:"actor",companyId:"company"} as never;
function document(project=true,product=true){return{id:"bill",type:"PURCHASE_BILL",purchasePurpose:project?"PROJECT":"INVENTORY_SALES",branchId:"branch",issueDate:new Date("2026-10-01"),taxCreditTreatment:"ELIGIBLE",lines:[{id:"line",productId:product?"product":null,warehouseId:"warehouse",batchId:"batch",serialNumberId:null,purchaseAllocations:[{id:"allocation",allocationType:"PROJECT",projectId:"project-a",projectBudgetLineId:"budget",quantity:D("10"),taxableAmount:D("5000"),taxAmount:D("900")}]}]} as never}
function transaction(){const stock=vi.fn().mockResolvedValue({}),project=vi.fn().mockResolvedValue({id:"project-movement"});return{tx:{$queryRaw:vi.fn(),accountProduct:{findFirst:vi.fn().mockResolvedValue({id:"product"})},warehouse:{findFirst:vi.fn().mockResolvedValue({id:"warehouse"})},inventoryBatch:{findFirst:vi.fn().mockResolvedValue({id:"batch"})},inventorySerialNumber:{findFirst:vi.fn()},stockMovement:{create:stock,aggregate:vi.fn().mockResolvedValue({_sum:{quantity:0}})},projectMaterialMovement:{create:project}},stock,project}}
describe("Project Purchase Inventory receipt and automatic Project issue",()=>{
 it("does not create Project material for a regular purchase",async()=>{const x=transaction();await expect(postProjectPurchaseMaterialsInTx(x.tx as never,actor,document(false))).resolves.toEqual([]);expect(x.stock).not.toHaveBeenCalled();expect(x.project).not.toHaveBeenCalled()});
 it("posts equal physical receipt and issue with purchase lineage",async()=>{const x=transaction();await postProjectPurchaseMaterialsInTx(x.tx as never,actor,document());expect(x.stock).toHaveBeenCalledTimes(2);const receipt=x.stock.mock.calls[0][0].data,issue=x.stock.mock.calls[1][0].data,movement=x.project.mock.calls[0][0].data;expect([receipt.movementType,issue.movementType]).toEqual(["PURCHASE","TRANSFER_OUT"]);expect(receipt.quantity.toString()).toBe("10");expect(receipt.totalCost.toString()).toBe("5000");expect(issue.totalCost.toString()).toBe("5000");expect(movement.originalUnitCost.toString()).toBe("500");expect(movement.totalCost.toString()).toBe("5000");expect(movement).toMatchObject({projectId:"project-a",purchaseDocumentId:"bill",purchaseLineId:"line",purchaseAllocationId:"allocation",warehouseId:"warehouse",batchId:"batch"});expect(issue.sourceId).toBe("project-movement")});
 it("does not invent stock for a non-stock Project service",async()=>{const x=transaction();await expect(postProjectPurchaseMaterialsInTx(x.tx as never,actor,document(true,false))).resolves.toEqual([]);expect(x.stock).not.toHaveBeenCalled();expect(x.project).not.toHaveBeenCalled()});
});
