import {Prisma,ProjectChangeOrderStatus} from "@prisma/client";
import {z} from "zod";
import {db} from "@/lib/db";
import {AuthorizationError,requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";
import {requireAccountModules} from "./modules";
import {authorizedProjectBranchIds,projectRecordScope,type ProjectActor} from "./projects";
import {allocateDocumentNumberInTx} from "./numbering";
const D=Prisma.Decimal,Z=new D(0),sum=(xs:Prisma.Decimal[])=>xs.reduce((a,b)=>a.add(b),Z);
export type CostDocument={id?:string;type:string;status:string;grandTotal:Prisma.Decimal;sourcePurchaseOrderId?:string|null};
export function projectCosting(input:{originalValue:Prisma.Decimal;estimatedCost:Prisma.Decimal;budget:Prisma.Decimal;documents:CostDocument[];expenses?:Prisma.Decimal[];approvedChanges?:Array<{valueDelta:Prisma.Decimal;estimatedCostDelta:Prisma.Decimal}>;closed?:boolean}){const changes=input.approvedChanges??[],currentValue=input.originalValue.add(sum(changes.map(x=>x.valueDelta))),estimated=input.estimatedCost.add(sum(changes.map(x=>x.estimatedCostDelta))),actualPurchases=sum(input.documents.filter(x=>x.status==="POSTED"&&(x.type==="PURCHASE_BILL"||x.type==="SUBCONTRACT_PURCHASE")).map(x=>x.grandTotal)).sub(sum(input.documents.filter(x=>x.status==="POSTED"&&x.type==="DEBIT_NOTE").map(x=>x.grandTotal))),actualCost=actualPurchases.add(sum(input.expenses??[])),billed=new Map<string,Prisma.Decimal>();for(const bill of input.documents.filter(x=>x.status==="POSTED"&&x.type==="PURCHASE_BILL"&&x.sourcePurchaseOrderId))billed.set(bill.sourcePurchaseOrderId!,(billed.get(bill.sourcePurchaseOrderId!)??Z).add(bill.grandTotal));const committed=sum(input.documents.filter(x=>x.status!=="CANCELLED"&&x.type==="PURCHASE_ORDER").map(po=>Prisma.Decimal.max(Z,po.grandTotal.sub(billed.get(po.id??"")??Z)))),revenue=sum(input.documents.filter(x=>x.status==="POSTED"&&x.type==="SALES_INVOICE").map(x=>x.grandTotal)).sub(sum(input.documents.filter(x=>x.status==="POSTED"&&x.type==="CREDIT_NOTE").map(x=>x.grandTotal))),remainingPlan=Prisma.Decimal.max(Z,estimated.sub(actualCost).sub(committed)),forecastCost=actualCost.add(committed).add(remainingPlan),expectedProfit=currentValue.sub(estimated),forecastProfit=currentValue.sub(forecastCost),profit=revenue.sub(actualCost),margin=(value:Prisma.Decimal,base:Prisma.Decimal)=>base.isZero()?Z:value.div(base).mul(100);return{originalValue:input.originalValue,currentValue,estimatedCost:estimated,actualCost,committedCost:committed,remainingForecast:forecastCost.sub(actualCost),forecastCost,budgetVariance:input.budget.sub(actualCost),revenue,profit,expectedProfit,forecastProfit,finalProfit:input.closed?profit:null,expectedMarginPercent:margin(expectedProfit,currentValue),forecastMarginPercent:margin(forecastProfit,currentValue),actualMarginPercent:margin(profit,revenue)}}
type Actor=ProjectActor;
async function costingActor(edit=false){const actor=(edit?await requirePermissionForMutation("ACCOUNT_PROJECT_COST_EDIT"):await requirePermission("ACCOUNT_PROJECT_COST_VIEW")) as Actor;await requireAccountModules(actor,"PROJECTS","PROJECT_COSTING");return actor}
async function scopedProject(actor:Actor,id:string){const branches=await authorizedProjectBranchIds(actor),project=await db.project.findFirst({where:{id,...projectRecordScope(actor,branches)},include:{budgetLines:true,commercialDocuments:{include:{lines:true}},customer:true}});if(!project)throw new AuthorizationError();return project}
export function packageProfitability(documents:Array<{type:string;status:string;lines:Array<{workPackageId:string|null;lineTotal:Prisma.Decimal}>}>,estimate:Array<{workPackageId:string|null;lineTotal:Prisma.Decimal;internalCostTotal:Prisma.Decimal}>,names:Map<string,string>){const keys=new Set<string|null>([null,...estimate.map(x=>x.workPackageId),...documents.flatMap(x=>x.lines.map(l=>l.workPackageId))]);return [...keys].map(id=>{const estimatedRevenue=sum(estimate.filter(x=>x.workPackageId===id).map(x=>x.lineTotal)),estimatedCost=sum(estimate.filter(x=>x.workPackageId===id).map(x=>x.internalCostTotal)),actualRevenue=sum(documents.filter(x=>x.status==="POSTED"&&x.type==="SALES_INVOICE").flatMap(x=>x.lines.filter(l=>l.workPackageId===id).map(l=>l.lineTotal))).sub(sum(documents.filter(x=>x.status==="POSTED"&&x.type==="CREDIT_NOTE").flatMap(x=>x.lines.filter(l=>l.workPackageId===id).map(l=>l.lineTotal)))),actualCost=sum(documents.filter(x=>x.status==="POSTED"&&["PURCHASE_BILL","SUBCONTRACT_PURCHASE"].includes(x.type)).flatMap(x=>x.lines.filter(l=>l.workPackageId===id).map(l=>l.lineTotal))).sub(sum(documents.filter(x=>x.status==="POSTED"&&x.type==="DEBIT_NOTE").flatMap(x=>x.lines.filter(l=>l.workPackageId===id).map(l=>l.lineTotal)))),profit=actualRevenue.sub(actualCost);return{id,name:id?names.get(id)??"Unknown":"Other / Unassigned",estimatedRevenue,estimatedCost,actualRevenue,actualCost,profit,marginPercent:actualRevenue.isZero()?Z:profit.div(actualRevenue).mul(100)}})}
export async function loadProjectCosting(projectId:string){const actor=await costingActor(),project=await scopedProject(actor,projectId),quotation=project.sourceQuotationId?await db.quotationDocument.findFirst({where:{id:project.sourceQuotationId,companyId:actor.companyId,status:"ACCEPTED"},include:{revisions:{where:{status:"ACCEPTED"},orderBy:{revisionNumber:"desc"},take:1,include:{lines:true}}}}):null,changes=await db.projectChangeOrder.findMany({where:{companyId:actor.companyId,projectId},orderBy:{createdAt:"desc"}}),expenses=await db.expenseTransaction.findMany({where:{companyId:actor.companyId,projectId,status:"POSTED",type:{in:["PROJECT_EXPENSE","REIMBURSEMENT"]}}}),budget=sum(project.budgetLines.map(x=>x.amount)),estimate=quotation?.revisions[0]?.internalCostTotal??budget,metrics=projectCosting({originalValue:project.projectValue,estimatedCost:estimate,budget,documents:project.commercialDocuments,expenses:expenses.map(x=>x.taxableAmount),approvedChanges:changes.filter(x=>x.status==="APPROVED"),closed:project.status==="CLOSED"}),workIds=[...new Set([...quotation?.revisions[0]?.lines.map(x=>x.workPackageId)??[],...project.commercialDocuments.flatMap(x=>x.lines.map(l=>l.workPackageId))].filter(Boolean))] as string[],works=await db.workPackage.findMany({where:{companyId:actor.companyId,id:{in:workIds}}});return{project,changes,metrics,packages:packageProfitability(project.commercialDocuments,quotation?.revisions[0]?.lines??[],new Map(works.map(x=>[x.id,x.name]))),estimateSource:quotation?"ACCEPTED_QUOTATION":"PROJECT_BUDGET"}}
const changeInput=z.object({projectId:z.string().uuid(),title:z.string().trim().min(1).max(240),description:z.string().trim().max(5000).optional(),valueDelta:z.string(),estimatedCostDelta:z.string()}).strict();
export async function createChangeOrder(raw:unknown){const actor=await costingActor(true),data=changeInput.parse(raw),project=await scopedProject(actor,data.projectId);return db.$transaction(async tx=>{const changeOrderNumber=await allocateDocumentNumberInTx(tx,{companyId:actor.companyId,branchId:project.branchId,seriesKey:"PROJECT_CHANGE_ORDER",defaults:{prefix:"CO-",padding:6}}),row=await tx.projectChangeOrder.create({data:{companyId:actor.companyId,projectId:project.id,changeOrderNumber,title:data.title,description:data.description,valueDelta:new D(data.valueDelta),estimatedCostDelta:new D(data.estimatedCostDelta),createdById:actor.id}});await tx.projectAuditEvent.create({data:{companyId:actor.companyId,projectId:project.id,actorUserId:actor.id,eventType:"CHANGE_ORDER_CREATED",metadata:{changeOrderId:row.id}}});return row},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function updateChangeOrder(raw:unknown){const actor=await costingActor(true),data=changeInput.extend({changeOrderId:z.string().uuid()}).parse(raw);await scopedProject(actor,data.projectId);const changed=await db.projectChangeOrder.updateMany({where:{id:data.changeOrderId,companyId:actor.companyId,projectId:data.projectId,status:"DRAFT"},data:{title:data.title,description:data.description,valueDelta:new D(data.valueDelta),estimatedCostDelta:new D(data.estimatedCostDelta)}});if(changed.count!==1)throw new Error("CHANGE_ORDER_NOT_EDITABLE")}
export async function transitionChangeOrder(projectId:string,changeOrderId:string,to:ProjectChangeOrderStatus){const actor=await costingActor(true);await scopedProject(actor,projectId);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "project_change_orders" WHERE "id"=${changeOrderId}::uuid AND "companyId"=${actor.companyId}::uuid FOR UPDATE`;const row=await tx.projectChangeOrder.findFirst({where:{id:changeOrderId,companyId:actor.companyId,projectId}});if(!row)throw new AuthorizationError();const allowed:Record<ProjectChangeOrderStatus,ProjectChangeOrderStatus[]>={DRAFT:["PENDING_APPROVAL","CANCELLED"],PENDING_APPROVAL:["APPROVED","REJECTED","CANCELLED"],APPROVED:[],REJECTED:[],CANCELLED:[]};if(!allowed[row.status].includes(to))throw new Error("INVALID_CHANGE_ORDER_TRANSITION");if(["APPROVED","REJECTED"].includes(to)){if(actor.accountRole!=="ACCOUNT_ADMIN")throw new AuthorizationError();if(row.createdById===actor.id)throw new Error("CHANGE_ORDER_SELF_APPROVAL_FORBIDDEN")}const updated=await tx.projectChangeOrder.update({where:{id:row.id},data:{status:to,...(to==="APPROVED"?{approvedAt:new Date(),approvedById:actor.id}:{})}});await tx.projectAuditEvent.create({data:{companyId:actor.companyId,projectId,actorUserId:actor.id,eventType:({PENDING_APPROVAL:"CHANGE_ORDER_SUBMITTED",APPROVED:"CHANGE_ORDER_APPROVED",REJECTED:"CHANGE_ORDER_REJECTED",CANCELLED:"CHANGE_ORDER_CANCELLED"} as const)[to as "PENDING_APPROVAL"|"APPROVED"|"REJECTED"|"CANCELLED"],metadata:{changeOrderId}}});return updated},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
