import{Prisma}from"@prisma/client";import{beforeEach,describe,expect,it,vi}from"vitest";
const m=vi.hoisted(()=>({project:vi.fn(),taskCount:vi.fn(),allocation:vi.fn(),advance:vi.fn()}));
vi.mock("@/lib/auth/authorization",()=>({AuthorizationError:class extends Error{},requirePermission:vi.fn(async()=>({id:"pm",name:"PM",companyId:"company",accountRole:"PROJECT_MANAGER",branchAccessScope:"ALL_BRANCHES",branchIds:["branch-a"]})),requirePermissionForMutation:vi.fn()}));
vi.mock("@/lib/db",()=>({db:{branch:{findMany:vi.fn(async()=>[{id:"branch-a"}])},project:{findFirst:m.project},projectTask:{count:m.taskCount},settlementAllocation:{aggregate:m.allocation},advanceApplication:{aggregate:m.advance}}}));
import{getProject,projectCustomerWhere,projectHistoryInput,PROJECT_MAX_PAGE_SIZE}from"./projects";
const D=(value:number)=>new Prisma.Decimal(value);
describe("bounded authoritative Project detail",()=>{beforeEach(()=>{vi.clearAllMocks();m.project.mockResolvedValue({id:"project",branchId:"branch-a",budgetLines:[],tasks:Array.from({length:25},(_,i)=>({id:`task-${i}`})),documents:[],quotationDocuments:[],commercialDocuments:[],audits:[],_count:{tasks:75,documents:51,quotationDocuments:1,commercialDocuments:80,audits:60}});m.taskCount.mockResolvedValue(75);m.allocation.mockResolvedValueOnce({_sum:{amount:D(100)}}).mockResolvedValueOnce({_sum:{amount:D(40)}});m.advance.mockResolvedValueOnce({_sum:{amount:D(25)}}).mockResolvedValueOnce({_sum:{amount:D(10)}})});it("reports all 75 open tasks independently of the 25-row task page",async()=>{const result=await getProject("project");expect(result.tasks).toHaveLength(25);expect(result.openTasks).toBe(75);expect(result.history.pages.tasks).toBe(3);expect(m.taskCount).toHaveBeenCalledWith({where:{companyId:"company",projectId:"project",status:{notIn:["COMPLETED","CANCELLED"]}}})});it("bounds every history and preserves Project Manager and branch scope",async()=>{await getProject("project",{tasksPage:"2",documentsPage:"2",commercialPage:"3",auditsPage:"2"});expect(m.project).toHaveBeenCalledWith(expect.objectContaining({where:{id:"project",companyId:"company",branchId:{in:["branch-a"]},OR:[{projectManagerId:"pm"},{members:{some:{userId:"pm"}}}]},include:expect.objectContaining({tasks:expect.objectContaining({skip:25,take:25}),documents:expect.objectContaining({skip:25,take:25}),commercialDocuments:expect.objectContaining({skip:50,take:25}),audits:expect.objectContaining({skip:25,take:25})})}))});it("calculates payment totals over full-history aggregate queries",async()=>{const result=await getProject("project");expect(result.customerPayments.toString()).toBe("125");expect(result.vendorPayments.toString()).toBe("50");expect(m.allocation).toHaveBeenCalledTimes(2);expect(m.advance).toHaveBeenCalledTimes(2)});it("clamps history page-size abuse",()=>expect(projectHistoryInput({pageSize:"10000"}).pageSize).toBe(PROJECT_MAX_PAGE_SIZE))});

describe("Project Customer branch boundary",()=>{it("requires the authenticated company and selected Project branch",()=>expect(projectCustomerWhere("company-a","branch-a","customer-a")).toEqual({id:"customer-a",companyId:"company-a",branchId:"branch-a",isActive:true,isAccountCustomer:true}))});
