import { Prisma, CustomFieldDataType, CustomFieldEntity, PrintPaperSize } from "@prisma/client";
import { z } from "zod";
import { db } from "@/lib/db";
import { AuthorizationError, requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";

const defaultsSchema = z.object({ defaultDueDays: z.coerce.number().int().min(0).max(365).optional(), salesTerms: z.string().max(10000).optional(), purchaseTerms: z.string().max(10000).optional(), projectTerms: z.string().max(10000).optional() }).strict();
const printProfileSchema = z.object({ displayName: z.string().max(160).optional(), bankName: z.string().max(120).optional(), accountName: z.string().max(120).optional(), accountNumber: z.string().regex(/^[0-9Xx* -]{4,30}$/).optional(), ifsc: z.string().regex(/^[A-Z]{4}0[A-Z0-9]{6}$/).optional(), upiId: z.string().regex(/^[\w.\-]{2,256}@[A-Za-z]{2,64}$/).optional(), upiPayeeName: z.string().max(120).optional(), authorizedSignatory: z.string().max(120).optional() }).strict();

export async function getAccountSettings() { const actor = await requirePermission("ACCOUNT_SETTINGS"); return db.accountSettings.findUnique({ where: { companyId: actor.companyId! } }); }
export async function updateAccountSettings(raw: unknown) { const actor = await requirePermissionForMutation("ACCOUNT_SETTINGS"); if (actor.accountRole !== "ACCOUNT_ADMIN") throw new AuthorizationError(); const input = z.object({ expenseApprovalRequired: z.boolean(), expenseApprovalThreshold: z.string(), negativeStockAllowed: z.boolean(), transactionDefaults: defaultsSchema, printProfile: printProfileSchema }).strict().parse(raw); const threshold = new Prisma.Decimal(input.expenseApprovalThreshold); if (threshold.isNegative()) throw new Error("INVALID_APPROVAL_THRESHOLD"); const row = await db.accountSettings.upsert({ where: { companyId: actor.companyId! }, create: { companyId: actor.companyId!, expenseApprovalRequired: input.expenseApprovalRequired, expenseApprovalThreshold: threshold, negativeStockAllowed: input.negativeStockAllowed, transactionDefaults: input.transactionDefaults, printProfile: input.printProfile }, update: { ...input, expenseApprovalThreshold: threshold } }); await db.accountingAuditEvent.create({ data: { companyId: actor.companyId!, actorUserId: actor.id, eventType: "SETTINGS_CHANGED", entityType: "ACCOUNT_SETTINGS", entityId: actor.companyId!, metadata: { sections: ["TRANSACTIONS", "INVENTORY", "APPROVALS", "PRINT_PROFILE"] } } }); return row; }

const fieldSchema = z.object({ id: z.string().uuid().optional(), entityType: z.nativeEnum(CustomFieldEntity), fieldKey: z.string().regex(/^[a-z][a-z0-9_]{1,59}$/), label: z.string().min(1).max(100), dataType: z.nativeEnum(CustomFieldDataType), isRequired: z.boolean().default(false), position: z.number().int().min(0).max(1000).default(0), options: z.array(z.string().min(1).max(100)).max(100).optional() }).strict();
export async function saveCustomField(raw: unknown) { const actor = await requirePermissionForMutation("ACCOUNT_SETTINGS"); if (actor.accountRole !== "ACCOUNT_ADMIN") throw new AuthorizationError(); const input = fieldSchema.parse(raw); if (input.dataType === "SELECT" && !input.options?.length) throw new Error("SELECT_OPTIONS_REQUIRED"); const data = { companyId: actor.companyId!, entityType: input.entityType, fieldKey: input.fieldKey, label: input.label, dataType: input.dataType, isRequired: input.isRequired, position: input.position, options: input.options ?? Prisma.JsonNull }; const row = input.id ? await db.customFieldDefinition.updateMany({ where: { id: input.id, companyId: actor.companyId! }, data }) : await db.customFieldDefinition.create({ data }); await db.accountingAuditEvent.create({ data: { companyId: actor.companyId!, actorUserId: actor.id, eventType: "SETTINGS_CHANGED", entityType: "CUSTOM_FIELD", entityId: input.id ?? (row as { id: string }).id } }); return row; }
export async function deactivateCustomField(id: string) { const actor = await requirePermissionForMutation("ACCOUNT_SETTINGS"); if (actor.accountRole !== "ACCOUNT_ADMIN") throw new AuthorizationError(); return db.customFieldDefinition.updateMany({ where: { id, companyId: actor.companyId! }, data: { isActive: false } }); }
export async function saveCustomFieldValues(entityType: CustomFieldEntity, entityId: string, values: Record<string, unknown>) { const actor = await requirePermissionForMutation("ACCOUNT_ACCOUNTS"); const definitions = await db.customFieldDefinition.findMany({ where: { companyId: actor.companyId!, entityType, isActive: true } }); const missing = definitions.filter((x) => x.isRequired && (values[x.fieldKey] === undefined || values[x.fieldKey] === "")); if (missing.length) throw new Error(`CUSTOM_FIELDS_REQUIRED:${missing.map((x) => x.fieldKey).join(",")}`); return db.$transaction(definitions.filter((x) => values[x.fieldKey] !== undefined).map((definition) => db.customFieldValue.upsert({ where: { companyId_definitionId_entityId: { companyId: actor.companyId!, definitionId: definition.id, entityId } }, create: { companyId: actor.companyId!, definitionId: definition.id, entityType, entityId, value: values[definition.fieldKey] as Prisma.InputJsonValue }, update: { value: values[definition.fieldKey] as Prisma.InputJsonValue } }))); }

const templateSchema = z.object({ branchId: z.string().uuid().nullable().optional(), documentType: z.enum(["INVOICE", "QUOTATION", "PURCHASE_ORDER", "RECEIPT", "BOQ"]), name: z.string().min(1).max(120), paperSize: z.nativeEnum(PrintPaperSize), isDefault: z.boolean().default(false), config: z.object({ accentColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#075985"), showBank: z.boolean().default(true), showUpiQr: z.boolean().default(false), showSignature: z.boolean().default(true), footer: z.string().max(500).optional() }).strict() }).strict();
export async function createPrintTemplate(raw: unknown) { const actor = await requirePermissionForMutation("ACCOUNT_SETTINGS"); if (actor.accountRole !== "ACCOUNT_ADMIN") throw new AuthorizationError(); const input = templateSchema.parse(raw); if (input.branchId && !await db.branch.findFirst({ where: { id: input.branchId, companyId: actor.companyId!, isActive: true } })) throw new Error("INVALID_BRANCH"); return db.$transaction(async (tx) => { if (input.isDefault) await tx.printTemplate.updateMany({ where: { companyId: actor.companyId!, branchId: input.branchId ?? null, documentType: input.documentType, paperSize: input.paperSize }, data: { isDefault: false } }); const latest = await tx.printTemplate.aggregate({ where: { companyId: actor.companyId!, branchId: input.branchId ?? null, documentType: input.documentType, name: input.name }, _max: { version: true } }); const row = await tx.printTemplate.create({ data: { ...input, branchId: input.branchId ?? null, companyId: actor.companyId!, version: (latest._max.version ?? 0) + 1, createdById: actor.id } }); await tx.accountingAuditEvent.create({ data: { companyId: actor.companyId!, actorUserId: actor.id, eventType: "SETTINGS_CHANGED", entityType: "PRINT_TEMPLATE", entityId: row.id } }); return row; }); }
export async function resolvePrintTemplate(companyId: string, branchId: string, documentType: string, paperSize: PrintPaperSize) { return db.printTemplate.findFirst({ where: { companyId, documentType, paperSize, isActive: true, OR: [{ branchId }, { branchId: null }] }, orderBy: [{ branchId: "desc" }, { isDefault: "desc" }, { version: "desc" }] }); }
export function buildUpiUri(profile: { upiId?: string; upiPayeeName?: string }, amount?: Prisma.Decimal, reference?: string) { if (!profile.upiId) return null; const params = new URLSearchParams({ pa: profile.upiId, pn: profile.upiPayeeName ?? "" }); if (amount) params.set("am", amount.toFixed(2)); if (reference) params.set("tn", reference.slice(0, 80)); params.set("cu", "INR"); return `upi://pay?${params.toString()}`; }
