import { Prisma, TaxMode } from "@prisma/client";
import { z } from "zod";
const D=Prisma.Decimal,Z=new D(0),round=(x:Prisma.Decimal)=>x.toDecimalPlaces(2,Prisma.Decimal.ROUND_HALF_UP);
export const GSTIN=/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;
export const validateGstin=(value:string)=>{const gstin=value.trim().toUpperCase();if(!GSTIN.test(gstin))throw new Error("INVALID_GSTIN");return gstin;};
export type TaxInput={amount:Prisma.Decimal;taxRate:Prisma.Decimal;cessRate?:Prisma.Decimal;cessFixed?:Prisma.Decimal;taxMode:TaxMode;sellerStateCode?:string|null;stateOfSupplyCode?:string|null;reverseCharge?:boolean;composition?:boolean;itcEligible?:boolean};
export function calculateTax(i:TaxInput){if(i.amount.lt(0)||i.taxRate.lt(0))throw new Error("INVALID_TAX_INPUT");const cessRate=i.cessRate??Z,cessFixed=i.cessFixed??Z,denominator=new D(100).add(i.taxRate).add(cessRate),taxable=round(i.taxMode==="INCLUSIVE"?i.amount.sub(cessFixed).mul(100).div(denominator):i.amount),gst=round(taxable.mul(i.taxRate).div(100)),cess=round(taxable.mul(cessRate).div(100).add(cessFixed)),interstate=!!i.sellerStateCode&&!!i.stateOfSupplyCode&&i.sellerStateCode!==i.stateOfSupplyCode,composition=!!i.composition,chargeableGst=composition?Z:gst,cgst=interstate?Z:round(chargeableGst.div(2)),sgst=interstate?Z:chargeableGst.sub(cgst),igst=interstate?chargeableGst:Z,totalTax=chargeableGst.add(cess),grandTotal=round(i.taxMode==="INCLUSIVE"?i.amount:taxable.add(totalTax));return {taxable,cgst,sgst,igst,cess,totalTax,grandTotal,interstate,reverseCharge:!!i.reverseCharge,itcEligible:!!i.itcEligible&&!composition};}
export function calculateWithholding(base:Prisma.Decimal,rate:Prisma.Decimal){if(base.lt(0)||rate.lt(0)||rate.gt(100))throw new Error("INVALID_WITHHOLDING");return round(base.mul(rate).div(100));}
export const taxProfileInput=z.object({gstin:z.string().transform(validateGstin).optional(),stateCode:z.string().regex(/^\d{2}$/).optional(),registrationType:z.enum(["UNREGISTERED","REGULAR","COMPOSITION","SEZ"])}).strict();
export function buildEInvoicePayload(document:{documentNumber:string;issueDate:Date;sellerGstin:string|null;partyGstin:string|null;stateOfSupplyCode:string|null;taxableTotal:Prisma.Decimal;cgstTotal:Prisma.Decimal;sgstTotal:Prisma.Decimal;igstTotal:Prisma.Decimal;cessTotal:Prisma.Decimal;grandTotal:Prisma.Decimal;lines:Array<{itemName:string;hsnSacCode:string|null;quantity:Prisma.Decimal;taxableAmount:Prisma.Decimal;cgstAmount:Prisma.Decimal;sgstAmount:Prisma.Decimal;igstAmount:Prisma.Decimal;cessAmount:Prisma.Decimal}>}){if(!document.sellerGstin)throw new Error("SUPPLIER_GSTIN_REQUIRED");return {version:"1.1",document:{number:document.documentNumber,date:document.issueDate.toISOString().slice(0,10)},supplier:{gstin:document.sellerGstin},buyer:{gstin:document.partyGstin},placeOfSupply:document.stateOfSupplyCode,items:document.lines.map((l,index)=>({serial:index+1,description:l.itemName,hsnSac:l.hsnSacCode,quantity:l.quantity.toFixed(4),taxable:l.taxableAmount.toFixed(2),cgst:l.cgstAmount.toFixed(2),sgst:l.sgstAmount.toFixed(2),igst:l.igstAmount.toFixed(2),cess:l.cessAmount.toFixed(2)})),totals:{taxable:document.taxableTotal.toFixed(2),cgst:document.cgstTotal.toFixed(2),sgst:document.sgstTotal.toFixed(2),igst:document.igstTotal.toFixed(2),cess:document.cessTotal.toFixed(2),grand:document.grandTotal.toFixed(2)}};}
export function buildEWayBillPayload(document:Parameters<typeof buildEInvoicePayload>[0],transport:{dispatchFrom:string;deliveryTo:string;transporterId?:string;vehicleNumber?:string;distanceKm?:number}){return {...buildEInvoicePayload(document),transport,status:"NOT_GENERATED",...transport};}
export function summarizeTaxes(rows:Array<{taxableTotal:Prisma.Decimal;cgstTotal:Prisma.Decimal;sgstTotal:Prisma.Decimal;igstTotal:Prisma.Decimal;cessTotal:Prisma.Decimal;tdsAmount:Prisma.Decimal;tcsAmount:Prisma.Decimal;reverseCharge:boolean}>){return rows.reduce((a,r)=>({taxable:a.taxable.add(r.taxableTotal),cgst:a.cgst.add(r.cgstTotal),sgst:a.sgst.add(r.sgstTotal),igst:a.igst.add(r.igstTotal),cess:a.cess.add(r.cessTotal),tds:a.tds.add(r.tdsAmount),tcs:a.tcs.add(r.tcsAmount),reverseCharge:a.reverseCharge.add(r.reverseCharge?r.cgstTotal.add(r.sgstTotal).add(r.igstTotal).add(r.cessTotal):Z)}),{taxable:Z,cgst:Z,sgst:Z,igst:Z,cess:Z,tds:Z,tcs:Z,reverseCharge:Z});}
