"use client";
import Link from "next/link";import {useMemo,useState} from "react";import {AccountIcon,type AccountIconName} from "./account-icons";
type Item={id:string;name:string;code:string|null;category:string|null;salePrice:string;purchasePrice:string;stock:number};
const links:{label:string;href:string;icon:AccountIconName}[]=[{label:"Online Store",href:"/workspace/account/inventory/online-store",icon:"store"},{label:"Stock Summary",href:"/workspace/account/inventory/stock-summary",icon:"stock"},{label:"Item Settings",href:"/workspace/account/inventory/item-settings",icon:"settings"},{label:"Show All",href:"/workspace/account/inventory/items",icon:"grid"}];
const currency=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
export function ItemsScreen({items}:{items:Item[]}){const[q,setQ]=useState("");const visible=useMemo(()=>items.filter(i=>`${i.name} ${i.code??""}`.toLowerCase().includes(q.toLowerCase())),[items,q]);return <div className="account-items-screen">
 <header className="account-page-header"><div><h1>Items</h1><p>Products, services and live inventory</p></div></header>
 <section className="account-card account-quick-card"><h2>Quick Links</h2><div>{links.map(x=><Link href={x.href} key={x.label}><span><AccountIcon name={x.icon}/></span>{x.label}</Link>)}</div></section>
 <div className="account-compact-search"><AccountIcon name="search"/><input aria-label="Search items" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for an item or code"/><button aria-label="Filter items"><AccountIcon name="filter"/></button><button aria-label="More item actions"><AccountIcon name="more"/></button></div>
 <section className="account-item-list">{visible.length?visible.map(item=><article className="account-item-card" key={item.id}><div><h2>{item.name}</h2>{item.category&&<span className="account-category">{item.category}</span>}<small>{item.code||"No item code"}</small></div><button aria-label={`Share ${item.name}`}><AccountIcon name="share"/></button><dl><div><dt>Sale price</dt><dd>{currency.format(Number(item.salePrice))}</dd></div><div><dt>Purchase price</dt><dd>{currency.format(Number(item.purchasePrice))}</dd></div><div><dt>Current stock</dt><dd className={item.stock<0?"negative":undefined}>{item.stock.toFixed(2)}</dd></div></dl></article>):<div className="account-home-empty"><strong>No items found</strong><p>Try another item name or code.</p></div>}</section>
 <Link className="account-floating-action" href="/workspace/account/inventory/items">＋ Add New Item</Link>
 </div>}
