"use client";
import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {createAccountUnitAction,updateAccountUnitAction,saveUnitConversionAction} from "@/app/actions/account-masters";
type Unit={id:string;name:string;symbol:string;itemCount:number};
type Conv={baseUnitId:string;secondaryUnitId:string;rate:number};
export function UnitsManager({units:initial,conversions:initialConversions}:{units:Unit[];conversions:Conv[]}){
 const[units,setUnits]=useState(initial),[q,setQ]=useState(""),[open,setOpen]=useState(false),[edit,setEdit]=useState<Unit|null>(null),[name,setName]=useState(""),[symbol,setSymbol]=useState(""),[conversionOpen,setConversionOpen]=useState(false),[base,setBase]=useState(""),[secondary,setSecondary]=useState(""),[rate,setRate]=useState("1"),[conversions,setConversions]=useState(initialConversions),[pending,startTransition]=useTransition();
 const visible=useMemo(()=>units.filter(x=>`${x.name} ${x.symbol}`.toLowerCase().includes(q.toLowerCase())),[units,q]);
 const beginAdd=()=>{setEdit(null);setName("");setSymbol("");setOpen(true)};
 const beginEdit=(u:Unit)=>{setEdit(u);setName(u.name);setSymbol(u.symbol);setOpen(true)};
 const saveUnit=()=>{if(!name.trim()||!symbol.trim())return;startTransition(async()=>{const row=edit?await updateAccountUnitAction(edit.id,{name:name.trim(),symbol:symbol.trim()}):await createAccountUnitAction({name:name.trim(),symbol:symbol.trim()});setUnits(old=>{const rest=old.filter(x=>x.id!==row.id);return[...rest,{id:row.id,name:row.name,symbol:row.symbol,itemCount:edit?.itemCount??0}].sort((a,b)=>a.name.localeCompare(b.name))});setOpen(false)})};
 const saveConversion=()=>{if(!base||!secondary||base===secondary||!(Number(rate)>0))return;startTransition(async()=>{await saveUnitConversionAction({baseUnitId:base,secondaryUnitId:secondary,rate});const n=Number(rate);setConversions(old=>[...old.filter(x=>!(x.baseUnitId===base&&x.secondaryUnitId===secondary)),{baseUnitId:base,secondaryUnitId:secondary,rate:n}]);setConversionOpen(false)})};
 const conversionFor=(id:string)=>conversions.find(x=>x.baseUnitId===id||x.secondaryUnitId===id);
 return <main className="items-manager-page">
  <header className="items-manager-header"><Link href="/workspace/account/inventory">←</Link><h1>Units</h1><Link href="/workspace/account/inventory/item-settings">⚙</Link></header>
  <div className="manager-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Unit"/></div>
  <div className="unit-top-actions"><button onClick={()=>{setBase(units[0]?.id??"");setSecondary(units[1]?.id??"");setRate("1");setConversionOpen(true)}}>Set Conversion</button><button disabled title="Send a Unit to Items reference screen to define this page">Unit to Items</button></div>
  <div className="unit-list">{visible.map(u=>{const conv=conversionFor(u.id);return <div className="unit-row" key={u.id}><div><strong>{u.name.toUpperCase()}</strong><small>{u.symbol}</small>{conv&&<em>{conv.baseUnitId===u.id?`1 ${u.symbol} = ${conv.rate} ${units.find(x=>x.id===conv.secondaryUnitId)?.symbol??""}`:`Used in conversion`}</em>}</div>{conv&&<span>⌄</span>}<button onClick={()=>beginEdit(u)} aria-label={`Edit ${u.name}`}>✎</button></div>})}</div>
  <button className="manager-fab" onClick={beginAdd}>⊕ Add Unit</button>
  {open&&<div className="sale-more-sheet"><section><header><h2>{edit?"Edit Unit":"Add Unit"}</h2><button onClick={()=>setOpen(false)}>×</button></header><div className="manager-sheet-body"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter Full Unit Name"/><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Short Name"/><div className="manager-sheet-actions"><button onClick={()=>setOpen(false)}>Cancel</button><button disabled={!name.trim()||!symbol.trim()||pending} onClick={saveUnit}>{pending?"Saving…":"Save"}</button></div></div></section></div>}
  {conversionOpen&&<div className="manager-fullscreen"><header className="items-manager-header"><button onClick={()=>setConversionOpen(false)}>←</button><h1>Set Conversion</h1><span/></header><div className="conversion-body"><label>Base unit<select value={base} onChange={e=>setBase(e.target.value)}>{units.map(u=><option value={u.id} key={u.id}>{u.name.toUpperCase()}</option>)}</select></label><label>Secondary unit<select value={secondary} onChange={e=>setSecondary(e.target.value)}>{units.map(u=><option value={u.id} key={u.id}>{u.name.toUpperCase()}</option>)}</select></label><label>Conversion Rate<input type="number" min=".0001" step=".0001" value={rate} onChange={e=>setRate(e.target.value)}/></label><p>ⓘ 1 {units.find(x=>x.id===base)?.name.toUpperCase()??"BASE"} = {rate||"0"} {units.find(x=>x.id===secondary)?.name.toUpperCase()??"SECONDARY"}</p></div><footer className="manager-bottom-actions"><button onClick={()=>setConversionOpen(false)}>Cancel</button><button disabled={!base||!secondary||base===secondary||!(Number(rate)>0)||pending} onClick={saveConversion}>Save</button></footer></div>}
 </main>
}