package com.salespunch360.mobile.ui.account.inventory
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.AccountAddItemViewModel
@OptIn(ExperimentalMaterial3Api::class)
@Composable fun AddItemScreen(back:()->Unit,navigate:(String)->Unit,vm:AccountAddItemViewModel=viewModel()){val s=vm.state.collectAsStateWithLifecycle().value;var service by remember{mutableStateOf(false)};var name by remember{mutableStateOf("")};var unit by remember{mutableStateOf<String?>(null)};var unitsOpen by remember{mutableStateOf(false)};var settings by remember{mutableStateOf(false)};Scaffold(topBar={TopAppBar(title={Text("Add Item")},navigationIcon={TextButton(back){Text("‹ Back")}},actions={IconButton({}){Text("📷")};IconButton({settings=true}){Text("⚙")}})},bottomBar={Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(back,Modifier.weight(1f)){Text("Cancel")};Button({vm.save(service,name,unit){back()}},enabled=name.isNotBlank()&&!s.saving,modifier=Modifier.weight(1f)){Text(if(s.saving)"Saving…" else "Save")}}}){padding->Column(Modifier.padding(padding).padding(16.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){SingleChoiceSegmentedButtonRow{SegmentedButton(!service,{service=false},SegmentedButtonDefaults.itemShape(0,2)){Text("Product")};SegmentedButton(service,{service=true},SegmentedButtonDefaults.itemShape(1,2)){Text("Services")}};OutlinedTextField(name,{name=it},label={Text("Item Name *")},modifier=Modifier.fillMaxWidth());Box{OutlinedButton({unitsOpen=true},Modifier.fillMaxWidth()){Text(s.units.firstOrNull{it.id==unit}?.name?:"Select Unit")};DropdownMenu(unitsOpen,{unitsOpen=false}){s.units.forEach{u->DropdownMenuItem({Text(u.name)},{unit=u.id;unitsOpen=false})}}};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}};if(settings)ModalBottomSheet({settings=false}){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Add Item Settings",style=MaterialTheme.typography.titleLarge);listOf("Item Custom Fields","Additional Item Fields","Wholesale Price","Barcode Scan","Item Category","Description").forEach{Text("$it  ›")};Text("Service Reminders · Coming Soon");TextButton({settings=false;navigate("/workspace/account/inventory/item-settings")}){Text("⚙ More Settings")}}}}
