import type {Metadata} from "next";
import Link from "next/link";
import Image from "next/image";
import {BrandLogo} from "@/components/brand-logo";
import {LiveLocation} from "@/components/workspace/live-location";
import {dashboardData} from "@/lib/workspace/dashboard";
import {db} from "@/lib/db";
import {profileComplete} from "@/lib/company/profile";
import {VerificationResend} from "./verification-resend";
import {CompanyIdentityLogo} from "@/components/workspace/company-identity-logo";

export const metadata:Metadata={title:"Company dashboard"};
type Params={setup?:string;from?:string;checkInEmployee?:string;liveEmployee?:string};
const baseLinks=[["▦","Dashboard","/workspace"],["◷","Attendance","/workspace/attendance"],["♙","Customers","/workspace/customers"],["◈","Check-ins","/workspace/check-ins"],["◎","Leads","/workspace/leads"],["✓","Follow-ups","/workspace/follow-up-tasks"],["◉","Targets","/workspace/targets"]] as const;
const adminLinks=[["♟","Employees","/workspace/employees"],["▣","Billing & Subscription","/workspace/billing"],["⚙","Settings","/workspace/settings"]] as const;
const adminReports=[["Check-in Report","/workspace/reports/check-ins"],["Attendance Report","/workspace/reports/attendance"],["GPS Route Report","/workspace/reports/gps"],["Geofence Report","/workspace/reports/geofence-breaches"],["Target Analysis","/workspace/reports/targets"],["Expense Report","/workspace/reports/expenses"]] as const;
const managerReports=[["Check-in Report","/workspace/reports/check-ins"],["Attendance Report","/workspace/reports/attendance"],["GPS Route Report","/workspace/reports/gps"],["Geofence Report","/workspace/reports/geofence-breaches"],["Target Analysis","/workspace/reports/targets"]] as const;
const salesReports=[["Check-in Report","/workspace/reports/check-ins"],["My Attendance","/workspace/reports/attendance"],["My Travel / Distance","/workspace/reports/gps"],["My Performance","/workspace/reports/targets"]] as const;
const fmt=(d:Date|null)=>d?d.toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}):"—";
function ReportsMenu({items}:{items:readonly(readonly[string,string])[]}){return <details className="reports-menu"><summary><span>▥</span>Reports</summary>{items.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</details>}
function Nav({role}:{role:"COMPANY_ADMIN"|"MANAGER"|"SALES"}){const reports=role==="COMPANY_ADMIN"?adminReports:role==="MANAGER"?managerReports:salesReports;const operationalLinks=role!=="SALES"?baseLinks.filter(([, ,href])=>href!=="/workspace/check-ins"):baseLinks;const links=role==="COMPANY_ADMIN"?[operationalLinks[0],adminLinks[0],...operationalLinks.slice(1),...adminLinks.slice(1)]:operationalLinks;return <>{links.map(([icon,label,href])=><Link className={href==="/workspace"?"active":""} href={href} key={href}><span>{icon}</span>{label}</Link>)}<ReportsMenu items={reports}/></>}
export default async function WorkspacePage({searchParams}:{searchParams:Promise<Params>}){
 const params=await searchParams,d=await dashboardData(params),role=d.actor.role as "COMPANY_ADMIN"|"MANAGER"|"SALES",fieldWorker=role==="SALES"||(role==="MANAGER"&&d.actor.managerType!=="MANAGER_ONLY");
 if(role==="COMPANY_ADMIN"&&params.setup==="1"){
  const setup=await db.company.findUniqueOrThrow({where:{id:d.actor.companyId},select:{name:true,teamStructure:true,addressLine1:true,city:true,state:true,postalCode:true,country:true,primaryContactName:true,primaryPhone:true,contactEmail:true,users:{where:{id:d.actor.id},select:{emailVerifiedAt:true},take:1}}});const verified=Boolean(setup.users[0]?.emailVerifiedAt),complete=profileComplete(setup as unknown as Record<string,unknown>);
  return <main className="setup-page"><section className="setup-card"><BrandLogo/><h1>Complete your company setup</h1><p>Finish the requirements below before adding Managers or Sales employees.</p><div className="setup-row"><span>EMAIL VERIFICATION</span><strong>{verified?"✓ Email verified":"Email verification required"}</strong></div>{!verified&&<VerificationResend/>}<div className="setup-row"><span>COMPANY DETAILS</span><strong>{complete?"✓ Company details complete":"Company details incomplete"}</strong></div>{verified&&<Link className="primary-button" href={complete&&params.from==="employees"?"/workspace/employees":"/workspace/company-profile"}>Continue</Link>}<Link href="/workspace">Back to dashboard</Link></section></main>;
 }
 const address=[d.company.addressLine1,d.company.addressLine2,d.company.locality,d.company.city,d.company.state,d.company.postalCode,d.company.country].filter(Boolean).join(", ");
 return <main className="dashboard-shell"><aside className="dashboard-sidebar"><BrandLogo inverse/><p>MAIN</p><nav><Nav role={role}/></nav></aside><section className="dashboard-main"><header><details className="dash-mobile-nav"><summary aria-label="Open workspace menu">☰</summary><nav><Nav role={role}/></nav></details><div className="tenant-identity"><CompanyIdentityLogo name={d.company.name} hasLogo={Boolean(d.company.logoObjectKey)} version={d.company.updatedAt.getTime()}/><span><strong>{d.company.name}</strong>{address&&<small>{address}</small>}</span><em>{d.company.subscriptionStatus}</em></div></header><div className="dashboard-body">
  <div className="dashboard-welcome"><div><p>{role==="MANAGER"?(d.actor.managerType==="MANAGER_ONLY"?"MANAGER ONLY":"FIELD MANAGER"):role.replaceAll("_"," ")}</p><h2>Good day, {d.actor.name.split(" ")[0]}!</h2><span>{role==="SALES"?"Your field-work overview.":role==="MANAGER"?(d.actor.managerType==="MANAGER_ONLY"?"Your assigned Sales team overview.":"Your attendance and assigned Sales team."):"Your company field-team overview."}</span></div></div>
  <div className="kpi-grid">{role==="SALES"?<><article><div><span>Check-ins This Month</span><strong>{d.monthVisitCount}</strong><small>Current month</small></div><i className="blue">▤</i></article><article><div><span>Leads This Month</span><strong>{d.monthLeadCount}</strong><small>Current month</small></div><i className="green">◎</i></article><article><div><span>Check-ins Today</span><strong>{d.todayVisitCount}</strong><small>Field visits</small></div><i className="orange">⌖</i></article><article><div><span>Leads Today</span><strong>{d.todayLeadCount}</strong><small>Assigned activity</small></div><i className="purple">◎</i></article></>:<><article><div><span>Team members</span><strong>{d.employees.length}</strong><small>Real company data</small></div><i className="blue">▤</i></article><article><div><span>Present today</span><strong>{d.presentCount}</strong><small>Started today</small></div><i className="green">♟</i></article><article><div><span>Check-ins today</span><strong>{d.todayVisitCount}</strong><small>Field visits</small></div><i className="orange">⌖</i></article><article><div><span>Leads today</span><strong>{d.todayLeadCount}</strong><small>Assigned activity</small></div><i className="purple">◎</i></article></>}</div>

  <div className="dashboard-grid dashboard-role-grid"><article className="dash-card dashboard-checkins"><div className="card-title"><h3>{role==="SALES"?"My Recent Check-ins":"Check-in Activity"}</h3><Link href="/workspace/reports/check-ins">View All</Link></div>{role!=="SALES"&&<form className="dashboard-selector"><label>Employee<select name="checkInEmployee" defaultValue={d.checkUserId||""}><option value="">All authorized employees</option>{d.employees.map(e=><option value={e.id} key={e.id}>{e.name} · {e.role}</option>)}</select></label>{d.liveUserId&&<input type="hidden" name="liveEmployee" value={d.liveUserId}/>}<button>View</button></form>}{d.visits.length?<div className="recent-checkins-slider" aria-label="Recent completed check-ins">{d.visits.map(v=><div className="checkin-row" key={v.id}><b>{v.user.name.charAt(0)}</b><span><strong>{v.user.name} · {v.customer?.name||v.contactName||"Field prospect"}</strong>{v.photo&&<Image src={`/api/visit-photos/${v.id}/thumbnail`} loading="lazy" unoptimized width={96} height={96} alt="Check-in thumbnail"/>}<small>{v.checkInAddress||`${v.checkInLatitude.toFixed(5)}, ${v.checkInLongitude.toFixed(5)}`} · {v.checkedOutAt?"Completed":"Checked in"}{v.checkoutSentiment?` · ${v.checkoutSentiment}`:""}</small></span><time>{fmt(v.checkedInAt)}<small>{v.checkedOutAt?`Out ${fmt(v.checkedOutAt)}`:"No checkout recorded"}</small></time><Link href="/workspace/reports/check-ins">Details</Link></div>)}</div>:<p className="dash-empty">No completed check-ins match this selection.</p>}{fieldWorker&&<><div className="card-title"><h3>My Follow-ups</h3></div><div className="personal-task-counts"><Link href="/workspace/follow-up-tasks?status=TODAY"><span>Pending Today</span><strong>{d.pendingTodayTasks}</strong></Link><Link href="/workspace/follow-up-tasks?status=OVERDUE"><span>Overdue</span><strong>{d.overdueTasks}</strong></Link></div></>}{fieldWorker&&<div className="dashboard-checkin-action"><Link className="primary-button add-checkin" href="/workspace/check-ins">+ Add Check-in</Link></div>}</article>
  {role!=="SALES"&&<article id="live-tracking" className="dash-card dashboard-tracking"><div className="card-title"><h3>Live Tracking</h3></div><form className="dashboard-selector" action="/workspace#live-tracking"><select name="liveEmployee" defaultValue={d.liveUserId||""} required aria-label="Select employee"><option value="">Select employee</option>{d.employees.map(e=><option value={e.id} key={e.id}>{e.name} · {e.role}</option>)}</select>{d.checkUserId&&<input type="hidden" name="checkInEmployee" value={d.checkUserId}/>}<button>View</button></form>{d.liveUserId?<>{d.latestLocation&&<div className="location-meta"><strong>{d.latestLocation.user.name}</strong><span>Last known location · {fmt(d.latestLocation.capturedAt)}</span><small>{d.latestLocation.latitude.toFixed(6)}, {d.latestLocation.longitude.toFixed(6)}</small></div>}<LiveLocation point={d.latestLocation}/></>:<div className="empty-state">Select an authorized employee to view their latest stored GPS point.</div>}</article>}</div>

 </div></section></main>;
}
