import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const css=readFileSync(new URL("../globals.css",import.meta.url),"utf8");
const header=readFileSync(new URL("../../components/workspace/workspace-header.tsx",import.meta.url),"utf8");
const contract=(name:string,value:string)=>expect(css).toMatch(new RegExp(`${name}:${value.replace(/[.*+?^${}()|[\\]\\\\]/g,"\\\\$&")}`));
describe("shared authenticated UI sizing",()=>{
  it("has no Company Admin-specific menu sizing hook",()=>{expect(css).not.toContain("workspace-mobile-drawer-admin");expect(header).not.toContain("workspace-mobile-drawer-admin")});
  it("uses the same desktop and mobile menu contracts for every role",()=>{for(const role of["ADMIN","MANAGER","SALES"])expect(header).toContain(role);for(const token of["--menu-font-size","--menu-font-weight","--menu-icon-width","--menu-icon-gap","--menu-desktop-min-height","--menu-desktop-inline-padding","--menu-mobile-min-height","--menu-mobile-inline-padding","--menu-item-radius","--menu-submenu-font-size"])expect(css).toContain(token);expect(css).toContain(".dashboard-sidebar nav>a,\n.dashboard-sidebar .reports-menu>summary");expect(css).toContain(".workspace-mobile-drawer a,\n  .workspace-reports-toggle");expect(css).toContain(".workspace-report-links a,\n  .dash-mobile-nav .reports-menu>a")});
  it("defines and applies the normal action contract",()=>{contract("--ui-control-min-height","42px");contract("--ui-control-font-size","13px");contract("--ui-control-font-weight","700");contract("--ui-control-inline-padding","14px");contract("--ui-control-radius","8px");for(const selector of[".primary-button",".danger-button",".report-filters button",".dashboard-selector button",".monthly-target-row button",".expense-approval-actions button"])expect(css).toContain(selector);expect(css).toContain("min-height:var(--ui-control-min-height)");expect(css).toContain("padding:0 var(--ui-control-inline-padding)")});
  it("defines and applies the standard field contract without sizing toggles",()=>{contract("--ui-field-inline-padding","12px");for(const selector of[".employee-form input",".report-filters input",".billing-form select",".lead-scope-filter input",".target-metric input"])expect(css).toContain(selector);expect(css).toContain("padding:0 var(--ui-field-inline-padding)");expect(css).toContain(".settings-card input { width:44px; height:24px")});
});
