import Link from "next/link";
import { notFound } from "next/navigation";
import { permanentlyDeleteCompanyAction } from "@/app/actions/permanent-company-delete";
import { previewPermanentCompanyDelete, showsActiveTrialWarning, STORAGE_OWNERSHIP_BLOCKED } from "@/lib/admin/permanent-company-delete";
import { requireGlobalSuperAdmin } from "@/lib/auth/authorization";
import { getAdminCompany } from "@/lib/admin/dashboard";
import { overrideSubscriptionAction } from "@/app/actions/billing";
export default async function CompanyDangerPage({ params, searchParams }: { params: Promise<{ companyId: string }>; searchParams: Promise<{ prepare?: string; error?: string }> }) {
  await requireGlobalSuperAdmin(); const { companyId } = await params; const query = await searchParams; const company=await getAdminCompany(companyId);if(!company)notFound(); let preview = null; let blocked = false;
  if (query.prepare === "1") { try { preview = await previewPermanentCompanyDelete(companyId); } catch (error) { if (error instanceof Error && error.message === STORAGE_OWNERSHIP_BLOCKED) blocked = true; else if (error instanceof Error && error.message.includes("TENANT_NOT_FOUND")) notFound(); else throw error; } }
  const active = preview && showsActiveTrialWarning(preview.company);
  return <main className="admin-content company-danger-page"><Link href="/admin/companies" className="ghost-button admin-action">← Companies</Link><p className="eyebrow">Platform administration · Company</p><h1>{company.name}</h1><section className="admin-panel"><h2>Company &amp; Subscription</h2><div className="billing-summary"><article><strong>{company.productEdition}</strong><span>Edition</span></article><article><strong>{company.subscriptionStatus}</strong><span>Company status</span></article><article><strong>{company.trialEndsAt?.toLocaleDateString('en-IN')??'—'}</strong><span>Trial end</span></article><article><strong>{company.users.length}</strong><span>Active users</span></article></div>{company.subscriptions.length===0?<p className="muted">No subscription records.</p>:company.subscriptions.map(s=><article className="history-row" key={s.id}><div><strong>{s.status} · {s.billingPeriod.replace('_',' ')}</strong><span>{s.startsAt.toLocaleDateString('en-IN')} – {s.endsAt.toLocaleDateString('en-IN')} · {s.adminSeats} Admin / {s.managerSeats} Manager / {s.salesSeats} Sales</span></div></article>)}<details><summary>Manual Override</summary><p className="muted">Exceptional Super Admin entitlement action only. Normal manual payments must be confirmed from Billing.</p><form action={overrideSubscriptionAction} className="billing-form"><input type="hidden" name="companyId" value={company.id}/><select name="status"><option>ACTIVE</option><option>SUSPENDED</option></select><select name="billingPeriod"><option>MONTHLY</option><option>SIX_MONTH</option><option>YEARLY</option></select><input name="adminSeats" type="number" min="0" placeholder="Additional Admin seats" required/><input name="managerSeats" type="number" min="0" placeholder="Manager seats" required/><input name="salesSeats" type="number" min="0" placeholder="Sales seats" required/><label>Ends at<input name="endsAt" type="datetime-local" required/></label><input name="reason" minLength={10} maxLength={500} placeholder="Required operational reason" required/><button>Apply audited override</button></form></details></section>
    <section className="danger-zone"><h2>Danger Zone</h2><h3>Permanently Delete Company</h3><p>This action is permanent and irreversible. All Company users, operational data, tenant billing/history, and Company photos, logo, and storage will be deleted. This cannot be undone.</p>
      {!preview && !blocked && <Link className="danger-button admin-action" href={`/admin/companies/${companyId}?prepare=1`}>Prepare permanent deletion</Link>}{blocked && <p className="danger-alert" role="alert">{STORAGE_OWNERSHIP_BLOCKED}</p>}
      {query.error === "confirmation" && <p className="danger-alert" role="alert">The confirmation was incorrect. No data was deleted.</p>}{query.error === "blocked" && <p className="danger-alert" role="alert">Company deletion was blocked. No database deletion was committed.</p>}
      {preview && <div className="deletion-preview"><dl><div><dt>Company name</dt><dd>{preview.company.name}</dd></div><div><dt>Company UUID</dt><dd>{preview.company.id}</dd></div><div><dt>Slug</dt><dd>{preview.company.slug}</dd></div><div><dt>Created</dt><dd>{preview.company.createdAt?.toLocaleString() ?? "—"}</dd></div><div><dt>Product edition</dt><dd>{preview.company.productEdition ?? "—"}</dd></div><div><dt>Subscription / trial status</dt><dd>{preview.company.subscriptionStatus ?? "—"}{preview.company.trialEndsAt ? ` · trial ends ${preview.company.trialEndsAt.toLocaleDateString()}` : ""}</dd></div></dl>
        {active && <p className="danger-alert"><strong>This Company is currently active/trial.</strong> Permanent deletion will immediately remove all access and data.</p>}<h3>Authoritative deletion inventory</h3><ul className="count-grid">{Object.entries(preview.counts).map(([model, count]) => <li key={model}><span>{model}</span><strong>{count}</strong></li>)}</ul><p><strong>Total rows to delete:</strong> {preview.totalRows}</p><p><strong>Total storage objects to delete:</strong> {preview.totalStorageObjects}</p>
        <form action={permanentlyDeleteCompanyAction} className="delete-confirmation"><input type="hidden" name="companyId" value={companyId}/><label>Type <strong>DELETE {preview.company.slug}</strong> exactly<input name="confirmation" autoComplete="off" required/></label><button className="danger-button admin-action">Permanently Delete Company</button></form></div>}
    </section></main>;
}
