import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({read:vi.fn(),mutation:vi.fn(),query:vi.fn(),findCompany:vi.fn(),updateCompany:vi.fn(),countUsers:vi.fn(),findOrder:vi.fn(),findSubscription:vi.fn(),order:[] as string[]}));
vi.mock("@/lib/company/owner-authorization",()=>({requirePrimaryOwner:vi.fn().mockResolvedValue({actor:{id:"primary",companyId:"company-a"},company:{productEdition:"SALESPUNCH360"}})}));
vi.mock("@/lib/auth/authorization",()=>({requirePermission:mocks.read,requirePermissionForMutation:mocks.mutation}));
vi.mock("@/lib/db",()=>({db:{company:{findUniqueOrThrow:mocks.findCompany},$transaction:vi.fn(async(fn)=>fn({$queryRaw:mocks.query,company:{findUnique:mocks.findCompany,update:mocks.updateCompany},user:{count:mocks.countUsers},billingOrder:{findFirst:mocks.findOrder},companySubscription:{findFirst:mocks.findSubscription}}))}}));
import{companyProfileSelect,getCompanyProfile,updateCompanyProfile}from"./profile";

const input=(teamStructure:"MANAGERS_AND_SALES"|"SALES_ONLY")=>({name:"Acme",addressLine1:"One Road",addressLine2:"",locality:"",city:"Pune",state:"Maharashtra",postalCode:"411001",country:"India",primaryContactName:"Priya",primaryPhone:"9999999999",contactEmail:"hello@acme.test",alternatePhone:"",website:"",gstin:"27AAPFU0939F1ZV",pan:"AAPFU0939F",registrationNumber:"REG-1",description:"",teamStructure,enabledModules:["ATTENDANCE","REPORTS"]});
const company={productEdition:"SALESPUNCH360" as const,name:"Acme",addressLine1:"One Road",addressLine2:null,locality:null,city:"Pune",state:"Maharashtra",postalCode:"411001",country:"India",primaryContactName:null,primaryPhone:"9999999999",contactEmail:null,alternatePhone:null,website:null,gstin:null,pan:null,registrationNumber:null,description:null,teamStructure:"MANAGERS_AND_SALES" as const,enabledModules:["SALES_CRM","ATTENDANCE"],branches:[{name:"Head Office",code:"HO"}],logoObjectKey:"Logo/company-a.webp",updatedAt:new Date("2026-09-09T00:00:00Z")};

beforeEach(()=>{vi.clearAllMocks();mocks.order.length=0;mocks.read.mockResolvedValue({id:"primary",name:"Primary",email:"primary@acme.test",companyId:"company-a",salesRole:"PRIMARY_ADMIN"});mocks.mutation.mockResolvedValue({id:"primary",companyId:"company-a"});mocks.findCompany.mockImplementation(async()=>{mocks.order.push("reread");return company});mocks.query.mockImplementation(async()=>{mocks.order.push("lock");return[]});mocks.countUsers.mockImplementation(async()=>{mocks.order.push("count");return 0});mocks.findOrder.mockImplementation(async()=>{mocks.order.push("billing-order");return null});mocks.findSubscription.mockImplementation(async()=>{mocks.order.push("subscription");return null});mocks.updateCompany.mockImplementation(async()=>{mocks.order.push("update");return{id:"company-a"}})});

describe("safe company profile DTO",()=>{
 it("uses the canonical read permission and an explicit allowlisted select",async()=>{const result=await getCompanyProfile();expect(mocks.read).toHaveBeenCalledWith("COMPANY_VIEW");expect(mocks.findCompany).toHaveBeenCalledWith({where:{id:"company-a"},select:companyProfileSelect});expect(result.editable).toBe(true)});
 it("returns business fields and derived logo metadata without internal Company fields",async()=>{mocks.findCompany.mockResolvedValue({...company,id:"company-a",slug:"acme",productEdition:"SALESPUNCH360",subscriptionStatus:"ACTIVE",trialStartedAt:new Date(),trialEndsAt:new Date(),attendanceReferenceLatitude:1,attendanceReferenceLongitude:2});const {profile}=await getCompanyProfile();expect(profile).toMatchObject({name:"Acme",city:"Pune",primaryContactName:"Primary",contactEmail:"primary@acme.test",teamStructure:"MANAGERS_AND_SALES",hasLogo:true,logoVersion:"2026-09-09T00:00:00.000Z"});for(const key of["id","slug","logoObjectKey","productEdition","subscriptionStatus","trialStartedAt","trialEndsAt","attendanceReferenceLatitude","attendanceReferenceLongitude"])expect(profile).not.toHaveProperty(key)});
});

describe("business and module validation",()=>{
 it("normalizes valid GST/PAN and stores only server-approved modules",async()=>{await updateCompanyProfile({...input("MANAGERS_AND_SALES"),gstin:"27aapfu0939f1zv",pan:"aapfu0939f"});expect(mocks.updateCompany).toHaveBeenCalledWith({where:{id:"company-a"},data:expect.objectContaining({gstin:"27AAPFU0939F1ZV",pan:"AAPFU0939F",enabledModules:["SALES_CRM","ATTENDANCE","REPORTS"]})})});
 it("rejects malformed GST and unavailable modules before update",async()=>{await expect(updateCompanyProfile({...input("MANAGERS_AND_SALES"),gstin:"invalid"})).rejects.toThrow();await expect(updateCompanyProfile({...input("MANAGERS_AND_SALES"),enabledModules:["ACCOUNTING"]})).rejects.toThrow();expect(mocks.updateCompany).not.toHaveBeenCalled()});
});

describe("team structure transition serialization",()=>{
 it("rejects an active canonical Manager before update after taking the company lock",async()=>{mocks.countUsers.mockImplementation(async()=>{mocks.order.push("count");return 1});await expect(updateCompanyProfile(input("SALES_ONLY"))).rejects.toThrow("TEAM_STRUCTURE_CONFLICT");expect(mocks.order).toEqual(["lock","reread","count"]);expect(mocks.countUsers).toHaveBeenCalledWith({where:{companyId:"company-a",salesRole:"MANAGER",isActive:true,salesAccessActive:true}});expect(mocks.updateCompany).not.toHaveBeenCalled()});
 it("rejects a live pending Manager-seat order without rewriting it",async()=>{mocks.findOrder.mockImplementation(async()=>{mocks.order.push("billing-order");return{id:"pending"}});await expect(updateCompanyProfile(input("SALES_ONLY"))).rejects.toThrow("TEAM_STRUCTURE_CONFLICT");expect(mocks.order).toEqual(["lock","reread","count","billing-order"]);expect(mocks.findOrder).toHaveBeenCalledWith({where:{companyId:"company-a",status:"PENDING",managerSeats:{gt:0},OR:[{expiresAt:null},{expiresAt:{gt:expect.any(Date)}}]},select:{id:true}});expect(mocks.updateCompany).not.toHaveBeenCalled()});
 it("rejects an unexpired ACTIVE Manager-seat subscription, including a future renewal, without rewriting it",async()=>{mocks.findSubscription.mockImplementation(async()=>{mocks.order.push("subscription");return{id:"renewal"}});await expect(updateCompanyProfile(input("SALES_ONLY"))).rejects.toThrow("TEAM_STRUCTURE_CONFLICT");expect(mocks.findSubscription).toHaveBeenCalledWith({where:{companyId:"company-a",status:"ACTIVE",managerSeats:{gt:0},endsAt:{gt:expect.any(Date)}},select:{id:true}});expect(mocks.updateCompany).not.toHaveBeenCalled()});
 it("allows the transition when expired/cancelled/failed billing state is excluded by the live-state queries",async()=>{await updateCompanyProfile(input("SALES_ONLY"));expect(mocks.findOrder).toHaveBeenCalledTimes(1);expect(mocks.findSubscription).toHaveBeenCalledTimes(1);expect(mocks.updateCompany).toHaveBeenCalledTimes(1)});
 it.each(["legacy-only Manager","Sales-suspended canonical Manager","globally inactive canonical Manager"])("does not count a %s",async()=>{await updateCompanyProfile(input("SALES_ONLY"));expect(mocks.countUsers).toHaveBeenCalledWith({where:{companyId:"company-a",salesRole:"MANAGER",isActive:true,salesAccessActive:true}});expect(mocks.updateCompany).toHaveBeenCalledTimes(1)});
 it("allows SALES_ONLY to MANAGERS_AND_SALES without a Manager query",async()=>{mocks.findCompany.mockResolvedValue({...company,teamStructure:"SALES_ONLY"});await updateCompanyProfile(input("MANAGERS_AND_SALES"));expect(mocks.countUsers).not.toHaveBeenCalled();expect(mocks.updateCompany).toHaveBeenCalledTimes(1)});
 it("allows an unchanged structure without a Manager query",async()=>{await updateCompanyProfile(input("MANAGERS_AND_SALES"));expect(mocks.countUsers).not.toHaveBeenCalled();expect(mocks.updateCompany).toHaveBeenCalledTimes(1)});
 it("locks and rereads before validation/update and performs no automatic billing or user mutation",async()=>{await updateCompanyProfile(input("SALES_ONLY"));expect(mocks.query).toHaveBeenCalledTimes(1);expect(mocks.order).toEqual(["lock","reread","count","billing-order","subscription","update"]);expect(Object.keys((mocks.updateCompany.mock.calls[0][0] as {data:object}).data)).not.toContain("users")});
});
