import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const sql=readFileSync("prisma/migrations/20260911010000_a4_a5_completion_hardening/migration.sql","utf8");
describe("A4/A5 hardening migration",()=>{it("adds idempotent controlled system ledgers",()=>{expect(sql).toContain("INPUT_TAX_CREDIT");expect(sql).toContain("CUSTOMER_ADVANCES");expect(sql.match(/ON CONFLICT \("companyId","systemKey"\) DO NOTHING/g)).toHaveLength(2)});it.each(["commercial_party_exactly_one","commercial_project_reference","commercial_totals_nonnegative","commercial_line_positive","commercial_line_source_consistent","settlement_positive","allocation_positive","advance_application_positive"])("adds constraint %s",name=>expect(sql).toContain(name));it("protects financial and audit history with exact cleanup scope",()=>{expect(sql).toContain("commercial_posted_immutable");expect(sql).toContain("settlement_update_guard");expect(sql).toContain("commercial_audit_append_only");expect(sql).toContain("app.account_cleanup_company_id");expect(sql).not.toContain("session_replication_role")});it("adds composite company foreign keys",()=>expect(sql).toContain('FOREIGN KEY("companyId","documentId")'));it("adds allocation and application idempotency",()=>{expect(sql).toContain('UNIQUE("companyId","settlementId","documentId")');expect(sql).toContain('UNIQUE("companyId","idempotencyKey")')})});
describe("A4/A5 correction migration contracts",()=>{
 it("creates the settlement composite key before referencing it",()=>expect(sql.indexOf('account_settlements_companyId_id_key')).toBeLessThan(sql.indexOf('REFERENCES "account_settlements"("companyId","id")')));
 it("aligns required settlement journals without fabricated journals",()=>{expect(sql).toContain('ALTER COLUMN "journalEntryId" SET NOT NULL');expect(sql).toContain("legacy row lacks authoritative journal");expect(sql).not.toMatch(/INSERT INTO "journal_entries"[\s\S]*legacy/i)});
 it("stores application date",()=>expect(sql).toContain('"applicationDate" DATE NOT NULL'));
 it("makes settlement requests company-idempotent",()=>expect(sql).toContain('account_settlements_companyId_idempotencyKey_key'));
 it.each(["commercial_line_history_guard","settlement_allocation_append_only","settlement_allocation_insert_guard","advance_application_append_only"])("installs immutable history trigger %s",name=>expect(sql).toContain(name));
 it("has reminder and settlement same-company party foreign keys",()=>{expect(sql).toContain('payment_reminders" ADD FOREIGN KEY("companyId","customerId")');expect(sql).toContain('settlement_party_exactly_one');expect(sql).toContain('FOREIGN KEY("companyId","vendorId")')});
});
