package com.salespunch360.mobile.ui.account.admin
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.AccountAdministrationViewModel
import kotlinx.serialization.json.*
@Composable fun AccountAdministrationScreen(mode:String,padding:PaddingValues,vm:AccountAdministrationViewModel=viewModel()){val s=vm.state.collectAsStateWithLifecycle().value;LaunchedEffect(mode){vm.load(mode)};Column(Modifier.fillMaxSize().padding(padding).padding(16.dp)){Row{Text(mode.replace('-',' ').replaceFirstChar{it.uppercase()},style=MaterialTheme.typography.headlineSmall,modifier=Modifier.weight(1f));IconButton({vm.load(mode)}){Icon(Icons.Default.Refresh,"Refresh")}};if(s.loading)LinearProgressIndicator(Modifier.fillMaxWidth());s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};s.message?.let{Text(it,color=MaterialTheme.colorScheme.primary)};when(mode){"users"->UserView(s.data,vm);"settings"->SettingsForm(s.data,vm);"custom-fields"->CustomFieldView(s.data,vm);"modules"->ModuleView(s.data,vm);"print-templates"->TemplateView(s.data,vm);"tax-settings"->TaxSettingsForm(s.data,vm);else->JsonRows(s.data)}}}
@Composable private fun SettingsForm(data:JsonElement,vm:AccountAdministrationViewModel){val context=LocalContext.current;val signaturePicker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{val mime=context.contentResolver.getType(it)?:"application/octet-stream";vm.uploadSignature(it.lastPathSegment?:"signature",mime,context.contentResolver.openInputStream(it)!!.readBytes())}};val root=data as? JsonObject?:return;val current=root["settings"]?.jsonObject?:JsonObject(emptyMap());var due by remember(current){mutableStateOf(current["transactionDefaults"]?.jsonObject?.get("defaultDueDays")?.jsonPrimitive?.content?:"0")};var sales by remember(current){mutableStateOf(current["transactionDefaults"]?.jsonObject?.get("salesTerms")?.jsonPrimitive?.content?:"")};var purchase by remember(current){mutableStateOf(current["transactionDefaults"]?.jsonObject?.get("purchaseTerms")?.jsonPrimitive?.content?:"")};var threshold by remember(current){mutableStateOf(current["expenseApprovalThreshold"]?.jsonPrimitive?.content?:"0")};var negative by remember(current){mutableStateOf(current["negativeStockAllowed"]?.jsonPrimitive?.booleanOrNull?:false)};var approval by remember(current){mutableStateOf(current["expenseApprovalRequired"]?.jsonPrimitive?.booleanOrNull?:false)};Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(due,{due=it},label={Text("Default due days")});OutlinedTextField(sales,{sales=it},label={Text("Sales terms")});OutlinedTextField(purchase,{purchase=it},label={Text("Purchase terms")});OutlinedTextField(threshold,{threshold=it},label={Text("Expense approval threshold")});Row{Checkbox(negative,{negative=it});Text("Allow negative stock")};Row{Checkbox(approval,{approval=it});Text("Expense approval required")};Row{Button({signaturePicker.launch(arrayOf("image/jpeg","image/png","image/webp"))}){Text("Upload signature")};TextButton(vm::removeSignature){Text("Remove signature")}};Button({vm.save("settings",buildJsonObject{put("negativeStockAllowed",negative);put("expenseApprovalRequired",approval);put("expenseApprovalThreshold",threshold);putJsonObject("transactionDefaults"){put("defaultDueDays",due.toIntOrNull()?:0);put("salesTerms",sales);put("purchaseTerms",purchase)};putJsonObject("printProfile"){}})}){Text("Save authoritative settings")}}}
@Composable private fun CustomFieldView(data:JsonElement,vm:AccountAdministrationViewModel){val root=data as?JsonObject?:return;var key by remember{mutableStateOf("")};var label by remember{mutableStateOf("")};Column{OutlinedTextField(key,{key=it},label={Text("Field key")});OutlinedTextField(label,{label=it},label={Text("Label")});Button({vm.save("custom-fields",buildJsonObject{put("entityType","CUSTOMER");put("fieldKey",key);put("label",label);put("dataType","TEXT");put("isRequired",false);put("position",0)})}){Text("Create custom field")};JsonRows(root["fields"]?:JsonArray(emptyList()))}}
@Composable private fun ModuleView(data:JsonElement,vm:AccountAdministrationViewModel){val root=data as?JsonObject?:return;val enabled=root["modules"]?.jsonArray?.map{it.jsonPrimitive.content}?.toMutableSet()?:mutableSetOf();var selected by remember(root){mutableStateOf(enabled.toSet())};LazyColumn{items(root["catalog"]?.jsonArray?:JsonArray(emptyList())){e->val x=e.jsonObject,k=x["key"]!!.jsonPrimitive.content;Row{Checkbox(k in selected,{selected=if(it)selected+k else selected-k});Text(x["name"]!!.jsonPrimitive.content)}};item{Button({vm.save("modules",buildJsonObject{put("businessType",root["settings"]?.jsonObject?.get("businessType")?.jsonPrimitive?.content?:"OTHER_MIXED");putJsonArray("enabledModules"){selected.forEach{add(it)}}})}){Text("Save modules")}}}}
@Composable private fun TemplateView(data:JsonElement,vm:AccountAdministrationViewModel){val root=data as?JsonObject?:return;var name by remember{mutableStateOf("")};Column{OutlinedTextField(name,{name=it},label={Text("Template name")});Button({vm.save("print-templates",buildJsonObject{put("documentType","INVOICE");put("name",name);put("paperSize","A4");put("isDefault",false);putJsonObject("config"){put("accentColor","#075985");put("showBank",true);put("showUpiQr",false);put("showSignature",true);put("footer","")}})}){Text("Create invoice template version")};JsonRows(root["templates"]?:JsonArray(emptyList()))}}
@Composable private fun JsonRows(data:JsonElement){val rows=when(data){is JsonArray->data;is JsonObject->data["rows"] as?JsonArray?:data["report"]?.jsonObject?.get("rows") as?JsonArray?:JsonArray(listOf(data));else->JsonArray(emptyList())};LazyColumn{items(rows){x->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Text(x.toString(),Modifier.padding(12.dp),style=MaterialTheme.typography.bodySmall)}}}}

@Composable private fun TaxSettingsForm(data:JsonElement,vm:AccountAdministrationViewModel){val root=data as?JsonObject?:return;val settings=root["settings"] as?JsonObject?:JsonObject(emptyMap());var registration by remember(settings){mutableStateOf(settings["gstRegistrationType"]?.jsonPrimitive?.content?:"UNREGISTERED")};var state by remember(settings){mutableStateOf(settings["defaultStateCode"]?.jsonPrimitive?.content?:"")};var inclusive by remember(settings){mutableStateOf(settings["defaultTaxMode"]?.jsonPrimitive?.content=="INCLUSIVE")};var composition by remember(settings){mutableStateOf(settings["compositionEnabled"]?.jsonPrimitive?.booleanOrNull?:false)};Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(registration,{registration=it},label={Text("GST registration type")});OutlinedTextField(state,{state=it},label={Text("Default state code")});Row{Checkbox(inclusive,{inclusive=it});Text("Tax-inclusive pricing")};Row{Checkbox(composition,{composition=it});Text("Composition scheme")};Button({vm.save("tax-settings",buildJsonObject{put("gstRegistrationType",registration);if(state.isNotBlank())put("defaultStateCode",state);put("compositionEnabled",composition);put("defaultTaxMode",if(inclusive)"INCLUSIVE" else "EXCLUSIVE")})}){Text("Save tax settings")};Text("Branch GST profiles");JsonRows(root["branches"]?:JsonArray(emptyList()))}}

@Composable private fun UserView(data:JsonElement,vm:AccountAdministrationViewModel){val root=data as?JsonObject?:return;var name by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var role by remember{mutableStateOf("ACCOUNTANT")};Column{OutlinedTextField(name,{name=it},label={Text("Name")});OutlinedTextField(email,{email=it},label={Text("Email")});OutlinedTextField(password,{password=it},label={Text("Temporary password")});OutlinedTextField(role,{role=it},label={Text("Account role")});Button({vm.saveUser(buildJsonObject{put("name",name);put("email",email);put("password",password);put("confirmPassword",password);put("accountRole",role);put("branchAccessScope","ALL_BRANCHES");putJsonArray("branchIds"){}})}){Text("Create Account user")};Text("Effective roles and access");LazyColumn{items(root["users"]?.jsonArray?:JsonArray(emptyList())){e->val u=e.jsonObject;Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(u["name"]!!.jsonPrimitive.content);Text("${u["accountRole"]?.jsonPrimitive?.contentOrNull?:"No Account role"} · ${u["branchAccessScope"]?.jsonPrimitive?.content?:""}");Button({vm.saveUser(buildJsonObject{put("userId",u["id"]!!.jsonPrimitive.content);u["accountRole"]?.jsonPrimitive?.contentOrNull?.let{put("accountRole",it)}?:put("accountRole",JsonNull);put("accountAccessActive",!(u["accountAccessActive"]?.jsonPrimitive?.booleanOrNull?:false));put("branchAccessScope",u["branchAccessScope"]?.jsonPrimitive?.content?:"ALL_BRANCHES");putJsonArray("branchIds"){u["branchAccesses"]?.jsonArray?.forEach{a->add(a.jsonObject["branchId"]!!.jsonPrimitive.content)}}})}){Text(if(u["accountAccessActive"]?.jsonPrimitive?.booleanOrNull==true)"Deactivate Account access" else "Reactivate Account access")}}}}}}
