package com.salespunch360.mobile.ui.account.admin
import android.content.Intent
import java.io.File
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.salespunch360.mobile.AccountUtilityViewModel
import kotlinx.serialization.json.*
@Composable fun AccountUtilityScreen(mode:String,padding:PaddingValues,vm:AccountUtilityViewModel=viewModel()){val s=vm.state.collectAsStateWithLifecycle().value;val context=LocalContext.current;var importType by remember{mutableStateOf("CUSTOMERS")};var confirmRestore by remember{mutableStateOf<String?>(null)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?.let{val name=uri.lastPathSegment?.substringAfterLast('/')?:"import.csv",mime=context.contentResolver.getType(uri)?:if(name.endsWith(".xlsx"))"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" else "text/csv";vm.upload(importType,name,mime,context.contentResolver.openInputStream(uri)!!.readBytes(),false)}};LaunchedEffect(mode){vm.load(mode)};LaunchedEffect(s.file){s.file?.let{val f=File(context.cacheDir,it.first);f.writeBytes(it.second);val uri=FileProvider.getUriForFile(context,"${context.packageName}.files",f);context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType(if(f.extension=="xlsx")"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" else "application/json").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION),"Share ${f.name}"));vm.consumed()}};Column(Modifier.fillMaxSize().padding(padding).padding(16.dp)){Text(mode.replaceFirstChar{it.uppercase()},style=MaterialTheme.typography.headlineSmall);s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};s.message?.let{Text(it,color=MaterialTheme.colorScheme.primary)};when(mode){"import"->{Row{listOf("CUSTOMERS","VENDORS","ITEMS","PROJECTS","OPENING_BALANCES").forEach{FilterChip(importType==it,{importType=it},{Text(it)})}};Button({picker.launch(arrayOf("text/csv","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))}){Text("Choose CSV or XLSX")};s.preview?.let{p->Text("Valid ${p["validCount"]} · Invalid ${p["invalidCount"]}");JsonList(p["rows"] as?JsonArray?:JsonArray(emptyList()));val id=p["job"]?.jsonObject?.get("id")?.jsonPrimitive?.content;if(id!=null&&p["invalidCount"]?.jsonPrimitive?.intOrNull==0)Button({vm.execute(id)}){Text("Confirm authoritative import")}}};"export"->{listOf("customers","vendors","items","projects","chart-of-accounts").forEach{type->Row{Text(type,Modifier.weight(1f));Button({vm.export(type,"csv")}){Text("CSV")};Button({vm.export(type,"xlsx")}){Text("XLSX")}}}};"backup"->Button(vm::backup){Text("Generate and share backup")};else->JsonList(s.rows){id->confirmRestore=id}}};confirmRestore?.let{id->AlertDialog(onDismissRequest={confirmRestore=null},title={Text("Restore record?")},text={Text("The server will verify conflicts and permissions before restoring.")},confirmButton={Button({vm.restored(id);confirmRestore=null}){Text("Restore")}},dismissButton={TextButton({confirmRestore=null}){Text("Cancel")}})}}
@Composable private fun JsonList(rows:JsonArray,onRestore:((String)->Unit)?=null){LazyColumn{items(rows){e->val x=e.jsonObject;Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(x["displayName"]?.jsonPrimitive?.content?:x["fileName"]?.jsonPrimitive?.content?:x.toString());onRestore?.let{Button({it(x["id"]!!.jsonPrimitive.content)}){Text("Restore")}}}}}}}
