import {WorkspacePageHeader} from '@/components/workspace/workspace-page-header';
import {billingDashboard} from '@/lib/billing/service';
import {getTelecallerBillingOverview} from '@/lib/billing/telecaller';
import {unifiedTelecallerOrderFields} from '@/lib/billing/unified-sales-team';
import {AccountIncreaseCalculator,AddTeamCalculator,BillingCalculator} from './billing-calculator';
import {ACCOUNT_PACKAGE_ORDER_PROVIDER} from '@/lib/billing/account-package';
import {PLUS_ORDER_PROVIDER} from '@/lib/billing/combined-order';

type Search=Promise<Record<string,string|string[]|undefined>>;
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const orderErrors:Record<string,string>={SEATS_BELOW_USAGE:'The selected seat count is below your current active users. Keep enough seats for the active team before creating this order.',INVALID_SEAT_SELECTION:'The selected users to retain do not match the active team. Review the retention selection and try again.',SEAT_SELECTION_REQUIRED:'For a seat reduction, leave retention empty for automatic retention or select exactly the users you want to keep.',SEAT_REDUCTION_SELECTION_REQUIRED:'The renewal retention selection is no longer valid. Review the active users and try again.',PRICING_UNAVAILABLE:'Current subscription pricing is unavailable. Please try again shortly.',MANAGERS_DISABLED:'Manager seats are not available for the selected Sales team structure.',PLUS_ACCOUNT_PACKAGE_REQUIRED:'Plus requires at least one Account package.',ACCOUNT_PACKAGE_NOT_ALLOWED:'Account packages are not available for this Sales-only order.',INVALID_TELECALLER_SEATS:'Enter a valid Telecaller seat count.',TELECALLER_SEATS_BELOW_USAGE:'Telecaller seats cannot be below your active Telecaller employees. Deactivate employees first.',ADD_TEAM_CANNOT_REDUCE_TELECALLERS:'Add Team can only increase Telecaller seats. Use Renewal for next-term changes.',ACTIVE_SALES_SUBSCRIPTION_REQUIRED:'An active Sales subscription is required before adding team seats.',BILLING_PERIOD_MISMATCH:'Add Team must use the current Sales subscription period.',RATE_LIMITED:'Too many billing requests were submitted. Wait a minute and try again.',UNTRUSTED_ORIGIN:'The billing security check could not verify this request. Return to Billing and try again.',INVALID_INPUT:'The billing request is incomplete. Review the selected plan and try again.',ORDER_CREATE_FAILED:'The payment request could not be created. Please review the order and try again.'};
const date=(value:Date|null|undefined)=>value?value.toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'}):'—';
const summaryStyle={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(118px,1fr))',gap:8} as const;
const tileStyle={padding:'10px 12px',border:'1px solid var(--line)',borderRadius:10,display:'grid',gap:3,minHeight:62} as const;
const Tile=({value,label}:{value:string;label:string})=><article style={tileStyle}><strong>{value}</strong><span style={{fontSize:12,color:'var(--muted)'}}>{label}</span></article>;

export default async function Page({searchParams}:{searchParams:Search}){
 const q=await searchParams,orderError=one(q.orderError),r=await billingDashboard(),e=r.entitlement;
 const telecaller=r.hasSales?await getTelecallerBillingOverview():null;
 const orderTelecaller=await unifiedTelecallerOrderFields(r.orders.map(o=>o.id));
 const managersEnabled=r.company?.teamStructure==='MANAGERS_AND_SALES',backHref=r.company?.productEdition==='SALESPUNCH360_ACCOUNT'?'/workspace/account':'/workspace';
 const price=(role:'ADMIN'|'MANAGER'|'SALES',period:'SIX_MONTH'|'YEARLY',fallback:number)=>Number(r.prices.find(p=>p.role===role&&p.period===period)?.amount??fallback),prices={SIX_MONTH:{admin:price('ADMIN','SIX_MONTH',1400),manager:price('MANAGER','SIX_MONTH',1100),sales:price('SALES','SIX_MONTH',800)},YEARLY:{admin:price('ADMIN','YEARLY',2800),manager:price('MANAGER','YEARLY',2100),sales:price('SALES','YEARLY',1500)}},accountPrices={SIX_MONTH:r.account.sixMonthUnitPrice,YEARLY:r.account.yearlyUnitPrice};
 const accountCurrent=r.account.subscriptions[0],isPlus=r.company?.productEdition==='SALESPUNCH360_PLUS',salesStatus=e?(e.paidActive?'ACTIVE':e.trialActive?'TRIAL':r.company?.subscriptionStatus==='ACTIVE'?'ACTIVE':'INACTIVE'):'INACTIVE',accountStatus=accountCurrent?'ACTIVE':r.company?.subscriptionStatus==='TRIAL'&&r.account.packageCount>0?'TRIAL':'INACTIVE',activePeriod=(e?.subscription?.billingPeriod??'SIX_MONTH') as 'SIX_MONTH'|'YEARLY',activeEmployees=r.activeEmployees as {id:string;name:string;salesRole:'ADMIN'|'MANAGER'|'SALES';managerType?:string|null}[];
 const telecallerUsage=telecaller?.used??0,telecallerLimit=telecaller?.limit??0;
 return <main className="billing-content"><WorkspacePageHeader title="Billing & Subscription" backHref={backHref}/>{orderError&&<section className="billing-card"><p className="form-error">{orderErrors[orderError]??orderErrors.ORDER_CREATE_FAILED}</p></section>}
 {r.hasSales&&e&&<section className="billing-card"><h2>Sales Subscription</h2><div style={summaryStyle}><Tile value={salesStatus} label="Status"/><Tile value={date(e.subscription?.endsAt??r.company?.trialEndsAt)} label="Valid until / renewal"/><Tile value={`${e.adminUsage} / ${e.adminLimit}`} label="Additional Admin"/>{managersEnabled&&<Tile value={`${e.managerUsage} / ${e.managerLimit}`} label="Manager"/>}<Tile value={`${e.salesUsage} / ${e.salesLimit}`} label="Sales"/><Tile value={`${telecallerUsage} / ${telecallerLimit}`} label="Telecaller"/></div>{e.paidActive&&<details id="sales-add-team" className="billing-purchase"><summary>Add Team</summary><AddTeamCalculator managersEnabled={managersEnabled} adminLimit={e.adminLimit} managerLimit={e.managerLimit} salesLimit={e.salesLimit} telecallerLimit={telecallerLimit} period={activePeriod} prices={prices} isPlus={isPlus} accountPackages={Math.max(1,r.account.packageCount)} endsAt={e.subscription?.endsAt}/></details>}{!isPlus&&<details id="sales-purchase" className="billing-purchase"><summary>{e.paidActive?'Renewal':'Choose Sales Plan'}</summary><BillingCalculator managersEnabled={managersEnabled} adminUsage={e.adminUsage} managerUsage={e.managerUsage} salesUsage={e.salesUsage} telecallerUsage={telecallerUsage} telecallerLimit={telecallerLimit} prices={prices} isRenewal={e.paidActive} activeEmployees={activeEmployees} initialAdminSeats={e.paidActive?e.adminLimit:e.adminUsage} initialManagerSeats={e.paidActive?e.managerLimit:e.managerUsage} initialSalesSeats={e.paidActive?e.salesLimit:e.salesUsage}/></details>}</section>}
 {r.hasAccount&&<section className="billing-card"><h2>Account Subscription</h2><div style={summaryStyle}><Tile value={accountStatus} label="Status"/><Tile value={date(accountCurrent?.endsAt??(accountStatus==='TRIAL'?r.company?.trialEndsAt:null))} label="Valid until / renewal"/><Tile value={`${r.account.usage.ACCOUNT_ADMIN} / ${r.account.limits.ACCOUNT_ADMIN}`} label="Account Admin"/><Tile value={`${r.account.usage.ACCOUNTANT} / ${r.account.limits.ACCOUNTANT}`} label="Accountant"/><Tile value={`${r.account.usage.PROJECT_MANAGER} / ${r.account.limits.PROJECT_MANAGER}`} label="Project Manager"/><Tile value={`${r.account.usage.DATA_ENTRY} / ${r.account.limits.DATA_ENTRY}`} label="Data Entry"/></div>{isPlus&&e&&e.paidActive&&accountStatus==='ACTIVE'&&<details id="account-increase" className="billing-purchase"><summary>Increase Account Packages</summary><AccountIncreaseCalculator managersEnabled={managersEnabled} adminLimit={e.adminLimit} managerLimit={e.managerLimit} salesLimit={e.salesLimit} period={activePeriod} currentPackages={Math.max(1,r.account.packageCount)} accountPrice={accountPrices[activePeriod]} endsAt={accountCurrent?.endsAt??e.subscription?.endsAt}/></details>}{isPlus&&e?<details id="plus-purchase" className="billing-purchase"><summary>{e.paidActive?'Renewal':'Choose Plus Plan'}</summary><BillingCalculator managersEnabled={managersEnabled} adminUsage={e.adminUsage} managerUsage={e.managerUsage} salesUsage={e.salesUsage} telecallerUsage={telecallerUsage} telecallerLimit={telecallerLimit} prices={prices} isRenewal={e.paidActive} activeEmployees={activeEmployees} isPlus accountPackages={Math.max(1,r.account.packageCount)} accountPrices={accountPrices} initialAdminSeats={e.paidActive?e.adminLimit:e.adminUsage} initialManagerSeats={e.paidActive?e.managerLimit:e.managerUsage} initialSalesSeats={e.paidActive?e.salesLimit:e.salesUsage}/></details>:!isPlus?<details className="billing-purchase"><summary>Add / Renew Account Seats</summary><form action="/workspace/billing/checkout/account" method="GET" className="billing-form"><p className="muted">6 Months ₹{r.account.sixMonthUnitPrice.toLocaleString('en-IN')} · 1 Year ₹{r.account.yearlyUnitPrice.toLocaleString('en-IN')} per package.</p><label>Billing period<select name="billingPeriod" defaultValue="SIX_MONTH"><option value="SIX_MONTH">6 Months</option><option value="YEARLY">1 Year</option></select></label><label>Additional packages<input name="quantity" type="number" min="1" max="100" defaultValue="1"/></label><button>Continue to Checkout</button></form></details>:null}</section>}
 <details className="billing-card"><summary><strong>Order & payment history</strong></summary>{r.orders.length===0&&(!telecaller||telecaller.orders.length===0)&&<p className="muted">No orders yet.</p>}{r.orders.map(o=>{const t=orderTelecaller.get(o.id);return <article className="history-row" key={o.id}><div><strong>{o.provider===ACCOUNT_PACKAGE_ORDER_PROVIDER?`${o.accountPackages||o.adminSeats} Account package${(o.accountPackages||o.adminSeats)===1?'':'s'} · ${o.billingPeriod}`:o.provider===PLUS_ORDER_PROVIDER?`${o.billingPeriod} · ${o.adminSeats} Admin / ${o.managerSeats} Manager / ${o.salesSeats} Sales${t?.telecallerIncluded?` / ${t.telecallerSeats} Telecaller`:''} + ${o.accountPackages} Account package${o.accountPackages===1?'':'s'}`:`${o.billingPeriod} · ${o.adminSeats} Admin / ${o.managerSeats} Manager / ${o.salesSeats} Sales${t?.telecallerIncluded?` / ${t.telecallerSeats} Telecaller`:''}`}</strong><span>{o.createdAt.toLocaleString('en-IN')} · Ref {o.id.slice(0,8)}</span></div><b>{o.currency} {o.totalAmount.toFixed(2)} · {o.status}</b></article>})}{telecaller?.orders.map(o=><article className="history-row" key={`legacy-${o.id}`}><div><strong>Telecaller · {o.billingPeriod} · +{o.addedSeats} seats</strong><span>Historical Telecaller order · {o.createdAt.toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · Ref {o.id.slice(0,8)}</span></div><b>INR {o.totalAmount.toFixed(2)} · {o.status}</b></article>)}</details>
 </main>;
}
