import { describe,expect,it } from "vitest";import fs from "node:fs";
const read=(p:string)=>fs.readFileSync(p,"utf8"),service=read("src/lib/quotations/service.ts"),schema=read("prisma/schema.prisma"),migration=read("prisma/migrations/20260910020000_a3_quotation_estimate_boq/migration.sql"),cleanup=read("src/lib/tenant-cleanup.ts")+read("src/lib/tenant-cleanup-database.ts");
describe("A3 architecture and database contract",()=>{
 it("uses one typed document/revision engine",()=>{expect(schema).toContain("enum QuotationDocumentType");expect(schema).toContain("model QuotationDocument");expect(schema).toContain("model QuotationRevision");expect(schema).not.toContain("model EstimateDocument")});
 it("uses the shared transaction allocator with branch-safe uniqueness",()=>{expect(service).toContain("allocateDocumentNumberInTx");expect(service).not.toMatch(/UPDATE numbering_series/);expect(schema).toContain("@@unique([companyId, branchId, documentType, documentNumber])")});
 it("has decimal quantity/money and revision/share uniqueness",()=>{expect(schema).toContain("@db.Decimal(18, 4)");expect(schema).toContain("@db.Decimal(18, 2)");expect(schema).toContain("@@unique([documentId, revisionNumber])");expect(schema).toContain("tokenHash  String");expect(schema).toContain("@unique")});
 it("derives tenant from actor and enforces branch and master tenant filters",()=>{expect(service).not.toMatch(/companyId:z\./);expect(service).toContain("companyId:a.companyId!");expect(service).toContain("branchAccessScope");for(const name of ["accountProduct","accountService","workPackage","accountUnit","customer"])expect(service).toContain(name)});
 it("gates Plus leads through Sales identity and existing scope",()=>{expect(service).toContain("SALESPUNCH360_PLUS");expect(service).toContain("salesAccessActive");expect(service).toContain("visibilityWhere")});
 it("filters private costs before unauthenticated output",()=>{const publicBody=service.slice(service.indexOf("export async function getPublicQuotation"));expect(publicBody).toContain("internalCostTotal:");expect(publicBody).toContain("expectedMarginPercent:")});
 it("is additive, explicitly transactional and registers cleanup child-first",()=>{expect(migration.startsWith("BEGIN;")).toBe(true);expect(migration.trimEnd().endsWith("COMMIT;")).toBe(true);const order=cleanup.slice(cleanup.indexOf('export const DELETE_ORDER'));expect(order.indexOf('\"QuotationAuditEvent\"')).toBeLessThan(order.indexOf('\"QuotationDocument\"'))});
 it("does not post accounting, win a lead, or create a project",()=>{expect(service).not.toMatch(/journalEntry\.(create|update)/);expect(service).not.toMatch(/lead\.(update|create)/);expect(service).not.toMatch(/project\.(create|update)/)});
});
