import {beforeEach,describe,expect,it,vi} from "vitest";import {Prisma} from "@prisma/client";
const C="11111111-1111-4111-8111-111111111111",B="22222222-2222-4222-8222-222222222222",ID="33333333-3333-4333-8333-333333333333",R="44444444-4444-4444-8444-444444444444";
const m=vi.hoisted(()=>({auth:vi.fn(),allocate:vi.fn(),visibility:vi.fn(()=>({assignedUserId:"actor"})),txRun:vi.fn(),branch:vi.fn(),customer:vi.fn(),company:vi.fn(),lead:vi.fn(),product:vi.fn(),service:vi.fn(),work:vi.fn(),unit:vi.fn(),docCreate:vi.fn(),docFind:vi.fn(),docMany:vi.fn(),docUpdateMany:vi.fn(),revisionCreate:vi.fn(),revisionFind:vi.fn(),revisionUpdate:vi.fn(),revisionDelete:vi.fn(),lineCreate:vi.fn(),lineDelete:vi.fn(),adjustCreate:vi.fn(),adjustDelete:vi.fn(),paymentCreate:vi.fn(),paymentDelete:vi.fn(),auditCreate:vi.fn(),shareCreate:vi.fn(),shareFind:vi.fn(),shareUpdateMany:vi.fn(),raw:vi.fn(),listDocs:vi.fn()}));
vi.mock("@/lib/auth/authorization",()=>({requirePermission:m.auth,requirePermissionForMutation:m.auth}));vi.mock("@/lib/account/numbering",()=>({allocateDocumentNumberInTx:m.allocate}));vi.mock("@/lib/leads/policy",()=>({visibilityWhere:m.visibility}));
const tx={branch:{findFirst:m.branch},customer:{findFirst:m.customer},company:{findUnique:m.company},lead:{findFirst:m.lead},accountProduct:{findFirst:m.product},accountService:{findFirst:m.service},workPackage:{findFirst:m.work},accountUnit:{findFirst:m.unit},quotationDocument:{create:m.docCreate,findFirst:m.docFind,updateMany:m.docUpdateMany},quotationRevision:{create:m.revisionCreate,findFirst:m.revisionFind,update:m.revisionUpdate,delete:m.revisionDelete},quotationLine:{createMany:m.lineCreate,deleteMany:m.lineDelete},quotationAdjustment:{createMany:m.adjustCreate,deleteMany:m.adjustDelete},quotationPaymentSchedule:{createMany:m.paymentCreate,deleteMany:m.paymentDelete},quotationAuditEvent:{create:m.auditCreate},quotationShare:{create:m.shareCreate,findFirst:m.shareFind,updateMany:m.shareUpdateMany},$queryRaw:m.raw};
vi.mock("@/lib/db",()=>({db:{$transaction:m.txRun,quotationDocument:{findMany:m.listDocs,findFirst:m.docFind,fields:{currentRevisionNumber:"currentRevisionNumber"}},quotationRevision:{findFirst:m.revisionFind},quotationShare:{findFirst:m.shareFind},company:{findUniqueOrThrow:m.company},branch:{findMany:vi.fn()},customer:{findMany:vi.fn()},accountProduct:{findMany:vi.fn()},accountService:{findMany:vi.fn()},workPackage:{findMany:vi.fn()},accountUnit:{findMany:vi.fn()},lead:{findMany:vi.fn()}}}));
import {createQuotation,createQuotationRevision,createShare,getPublicQuotation,listQuotations,revokeShare,transitionQuotation,updateQuotationDraft} from "./service";
const actor=(role:"ACCOUNT_ADMIN"|"ACCOUNTANT"|"PROJECT_MANAGER"|"DATA_ENTRY"="ACCOUNT_ADMIN",extra={})=>({id:"actor",companyId:C,accountRole:role,accountAccessActive:true,salesAccessActive:false,salesRole:null,branchAccessScope:"ALL_BRANCHES",branchIds:[],...extra});
const input=(overrides:Record<string,unknown>={})=>({branchId:B,documentType:"QUOTATION",customerId:ID,issueDate:"2026-09-10",lines:[{lineType:"CUSTOM",itemName:"Work",quantity:"1",rate:"100",taxRate:"18"}],adjustments:[],paymentSchedule:[],...overrides});
const customer={name:"Acme",contactPerson:"P",phone:"1",email:"a@b.c",billingAddress:"Bill",shippingAddress:"Site",address:null,gstin:null,pan:null};
const revision=(status="DRAFT")=>({id:R,companyId:C,documentId:ID,revisionNumber:0,status,issueDate:new Date(),validUntil:null,customerName:"Acme",contactPerson:null,phone:null,email:null,billingAddress:null,siteAddress:null,gstin:null,pan:null,terms:null,inclusions:null,exclusions:null,notes:null,subtotal:new Prisma.Decimal(100),discountTotal:new Prisma.Decimal(0),additionalChargeTotal:new Prisma.Decimal(0),taxableTotal:new Prisma.Decimal(100),taxTotal:new Prisma.Decimal(18),grandTotal:new Prisma.Decimal(118),internalCostTotal:new Prisma.Decimal(0),expectedProfit:new Prisma.Decimal(100),expectedMarginPercent:new Prisma.Decimal(100),lines:[{quantity:"1",rate:"100",taxRate:"18",internalUnitCost:"0"}],adjustments:[],paymentSchedule:[],shares:[]});
beforeEach(()=>{vi.clearAllMocks();m.auth.mockResolvedValue(actor());m.txRun.mockImplementation((fn:unknown)=>typeof fn==="function"?(fn as (x:typeof tx)=>unknown)(tx):fn);m.branch.mockResolvedValue({id:B});m.customer.mockResolvedValue(customer);m.company.mockResolvedValue({productEdition:"SALESPUNCH360_PLUS"});m.allocate.mockResolvedValue("Q-000001");m.docCreate.mockResolvedValue({id:ID});m.revisionCreate.mockResolvedValue({id:R});m.docUpdateMany.mockResolvedValue({count:1});m.shareUpdateMany.mockResolvedValue({count:1});m.raw.mockResolvedValue([])});
describe("A3 service runtime create and authorization",()=>{
 it("requires Account product permission",async()=>{m.auth.mockRejectedValue(new Error("Not authorized"));await expect(createQuotation(input())).rejects.toThrow("Not authorized")});
 it("denies a Sales-only identity at the Account boundary",async()=>{m.auth.mockRejectedValue(new Error("Not authorized"));await expect(createQuotation(input())).rejects.toThrow()});
 it("rejects an unauthorized or cross-company Branch",async()=>{m.branch.mockResolvedValue(null);await expect(createQuotation(input())).rejects.toThrow("INVALID_BRANCH")});
 it("rejects a cross-company Customer",async()=>{m.customer.mockResolvedValue(null);await expect(createQuotation(input())).rejects.toThrow("INVALID_CUSTOMER")});
 it.each([["PRODUCT","product"],["SERVICE","service"],["WORK_PACKAGE","work"]] as const)("rejects a cross-company %s",async(type,key)=>{m[key].mockResolvedValue(null);await expect(createQuotation(input({lines:[{lineType:type,sourceId:ID,quantity:"1"}]}))).rejects.toThrow("INVALID_LINE_REFERENCE")});
 it("rejects a cross-company Unit",async()=>{m.unit.mockResolvedValue(null);await expect(createQuotation(input({lines:[{lineType:"CUSTOM",itemName:"X",unitId:ID,quantity:"1",rate:"1"}]}))).rejects.toThrow("INVALID_UNIT")});
 it("uses the shared allocator and writes snapshots",async()=>{await createQuotation(input());expect(m.allocate).toHaveBeenCalledWith(tx,expect.objectContaining({companyId:C,branchId:B,seriesKey:"QUOTATION"}));expect(m.lineCreate).toHaveBeenCalledWith({data:[expect.objectContaining({itemName:"Work",quantity:"1",rate:"100",taxAmount:expect.anything()})]})});
});
describe("Plus Lead boundary",()=>{
 const leadInput=()=>input({customerId:undefined,sourceLeadId:ID});
 it("denies Account-only identity",async()=>{await expect(createQuotation(leadInput())).rejects.toThrow("LEAD_ACCESS_REQUIRED")});
 it("denies Lead use outside Plus",async()=>{m.auth.mockResolvedValue(actor("ACCOUNT_ADMIN",{salesAccessActive:true,salesRole:"ADMIN"}));m.company.mockResolvedValue({productEdition:"SALESPUNCH360_ACCOUNT"});await expect(createQuotation(leadInput())).rejects.toThrow("PLUS_LEAD_REQUIRED")});
 it("allows an authorized Plus Lead and applies existing visibility scope without mutation",async()=>{m.auth.mockResolvedValue(actor("ACCOUNT_ADMIN",{salesAccessActive:true,salesRole:"MANAGER"}));m.lead.mockResolvedValue({companyName:"Lead Co",title:"Lead",contactName:"C",phone:"1",email:null});await createQuotation(leadInput());expect(m.visibility).toHaveBeenCalled();expect(m.lead).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({companyId:C,branchId:B,assignedUserId:"actor"})}));expect(m.lead).not.toHaveBeenCalledWith(expect.objectContaining({data:expect.anything()}))});
 it("rejects a cross-company or invisible Lead",async()=>{m.auth.mockResolvedValue(actor("ACCOUNT_ADMIN",{salesAccessActive:true,salesRole:"ADMIN"}));m.lead.mockResolvedValue(null);await expect(createQuotation(leadInput())).rejects.toThrow("INVALID_LEAD")});
});
describe("cost, draft, revision and lifecycle",()=>{
 it.each(["ACCOUNT_ADMIN","ACCOUNTANT","PROJECT_MANAGER"] as const)("allows %s cost override",async role=>{m.auth.mockResolvedValue(actor(role));await createQuotation(input({lines:[{lineType:"CUSTOM",itemName:"X",quantity:"1",rate:"100",internalUnitCost:"60"}]}));expect(m.lineCreate).toHaveBeenCalledWith({data:[expect.objectContaining({internalUnitCost:"60"})]})});
 it("rejects Data Entry cost override",async()=>{m.auth.mockResolvedValue(actor("DATA_ENTRY"));await expect(createQuotation(input({lines:[{lineType:"CUSTOM",itemName:"X",quantity:"1",rate:"1",internalUnitCost:"1"}]}))).rejects.toThrow("QUOTATION_COST_PERMISSION_REQUIRED")});
 it("strips list cost totals for Data Entry",async()=>{m.auth.mockResolvedValue(actor("DATA_ENTRY"));m.listDocs.mockResolvedValue([{id:ID,revisions:[{grandTotal:118,internalCostTotal:60,expectedProfit:40,expectedMarginPercent:40}]}]);expect(JSON.stringify(await listQuotations())).not.toMatch(/internalCost|expectedProfit|expectedMargin/)});
 it("edits Draft by deleting children then recreating, but rejects issued",async()=>{m.docFind.mockResolvedValue({id:ID,companyId:C,branchId:B,documentType:"QUOTATION",customerId:ID,sourceLeadId:null,status:"DRAFT",revisions:[revision()]});await updateQuotationDraft(ID,input());expect(m.revisionDelete).toHaveBeenCalledWith({where:{id:R}});m.docFind.mockResolvedValue(null);await expect(updateQuotationDraft(ID,input())).rejects.toThrow("DRAFT_NOT_EDITABLE")});
 it("preserves old revisions and creates the next under a lock",async()=>{m.docFind.mockResolvedValue({id:ID,companyId:C,branchId:B,documentType:"QUOTATION",customerId:ID,sourceLeadId:null,status:"APPROVED",currentRevisionNumber:0});await createQuotationRevision(ID,input());expect(m.raw).toHaveBeenCalled();expect(m.revisionDelete).not.toHaveBeenCalled();expect(m.revisionCreate).toHaveBeenCalledWith({data:expect.objectContaining({revisionNumber:1})})});
 it("rejects revision identity changes",async()=>{m.docFind.mockResolvedValue({id:ID,companyId:C,branchId:B,documentType:"QUOTATION",customerId:ID,sourceLeadId:null,status:"APPROVED",currentRevisionNumber:0});await expect(createQuotationRevision(ID,input({branchId:ID}))).rejects.toThrow("DOCUMENT_IDENTITY_IMMUTABLE")});
 it("requires approval permission and rejects invalid transitions",async()=>{m.auth.mockRejectedValue(new Error("Not authorized"));await expect(transitionQuotation(ID,"APPROVED")).rejects.toThrow();m.auth.mockResolvedValue(actor());m.docFind.mockResolvedValue({id:ID,status:"ACCEPTED",revisions:[revision("ACCEPTED")],branch:{},company:{},audits:[]});await expect(transitionQuotation(ID,"SENT")).rejects.toThrow("INVALID_TRANSITION")});
});
describe("share concurrency and public DTO",()=>{
 it("locks and conditionally moves APPROVED to SENT",async()=>{m.docFind.mockResolvedValue({id:ID,status:"APPROVED",revisions:[revision("APPROVED")],branch:{},company:{},audits:[]});const token=await createShare(ID);expect(token).toMatch(/^[A-Za-z0-9_-]{40,}$/);expect(m.raw).toHaveBeenCalled();expect(m.docUpdateMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({status:"APPROVED"})}));expect(m.shareCreate.mock.calls[0][0].data).toHaveProperty("tokenHash");expect(m.shareCreate.mock.calls[0][0].data).not.toHaveProperty("token")});
 it("cannot regress accepted/cancelled state during share",async()=>{m.docFind.mockResolvedValue({id:ID,status:"ACCEPTED",revisions:[revision("ACCEPTED")],branch:{},company:{},audits:[]});await expect(createShare(ID)).rejects.toThrow("APPROVAL_REQUIRED");expect(m.docUpdateMany).not.toHaveBeenCalled()});
 it("revocation is idempotent and audits once",async()=>{m.shareFind.mockResolvedValue({id:ID,companyId:C,revision:{documentId:ID,revisionNumber:0}});m.shareUpdateMany.mockResolvedValueOnce({count:1}).mockResolvedValueOnce({count:0});expect(await revokeShare(ID)).toBe(true);expect(await revokeShare(ID)).toBe(false);expect(m.auditCreate).toHaveBeenCalledTimes(1)});
 it("returns only the explicit public DTO",async()=>{m.shareFind.mockResolvedValue({revision:{revisionNumber:0,customerName:"Acme",document:{documentType:"QUOTATION",documentNumber:"Q-1",company:{name:"Safe"},branch:{name:"Main"}},lines:[],adjustments:[],paymentSchedule:[]}});const result=await getPublicQuotation("token");const json=JSON.stringify(result);expect(json).toContain("Safe");expect(json).not.toMatch(/companyId|customerId|sourceLeadId|createdById|logoObjectKey|subscriptionStatus|internalCost|expectedProfit/);expect(m.shareFind).toHaveBeenCalledWith(expect.objectContaining({select:expect.anything()}))});
});
