import { createHash, randomBytes } from "node:crypto";
import { Prisma, type QuotationStatus } from "@prisma/client";
import { z } from "zod";
import { db } from "@/lib/db";
import { requirePermission, requirePermissionForMutation } from "@/lib/auth/authorization";
import { accountRoleHasCapability } from "@/lib/auth/account-capabilities";
import { allocateDocumentNumberInTx } from "@/lib/account/numbering";
import { visibilityWhere } from "@/lib/leads/policy";
import { calculateQuotation, reconcilePaymentSchedule } from "./calculation";

const decimal=z.union([z.string(),z.number()]).transform(String);
const line=z.object({lineType:z.enum(["PRODUCT","SERVICE","WORK_PACKAGE","CUSTOM"]),sourceId:z.string().uuid().optional(),unitId:z.string().uuid().optional(),itemName:z.string().trim().min(1).max(240).optional(),description:z.string().max(10000).optional(),specification:z.string().max(20000).optional(),unitName:z.string().max(80).optional(),unitSymbol:z.string().max(20).optional(),quantity:decimal,rate:decimal.optional(),internalUnitCost:decimal.optional(),taxRate:decimal.optional(),discountType:z.enum(["PERCENTAGE","FIXED"]).nullable().optional(),discountValue:decimal.nullable().optional()});
const adjustment=z.object({type:z.enum(["DISCOUNT","ADDITIONAL_CHARGE"]),label:z.string().trim().min(1).max(160),valueType:z.enum(["PERCENTAGE","FIXED"]),value:decimal,taxable:z.boolean().optional(),taxRate:decimal.optional()});
const payment=z.object({label:z.string().trim().min(1).max(160),valueType:z.enum(["PERCENTAGE","FIXED"]),value:decimal,dueDescription:z.string().max(500).optional()});
export const quotationInput=z.object({branchId:z.string().uuid(),documentType:z.enum(["QUOTATION","ESTIMATE","BOQ"]),customerId:z.string().uuid().optional(),sourceLeadId:z.string().uuid().optional(),issueDate:z.coerce.date(),validUntil:z.coerce.date().optional(),terms:z.string().max(30000).optional(),inclusions:z.string().max(30000).optional(),exclusions:z.string().max(30000).optional(),notes:z.string().max(30000).optional(),lines:z.array(line).min(1).max(500),adjustments:z.array(adjustment).max(50).default([]),paymentSchedule:z.array(payment).max(50).default([])}).refine(v=>!!v.customerId!==!!v.sourceLeadId,{message:"Choose exactly one Customer or Plus Lead"});
type Actor=Awaited<ReturnType<typeof requirePermissionForMutation>>;
function branchWhere(a:Actor,branchId?:string){return {companyId:a.companyId!,isActive:true,id:branchId,...(a.branchAccessScope==="SELECTED_BRANCHES"?{id:{in:a.branchIds??[],...(branchId?{equals:branchId}:{})}}:{})};}
async function assertBranch(a:Actor,id:string,tx:Prisma.TransactionClient){if(!await tx.branch.findFirst({where:branchWhere(a,id),select:{id:true}}))throw new Error("INVALID_BRANCH");}
async function commercialSnapshot(a:Actor,d:z.infer<typeof quotationInput>,tx:Prisma.TransactionClient){
 if(d.customerId){const c=await tx.customer.findFirst({where:{id:d.customerId,companyId:a.companyId!,isActive:true,isAccountCustomer:true},select:{name:true,contactPerson:true,phone:true,email:true,billingAddress:true,shippingAddress:true,address:true,gstin:true,pan:true}});if(!c)throw new Error("INVALID_CUSTOMER");return {customerName:c.name,contactPerson:c.contactPerson,phone:c.phone,email:c.email,billingAddress:c.billingAddress??c.address,siteAddress:c.shippingAddress,gstin:c.gstin,pan:c.pan};}
 if(!a.salesAccessActive||!a.salesRole)throw new Error("LEAD_ACCESS_REQUIRED");
 const company=await tx.company.findUnique({where:{id:a.companyId!},select:{productEdition:true}});if(company?.productEdition!=="SALESPUNCH360_PLUS")throw new Error("PLUS_LEAD_REQUIRED");
 const l=await tx.lead.findFirst({where:{id:d.sourceLeadId,companyId:a.companyId!,branchId:d.branchId,...visibilityWhere(a as never)},select:{companyName:true,title:true,contactName:true,phone:true,email:true}});if(!l)throw new Error("INVALID_LEAD");return {customerName:l.companyName??l.title,contactPerson:l.contactName,phone:l.phone,email:l.email,billingAddress:null,siteAddress:null,gstin:null,pan:null};
}
async function snapshotLines(a:Actor,d:z.infer<typeof quotationInput>,tx:Prisma.TransactionClient){return Promise.all(d.lines.map(async(raw,position)=>{
 let master:{id:string;name:string;code:string|null;description:string|null;rate:Prisma.Decimal|null;cost:Prisma.Decimal|null;tax:Prisma.Decimal|null;unit:{id:string;name:string;symbol:string}|null}|null=null;
 if(raw.lineType==="PRODUCT"&&raw.sourceId){const x=await tx.accountProduct.findFirst({where:{id:raw.sourceId,companyId:a.companyId!,isActive:true},include:{unit:true}});if(x)master={id:x.id,name:x.name,code:x.code,description:x.description,rate:x.salePrice,cost:x.costPrice,tax:x.taxRate,unit:x.unit};}
 if(raw.lineType==="SERVICE"&&raw.sourceId){const x=await tx.accountService.findFirst({where:{id:raw.sourceId,companyId:a.companyId!,isActive:true},include:{unit:true}});if(x)master={id:x.id,name:x.name,code:x.code,description:x.description,rate:x.sellingRate,cost:x.estimatedCost,tax:x.taxRate,unit:x.unit};}
 if(raw.lineType==="WORK_PACKAGE"&&raw.sourceId){const x=await tx.workPackage.findFirst({where:{id:raw.sourceId,companyId:a.companyId!,isActive:true},include:{unit:true}});if(x)master={id:x.id,name:x.name,code:x.code,description:x.description,rate:x.sellingRate,cost:x.estimatedCost,tax:null,unit:x.unit};}
 if(raw.lineType!=="CUSTOM"&&!master)throw new Error("INVALID_LINE_REFERENCE");
 if(raw.unitId&&!await tx.accountUnit.findFirst({where:{id:raw.unitId,companyId:a.companyId!,isActive:true}}))throw new Error("INVALID_UNIT");
 return {raw,position,master,itemName:master?.name??raw.itemName!,itemCode:master?.code,description:raw.description??master?.description,unitId:raw.unitId??master?.unit?.id,unitName:raw.unitName??master?.unit?.name,unitSymbol:raw.unitSymbol??master?.unit?.symbol,rate:raw.rate??master?.rate?.toString()??"0",cost:raw.internalUnitCost??master?.cost?.toString()??"0",tax:raw.taxRate??master?.tax?.toString()??"0"};}));}
async function createRevisionRows(a:Actor,documentId:string,revisionNumber:number,d:z.infer<typeof quotationInput>,snapshot:Awaited<ReturnType<typeof commercialSnapshot>>,tx:Prisma.TransactionClient){
 const lines=await snapshotLines(a,d,tx);const calc=calculateQuotation(lines.map(x=>({quantity:x.raw.quantity,rate:x.rate,internalUnitCost:x.cost,taxRate:x.tax,discountType:x.raw.discountType,discountValue:x.raw.discountValue})),d.adjustments);const schedule=reconcilePaymentSchedule(d.paymentSchedule,calc.grandTotal);
 const revision=await tx.quotationRevision.create({data:{companyId:a.companyId!,documentId,revisionNumber,status:"DRAFT",issueDate:d.issueDate,validUntil:d.validUntil,...snapshot,terms:d.terms,inclusions:d.inclusions,exclusions:d.exclusions,notes:d.notes,subtotal:calc.subtotal,discountTotal:calc.discountTotal,additionalChargeTotal:calc.additionalChargeTotal,taxableTotal:calc.taxableTotal,taxTotal:calc.taxTotal,grandTotal:calc.grandTotal,internalCostTotal:calc.internalCostTotal,expectedProfit:calc.expectedProfit,expectedMarginPercent:calc.expectedMarginPercent}});
 await tx.quotationLine.createMany({data:lines.map((x,i)=>({companyId:a.companyId!,revisionId:revision.id,position:i,lineType:x.raw.lineType,productId:x.raw.lineType==="PRODUCT"?x.master?.id:null,serviceId:x.raw.lineType==="SERVICE"?x.master?.id:null,workPackageId:x.raw.lineType==="WORK_PACKAGE"?x.master?.id:null,unitId:x.unitId,itemName:x.itemName,itemCode:x.itemCode,description:x.description,specification:x.raw.specification,unitName:x.unitName,unitSymbol:x.unitSymbol,quantity:x.raw.quantity,rate:x.rate,discountType:x.raw.discountType,discountValue:x.raw.discountValue,...calc.lines[i],internalUnitCost:x.cost}))});
 if(d.adjustments.length)await tx.quotationAdjustment.createMany({data:d.adjustments.map((x,i)=>({companyId:a.companyId!,revisionId:revision.id,position:i,...x,...calc.adjustments[i]}))});
 if(d.paymentSchedule.length)await tx.quotationPaymentSchedule.createMany({data:d.paymentSchedule.map((x,i)=>({companyId:a.companyId!,revisionId:revision.id,position:i,...x,amount:schedule[i]}))});return revision;
}
export async function createQuotation(raw:unknown){const a=await requirePermissionForMutation("ACCOUNT_QUOTATION_EDIT"),d=quotationInput.parse(raw);return db.$transaction(async tx=>{await assertBranch(a,d.branchId,tx);const snapshot=await commercialSnapshot(a,d,tx);const documentNumber=await allocateDocumentNumberInTx(tx,{companyId:a.companyId!,branchId:d.branchId,seriesKey:d.documentType,defaults:{prefix:d.documentType==="QUOTATION"?"Q-":d.documentType==="ESTIMATE"?"E-":"B-",padding:6}});const doc=await tx.quotationDocument.create({data:{companyId:a.companyId!,branchId:d.branchId,documentType:d.documentType,documentNumber,customerId:d.customerId,sourceLeadId:d.sourceLeadId,createdById:a.id}});await createRevisionRows(a,doc.id,0,d,snapshot,tx);await tx.quotationAuditEvent.create({data:{companyId:a.companyId!,documentId:doc.id,actorId:a.id,eventType:"CREATED",revisionNumber:0}});return doc;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function createQuotationRevision(id:string,raw:unknown){const a=await requirePermissionForMutation("ACCOUNT_QUOTATION_EDIT"),d=quotationInput.parse(raw);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "quotation_documents" WHERE "id"=${id}::uuid AND "companyId"=${a.companyId!}::uuid FOR UPDATE`;const doc=await tx.quotationDocument.findFirst({where:{id,companyId:a.companyId!,...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})}});if(!doc||!["APPROVED","REJECTED","SENT","DECLINED","EXPIRED"].includes(doc.status))throw new Error("REVISION_NOT_ALLOWED");if(d.branchId!==doc.branchId||d.documentType!==doc.documentType||d.customerId!==doc.customerId||d.sourceLeadId!==doc.sourceLeadId)throw new Error("DOCUMENT_IDENTITY_IMMUTABLE");const next=doc.currentRevisionNumber+1,snapshot=await commercialSnapshot(a,d,tx),revision=await createRevisionRows(a,id,next,d,snapshot,tx);const changed=await tx.quotationDocument.updateMany({where:{id,companyId:a.companyId!,currentRevisionNumber:doc.currentRevisionNumber},data:{currentRevisionNumber:next,status:"DRAFT"}});if(changed.count!==1)throw new Error("STALE");await tx.quotationAuditEvent.create({data:{companyId:a.companyId!,documentId:id,actorId:a.id,eventType:"REVISION_CREATED",revisionNumber:next}});return revision;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function updateQuotationDraft(id:string,raw:unknown){const a=await requirePermissionForMutation("ACCOUNT_QUOTATION_EDIT"),d=quotationInput.parse(raw);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "quotation_documents" WHERE "id"=${id}::uuid AND "companyId"=${a.companyId!}::uuid FOR UPDATE`;const doc=await tx.quotationDocument.findFirst({where:{id,companyId:a.companyId!,status:"DRAFT",...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})},include:{revisions:{orderBy:{revisionNumber:"desc"},take:1}}});if(!doc||!doc.revisions[0])throw new Error("DRAFT_NOT_EDITABLE");if(d.branchId!==doc.branchId||d.documentType!==doc.documentType||d.customerId!==doc.customerId||d.sourceLeadId!==doc.sourceLeadId)throw new Error("DOCUMENT_IDENTITY_IMMUTABLE");const old=doc.revisions[0];await tx.quotationPaymentSchedule.deleteMany({where:{revisionId:old.id}});await tx.quotationAdjustment.deleteMany({where:{revisionId:old.id}});await tx.quotationLine.deleteMany({where:{revisionId:old.id}});await tx.quotationRevision.delete({where:{id:old.id}});return createRevisionRows(a,id,old.revisionNumber,d,await commercialSnapshot(a,d,tx),tx);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function listQuotations(){const a=await requirePermission("ACCOUNT_QUOTATION_VIEW");return db.quotationDocument.findMany({where:{companyId:a.companyId!,...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})},include:{revisions:{orderBy:{revisionNumber:"desc"},take:1}},orderBy:{updatedAt:"desc"}});}
async function loadDocument(a:Actor,id:string){const doc=await db.quotationDocument.findFirst({where:{id,companyId:a.companyId!,...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})},include:{branch:true,company:true,revisions:{include:{lines:true,adjustments:true,paymentSchedule:true,shares:true},orderBy:{revisionNumber:"desc"}},audits:{orderBy:{createdAt:"desc"}}}});if(!doc)throw new Error("NOT_FOUND");return doc;}
export async function getQuotation(id:string){const a=await requirePermission("ACCOUNT_QUOTATION_VIEW");const doc=await loadDocument(a,id);if(accountRoleHasCapability(a.accountRole,"COST_PROFIT_VISIBILITY"))return doc;// eslint-disable-next-line @typescript-eslint/no-unused-vars
 return {...doc,revisions:doc.revisions.map(({internalCostTotal:_,expectedProfit:__,expectedMarginPercent:___,...r})=>({...r,lines:r.lines.map(({internalUnitCost:____,internalCostTotal:_____,...l})=>l)}))};}
const transitions:Record<QuotationStatus,QuotationStatus[]>= {DRAFT:["PENDING_APPROVAL","CANCELLED"],PENDING_APPROVAL:["APPROVED","REJECTED","CANCELLED"],APPROVED:["SENT","ACCEPTED","DECLINED","CANCELLED"],REJECTED:[],SENT:["ACCEPTED","DECLINED","EXPIRED","CANCELLED"],ACCEPTED:[],DECLINED:[],EXPIRED:[],CANCELLED:[]};
export async function transitionQuotation(id:string,to:QuotationStatus,note?:string){const permission=to==="APPROVED"||to==="REJECTED"?"ACCOUNT_QUOTATION_APPROVE":"ACCOUNT_QUOTATION_EDIT";const a=await requirePermissionForMutation(permission);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "quotation_documents" WHERE "id"=${id}::uuid AND "companyId"=${a.companyId!}::uuid FOR UPDATE`;const doc=await loadDocument(a,id),revision=doc.revisions[0];if(!transitions[doc.status].includes(to))throw new Error("INVALID_TRANSITION");if(to==="APPROVED"){const recalculated=calculateQuotation(revision.lines,revision.adjustments);await tx.quotationRevision.update({where:{id:revision.id},data:{subtotal:recalculated.subtotal,discountTotal:recalculated.discountTotal,additionalChargeTotal:recalculated.additionalChargeTotal,taxableTotal:recalculated.taxableTotal,taxTotal:recalculated.taxTotal,grandTotal:recalculated.grandTotal,internalCostTotal:recalculated.internalCostTotal,expectedProfit:recalculated.expectedProfit,expectedMarginPercent:recalculated.expectedMarginPercent}});}const changed=await tx.quotationDocument.updateMany({where:{id,companyId:a.companyId!,status:doc.status},data:{status:to,...(to==="ACCEPTED"?{acceptedAt:new Date(),acceptedById:a.id,acceptanceNote:note}:{})}});if(changed.count!==1)throw new Error("STALE");await tx.quotationRevision.update({where:{id:revision.id},data:{status:to}});await tx.quotationAuditEvent.create({data:{companyId:a.companyId!,documentId:id,actorId:a.id,eventType:({PENDING_APPROVAL:"SUBMITTED_FOR_APPROVAL",APPROVED:"APPROVED",REJECTED:"REJECTED",SENT:"SENT",ACCEPTED:"ACCEPTED",DECLINED:"DECLINED",CANCELLED:"CANCELLED",DRAFT:"REVISION_CREATED",EXPIRED:"EXPIRED"} as const)[to],revisionNumber:revision.revisionNumber,note}});return to;});}
export async function createShare(id:string,expiresAt?:Date){const a=await requirePermissionForMutation("ACCOUNT_QUOTATION_SHARE"),doc=await loadDocument(a,id),revision=doc.revisions[0];if(!["APPROVED","SENT"].includes(revision.status))throw new Error("APPROVAL_REQUIRED");const token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex");await db.$transaction(async tx=>{await tx.quotationShare.create({data:{companyId:a.companyId!,revisionId:revision.id,tokenHash,expiresAt}});await tx.quotationAuditEvent.create({data:{companyId:a.companyId!,documentId:id,actorId:a.id,eventType:"SHARED",revisionNumber:revision.revisionNumber}});if(doc.status==="APPROVED"){await tx.quotationDocument.update({where:{id},data:{status:"SENT"}});await tx.quotationRevision.update({where:{id:revision.id},data:{status:"SENT"}});}});return token;}
export async function revokeShare(id:string){const a=await requirePermissionForMutation("ACCOUNT_QUOTATION_SHARE");const share=await db.quotationShare.findFirst({where:{id,companyId:a.companyId!,revision:{document:{...(a.branchAccessScope==="SELECTED_BRANCHES"?{branchId:{in:a.branchIds??[]}}:{})}}},include:{revision:true}});if(!share)throw new Error("NOT_FOUND");await db.$transaction([db.quotationShare.update({where:{id},data:{revokedAt:new Date()}}),db.quotationAuditEvent.create({data:{companyId:a.companyId!,documentId:share.revision.documentId,actorId:a.id,eventType:"SHARE_REVOKED",revisionNumber:share.revision.revisionNumber}})]);}
export async function getPublicQuotation(token:string){const tokenHash=createHash("sha256").update(token).digest("hex"),now=new Date();const share=await db.quotationShare.findFirst({where:{tokenHash,revokedAt:null,OR:[{expiresAt:null},{expiresAt:{gt:now}}]},include:{revision:{include:{document:{include:{company:true,branch:true}},lines:true,adjustments:true,paymentSchedule:true}}}});if(!share)throw new Error("NOT_FOUND");
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 const {internalCostTotal:_,expectedProfit:__,expectedMarginPercent:___,...revision}=share.revision;return {...revision,lines:revision.lines.map(({internalUnitCost:____,internalCostTotal:_____,productId:______,serviceId:_______,workPackageId:________,...l})=>l)};}

export async function getCustomerQuotation(id:string){const d=await getQuotation(id);return {...d,revisions:d.revisions.map(r=>{const entries=Object.entries(r).filter(([k])=>!["internalCostTotal","expectedProfit","expectedMarginPercent"].includes(k));const safe=Object.fromEntries(entries) as typeof r;return {...safe,lines:r.lines.map(l=>Object.fromEntries(Object.entries(l).filter(([k])=>!["internalUnitCost","internalCostTotal","productId","serviceId","workPackageId"].includes(k))) as typeof l)}})};}
