import Link from "next/link";
import { addMilestoneAction, addProjectDocumentAction, addProjectMemberAction, addTaskAction, closeProjectAction, linkBoqAction, reopenProjectAction, replaceBudgetAction, updateMilestoneAction, updateTaskAction } from "@/app/actions/projects";
import { getProject, getProjectFormOptions } from "@/lib/account/projects";
import { WorkspacePageHeader } from "@/components/workspace/workspace-page-header";
const date = (value: Date | null) => value?.toISOString().slice(0, 10) ?? "";
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params, [project, options] = await Promise.all([getProject(id), getProjectFormOptions(id)]);
  const sales = project.commercialDocuments.filter(row => ["SALES_INVOICE", "CREDIT_NOTE"].includes(row.type));
  const purchases = project.commercialDocuments.filter(row => ["PURCHASE_ORDER", "PURCHASE_BILL", "DEBIT_NOTE", "SUBCONTRACT_PURCHASE"].includes(row.type));
  const expenses = purchases.filter(row => row.type === "PURCHASE_BILL" && row.purchasePurpose === "PROJECT" && row.purchaseClassification === "GENERAL_EXPENSES");
  const mutable = !["CLOSED", "CANCELLED"].includes(project.status);
  return <main className="employees-shell"><section className="employees-content"><WorkspacePageHeader title={`${project.projectNumber} · ${project.name}`} backHref="/workspace/account/projects"/><p><Link href={`/workspace/account/projects/${id}/edit`}>Edit project</Link></p>
    <div className="metric-grid"><article><b>Project value</b><p>{project.projectValue.toString()}</p></article><article><b>Budget</b><p>{project.budgetTotal.toString()}</p></article><article><b>Status</b><p>{project.status}</p></article><article><b>Open tasks</b><p>{project.tasks.filter(task => !["COMPLETED", "CANCELLED"].includes(task.status)).length}</p></article></div>
    <h2>Customer & site</h2><p>{project.customer.name} · {project.siteName ?? "No site name"}</p><p>{project.siteAddress}</p>
    <h2>Team / project manager</h2><p>{project.projectManager?.name ?? "Unassigned"}</p><ul>{project.members.map(member => <li key={member.id}>{member.user.name} — {member.role}</li>)}</ul>{mutable && <form action={addProjectMemberAction}><input type="hidden" name="projectId" value={id}/><label>Team member<select name="userId" required><option value="">Select user</option>{options.memberCandidates.map(user => <option key={user.id} value={user.id}>{user.name} · {user.accountRole}</option>)}</select></label><input type="hidden" name="role" value="MEMBER"/><button>Add team member</button></form>}
    <h2>BOQ</h2><ul>{project.quotationDocuments.map(boq => <li key={boq.id}>{boq.documentNumber} — {boq.status}</li>)}</ul>{mutable && <form action={linkBoqAction}><input type="hidden" name="projectId" value={id}/><label>Compatible BOQ<select name="boqId" required><option value="">Select BOQ</option>{options.boqCandidates.map(boq => <option key={boq.id} value={boq.id}>{boq.documentNumber} · {boq.status}</option>)}</select></label><button>Link BOQ</button></form>}
    <h2>Budget</h2><ul>{project.budgetLines.map(line => <li key={line.id}>{line.category}: {line.title} — {line.amount.toString()}</li>)}</ul>{mutable && <form action={replaceBudgetAction}><input type="hidden" name="projectId" value={id}/><input name="category" placeholder="Category" required/><input name="title" placeholder="Budget title" required/><input name="amount" placeholder="0.00" required/><button>Replace budget</button></form>}
    <h2>Milestones</h2>{project.milestones.map(milestone => <form key={milestone.id} action={updateMilestoneAction} className="stack"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="milestoneId" value={milestone.id}/><input name="title" defaultValue={milestone.title} required/><textarea name="description" defaultValue={milestone.description ?? ""}/><input type="date" name="startDate" defaultValue={date(milestone.startDate)}/><input type="date" name="dueDate" defaultValue={date(milestone.dueDate)}/><select name="status" defaultValue={milestone.status}>{["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"].map(status => <option key={status}>{status}</option>)}</select>{mutable && <button>Update milestone</button>}</form>)}{mutable && <form action={addMilestoneAction}><input type="hidden" name="projectId" value={id}/><input name="title" required/><input type="date" name="dueDate"/><button>Add milestone</button></form>}
    <h2>Tasks</h2>{project.tasks.map(task => <form key={task.id} action={updateTaskAction} className="stack"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="taskId" value={task.id}/><input name="title" defaultValue={task.title} required/><textarea name="description" defaultValue={task.description ?? ""}/><select name="milestoneId" defaultValue={task.milestoneId ?? ""}><option value="">No milestone</option>{project.milestones.map(milestone => <option key={milestone.id} value={milestone.id}>{milestone.title}</option>)}</select><select name="assigneeUserId" defaultValue={task.assigneeUserId ?? ""}><option value="">Unassigned</option>{project.members.map(member => <option key={member.userId} value={member.userId}>{member.user.name}</option>)}</select><input type="date" name="dueDate" defaultValue={date(task.dueDate)}/><select name="priority" defaultValue={task.priority}>{[0, 1, 2, 3].map(priority => <option key={priority}>{priority}</option>)}</select><select name="status" defaultValue={task.status}>{["TODO", "IN_PROGRESS", "COMPLETED", "CANCELLED"].map(status => <option key={status}>{status}</option>)}</select>{mutable && <button>Update task</button>}</form>)}{mutable && <form action={addTaskAction}><input type="hidden" name="projectId" value={id}/><input name="title" required/><select name="assigneeUserId"><option value="">Unassigned</option>{project.members.map(member => <option key={member.userId} value={member.userId}>{member.user.name}</option>)}</select><button>Add task</button></form>}
    <h2>Documents</h2><ul>{project.documents.map(document => <li key={document.id}><a href={`/api/project-documents/${document.id}`}>{document.displayName}</a></li>)}</ul>{mutable && <form action={addProjectDocumentAction}><input type="hidden" name="projectId" value={id}/><input type="file" name="file" required/><button>Upload private document</button></form>}
    <h2>Project expenses</h2><p>{expenses.length} linked general-expense purchase bills.</p><h2>Purchases & vendor/subcontractor activity</h2><Documents rows={purchases}/><h2>Invoices</h2><Documents rows={sales}/><h2>Payments</h2><p>Customer payments: {project.customerPayments.toString()} · Vendor payments: {project.vendorPayments.toString()}</p><p>Totals derive only from existing settlement allocations and advance applications.</p>
    <h2>Closure / handover</h2>{project.status === "CLOSED" ? <form action={reopenProjectAction}><input type="hidden" name="projectId" value={id}/><p>Closed {project.closedAt?.toLocaleString()}</p><button>Reopen project (Account Admin)</button></form> : mutable && <form action={closeProjectAction}><input type="hidden" name="projectId" value={id}/><input type="date" name="handoverDate"/><textarea name="handoverNote" placeholder="Handover note"/><textarea name="closureNote" placeholder="Closure note"/><button>Close project</button></form>}
    <h2>Audit history</h2><ul>{project.audits.map(event => <li key={event.id}>{event.createdAt.toLocaleString()} — {event.eventType}</li>)}</ul>
  </section></main>;
}
function Documents({ rows }: { rows: Array<{ id: string; documentNumber: string; type: string; status: string; grandTotal: { toString(): string }; balanceDue: { toString(): string } }> }) { return <div className="table-wrap"><table><thead><tr><th>Type</th><th>Number</th><th>Status</th><th>Total</th><th>Outstanding</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.type}</td><td>{row.documentNumber}</td><td>{row.status}</td><td>{row.grandTotal.toString()}</td><td>{row.balanceDue.toString()}</td></tr>)}</tbody></table></div>; }
