import {Prisma,type Role,type FollowUpTaskStatus} from "@prisma/client";
import {db} from "@/lib/db";
import {requireRole} from "@/lib/auth/authorization";
import {assertOperationalWrite} from "@/lib/billing/entitlement";
import {canAssign,visibilityWhere} from "@/lib/leads/policy";
import {indiaDateText,parseIndiaBusinessDate} from "./date";

export class FollowUpTaskError extends Error{constructor(public code:"NOT_FOUND"|"INVALID_ASSIGNMENT"|"INVALID_STATE"|"INVALID_DATE"){super(code)}}
export type TaskActor={id:string;companyId:string;role:Role};
export async function taskActor():Promise<TaskActor>{const user=await requireRole("COMPANY_ADMIN","MANAGER","SALES");if(!user.companyId)throw new FollowUpTaskError("NOT_FOUND");return{...user,companyId:user.companyId};}
export function taskScope(actor:TaskActor):Prisma.FollowUpTaskWhereInput{return actor.role==="COMPANY_ADMIN"?{companyId:actor.companyId}:actor.role==="MANAGER"?{companyId:actor.companyId,OR:[{assignedUserId:actor.id},{assignedUser:{role:"SALES",managerId:actor.id}}]}:{companyId:actor.companyId,assignedUserId:actor.id};}
export async function syncLeadFollowUpAt(tx:Prisma.TransactionClient,leadId:string){const first=await tx.followUpTask.findFirst({where:{leadId,status:"PENDING"},orderBy:[{dueDate:"asc"},{createdAt:"asc"},{id:"asc"}],select:{dueDate:true}});await tx.lead.update({where:{id:leadId},data:{followUpAt:first?.dueDate??null}});return first?.dueDate??null;}
export async function createFollowUpTask(raw:{leadId:unknown;dueDate:unknown;notes?:unknown}){return createFollowUpTaskForActor(await taskActor(),raw);}
export async function createFollowUpTaskForActor(actor:TaskActor,raw:{leadId:unknown;dueDate:unknown;notes?:unknown}){await assertOperationalWrite(actor.companyId);const leadId=String(raw.leadId),dueText=String(raw.dueDate),notes=typeof raw.notes==="string"&&raw.notes.trim()?raw.notes.trim().slice(0,2000):undefined;let dueDate:Date;try{dueDate=parseIndiaBusinessDate(dueText)}catch{throw new FollowUpTaskError("INVALID_DATE")}
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "leads" WHERE "id"=${leadId}::uuid AND "companyId"=${actor.companyId}::uuid FOR UPDATE`;const lead=await tx.lead.findFirst({where:{id:leadId,companyId:actor.companyId,...visibilityWhere(actor)},select:{id:true,assignedUserId:true,assignedUser:{select:{id:true,role:true,isActive:true,managerId:true}}}});if(!lead)throw new FollowUpTaskError("NOT_FOUND");if(!canAssign(actor,lead.assignedUser))throw new FollowUpTaskError("INVALID_ASSIGNMENT");const task=await tx.followUpTask.create({data:{companyId:actor.companyId,leadId,assignedUserId:lead.assignedUserId,createdByUserId:actor.id,dueDate,notes}});await syncLeadFollowUpAt(tx,leadId);return task;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function cancelFollowUpTask(taskId:string){const actor=await taskActor();return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "follow_up_tasks" WHERE "id"=${taskId}::uuid AND "companyId"=${actor.companyId}::uuid FOR UPDATE`;const task=await tx.followUpTask.findFirst({where:{id:taskId,...taskScope(actor)},include:{completedVisit:{select:{checkedOutAt:true}}}});if(!task)throw new FollowUpTaskError("NOT_FOUND");if(task.status!=="PENDING"||task.completedVisitId&&task.completedVisit?.checkedOutAt===null)throw new FollowUpTaskError("INVALID_STATE");await tx.followUpTask.update({where:{id:task.id},data:{status:"CANCELLED"}});await syncLeadFollowUpAt(tx,task.leadId);});}
export type TaskListFilter={status?:string;employeeId?:string};
export async function listFollowUpTasks(raw:TaskListFilter={}){const actor=await taskActor(),today=parseIndiaBusinessDate(indiaDateText());const status=raw.status??"PENDING";const tomorrow=new Date(today.getTime()+86400000);const statusWhere:Prisma.FollowUpTaskWhereInput=status==="OVERDUE"?{status:"PENDING",dueDate:{lt:today}}:status==="TODAY"?{status:"PENDING",dueDate:{gte:today,lt:tomorrow}}:status==="PENDING"?{status:"PENDING",dueDate:{gte:today}}:status==="COMPLETED"||status==="CANCELLED"?{status:status as FollowUpTaskStatus}: {status:"PENDING",dueDate:{gte:today}};const allowedEmployee=raw.employeeId?await db.user.findFirst({where:{id:raw.employeeId,...(actor.role==="COMPANY_ADMIN"?{companyId:actor.companyId}:actor.role==="MANAGER"?{companyId:actor.companyId,OR:[{id:actor.id},{role:"SALES",managerId:actor.id}]}:{id:actor.id,companyId:actor.companyId})},select:{id:true}}):null;return db.followUpTask.findMany({where:{AND:[taskScope(actor),statusWhere],assignedUserId:allowedEmployee?.id},include:{lead:{select:{id:true,title:true,companyName:true,customer:{select:{name:true}}}},assignedUser:{select:{id:true,name:true}},createdByUser:{select:{name:true}},completedVisit:{select:{id:true,checkedInAt:true,checkedOutAt:true,user:{select:{name:true}}}}},orderBy:[{dueDate:"asc"},{createdAt:"asc"},{id:"asc"}],take:300});}
export async function taskEmployeeOptions(){const actor=await taskActor();if(actor.role==="SALES")return[];return db.user.findMany({where:actor.role==="COMPANY_ADMIN"?{companyId:actor.companyId,isActive:true,role:{in:["MANAGER","SALES"]}}:{companyId:actor.companyId,isActive:true,OR:[{id:actor.id},{role:"SALES",managerId:actor.id}]},select:{id:true,name:true},orderBy:{name:"asc"}});}
export async function personalTaskCounts(){const actor=await taskActor(),today=parseIndiaBusinessDate(indiaDateText()),tomorrow=new Date(today.getTime()+86400000);const where={companyId:actor.companyId,assignedUserId:actor.id,status:"PENDING" as const};const[todayCount,overdue]=await Promise.all([db.followUpTask.count({where:{...where,dueDate:{gte:today,lt:tomorrow}}}),db.followUpTask.count({where:{...where,dueDate:{lt:today}}})]);return{today:todayCount,overdue};}
