import {Prisma,type ManagerType,type SalesRole,type FollowUpTaskStatus} from "@prisma/client";
import {db} from "@/lib/db";
import {requirePermission,requirePermissionForMutation} from "@/lib/auth/authorization";
import {assertOperationalWrite} from "@/lib/billing/entitlement";
import {canAssign,visibilityWhere} from "@/lib/leads/policy";
import {operationalBranchContext,resolveOperationalWriteBranch} from "@/lib/branches/operational-scope";
import {indiaDateText,parseIndiaBusinessDate} from "./date";
import {decodeFollowUpNotes,encodeFollowUpNotes,parseFollowUpType} from "./type";

export class FollowUpTaskError extends Error{constructor(public code:"NOT_FOUND"|"INVALID_ASSIGNMENT"|"INVALID_STATE"|"INVALID_DATE"|"INVALID_TYPE"){super(code)}}
export type TaskActor={id:string;companyId:string;salesRole:SalesRole;managerType?:ManagerType|null;branchAccessScope?:"ALL_BRANCHES"|"SELECTED_BRANCHES";branchIds?:string[]};
export async function taskActor():Promise<TaskActor>{const user=await requirePermission("SALES_FOLLOW_UPS");if(!user.companyId||!user.salesRole)throw new FollowUpTaskError("NOT_FOUND");return{...user,salesRole:user.salesRole,companyId:user.companyId};}
async function taskMutationActor():Promise<TaskActor>{const user=await requirePermissionForMutation("SALES_FOLLOW_UPS");if(!user.companyId||!user.salesRole)throw new FollowUpTaskError("NOT_FOUND");return{...user,salesRole:user.salesRole,companyId:user.companyId};}
export function taskScope(actor:TaskActor):Prisma.FollowUpTaskWhereInput{return (actor.salesRole==="PRIMARY_ADMIN"||actor.salesRole==="ADMIN")?{companyId:actor.companyId}:actor.salesRole==="MANAGER"?(actor.managerType==="MANAGER_ONLY"?{companyId:actor.companyId,assignedUser:{salesRole:"SALES",managerId:actor.id}}:{companyId:actor.companyId,OR:[{assignedUserId:actor.id},{assignedUser:{salesRole:"SALES",managerId:actor.id}}]}):{companyId:actor.companyId,assignedUserId:actor.id};}
export async function syncLeadFollowUpAt(tx:Prisma.TransactionClient,leadId:string){const first=await tx.followUpTask.findFirst({where:{leadId,status:"PENDING"},orderBy:[{dueDate:"asc"},{createdAt:"asc"},{id:"asc"}],select:{dueDate:true}});await tx.lead.update({where:{id:leadId},data:{followUpAt:first?.dueDate??null}});return first?.dueDate??null;}
export async function createFollowUpTask(raw:{leadId:unknown;dueDate:unknown;notes?:unknown;type?:unknown}){return createFollowUpTaskForActor(await taskMutationActor(),raw);}
export async function createFollowUpTaskForActor(actor:TaskActor,raw:{leadId:unknown;dueDate:unknown;notes?:unknown;type?:unknown}){await assertOperationalWrite(actor.companyId);const leadId=String(raw.leadId),dueText=String(raw.dueDate);let type:"VISIT"|"CALL";try{type=parseFollowUpType(raw.type)}catch{throw new FollowUpTaskError("INVALID_TYPE")}const notes=encodeFollowUpNotes(type,raw.notes);let dueDate:Date;try{dueDate=parseIndiaBusinessDate(dueText)}catch{throw new FollowUpTaskError("INVALID_DATE")}
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "leads" WHERE "id"=${leadId}::uuid AND "companyId"=${actor.companyId}::uuid FOR UPDATE`;const lead=await tx.lead.findFirst({where:{id:leadId,companyId:actor.companyId,...visibilityWhere(actor)},select:{id:true,branchId:true,assignedUserId:true,assignedUser:{select:{id:true,salesRole:true,isActive:true,salesAccessActive:true,managerId:true,managerType:true}}}});if(!lead)throw new FollowUpTaskError("NOT_FOUND");await resolveOperationalWriteBranch(actor,lead.branchId,tx);if(!canAssign(actor,lead.assignedUser))throw new FollowUpTaskError("INVALID_ASSIGNMENT");const task=await tx.followUpTask.create({data:{companyId:actor.companyId,branchId:lead.branchId,leadId,assignedUserId:lead.assignedUserId,createdByUserId:actor.id,dueDate,notes}});await syncLeadFollowUpAt(tx,leadId);return{...task,type,notes:decodeFollowUpNotes(task.notes).notes};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function cancelFollowUpTask(taskId:string){return cancelFollowUpTaskForActor(await taskMutationActor(),taskId);}
export async function cancelFollowUpTaskForActor(actor:TaskActor,taskId:string){await assertOperationalWrite(actor.companyId);const branches=await operationalBranchContext(actor);return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "follow_up_tasks" WHERE "id"=${taskId}::uuid AND "companyId"=${actor.companyId}::uuid FOR UPDATE`;const task=await tx.followUpTask.findFirst({where:{id:taskId,branchId:branches.branchId,...taskScope(actor)},include:{completedVisit:{select:{checkedOutAt:true}}}});if(!task)throw new FollowUpTaskError("NOT_FOUND");if(task.status!=="PENDING"||task.completedVisitId&&task.completedVisit?.checkedOutAt===null)throw new FollowUpTaskError("INVALID_STATE");await tx.followUpTask.update({where:{id:task.id},data:{status:"CANCELLED"}});await syncLeadFollowUpAt(tx,task.leadId);});}
export type TaskListFilter={status?:string;employeeId?:string;branchId?:string};
export async function listFollowUpTasks(raw:TaskListFilter={}){const actor=await taskActor(),branches=await operationalBranchContext(actor,raw.branchId),today=parseIndiaBusinessDate(indiaDateText());const status=raw.status??"PENDING";const tomorrow=new Date(today.getTime()+86400000);const statusWhere:Prisma.FollowUpTaskWhereInput=status==="OVERDUE"?{status:"PENDING",dueDate:{lt:today}}:status==="TODAY"?{status:"PENDING",dueDate:{gte:today,lt:tomorrow}}:status==="PENDING"?{status:"PENDING",dueDate:{gte:today}}:status==="COMPLETED"||status==="CANCELLED"?{status:status as FollowUpTaskStatus}: {status:"PENDING",dueDate:{gte:today}};const allowedEmployee=raw.employeeId?await db.user.findFirst({where:{id:raw.employeeId,isActive:true,salesAccessActive:true,...((actor.salesRole==="PRIMARY_ADMIN"||actor.salesRole==="ADMIN")?{companyId:actor.companyId,salesRole:{in:["MANAGER","SALES"]}}:actor.salesRole==="MANAGER"?(actor.managerType==="MANAGER_ONLY"?{companyId:actor.companyId,salesRole:"SALES",managerId:actor.id}:{companyId:actor.companyId,OR:[{id:actor.id,salesRole:"MANAGER"},{salesRole:"SALES",managerId:actor.id}]}):{id:actor.id,companyId:actor.companyId,salesRole:"SALES"})},select:{id:true}}):null;if(raw.employeeId&&!allowedEmployee)return[];const tasks=await db.followUpTask.findMany({where:{AND:[taskScope(actor),statusWhere,{branchId:branches.branchId}],assignedUserId:allowedEmployee?.id},include:{lead:{select:{id:true,title:true,companyName:true,customer:{select:{name:true}}}},assignedUser:{select:{id:true,name:true}},createdByUser:{select:{name:true}},completedVisit:{select:{id:true,checkedInAt:true,checkedOutAt:true,user:{select:{name:true}}}}},orderBy:[{dueDate:"asc"},{createdAt:"asc"},{id:"asc"}],take:300});return tasks.map(task=>{const presentation=decodeFollowUpNotes(task.notes);return{...task,type:presentation.type,notes:presentation.notes};});}
export async function taskEmployeeOptions(){const actor=await taskActor();if(actor.salesRole==="SALES")return[];return db.user.findMany({where:(actor.salesRole==="PRIMARY_ADMIN"||actor.salesRole==="ADMIN")?{companyId:actor.companyId,isActive:true,salesAccessActive:true,OR:[{salesRole:"SALES"},{salesRole:"MANAGER",managerType:"FIELD_MANAGER"}]}:actor.managerType==="MANAGER_ONLY"?{companyId:actor.companyId,isActive:true,salesAccessActive:true,salesRole:"SALES",managerId:actor.id}:{companyId:actor.companyId,isActive:true,salesAccessActive:true,OR:[{id:actor.id},{salesRole:"SALES",managerId:actor.id}]},select:{id:true,name:true},orderBy:{name:"asc"}});}
export async function personalTaskCounts(){const actor=await taskActor(),branches=await operationalBranchContext(actor),today=parseIndiaBusinessDate(indiaDateText()),tomorrow=new Date(today.getTime()+86400000);const where={companyId:actor.companyId,branchId:branches.branchId,assignedUserId:actor.id,status:"PENDING" as const};const[todayCount,overdue]=await Promise.all([db.followUpTask.count({where:{...where,dueDate:{gte:today,lt:tomorrow}}}),db.followUpTask.count({where:{...where,dueDate:{lt:today}}})]);return{today:todayCount,overdue};}
