import ExcelJS from "exceljs";
import { db } from "@/lib/db";
import { attendanceReport } from "@/lib/reports/attendance";
import { checkInReport } from "@/lib/reports/check-ins";
import { expenseReport } from "@/lib/reports/expenses";
import { geofenceReport } from "@/lib/reports/geofence";
import { gpsReport } from "@/lib/reports/gps";
import { leadReport } from "@/lib/reports/leads";
import { reportActor } from "@/lib/reports/scope";
import { listTargets } from "@/lib/targets/service";

const MAX_ROWS=10_000;
const india=(date:Date|null|undefined)=>date?new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"medium",timeStyle:"medium"}).format(date):"";
type Cell=string|number|Date|null|undefined;
type ExportData={name:string;range:string;summary:Record<string,unknown>;headers:string[];rows:Cell[][];companyId:string};

async function dataFor(report:string,raw:Record<string,string>):Promise<ExportData>{
 const actor=await reportActor(),all={...raw,page:"1",pageSize:String(MAX_ROWS)};let data:Omit<ExportData,"companyId">;
 if(report==="attendance"){const r=await attendanceReport(all,actor,true);if(r.summary.total>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:"Attendance Report",range:`${r.filters.startText} to ${r.filters.endText}`,summary:r.summary,headers:["Employee","Role","Started","Ended","Status","Duration minutes","GPS points","Distance km"],rows:r.rows.map(a=>[a.user.name,a.user.role,india(a.startedAt),india(a.endedAt),a.endedAt?"COMPLETED":"OPEN",a.durationMs==null?null:a.durationMs/60000,a.locationPoints.length,a.routeDistanceMeters/1000])}}
 else if(report==="check-ins"||report==="advanced-check-ins"){const advanced=report.startsWith("advanced"),r=await checkInReport(all,advanced,actor,true);if(r.summary.total>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:advanced?"Advanced Check-in Report":"Check-in Report",range:`${r.filters.startText} to ${r.filters.endText}`,summary:r.summary,headers:["Employee","Role","Customer / prospect","Check-in","Checkout","Status","Duration minutes","Visit kind","Notes","Latitude","Longitude","Reference distance km","Leads"],rows:r.rows.map(v=>[v.user.name,v.user.role,v.customer?.name||v.contactName||"Field prospect",india(v.checkedInAt),india(v.checkedOutAt),v.checkedOutAt?"COMPLETED":"PENDING",v.durationMs==null?null:v.durationMs/60000,v.visitKind,v.visitNotes,v.checkInLatitude,v.checkInLongitude,v.referenceDistanceMeters==null?null:v.referenceDistanceMeters/1000,v._count.sourceLeads])}}
 else if(report==="leads"){const r=await leadReport(all,actor,true);if(r.summary.total>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:"Lead & Pipeline Report",range:`${r.filters.startText} to ${r.filters.endText}`,summary:{...r.summary,counts:JSON.stringify(r.summary.counts)},headers:["Lead","Customer / prospect","Assignee","Role","Stage","Source","Value","Currency","Follow-up","Created"],rows:r.rows.map(l=>[l.title,l.customer?.name||l.companyName||l.contactName||"Prospect",l.assignedUser.name,l.assignedUser.role,l.stage,l.source,l.estimatedValue?.toNumber()||0,l.currencyCode,india(l.followUpAt),india(l.createdAt)])}}
 else if(report==="geofence-breaches"){const r=await geofenceReport(all,actor,true);if(r.summary.total>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:"Geofence Breach Report",range:`${r.filters.startText} to ${r.filters.endText}`,summary:r.summary,headers:["Employee","Role","Occurred","Action","Type","Customer","Radius m","Distance km","Accuracy m","Reference latitude","Reference longitude","Actual latitude","Actual longitude"],rows:r.rows.map(e=>[e.employee.name,e.employee.role,india(e.occurredAt),e.action,e.type,e.customer?.name,e.allowedRadiusMeters,e.distanceMeters==null?null:e.distanceMeters/1000,e.accuracyMeters,e.referenceLatitude,e.referenceLongitude,e.actualLatitude,e.actualLongitude])}}
 else if(report==="gps"){const r=await gpsReport(raw,actor);if(r.events.length>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:"GPS Route Report",range:r.date||"No date selected",summary:{employee:r.employee?.name||"",sessions:r.sessions.length,acceptedPoints:r.points.length,distanceKm:r.routeDistanceMeters/1000},headers:["Event","Time","Customer","Detail","Latitude","Longitude","Session"],rows:r.events.map(e=>[e.type,india(e.at),e.customer,e.detail,e.latitude,e.longitude,e.sessionId])}}
 else if(report==="targets"){const r=await listTargets(raw,actor,true);if(r.targets.length>MAX_ROWS)throw new Error("ROW_LIMIT");data={name:"Target Analysis",range:`${raw.start||"All"} to ${raw.end||"All"}`,summary:{targets:r.targets.length},headers:["Employee","Role","Metric","Period","Start","End","Target","Actual","Remaining","Progress %","Status","Currency"],rows:r.targets.map(t=>[t.assignedUser.name,t.assignedUser.role,t.metric,t.periodType,t.startDate.toISOString().slice(0,10),t.endDate.toISOString().slice(0,10),t.targetValue.toNumber(),t.actual.toNumber(),t.remaining.toNumber(),t.percentage.toNumber(),t.status,t.currencyCode])}}
 else if(report==="expenses"){const r=await expenseReport(raw,actor);if(r.rows.length>MAX_ROWS||r.pointLimitExceeded)throw new Error("ROW_LIMIT");data={name:"Expense Report",range:`${r.filters.startText} to ${r.filters.endText}`,summary:{rows:r.rows.length},headers:["Employee","Date","Verified distance km","Travel rate","Travel expense"],rows:r.rows.map(x=>[x.employee,x.date,x.distanceMeters/1000,"Not configured",null])}}
 else throw new Error("NOT_FOUND");return{...data,companyId:actor.companyId};
}

export async function GET(request:Request,{params}:{params:Promise<{report:string}>}){try{const{report}=await params,raw=Object.fromEntries(new URL(request.url).searchParams),d=await dataFor(report,raw),company=await db.company.findUniqueOrThrow({where:{id:d.companyId},select:{name:true}}),workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("Report");sheet.addRow(["Company",company.name]);sheet.addRow(["Report",d.name]);sheet.addRow(["Selected date range",d.range]);sheet.addRow(["Active filters",Object.entries(raw).filter(([k,v])=>k!=="page"&&v).map(([k,v])=>`${k}: ${v}`).join(", ")||"None"]);sheet.addRow(["Generated",india(new Date())]);for(const[key,value]of Object.entries(d.summary))sheet.addRow([key,typeof value==="object"?JSON.stringify(value):value]);sheet.addRow([]);const header=sheet.addRow(d.headers);header.font={bold:true};for(const row of d.rows)sheet.addRow(row);sheet.columns.forEach(c=>{c.width=18});const buffer=await workbook.xlsx.writeBuffer();return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="${report}.xlsx"`,"Cache-Control":"private, no-store"}})}catch(error){const limited=error instanceof Error&&error.message==="ROW_LIMIT";return Response.json({error:limited?"More than 10,000 rows match. Narrow your filters and try again.":"Unable to export this report."},{status:limited?422:404,headers:{"Cache-Control":"no-store"}})}}
