import type {Metadata} from "next";
import Link from "next/link";
import {CTA} from "@/components/public/marketing-ui";
import {TRIAL_DURATION_DAYS} from "@/lib/trial/config";
import {db} from "@/lib/db";

export const metadata:Metadata={title:"Field Sales Tracking & Business Accounts",description:"Track field sales and manage business accounts together with SalesPunch360.",alternates:{canonical:"/"}};

const sales=["GPS-enabled check-ins","Lead & pipeline management","Follow-ups and reminders","Target vs achievement tracking","Powerful reports and analytics"];
const account=["User and role management","Subscription plans and payments","Invoices and billing history","Company settings and data security","Admin dashboards and reports"];
const industries=["Retail & FMCG","Distributors","Pharma & Healthcare","Electronics","Furniture","Automotive","Food & Beverage","Construction","And more"];\nconst industryMeta=[["▥","Stores & outlets"],["▦","Wholesale & distribution"],["✚","Medical representatives"],["▣","Dealers & service centers"],["▤","Showrooms & field sales"],["◆","Dealers & service"],["●","Sales & distribution"],["▰","Projects & field teams"],["•••","And many more industries"]];
const benefits=["Easy to Use","Mobile & Web","Secure & Reliable","Flexible Plans","Dedicated Support","Regular Updates"];

export default async function Home(){const testimonials=await db.publicTestimonial.findMany({where:{isPublished:true},orderBy:[{displayOrder:"asc"},{createdAt:"desc"}],take:6});return <>
<section className="new-hero reference-hero">
 <div className="hero-copy"><p className="eyebrow">ONE PLATFORM. COMPLETE BUSINESS CONTROL.</p><h1><span>Track Your Field Sales.</span><em>Manage Your Business.</em>Grow Without Limits.</h1><p>SalesPunch360 combines real-time sales tracking with powerful account and business management — giving you complete visibility, control, and growth in one easy-to-use platform.</p><div className="button-row"><Link className="button" href="/register">Start {TRIAL_DURATION_DAYS}-day Free Trial →</Link><Link className="button secondary" href="/demo">Watch Demo</Link></div><div className="hero-trust"><span>◉ No credit card required</span><span>⚙ Quick setup</span><span>▣ Secure & reliable</span><span>♟ Trusted by growing businesses</span></div></div>
 <div className="product-preview photo-hero" aria-label="SalesPunch360 field sales visual"><div className="hero-note">On the Field.<br/><b>Always Connected.</b><i>↘</i></div><div className="hero-map-pin" aria-hidden="true">●</div><div className="hero-person-photo" role="img" aria-label="Field sales professional using a tablet"/><div className="preview-window"><div className="preview-top"><b>SalesPunch360</b><span>Business overview</span></div><div className="preview-body"><aside>Dashboard<br/>Check-ins<br/>Leads<br/>Follow-ups<br/>Accounts<br/>Reports</aside><div className="preview-main"><h3>Good morning!</h3><div className="metric-row"><span><b>GPS</b>Check-ins</span><span><b>CRM</b>Leads</span><span><b>✓</b>Follow-ups</span><span><b>↗</b>Targets</span></div><div className="chart"><i/><i/><i/><i/><i/><i/></div></div></div></div><div className="phone-preview"><b>SalesPunch360</b><span>Check-in</span><span>Leads</span><span>Follow-ups</span><span>Accounts</span></div></div>
</section>
<section className="dual-products reference-products">
 <article className="focus-card sales-focus reference-sales-card"><div className="focus-copy"><h2>Sales Tracking</h2><h3>Track. Engage. Convert.</h3><p>Empower your field team with real-time location tracking, check-ins, leads, follow-ups and performance insights.</p><ul>{sales.map(x=><li key={x}>✓ {x}</li>)}</ul><Link className="focus-link" href="/products/salespunch360">Explore Sales Tracking →</Link></div><div className="focus-visual photo-card sales-photo"><div className="sales-checkin-card"><b>Check-in Successful</b><span>10:24 AM</span><small>HSR Layout, Bengaluru</small></div><div className="photo-caption"><strong>Live field activity</strong><span>GPS check-ins · Leads · Follow-ups</span></div></div></article>
 <article className="focus-card account-focus reference-account-card"><div className="focus-copy"><h2>Account & Business<br/>Management</h2><h3>Control. Manage. Scale.</h3><p>Manage your company, users, subscriptions, billing and settings — all from a single platform.</p><ul>{account.map(x=><li key={x}>✓ {x}</li>)}</ul><Link className="focus-link account-link" href="/products/account">Explore Account →</Link></div><div className="focus-visual photo-card account-photo"><div className="account-menu-float"><b>Business Overview</b><span>▣ Accounts</span><span>▤ Quotations & Invoices</span><span>◆ Projects</span><span>▦ Reports</span></div><div className="photo-caption"><strong>Business workspace</strong><span>Accounts · Projects · Reports</span></div></div></article>
</section>
<section className="industry-section reference-industries"><div className="section-heading center"><p className="eyebrow">BUILT FOR EVERY INDUSTRY</p><h2>Works for Your Business</h2><p>From retail to manufacturing, SalesPunch360 adapts to your industry needs.</p></div><div className="industry-grid">{industries.map((x,i)=><div className={`industry-card industry-${i+1}`} key={x}><b aria-hidden="true">{industryMeta[i][0]}</b><span>{x}</span><small>{industryMeta[i][1]}</small></div>)}</div></section>
<section className="proof-strip reference-proof" aria-label="SalesPunch360 business statistics"><div><i>⌂</i><b>1,000+</b><span>Active Businesses</span></div><div><i>☑</i><b>50,000+</b><span>Field Check-ins Daily</span></div><div><i>☆</i><b>95%</b><span>Customer Satisfaction</span></div><div><i>◴</i><b>99.9%</b><span>Uptime &amp; Reliability</span></div><aside className="proof-trust" aria-label="Trusted by businesses across India">↙ <strong>Trusted by<br/>Businesses Across India</strong></aside></section>
<section className="why-section reference-why"><div className="section-heading center"><p className="eyebrow">WHY CHOOSE SALESPUNCH360</p><h2>Everything You Need to Grow</h2><p>A complete solution to manage your field sales and business operations.</p></div><div className="reference-benefits">{benefits.map((x,i)=><article className={`benefit-${i+1}`} key={x}><i>{["✓","▣","◆","↗","♟","⟳"][i]}</i><div><b>{x}</b><span>{["Get started in minutes","Access anywhere","Your data is safe","For businesses of all sizes","We’re here to help","Always improving"][i]}</span></div></article>)}</div><div className="why-actions"><Link className="button" href="/features">Explore All Features →</Link><Link href="/security">Security & control →</Link></div></section>
<section className="testimonial-section reference-testimonials"><div className="section-heading center"><p className="eyebrow">WHAT OUR CUSTOMERS SAY</p><h2>Trusted by Businesses Across India</h2><p>See how SalesPunch360 helps businesses improve field sales and operations.</p></div>{testimonials.length>0?<><div className="testimonial-grid">{testimonials.slice(0,3).map((item,i)=><article key={item.id} className={i===1?"featured-testimonial":undefined}><div className="demo-stars" aria-label={`${item.rating} out of 5 stars`}>{"★".repeat(item.rating)}{"☆".repeat(5-item.rating)}</div><p>“{item.quote}”</p><div className="demo-person">{item.imagePath?<img src={item.imagePath} alt="" width={52} height={52}/>:<i>{item.customerName.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}</i>}<span><b>{item.customerName}</b><small>{[item.customerRole,item.companyName].filter(Boolean).join(" · ")}</small></span></div></article>)}</div>{testimonials.length>3?<div className="testimonial-dots" aria-hidden="true"><i/><i className="active"/><i/></div>:null}</>:<p className="testimonial-empty">Customer stories will be published here soon.</p>}</section>
<CTA/>
</>}