import type {Metadata} from "next";
import Link from "next/link";
import {CTA} from "@/components/public/marketing-ui";
import {TRIAL_DURATION_DAYS} from "@/lib/trial/config";

export const metadata:Metadata={title:"Field Sales Tracking & Business Accounts",description:"Track field sales and manage business accounts together with SalesPunch360.",alternates:{canonical:"/"}};

const sales=["GPS-enabled check-ins and attendance","Leads, pipeline and customer visits","Follow-ups and reminders","Monthly targets and achievement","Field reports and route visibility"];
const account=["Account users and role-based access","Subscription packages and payments","Quotations, invoices and receipts","Purchases, expenses and stock","Projects, profitability and financial reports"];
const industries=["Retail & FMCG","Distributors","Pharma & Healthcare","Electronics","Furniture","Automotive","Food & Beverage","Construction","And more"];
const benefits=["Easy to use","Web + Android","Secure & reliable","Flexible plans","Role-based access","Regular updates"];

export default function Home(){return <>
<section className="new-hero reference-hero">
 <div className="hero-copy"><p className="eyebrow">SMARTER FIELD SALES. STRONGER BUSINESS.</p><h1><span>Track Your Field Sales.</span><em>Manage Your Business.</em>Grow Without Limits.</h1><p>SalesPunch360 combines real-time field sales tracking with powerful account and business management—giving your team clear visibility, control and growth in one connected platform.</p><div className="button-row"><Link className="button" href="/register">Start {TRIAL_DURATION_DAYS}-day Free Trial →</Link><Link className="button secondary" href="/demo">Watch Demo</Link></div><div className="hero-trust"><span>✓ No credit card required</span><span>● Quick setup</span><span>◆ Secure & reliable</span></div></div>
 <div className="product-preview photo-hero" aria-label="SalesPunch360 field sales visual"><div className="hero-note">On the Field.<br/><b>Always Connected.</b><i>↘</i></div><div className="hero-map-pin" aria-hidden="true">●</div><div className="hero-person-photo" role="img" aria-label="Field sales professional using a tablet"/><div className="preview-window"><div className="preview-top"><b>SalesPunch360</b><span>Business overview</span></div><div className="preview-body"><aside>Dashboard<br/>Check-ins<br/>Leads<br/>Follow-ups<br/>Accounts<br/>Reports</aside><div className="preview-main"><h3>Good morning!</h3><div className="metric-row"><span><b>GPS</b>Check-ins</span><span><b>CRM</b>Leads</span><span><b>✓</b>Follow-ups</span><span><b>↗</b>Targets</span></div><div className="chart"><i/><i/><i/><i/><i/><i/></div></div></div></div><div className="phone-preview"><b>SalesPunch360</b><span>Check-in</span><span>Leads</span><span>Follow-ups</span><span>Accounts</span></div></div>
</section>
<section className="dual-products reference-products">
 <article className="focus-card sales-focus reference-sales-card"><div className="focus-copy"><p className="eyebrow">FIELD SALES MADE SIMPLE</p><h2>Sales Tracking</h2><h3>Track. Engage. Convert.</h3><p>Empower your field team with real-time activity, customer and performance visibility.</p><ul>{sales.map(x=><li key={x}>✓ {x}</li>)}</ul><Link className="focus-link" href="/products/salespunch360">Explore Sales Tracking →</Link></div><div className="focus-visual photo-card sales-photo"><div className="sales-checkin-card"><b>Check-in Successful</b><span>Customer visit recorded</span><small>● GPS verified</small></div><div className="photo-caption"><strong>Live field activity</strong><span>GPS check-ins · Leads · Follow-ups</span></div></div></article>
 <article className="focus-card account-focus"><div><p className="eyebrow">Business control</p><h2>Account & Business Management</h2><h3>Control. Manage. Scale.</h3><p>Run your business operations with authorized users, transactions, projects, stock and reporting.</p><ul>{account.map(x=><li key={x}>✓ {x}</li>)}</ul><Link href="/products/account">Explore Account →</Link></div><div className="focus-visual photo-card account-photo"><div className="photo-caption"><strong>Business workspace</strong><span>Accounts · Projects · Reports</span></div></div></article>
</section>
<section className="industry-section"><div className="section-heading center"><p className="eyebrow">Built for every industry</p><h2>Works for Your Business</h2><p>From distributors to retailers and service teams, SalesPunch360 adapts to the way your business works.</p></div><div className="industry-grid">{industries.map((x,i)=><div key={x}><b>{["▣","🚚","✚","▤","▥","◆","◉","▰","•••"][i]}</b><span>{x}</span></div>)}</div></section>
<section className="proof-strip"><div><b>Field</b><span>GPS visits & routes</span></div><div><b>Sales</b><span>Leads & follow-ups</span></div><div><b>Business</b><span>Accounts & projects</span></div><div><b>Reports</b><span>Actionable visibility</span></div></section>
<section className="why-section"><div className="why-visual growth-photo"><div className="activity-card"><b>Today on the field</b><span>✓ Visit recorded</span><span>✓ Lead added</span><span>✓ Follow-up scheduled</span><span>✓ Expense submitted</span></div></div><div><p className="eyebrow">Why SalesPunch360</p><h2>More Than Software.<br/>A Partner in Your Growth.</h2><p>Bring field execution and business operations into one secure platform without losing role boundaries or branch context.</p><div className="benefit-grid">{benefits.map(x=><span key={x}>✓ {x}</span>)}</div><div className="button-row"><Link className="button" href="/features">Explore Features</Link><Link href="/security">Security & control →</Link></div></div></section>
<section className="testimonial-section"><div className="section-heading center"><p className="eyebrow">Built for growing teams</p><h2>One connected view from field to business.</h2></div><div className="testimonial-grid"><article><b>Field visibility</b><p>Know where authorized field work is happening and what action comes next.</p></article><article><b>Connected operations</b><p>Move from customer activity into quotations, invoices, projects and reporting.</p></article><article><b>Controlled access</b><p>Give each Sales or Account user the workspace and permissions their role requires.</p></article></div></section>
<CTA/>
</>}