import {ZodError} from "zod";
import {getCheckInFailureStage} from "./field-checkin-stage";

const safeCodes=new Set(["ATTENDANCE_REQUIRED","CHECKOUT_REQUIRED","PHOTO_REQUIRED","PHOTO_INVALID","PHOTO_STORAGE_NOT_CONFIGURED","PHOTO_STORAGE_UNAVAILABLE","REPEAT_VISIT_OUTSIDE_RADIUS","SUBJECT_OWNERSHIP_CONFLICT","SUBSCRIPTION_REQUIRED","CUSTOMER_NOT_FOUND","VISIT_NOT_FOUND","AUTHENTICATION_REQUIRED","AUTHORIZATION_REQUIRED"]);
const codeOf=(error:unknown)=>error instanceof ZodError?"VALIDATION_FAILED":error instanceof Error&&error.name==="AuthorizationError"?"AUTHORIZATION_REQUIRED":error instanceof Error&&error.name==="AuthenticationError"?"AUTHENTICATION_REQUIRED":error instanceof Error&&safeCodes.has(error.message)?error.message:"UNEXPECTED_ERROR";
const databaseCodeOf=(error:unknown)=>{if(!error||typeof error!=="object"||!("meta" in error)||!error.meta||typeof error.meta!=="object")return undefined;const meta=error.meta as Record<string,unknown>;for(const value of [meta.database_error_code,meta.code,meta.dbCode])if(typeof value==="string"&&/^[0-9A-Z]{5}$/.test(value))return value;return undefined;};

export function fieldCheckInErrorMessage(error:unknown){const code=codeOf(error),distance=typeof error==="object"&&error&&"distanceMeters"in error?Math.round(Number(error.distanceMeters)):undefined;return code==="ATTENDANCE_REQUIRED"?"Start attendance before check-in.":code==="CHECKOUT_REQUIRED"?"Complete your current checkout before starting another check-in.":code==="PHOTO_REQUIRED"?"A photo is required for this check-in.":code==="PHOTO_INVALID"?"Unable to process this photo. Please take the photo again.":code==="PHOTO_STORAGE_NOT_CONFIGURED"?"Photo storage is not configured yet. Please contact your administrator.":code==="PHOTO_STORAGE_UNAVAILABLE"?"Photo storage is temporarily unavailable. Please try again later.":code==="REPEAT_VISIT_OUTSIDE_RADIUS"?`You are outside the allowed 50 m check-in radius. Current distance: ${distance} m.`:code==="SUBJECT_OWNERSHIP_CONFLICT"?"This phone or subject requires assignment resolution.":code==="SUBSCRIPTION_REQUIRED"?"Your subscription does not allow check-ins. Please contact your administrator.":code==="CUSTOMER_NOT_FOUND"?"This customer is unavailable or is not assigned to you.":code==="VISIT_NOT_FOUND"?"This visit or prospect is unavailable or is not assigned to you.":code==="AUTHENTICATION_REQUIRED"?"Your session has expired. Please sign in again.":code==="AUTHORIZATION_REQUIRED"?"You are not authorized to add this check-in.":code==="VALIDATION_FAILED"?"Check the required fields, GPS, and selected visit type.":"Unable to add check-in. Verify the selection, GPS, and photo."}

export function logFieldCheckInFailure(error:unknown,rawVisitType:string){const prismaCode=typeof error==="object"&&error&&"code"in error&&typeof error.code==="string"&&/^P\d{4}$/.test(error.code)?error.code:undefined;const databaseCode=databaseCodeOf(error);const zodFieldPaths=error instanceof ZodError?error.issues.map(issue=>issue.path.map(String).join(".")).filter(Boolean):[];const name=error instanceof Error&&/^[A-Za-z][A-Za-z0-9]*$/.test(error.name)?error.name.slice(0,80):"UnknownError";const visitType=["NEW","FOLLOW_UP","CUSTOMER"].includes(rawVisitType)?rawVisitType:"UNKNOWN";console.error({event:"FIELD_CHECKIN_FAILED",errorName:name,errorCode:codeOf(error),prismaCode,databaseCode,stage:getCheckInFailureStage(error),zodFieldPaths,visitType});}
