"use client";
import { useActionState, useMemo, useState } from "react";
import type { QuotationActionState } from "@/app/actions/quotations";
type Option={id:string;name:string;code?:string|null;unitId?:string|null;description?:string|null;salePrice?:unknown;sellingRate?:unknown;costPrice?:unknown;estimatedCost?:unknown;taxRate?:unknown};
type EditorOptions={branches:Array<{id:string;name:string;code:string}>;customers:Array<{id:string;name:string;contactPerson:string|null;branchId:string}>;leads:Array<{id:string;title:string;companyName:string|null;contactName:string|null;branchId:string}>;products:Option[];services:Option[];workPackages:Option[];units:Array<{id:string;name:string;symbol:string}>;canCost:boolean};
type Line={lineType:"PRODUCT"|"SERVICE"|"WORK_PACKAGE"|"CUSTOM";sourceId?:string;itemName?:string;unitId?:string;unitName?:string;unitSymbol?:string;description?:string;specification?:string;quantity:string;rate?:string;internalUnitCost?:string;taxRate?:string;discountType?:"PERCENTAGE"|"FIXED"|null;discountValue?:string|null};
type Adjustment={type:"DISCOUNT"|"ADDITIONAL_CHARGE";label:string;valueType:"PERCENTAGE"|"FIXED";value:string;taxable?:boolean;taxRate?:string};
type Payment={label:string;valueType:"PERCENTAGE"|"FIXED";value:string;dueDescription?:string};
type Initial={branchId:string;documentType:"QUOTATION"|"ESTIMATE"|"BOQ";customerId?:string;sourceLeadId?:string;issueDate:string|Date;validUntil?:string|Date;terms?:string;inclusions?:string;exclusions?:string;notes?:string;lines:Line[];adjustments:Adjustment[];paymentSchedule:Payment[]};
const today=()=>new Date().toISOString().slice(0,10);const blankLine:Line={lineType:"CUSTOM",itemName:"",quantity:"1",rate:"0",taxRate:"0",description:"",specification:""};
const blank:Initial={branchId:"",documentType:"QUOTATION",customerId:"",issueDate:today(),lines:[blankLine],adjustments:[],paymentSchedule:[],terms:"",inclusions:"",exclusions:"",notes:""};
export function QuotationEditor({action,options,initial,lockIdentity=false}:{action:(s:QuotationActionState,f:FormData)=>Promise<QuotationActionState>;options:EditorOptions;initial?:Initial;lockIdentity?:boolean}){
 const [state,submit,pending]=useActionState(action,{}),[value,setValue]=useState<Initial>(initial??{...blank,branchId:options.branches[0]?.id??""});
 const partyType=value.sourceLeadId!==undefined?"LEAD":"CUSTOMER";const masters=useMemo(()=>value.lines.map(line=>line.lineType==="PRODUCT"?options.products:line.lineType==="SERVICE"?options.services:line.lineType==="WORK_PACKAGE"?options.workPackages:[]),[value.lines,options]);
 const patch=(next:Partial<Initial>)=>setValue(old=>({...old,...next}));const patchLine=(i:number,next:Partial<Line>)=>patch({lines:value.lines.map((line,n)=>n===i?{...line,...next}:line)});
 const selectMaster=(i:number,id:string)=>{const item=masters[i].find(x=>x.id===id);if(!item)return patchLine(i,{sourceId:undefined});patchLine(i,{sourceId:id,itemName:item.name,unitId:item.unitId??undefined,description:item.description??"",rate:String(item.salePrice??item.sellingRate??0),internalUnitCost:options.canCost?String(item.costPrice??item.estimatedCost??0):undefined,taxRate:String(item.taxRate??0)});};
 return <form action={submit} className="stack"><input type="hidden" name="document" value={JSON.stringify(value)}/><fieldset><legend>Document</legend><label>Type <select disabled={lockIdentity} value={value.documentType} onChange={e=>patch({documentType:e.target.value as Initial["documentType"]})}><option value="QUOTATION">Quotation</option><option value="ESTIMATE">Estimate</option><option value="BOQ">BOQ</option></select></label><label>Branch <select disabled={lockIdentity} required value={value.branchId} onChange={e=>patch({branchId:e.target.value})}><option value="">Select branch</option>{options.branches.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><label>Party <select disabled={lockIdentity} value={partyType} onChange={e=>patch(e.target.value==="LEAD"?{sourceLeadId:"",customerId:undefined}:{customerId:"",sourceLeadId:undefined})}><option value="CUSTOMER">Account Customer</option>{options.leads.length>0&&<option value="LEAD">Plus Lead</option>}</select></label>{partyType==="CUSTOMER"?<label>Customer <select disabled={lockIdentity} required value={value.customerId??""} onChange={e=>patch({customerId:e.target.value})}><option value="">Select customer</option>{options.customers.filter(x=>!value.branchId||x.branchId===value.branchId).map(x=><option key={x.id} value={x.id}>{x.name}{x.contactPerson?` — ${x.contactPerson}`:""}</option>)}</select></label>:<label>Lead <select disabled={lockIdentity} required value={value.sourceLeadId??""} onChange={e=>patch({sourceLeadId:e.target.value})}><option value="">Select authorized lead</option>{options.leads.filter(x=>!value.branchId||x.branchId===value.branchId).map(x=><option key={x.id} value={x.id}>{x.companyName??x.title}{x.contactName?` — ${x.contactName}`:""}</option>)}</select></label>}<label>Issue date <input type="date" value={String(value.issueDate).slice(0,10)} onChange={e=>patch({issueDate:e.target.value})}/></label><label>Valid until <input type="date" value={value.validUntil?String(value.validUntil).slice(0,10):""} onChange={e=>patch({validUntil:e.target.value||undefined})}/></label></fieldset>
 <fieldset><legend>BOQ lines</legend>{value.lines.map((line,i)=><article key={i} className="stack"><label>Line type <select value={line.lineType} onChange={e=>patchLine(i,{...blankLine,lineType:e.target.value as Line["lineType"]})}><option value="PRODUCT">Product</option><option value="SERVICE">Service</option><option value="WORK_PACKAGE">Work / Package</option><option value="CUSTOM">Custom</option></select></label>{line.lineType!=="CUSTOM"?<label>Master item <select required value={line.sourceId??""} onChange={e=>selectMaster(i,e.target.value)}><option value="">Select item</option>{masters[i].map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:""}</option>)}</select></label>:<label>Item name <input required value={line.itemName??""} onChange={e=>patchLine(i,{itemName:e.target.value})}/></label>}<label>Unit <select value={line.unitId??""} onChange={e=>patchLine(i,{unitId:e.target.value||undefined})}><option value="">Custom / none</option>{options.units.map(x=><option key={x.id} value={x.id}>{x.name} ({x.symbol})</option>)}</select></label><label>Quantity <input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={e=>patchLine(i,{quantity:e.target.value})}/></label><label>Rate <input type="number" min="0" step="0.01" value={line.rate??""} onChange={e=>patchLine(i,{rate:e.target.value})}/></label><label>Tax % <input type="number" min="0" max="100" step="0.01" value={line.taxRate??""} onChange={e=>patchLine(i,{taxRate:e.target.value})}/></label><label>Line discount <select value={line.discountType??""} onChange={e=>patchLine(i,{discountType:(e.target.value||null) as Line["discountType"]})}><option value="">None</option><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed</option></select><input type="number" min="0" step="0.01" value={line.discountValue??""} onChange={e=>patchLine(i,{discountValue:e.target.value})}/></label>{options.canCost&&<label>Internal estimated unit cost <input type="number" min="0" step="0.01" value={line.internalUnitCost??""} onChange={e=>patchLine(i,{internalUnitCost:e.target.value})}/></label>}<label>Description <textarea value={line.description??""} onChange={e=>patchLine(i,{description:e.target.value})}/></label><label>Specification / materials <textarea value={line.specification??""} onChange={e=>patchLine(i,{specification:e.target.value})}/></label><button type="button" disabled={value.lines.length===1} onClick={()=>patch({lines:value.lines.filter((_,n)=>n!==i)})}>Remove line</button></article>)}<button type="button" onClick={()=>patch({lines:[...value.lines,{...blankLine}]})}>Add line</button></fieldset>
 <Rows title="Discounts / additional charges" rows={value.adjustments} setRows={adjustments=>patch({adjustments})}/><PaymentRows rows={value.paymentSchedule} setRows={paymentSchedule=>patch({paymentSchedule})}/><fieldset><legend>Customer terms</legend>{(["terms","inclusions","exclusions","notes"] as const).map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)} <textarea value={value[key]??""} onChange={e=>patch({[key]:e.target.value})}/></label>)}</fieldset><button disabled={pending}>{pending?"Saving…":"Save draft"}</button>{state.error&&<p role="alert">{state.error}</p>}</form>;
}
function Rows({title,rows,setRows}:{title:string;rows:Adjustment[];setRows:(x:Adjustment[])=>void}){return <fieldset><legend>{title}</legend>{rows.map((r,i)=><div key={i}><select value={r.type} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,type:e.target.value as Adjustment["type"]}:x))}><option value="DISCOUNT">Discount</option><option value="ADDITIONAL_CHARGE">Additional charge</option></select><input placeholder="Label" value={r.label} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><select value={r.valueType} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,valueType:e.target.value as Adjustment["valueType"]}:x))}><option value="FIXED">Fixed</option><option value="PERCENTAGE">Percentage</option></select><input type="number" min="0" step="0.01" value={r.value} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,value:e.target.value}:x))}/>{r.type==="ADDITIONAL_CHARGE"&&<><label>Taxable <input type="checkbox" checked={r.taxable??false} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,taxable:e.target.checked}:x))}/></label><label>Tax % <input type="number" min="0" max="100" step="0.01" value={r.taxRate??"0"} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,taxRate:e.target.value}:x))}/></label></>}<button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" onClick={()=>setRows([...rows,{type:"DISCOUNT",label:"",valueType:"FIXED",value:"0"}])}>Add adjustment</button></fieldset>}
function PaymentRows({rows,setRows}:{rows:Payment[];setRows:(x:Payment[])=>void}){return <fieldset><legend>Payment schedule</legend>{rows.map((r,i)=><div key={i}><input placeholder="Milestone" value={r.label} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><select value={r.valueType} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,valueType:e.target.value as Payment["valueType"]}:x))}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select><input type="number" min="0" step="0.01" value={r.value} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,value:e.target.value}:x))}/><input placeholder="Due timing" value={r.dueDescription??""} onChange={e=>setRows(rows.map((x,n)=>n===i?{...x,dueDescription:e.target.value}:x))}/><button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" onClick={()=>setRows([...rows,{label:"",valueType:"PERCENTAGE",value:"0"}])}>Add milestone</button></fieldset>}
