"use client";
import { useActionState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { replaceCompanyLogo, saveCompanyProfile } from "@/app/actions/company-profile";
import {CompanyIdentityLogo} from "@/components/workspace/company-identity-logo";
import type {CompanyProfileDto} from "@/lib/company/profile";
import type {ProductEdition} from "@prisma/client";
type ProfileField=Exclude<keyof CompanyProfileDto,"hasLogo"|"logoVersion"|"teamStructure"|"description"|"enabledModules"|"primaryBranch">;
const fields:[ProfileField,string,boolean][]=[["name","Company / business name",true],["addressLine1","Address line 1",true],["addressLine2","Address line 2",false],["locality","Locality",false],["city","City",true],["state","State",true],["postalCode","PIN / postal code",true],["country","Country",true],["primaryContactName","Primary contact name",true],["primaryPhone","Primary phone",true],["contactEmail","Company contact email",true],["alternatePhone","Alternate phone",false],["website","Website",false],["gstin","GSTIN",false],["pan","PAN",false],["registrationNumber","Registration number",false]];
export function ProfileForm({profile,edition,editable}:{profile:CompanyProfileDto;edition:ProductEdition;editable:boolean}){
 const[state,action,pending]=useActionState(saveCompanyProfile,{}),[logoState,logoAction,logoPending]=useActionState(replaceCompanyLogo,{}),router=useRouter();
 const returnHref=edition==="SALESPUNCH360_ACCOUNT"?"/workspace/account":"/workspace";
 useEffect(()=>{if(!state.success)return;const timer=window.setTimeout(()=>router.push(returnHref),700);return()=>window.clearTimeout(timer)},[state.success,returnHref,router]);
 return <><section className="profile-form"><h2>Primary Branch</h2><p><strong>{profile.primaryBranch?.name??"Head Office"}</strong> ({profile.primaryBranch?.code??"HO"})</p>{editable&&<Link className="primary-button" href="/workspace/branches">Add Branch</Link>}</section><section className="profile-form company-logo-settings"><h2>Company Logo</h2><div className="company-logo-current"><CompanyIdentityLogo name={profile.name||"Company"} hasLogo={profile.hasLogo} version={profile.logoVersion}/></div>{editable?<form action={logoAction}><label className="field">Replace logo (optional)<input name="companyLogo" type="file" accept="image/jpeg,image/png,image/webp" required/><small>JPEG, PNG, or WebP. Maximum 5 MB.</small></label>{logoState.error&&<p className="form-error">{logoState.error}</p>}{logoState.success&&<p className="form-success">{logoState.success}</p>}<button className="primary-button" disabled={logoPending}>{logoPending?"Uploading…":"Replace Company Logo"}</button></form>:<p className="muted">Only the Primary Admin can replace this logo.</p>}</section><form action={action} className="profile-form"><fieldset disabled={!editable}><div className="field-grid">{fields.map(([name,label,required])=><label className="field" key={name}>{label}<input name={name} defaultValue={profile[name]??""} required={required} type={name.includes("Email")||name==="contactEmail"?"email":name==="website"?"url":"text"}/>{state.fieldErrors?.[name]&&<span className="field-error">{state.fieldErrors[name][0]}</span>}</label>)}{edition!=="SALESPUNCH360_ACCOUNT"?<><label className="field full">Sales Team Structure<select className="team-structure-select" name="teamStructure" defaultValue={profile.teamStructure??"MANAGERS_AND_SALES"} required><option value="MANAGERS_AND_SALES">Admin → Managers → Sales Team</option><option value="SALES_ONLY">Admin → Sales Team</option></select></label><label className="field full">Company description<textarea name="description" defaultValue={profile.description??""} maxLength={2000}/></label></>:<><input type="hidden" name="teamStructure" value={profile.teamStructure}/><input type="hidden" name="description" value={profile.description??""}/></>} </div></fieldset>{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.success&&<p className="form-success" role="status">Saved successfully. Returning…</p>}{editable&&<button className="primary-button" disabled={pending}>{pending?"Saving…":"Save Company Details"}</button>}</form></>}
