export const editions = [
  {key:"SALESPUNCH360",name:"SalesPunch360",tagline:"Field Sales & CRM",href:"/products/salespunch360",summary:"Attendance, GPS, visits, leads, follow-ups, targets and field reports for teams on the move."},
  {key:"SALESPUNCH360_ACCOUNT",name:"SalesPunch360 Account",tagline:"Accounts & Business Management",href:"/products/account",summary:"Sales, purchases, projects, expenses, inventory, GST, financial reports and branches in one workspace."},
  {key:"SALESPUNCH360_PLUS",name:"SalesPunch360 Plus",tagline:"Field Sales + Accounts, Connected",href:"/products/plus",summary:"Connect Sales and Account workspaces in one Company, with role-based access and consolidated visibility."},
] as const;

export const features = [
  {slug:"field-sales",group:"Field sales",title:"Field Sales",problem:"Give field teams one clear daily workflow and managers reliable operational visibility.",capabilities:["Daily field workflow","Customer history","Manager reports","Mobile-responsive operations"],steps:["Plan the day","Work customer opportunities","Record outcomes","Review performance"]},
  {slug:"attendance-gps",group:"Field sales",title:"Attendance & GPS",problem:"Understand when the day starts and where field activity happens without relying on scattered updates.",capabilities:["Attendance records","Location tracking","Route history","Attendance and GPS reports"],steps:["Start the day","Capture permitted location activity","Build route history","Review reports"]},
  {slug:"check-ins-visits",group:"Field sales",title:"Check-ins & Visits",problem:"Turn every customer visit into structured, useful history.",capabilities:["New, follow-up and customer visits","Check-in records","Geofence reporting","Visit reports"],steps:["Choose visit type","Check in","Record the outcome","Review visit history"]},
  {slug:"leads-follow-ups",group:"Field sales",title:"Leads & Follow-ups",problem:"Keep the next sales action visible from first conversation to outcome.",capabilities:["Lead records","Pipeline stages","Follow-up tasks","Customer context"],steps:["Capture a lead","Move it through the pipeline","Schedule follow-up","Close with a clear outcome"]},
  {slug:"targets-performance",group:"Field sales",title:"Targets & Performance",problem:"Connect team goals to field execution and useful manager analysis.",capabilities:["Monthly targets","Team visibility","Target analysis","Performance reporting"],steps:["Set targets","Track activity","Compare progress","Coach with context"]},
  {slug:"quotations-sales",group:"Business",title:"Quotations & Sales",problem:"Move from an agreed scope to recorded revenue without re-entering the same business context.",capabilities:["Quotations and estimates","BOQ","Sales invoices","Receipts and advances"],steps:["Prepare a quotation","Confirm the scope","Raise an invoice","Record receipts"]},
  {slug:"purchases-vendors",group:"Business",title:"Purchases & Vendors",problem:"Keep buying activity and vendor obligations connected to the business and its projects.",capabilities:["Vendor masters","Purchase records","Purchase orders and bills","Vendor payables"],steps:["Select a vendor","Record the purchase","Allocate business context","Review payables"]},
  {slug:"projects-profitability",group:"Business",title:"Projects & Profitability",problem:"Know whether project delivery is on budget and making money.",capabilities:["Budgets and milestones","Revenue and actual cost","Committed cost","Profitability and budget-versus-actual"],steps:["Create the project","Set budget and tasks","Connect sales and costs","Review profitability"]},
  {slug:"expenses-money",group:"Business",title:"Expenses & Money",problem:"Bring operating expenses and funding movements into a controlled financial view.",capabilities:["Expenses and other income","Cash and bank","Capital and loans","Project and branch context"],steps:["Record the movement","Classify it","Connect context","Review balances"]},
  {slug:"inventory",group:"Business",title:"Inventory",problem:"See stock across warehouses and keep movements accountable.",capabilities:["Items and warehouses","Transfers and adjustments","Stock valuation","Multiple pricing"],steps:["Set up items","Receive or adjust stock","Transfer when needed","Review quantity and value"]},
  {slug:"gst-accounting",group:"Accounting",title:"GST & Accounting",problem:"Apply Indian tax rules while maintaining controlled accounting records.",capabilities:["CGST, SGST and IGST","HSN/SAC","Inclusive and exclusive tax","ITC, TDS and TCS workflows"],steps:["Configure tax details","Create transactions","Post accounting effects","Review tax information"]},
  {slug:"financial-reports",group:"Accounting",title:"Financial Reports",problem:"Turn day-to-day transactions into decision-ready financial statements.",capabilities:["Profit & Loss and Balance Sheet","Trial Balance and Cash Flow","General Ledger","Customer, vendor and aging reports"],steps:["Record controlled transactions","Review ledgers","Reconcile context","Read financial statements"]},
  {slug:"branches-consolidation",group:"Accounting",title:"Branches & Consolidation",problem:"Operate multiple branches without losing Company-wide visibility.",capabilities:["One Company, multiple Branches","Branch-aware access","Branch dashboards","Consolidated reporting"],steps:["Create branches","Assign access","Operate in branch context","Review consolidated results"]},
] as const;
export type Feature = (typeof features)[number];
export const faqs = [
 ["What is SalesPunch360?","A connected platform for field sales, CRM, accounts, projects, inventory, reporting and multi-branch operations."],
 ["What is the difference between SalesPunch360, Account and Plus?","SalesPunch360 is the Field Sales & CRM edition, Account is the accounts and business-management edition, and Plus enables both workspaces in one Company."],
 ["Can I start with Sales and later use Accounts?","Choose the edition that fits today; contact us when you want help moving to a broader edition."],
 ["Does SalesPunch360 support multiple branches?","Yes. Branch-aware access and Company-level visibility are available where the selected product and role permit them."],
 ["Can my field team use Android?","Yes. Field teams can use Android for operational field workflows; access remains role-based."],
 ["Can my accounts team use SalesPunch360?","Accounts teams use the Account workspace in SalesPunch360 Account or Plus, according to their assigned roles."],
 ["Is there a free trial?","Yes. Every public edition starts with the configured free trial period."],
 ["Do I need a credit card to start?","No credit card is required to begin the free trial."],
 ["Can different users have different roles?","Yes. Permissions, workspace access and branch access are role-based."],
 ["Does SalesPunch360 support GST and financial reports?","The Account workspace supports GST workflows and financial reports including P&L, Balance Sheet, Trial Balance, Cash Flow and ledgers."],
] as const;
