"use server"; import { revalidatePath } from "next/cache"; import { updateAccountSettings } from "@/lib/account/settings";
export async function updateAccountSettingsAction(fd: FormData) { await updateAccountSettings({ expenseApprovalRequired: fd.get("expenseApprovalRequired") === "on", expenseApprovalThreshold: String(fd.get("expenseApprovalThreshold") || "0"), negativeStockAllowed: fd.get("negativeStockAllowed") === "on", transactionDefaults: { defaultDueDays: Number(fd.get("defaultDueDays") || 0), salesTerms: String(fd.get("salesTerms") || ""), purchaseTerms: String(fd.get("purchaseTerms") || "") }, printProfile: { displayName: String(fd.get("displayName") || "") || undefined, bankName: String(fd.get("bankName") || "") || undefined, accountName: String(fd.get("accountName") || "") || undefined, accountNumber: String(fd.get("accountNumber") || "") || undefined, ifsc: String(fd.get("ifsc") || "") || undefined, upiId: String(fd.get("upiId") || "") || undefined, upiPayeeName: String(fd.get("upiPayeeName") || "") || undefined, authorizedSignatory: String(fd.get("authorizedSignatory") || "") || undefined } }); revalidatePath("/workspace/account/settings"); }
export async function uploadAuthorizedSignatureAction(fd:FormData){"use server";const{uploadAuthorizedSignature}=await import("@/lib/account/signatures");const file=fd.get("signature");if(!(file instanceof File))throw new Error("SIGNATURE_INVALID");await uploadAuthorizedSignature(file);revalidatePath("/workspace/account/settings")}
export async function removeAuthorizedSignatureAction(){"use server";const{removeCurrentAuthorizedSignature}=await import("@/lib/account/signatures");await removeCurrentAuthorizedSignature();revalidatePath("/workspace/account/settings")}
export async function updateItemSettingsAction(fd:FormData){"use server";const{updateItemSettings}=await import("@/lib/account/settings");const on=(key:string)=>fd.get(key)==="on";await updateItemSettings({enabled:on("enabled"),itemType:String(fd.get("itemType")||"BOTH"),barcodeScanning:on("barcodeScanning"),stockMaintenance:on("stockMaintenance"),itemUnits:on("itemUnits"),defaultUnit:String(fd.get("defaultUnit")||""),itemCategory:on("itemCategory"),partyWiseRate:on("partyWiseRate"),wholesalePrice:on("wholesalePrice"),quantityDecimals:Number(fd.get("quantityDecimals")||2),itemWiseTax:on("itemWiseTax"),taxOnMrp:on("taxOnMrp"),itemWiseDiscount:on("itemWiseDiscount"),updateSalePrice:on("updateSalePrice"),additionalFields:on("additionalFields"),customFields:on("customFields"),description:on("description"),hsnSac:on("hsnSac"),additionalCess:on("additionalCess")});revalidatePath("/workspace/account/inventory/item-settings")}
export async function updateGeneralSettingsAction(fd:FormData){"use server";const{updateGeneralSettings}=await import("@/lib/account/settings");await updateGeneralSettings({appLanguage:String(fd.get("appLanguage")||"en"),baseCurrency:String(fd.get("baseCurrency")||"INR"),displayDecimalPlaces:Number(fd.get("displayDecimalPlaces")??2),dateFormat:String(fd.get("dateFormat")||"DD/MM/YYYY"),warnUnsavedChanges:fd.get("warnUnsavedChanges")==="on",appearance:"STANDARD",fixedAssetsEnabled:fd.get("fixedAssetsEnabled")==="on"});revalidatePath("/workspace/account", "layout")}
export async function updateTransactionSettingsAction(fd:FormData){"use server";const {updateTransactionSettings}=await import("@/lib/account/settings");const {TRANSACTION_TOGGLES,PREFIX_TYPES}=await import("@/lib/account/transaction-settings");const preferences=Object.fromEntries(Object.values(TRANSACTION_TOGGLES).flat().map(([key])=>[key,fd.get(key)==="on"]));await updateTransactionSettings({preferences:{...preferences,shareAs:String(fd.get("shareAs")||"ASK"),roundingMode:"NEAREST",roundingStep:Number(fd.get("roundingStep")||1)},branchId:String(fd.get("branchId")||""),prefixes:Object.fromEntries(PREFIX_TYPES.map(([key])=>[key,String(fd.get(`prefix_${key}`)||"")]))});revalidatePath("/workspace/account/settings/transactions")}

export async function updateSalesInvoicePrefixAction(branchId:string,prefix:string){"use server";const{updateSalesInvoicePrefix}=await import("@/lib/account/settings");const row=await updateSalesInvoicePrefix(branchId,prefix);revalidatePath("/workspace/account/transactions/new");revalidatePath("/workspace/account/settings/transactions");return row}
