"use server";import {revalidatePath} from 'next/cache';import {redirect} from 'next/navigation';import {changePrice,confirmManualPayment,createAccountPackageOrder,createBillingOrder,manualOverride} from '@/lib/billing/service';import {attachTelecallerToBillingOrder,type TeamPurchaseMode} from '@/lib/billing/unified-team';import {notifyManualPaymentOrderApproved,notifyManualPaymentOrderCreated} from '@/lib/billing/manual-payment-email';import {logBillingFailure} from '@/lib/billing/diagnostics';import {mutationGuard} from '@/lib/security/request';
const knownOrderErrors=new Set(['SEATS_BELOW_USAGE','INVALID_SEAT_SELECTION','SEAT_SELECTION_REQUIRED','SEAT_REDUCTION_SELECTION_REQUIRED','PRICING_UNAVAILABLE','MANAGERS_DISABLED','PLUS_ACCOUNT_PACKAGE_REQUIRED','ACCOUNT_PACKAGE_NOT_ALLOWED','TELECALLER_SEATS_BELOW_USAGE','TELECALLER_SEAT_REDUCTION_RENEWAL_ONLY','SUBSCRIPTION_REQUIRED','RATE_LIMITED','UNTRUSTED_ORIGIN','INVALID_INPUT']);
const orderErrorCode=(error:unknown)=>{const code=error instanceof Error?error.message:'ORDER_CREATE_FAILED';return knownOrderErrors.has(code)?code:'ORDER_CREATE_FAILED'};
export async function createOrderAction(form:FormData){let orderId='';try{await mutationGuard('billing-order',10);if(form.get('paymentMethod')!=='MANUAL')throw new Error('INVALID_PAYMENT_METHOD');const base=await createBillingOrder({billingPeriod:form.get('billingPeriod'),adminSeats:form.get('adminSeats'),managerSeats:form.get('managerSeats'),salesSeats:form.get('salesSeats'),accountPackages:form.get('accountPackages'),retainAdminUserIds:form.getAll('retainAdminUserIds').map(String),retainManagerUserIds:form.getAll('retainManagerUserIds').map(String),retainSalesUserIds:form.getAll('retainSalesUserIds').map(String),idempotencyKey:crypto.randomUUID().replaceAll('-','')});const rawMode=String(form.get('purchaseMode')??'NEW'),mode:TeamPurchaseMode=rawMode==='ADD_TEAM'?'ADD_TEAM':rawMode==='RENEW'?'RENEW':'NEW';const order=await attachTelecallerToBillingOrder(base.id,base.companyId,base.createdByUserId,Math.max(0,Math.trunc(Number(form.get('telecallerSeats')??0))||0),mode);orderId=order.id;await notifyManualPaymentOrderCreated(order.id)}catch(error){logBillingFailure('CREATE_MANUAL_ORDER','createBillingOrder',error);redirect(`/workspace/billing?orderError=${encodeURIComponent(orderErrorCode(error))}`)}revalidatePath('/workspace/billing');redirect(`/workspace/billing/pending?order=${orderId}`)}
export async function createAccountPackageOrderAction(form:FormData){let orderId='';try{await mutationGuard('account-package-order',10);if(form.get('paymentMethod')!=='MANUAL')throw new Error('INVALID_PAYMENT_METHOD');const quantity=Number(form.get('quantity')??1),period=String(form.get('billingPeriod')??'YEARLY');if(period!=='SIX_MONTH'&&period!=='YEARLY')throw new Error('INVALID_BILLING_PERIOD');const order=await createAccountPackageOrder(quantity,period);orderId=order.id;await notifyManualPaymentOrderCreated(order.id)}catch(error){logBillingFailure('CREATE_ACCOUNT_PACKAGE_ORDER','createAccountPackageOrder',error);redirect(`/workspace/billing?orderError=${encodeURIComponent(orderErrorCode(error))}`)}revalidatePath('/workspace/billing');redirect(`/workspace/billing/pending?order=${orderId}`)}
export async function changePriceAction(form:FormData){await mutationGuard('pricing-change',10);await changePrice({role:form.get('role'),period:form.get('period'),amount:form.get('amount'),currency:'INR'});revalidatePath('/admin/pricing')}
export async function overrideSubscriptionAction(form:FormData){await mutationGuard('billing-override',10);await manualOverride({companyId:form.get('companyId'),status:form.get('status'),billingPeriod:form.get('billingPeriod'),adminSeats:form.get('adminSeats'),managerSeats:form.get('managerSeats'),salesSeats:form.get('salesSeats'),endsAt:new Date(String(form.get('endsAt'))).toISOString(),reason:form.get('reason')});revalidatePath('/admin/billing')}

export async function confirmManualPaymentAction(form:FormData){await mutationGuard('manual-payment-confirm',10);const reference=String(form.get('reference')??''),order=await confirmManualPayment(String(form.get('orderId')??''),reference);await notifyManualPaymentOrderApproved(order.id,reference);revalidatePath('/admin/billing');revalidatePath('/workspace/billing')}
