import{beforeEach,describe,expect,it,vi}from"vitest";
const m=vi.hoisted(()=>({origin:vi.fn(),user:vi.fn(),find:vi.fn(),verify:vi.fn(),hash:vi.fn(),replace:vi.fn()}));
vi.mock("next/navigation",()=>({redirect:vi.fn()}));vi.mock("@/lib/security/request",()=>({assertTrustedOrigin:m.origin,consumeRateLimit:vi.fn(),requestFingerprint:vi.fn()}));vi.mock("@/lib/auth/authorization",()=>({requireUser:m.user}));vi.mock("@/lib/auth/crypto",()=>({verifyPassword:m.verify,hashPassword:m.hash}));vi.mock("@/lib/auth/session",()=>({createSession:vi.fn(),revokeCurrentSession:vi.fn()}));vi.mock("@/lib/auth/session-generation",()=>({replacePasswordAndRevoke:m.replace}));vi.mock("@/lib/db",()=>({db:{user:{findUnique:m.find}}}));
import{changePassword}from"./auth";
const form=(current="OldPassword1",next="NewPassword2",confirm=next)=>{const f=new FormData();f.set("currentPassword",current);f.set("newPassword",next);f.set("confirmPassword",confirm);f.set("userId","another-user");return f};
beforeEach(()=>{vi.clearAllMocks();m.user.mockResolvedValue({id:"self",name:"Self",role:"SALES",companyId:"company"});m.find.mockResolvedValue({passwordHash:"old-hash"});m.verify.mockImplementation(async(hash:string,password:string)=>hash==="old-hash"&&password==="OldPassword1");m.hash.mockResolvedValue("new-hash")});
describe("web change password",()=>{
 it("rejects mismatched confirmation before reading a hash",async()=>{expect(await changePassword({},form("OldPassword1","NewPassword2","Different3"))).toMatchObject({error:expect.stringContaining("do not match")});expect(m.find).not.toHaveBeenCalled()});
 it("rejects weak new passwords",async()=>{expect(await changePassword({},form("OldPassword1","weak","weak"))).toHaveProperty("error");expect(m.replace).not.toHaveBeenCalled()});
 it("rejects a wrong current password",async()=>{m.verify.mockResolvedValue(false);expect(await changePassword({},form())).toMatchObject({error:expect.stringContaining("incorrect")});expect(m.replace).not.toHaveBeenCalled()});
 it("rejects reuse of the current password",async()=>{m.verify.mockResolvedValue(true);expect(await changePassword({},form("OldPassword1","OldPassword1"))).toMatchObject({error:expect.stringContaining("different")});expect(m.replace).not.toHaveBeenCalled()});
 it("updates only the authenticated user and revokes authentication everywhere",async()=>{m.verify.mockResolvedValueOnce(true).mockResolvedValueOnce(false);expect(await changePassword({},form())).toHaveProperty("success");expect(m.replace).toHaveBeenCalledWith("self","new-hash","old-hash");expect(m.replace).not.toHaveBeenCalledWith("another-user",expect.anything(),expect.anything());expect(m.origin).toHaveBeenCalled()});
});
