"use server";
import {revalidatePath} from "next/cache";
import {createLead,createLeadFromVisit,editLead,transitionLead} from "@/lib/leads/service";
import {LeadError} from "@/lib/leads/policy";
import {requirePermission} from "@/lib/auth/authorization";
import {ensureWonLeadProjectForActor} from "@/lib/leads/won-project";
export type LeadActionState={error?:string;success?:string};
const fields=(f:FormData)=>({title:f.get("title"),customerId:f.get("customerId"),contactName:f.get("contactName"),phone:f.get("phone"),email:f.get("email"),companyName:f.get("companyName"),source:f.get("source")||"MANUAL",estimatedValue:f.get("estimatedValue"),currencyCode:f.get("currencyCode")||"INR",followUpAt:f.get("followUpAt"),notes:f.get("notes"),assignedUserId:f.get("assignedUserId")});
export async function saveLead(_:LeadActionState,f:FormData):Promise<LeadActionState>{try{if(f.get("visitId")){const all=fields(f);const{source,customerId,...safe}=all;void source;void customerId;await createLeadFromVisit({...safe,visitId:f.get("visitId")});}else if(f.get("leadId"))await editLead({...fields(f),leadId:f.get("leadId"),version:f.get("version")} as never);else await createLead(fields(f) as never);revalidatePath("/workspace/leads");return{success:"Lead saved."};}catch(error){return{error:error instanceof LeadError&&error.code==="ACTIVE_FOLLOW_UP"?"Complete the active follow-up checkout before reassigning this lead.":"Unable to save the lead. Check its details and your access."};}}
export async function moveLead(_:LeadActionState,f:FormData):Promise<LeadActionState>{try{const leadId=String(f.get("leadId")),toStage=String(f.get("toStage"));await transitionLead({leadId,version:f.get("version"),toStage,lostReason:f.get("lostReason")} as never);let project:null|{id:string;projectNumber:string}=null;if(toStage==="WON"){try{const user=await requirePermission("SALES_LEADS");if(user.companyId)project=await ensureWonLeadProjectForActor({id:user.id,companyId:user.companyId},leadId);}catch{/* Lead detail performs an idempotent reconciliation if handover needs retry. */}}revalidatePath("/workspace/leads");revalidatePath(`/workspace/leads/${leadId}`);revalidatePath("/workspace/account/projects");return{success:project?`Lead won. Project ${project.projectNumber} created.`:"Pipeline updated."};}catch{return{error:"Unable to move this lead. Refresh and try again."};}}
export async function deleteLeadAction(f:FormData):Promise<void>{const{permanentlyDeleteLead}=await import("@/lib/leads/deletion");await permanentlyDeleteLead(String(f.get("leadId")));revalidatePath("/workspace/leads");revalidatePath("/workspace");}
