"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { addMilestone, addProjectDocument, addProjectMember, addTask, linkBoq, replaceBudget, updateMilestone, updateProject, updateTask } from "@/lib/account/projects";
import { assertProjectEditable, completeSimpleProject, createSimpleProject } from "@/lib/account/project-simple-workflow";
const text = (form: FormData, key: string) => String(form.get(key) || "") || undefined;
const projectPath = (id: string) => `/workspace/account/projects/${id}`;
export async function createProjectAction(form: FormData) { const project = await createSimpleProject({ branchId: text(form, "branchId"), name: text(form, "name"), siteName: text(form, "siteName"), siteAddress: text(form, "siteAddress"), siteContactName: text(form, "siteContactName"), siteContactPhone: text(form, "siteContactPhone"), projectManagerId: text(form, "projectManagerId"), startDate: text(form, "startDate"), projectValue: text(form, "projectValue") || "0" }); redirect(projectPath(project.id)); }
export async function updateProjectAction(form: FormData) { const projectId = text(form, "projectId")!; await assertProjectEditable(projectId); await updateProject({ projectId, name: text(form, "name"), siteName: text(form, "siteName"), siteAddress: text(form, "siteAddress"), siteContactName: text(form, "siteContactName"), siteContactPhone: text(form, "siteContactPhone"), projectManagerId: text(form, "projectManagerId"), startDate: text(form, "startDate"), targetEndDate: undefined, projectValue: text(form, "projectValue") || "0", status: text(form, "status") }); redirect(projectPath(projectId)); }
export async function addMilestoneAction(form: FormData) { const projectId = text(form, "projectId")!; await addMilestone({ projectId, title: text(form, "title"), description: text(form, "description"), startDate: text(form, "startDate"), dueDate: text(form, "dueDate"), status: text(form, "status") || "PENDING" }); revalidatePath(projectPath(projectId)); }
export async function updateMilestoneAction(form: FormData) { const projectId = text(form, "projectId")!; await updateMilestone({ projectId, milestoneId: text(form, "milestoneId"), title: text(form, "title"), description: text(form, "description"), startDate: text(form, "startDate"), dueDate: text(form, "dueDate"), status: text(form, "status") }); revalidatePath(projectPath(projectId)); }
export async function addTaskAction(form: FormData) { const projectId = text(form, "projectId")!; await addTask({ projectId, title: text(form, "title"), description: text(form, "description"), milestoneId: text(form, "milestoneId"), assigneeUserId: text(form, "assigneeUserId"), dueDate: text(form, "dueDate"), priority: text(form, "priority") || "0", status: text(form, "status") || "TODO" }); revalidatePath(projectPath(projectId)); }
export async function updateTaskAction(form: FormData) { const projectId = text(form, "projectId")!; await updateTask({ projectId, taskId: text(form, "taskId"), title: text(form, "title"), description: text(form, "description"), milestoneId: text(form, "milestoneId"), assigneeUserId: text(form, "assigneeUserId"), dueDate: text(form, "dueDate"), priority: text(form, "priority") || "0", status: text(form, "status") }); revalidatePath(projectPath(projectId)); }
export async function replaceBudgetAction(form: FormData) { const projectId = text(form, "projectId")!; const lines=JSON.parse(String(form.get("lines")||"[]")); await replaceBudget({ projectId, lines }); revalidatePath(projectPath(projectId)); }
export async function linkBoqAction(form: FormData) { const projectId = text(form, "projectId")!; await linkBoq(projectId, text(form, "boqId")!); revalidatePath(projectPath(projectId)); }
export async function completeProjectAction(form: FormData) { const projectId = text(form, "projectId")!; await completeSimpleProject(projectId); revalidatePath(projectPath(projectId)); revalidatePath("/workspace/account/projects"); }
export async function addProjectDocumentAction(form: FormData) { const projectId = text(form, "projectId")!, file = form.get("file"); if (!(file instanceof File)) throw new Error("INVALID_PROJECT_DOCUMENT"); await addProjectDocument(projectId, file, text(form, "category"), text(form, "notes")); revalidatePath(projectPath(projectId)); }
export async function addProjectMemberAction(form: FormData) { const projectId = text(form, "projectId")!; await addProjectMember(projectId, text(form, "userId")!, text(form, "role")); revalidatePath(projectPath(projectId)); }
