"use server";
import { redirect } from "next/navigation";
import { createQuotation, createQuotationRevision, createShare, revokeShare, transitionQuotation, updateQuotationDraft } from "@/lib/quotations/service";
export type QuotationActionState={error?:string};
const safe=(error:unknown)=>error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message.replaceAll("_"," "):"Unable to process quotation request";
const isRedirect=(error:unknown)=>Boolean(error&&typeof error==="object"&&"digest" in error);
export async function saveQuotation(_:QuotationActionState,form:FormData):Promise<QuotationActionState>{try{const document=await createQuotation(JSON.parse(String(form.get("document"))));redirect(`/workspace/account/quotations/${document.id}?saved=1`);}catch(error){if(isRedirect(error))throw error;return{error:safe(error)}}}
export async function saveRevision(id:string,_:QuotationActionState,form:FormData):Promise<QuotationActionState>{try{await createQuotationRevision(id,JSON.parse(String(form.get("document"))));redirect(`/workspace/account/quotations/${id}?revised=1`);}catch(error){if(isRedirect(error))throw error;return{error:safe(error)}}}
export async function updateDraft(id:string,_:QuotationActionState,form:FormData):Promise<QuotationActionState>{try{await updateQuotationDraft(id,JSON.parse(String(form.get("document"))));redirect(`/workspace/account/quotations/${id}?saved=1`);}catch(error){if(isRedirect(error))throw error;return{error:safe(error)}}}
export async function transitionQuotationAction(form:FormData){const id=String(form.get("id"));try{await transitionQuotation(id,String(form.get("to")) as never,String(form.get("note")??""));redirect(`/workspace/account/quotations/${id}?updated=1`);}catch(error){if(isRedirect(error))throw error;redirect(`/workspace/account/quotations/${id}?error=${encodeURIComponent(safe(error))}`)}}
export async function shareQuotationAction(form:FormData){const id=String(form.get("id"));try{const token=await createShare(id,form.get("expiresAt")?new Date(String(form.get("expiresAt"))):undefined);redirect(`/workspace/account/quotations/${id}?share=${encodeURIComponent(token)}`);}catch(error){if(isRedirect(error))throw error;redirect(`/workspace/account/quotations/${id}?error=${encodeURIComponent(safe(error))}`)}}
export async function revokeQuotationShareAction(form:FormData){const id=String(form.get("id"));try{await revokeShare(String(form.get("shareId")));redirect(`/workspace/account/quotations/${id}?revoked=1`);}catch(error){if(isRedirect(error))throw error;redirect(`/workspace/account/quotations/${id}?error=${encodeURIComponent(safe(error))}`)}}
