import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ auth: vi.fn(), group: vi.fn(), companies: vi.fn(), pending:vi.fn(), payments:vi.fn(), users:vi.fn() }));
vi.mock("@/lib/auth/authorization", () => ({ requireGlobalSuperAdmin: mocks.auth }));
vi.mock("@/lib/db", () => ({ db: { company: { groupBy: mocks.group, findMany: mocks.companies },billingOrder:{count:mocks.pending},paymentTransaction:{aggregate:mocks.payments},user:{count:mocks.users} } }));
import { getAdminCompanies, getAdminDashboard } from "./dashboard";
const company = { id: "11111111-1111-4111-8111-111111111111", name: "Alpha", productEdition: "SALESPUNCH360", subscriptionStatus: "ACTIVE", trialEndsAt: null, createdAt: new Date("2026-01-01") };
beforeEach(() => { vi.clearAllMocks(); mocks.auth.mockResolvedValue({ role: "SUPER_ADMIN", companyId: null }); mocks.group.mockResolvedValue([{ subscriptionStatus: "ACTIVE", _count: { _all: 2 } }, { subscriptionStatus: "TRIAL", _count: { _all: 1 } }]); mocks.companies.mockResolvedValue([company]);mocks.pending.mockResolvedValue(0);mocks.payments.mockResolvedValue({_count:{_all:0},_sum:{amount:null}});mocks.users.mockResolvedValue(0); });
describe("Super Admin Company data", () => {
  it("authorizes before returning correct counts and safe recent tenant identity", async () => { const result = await getAdminDashboard(); expect(mocks.auth).toHaveBeenCalledOnce(); expect(result.counts).toEqual({ total: 3, TRIAL: 1, ACTIVE: 2, EXPIRED: 0, SUSPENDED: 0 }); expect(result.recentCompanies[0]).toEqual(company); expect(mocks.companies).toHaveBeenCalledWith({ select: { id: true, name: true, productEdition: true, subscriptionStatus: true, trialEndsAt: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 8 }); expect(result.billing).toEqual({pendingOrders:0,capturedPayments:0,capturedRevenue:0,activeUsers:0});expect(JSON.stringify(result.recentCompanies)).not.toMatch(/email|phone|customer|payment/i); });
  it("denies dashboard data before any query", async () => { mocks.auth.mockRejectedValue(new Error("Not authorized")); await expect(getAdminDashboard()).rejects.toThrow("Not authorized"); expect(mocks.group).not.toHaveBeenCalled(); expect(mocks.companies).not.toHaveBeenCalled(); });
  it("lists Companies with one user-count query and UUID identity", async () => { mocks.companies.mockResolvedValue([{ ...company, _count: { users: 4 } }]); const result = await getAdminCompanies(); expect(result[0]).toMatchObject({ id: company.id, _count: { users: 4 } }); expect(mocks.companies.mock.calls[0][0].select).not.toHaveProperty("contactEmail"); });
});
