import { beforeEach, describe, expect, it, vi } from "vitest";
import { TENANT_MODELS, type CleanupDatabase, type Inventory, type LockedCleanupDatabase } from "../tenant-cleanup";
const auth = vi.hoisted(() => ({ read: vi.fn(), mutation: vi.fn() }));
vi.mock("@/lib/auth/authorization", () => ({ requireRole: auth.read, requireRoleForMutation: auth.mutation }));
vi.mock("@/lib/storage", () => ({ privateStorage: vi.fn() }));
vi.mock("@/lib/tenant-cleanup-database", () => ({ tenantCleanupDatabase: {} }));
import { permanentlyDeleteCompany, previewPermanentCompanyDelete, STORAGE_OWNERSHIP_BLOCKED } from "./permanent-company-delete";
const ID="11111111-1111-4111-8111-111111111111", USER="22222222-2222-4222-8222-222222222222", VISIT="33333333-3333-4333-8333-333333333333";
const makeInventory=(slug="alpha"):Inventory=>({company:{id:ID,name:"Alpha",slug,createdAt:new Date("2026-01-01"),productEdition:"SALESPUNCH360",subscriptionStatus:"ACTIVE"},counts:Object.fromEntries(TENANT_MODELS.map((m,i)=>[m,i+1])) as Inventory["counts"],storage:[{key:`Logo/${ID}.webp`,source:"Company.logoObjectKey"},{key:`companies/${ID}/employees/${USER}/check-ins/${VISIT}/photo.webp`,source:"VisitPhoto.objectKey",visitId:VISIT,uploadedByUserId:USER}]});
function harness(preview: Inventory=makeInventory(),lockedInventory: Inventory | null=preview){const events:string[]=[];const locked:LockedCleanupDatabase={inventory:vi.fn(async()=>{events.push("locked_inventory");return lockedInventory}),hasSuperAdmin:vi.fn(async()=>false),assertTransactionAlive:vi.fn(async()=>{events.push("alive")}),deleteTenant:vi.fn(async()=>{events.push("delete")}),verifyTenantAbsent:vi.fn(async()=>true)};const db:CleanupDatabase={inventory:vi.fn(async()=>preview),hasSuperAdmin:vi.fn(async()=>false),withLockedTenant:vi.fn(async(_id,work)=>{events.push("lock");return work(locked)})};return{db,locked,events,storage:{delete:vi.fn(async()=>{events.push("storage")})}}}
beforeEach(()=>{vi.clearAllMocks();auth.read.mockResolvedValue({role:"SUPER_ADMIN"});auth.mutation.mockResolvedValue({role:"SUPER_ADMIN"})});
describe("permanent Company deletion authorization and preview",()=>{
 it("allows canonical SUPER_ADMIN preview and returns safe identity, every count, and totals without mutation",async()=>{const h=harness();const result=await previewPermanentCompanyDelete(ID,h.db);expect(auth.read).toHaveBeenCalledWith("SUPER_ADMIN");expect(result.company).toMatchObject({id:ID,name:"Alpha",slug:"alpha"});expect(Object.keys(result.counts)).toEqual([...TENANT_MODELS]);expect(result.totalRows).toBe(TENANT_MODELS.length*(TENANT_MODELS.length+1)/2);expect(result.totalStorageObjects).toBe(2);expect(h.db.withLockedTenant).not.toHaveBeenCalled()});
 it.each(["COMPANY_ADMIN","MANAGER","SALES","PRIMARY_ADMIN","ADMIN","ACCOUNT_ADMIN"])("denies %s preview",async role=>{auth.read.mockRejectedValue(new Error(`DENIED:${role}`));const h=harness();await expect(previewPermanentCompanyDelete(ID,h.db)).rejects.toThrow("DENIED");expect(h.db.inventory).not.toHaveBeenCalled()});
 it("blocks unsafe storage ownership",async()=>{const bad=makeInventory();bad.storage=[{key:"companies/other/private.webp",source:"PendingStorageDeletion.objectKey"}];await expect(previewPermanentCompanyDelete(ID,harness(bad).db)).rejects.toThrow(STORAGE_OWNERSHIP_BLOCKED)});
});
describe("authoritative typed confirmation",()=>{
 it("allows canonical SUPER_ADMIN to delete with exact locked authoritative slug",async()=>{const h=harness();await permanentlyDeleteCompany(ID,"DELETE alpha",h.db,h.storage);expect(auth.mutation).toHaveBeenCalledWith("SUPER_ADMIN");expect(h.events.indexOf("lock")).toBeLessThan(h.events.indexOf("locked_inventory"));expect(h.events).toContain("delete")});
 it.each(["COMPANY_ADMIN","MANAGER","SALES","PRIMARY_ADMIN","ADMIN","ACCOUNT_ADMIN"])("denies direct %s invocation before locking",async role=>{auth.mutation.mockRejectedValue(new Error(`DENIED:${role}`));const h=harness();await expect(permanentlyDeleteCompany(ID,"DELETE alpha",h.db,h.storage)).rejects.toThrow("DENIED");expect(h.db.withLockedTenant).not.toHaveBeenCalled()});
 it.each(["wrong","DELETE beta"])("rejects wrong/other confirmation %s with zero mutation",async confirmation=>{const h=harness();await expect(permanentlyDeleteCompany(ID,confirmation,h.db,h.storage)).rejects.toThrow("PERMANENT_DELETE_CONFIRMATION_INCORRECT");expect(h.storage.delete).not.toHaveBeenCalled();expect(h.locked.deleteTenant).not.toHaveBeenCalled()});
 it("rejects stale preview slug after lock rereads the authoritative slug",async()=>{const h=harness(makeInventory("old"),makeInventory("new"));await expect(permanentlyDeleteCompany(ID,"DELETE old",h.db,h.storage)).rejects.toThrow("PERMANENT_DELETE_CONFIRMATION_INCORRECT");expect(h.storage.delete).not.toHaveBeenCalled()});
 it("fails a second delete closed as not found",async()=>{const h=harness(makeInventory(),null);await expect(permanentlyDeleteCompany(ID,"DELETE alpha",h.db,h.storage)).rejects.toThrow("TENANT_NOT_FOUND_OR_ALREADY_CLEANED");expect(h.storage.delete).not.toHaveBeenCalled()});
});
