import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
import {ACCOUNT_SETTINGS_MENU} from "../account-settings-menu";
describe("Account settings navigation",()=>{
 it("uses the exact requested list and order",()=>expect(ACCOUNT_SETTINGS_MENU.map(x=>x.label)).toEqual(["General","Transaction","Invoice Print","Taxes & GST","Employees","Transaction SMS","Reminders","Party","Item","Multi-Currency"]));
 it("makes profile Settings functional on Web and Android",()=>{const web=readFileSync("src/components/account/account-profile-menu.tsx","utf8"),android=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/NativeAccountApp.kt","utf8");expect(web).toContain('href="/workspace/account/settings"');expect(web).not.toContain('account-menu-placeholder">Settings');expect(android).toContain('Text("Settings")');expect(android).not.toContain('Settings · Coming soon')});
 it("keeps the same menu labels on Android",()=>{const android=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/admin/AccountAdministrationScreen.kt","utf8");for(const item of ACCOUNT_SETTINGS_MENU)expect(android).toContain(`"${item.label}"`)})
 it("renders one ordered Web list with no Settings search or grid",()=>{const menu=readFileSync("src/components/account/account-settings-menu.tsx","utf8"),page=readFileSync("src/app/workspace/account/settings/page.tsx","utf8");expect(menu).toContain("ACCOUNT_SETTINGS_MENU.map");expect(menu).not.toMatch(/<input|search/i);expect(page).not.toMatch(/search|grid/i);for(const item of ACCOUNT_SETTINGS_MENU)expect(menu).toContain(`href={item.href}`)})
 it("opens full-screen Settings from Sale while keeping the editor state mounted",()=>{const sale=readFileSync("src/app/workspace/account/transactions/new/sale-invoice-editor.tsx","utf8");expect(sale).toContain('if(settingsOpen)return <section className="sale-settings-page account-inner-page"');expect(sale).toContain('<AccountIcon name="settings"/>');expect(sale.indexOf("if(settingsOpen)return")).toBeLessThan(sale.indexOf('return <main className="sale-entry"'));expect(sale).toContain('onClick={()=>setSettingsOpen(false)}')})
 it("gives Android the same search-free list and dedicated Sale navigation",()=>{const admin=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/admin/AccountAdministrationScreen.kt","utf8"),sale=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/sales/SalesDocumentEditor.kt","utf8");const menu=admin.slice(admin.indexOf("fun AccountSettingsMenuScreen"),admin.indexOf("private data class PartyHelp"));expect(menu).not.toContain("Search");expect(menu).not.toContain("query");expect(menu).toContain("LazyColumn");expect(sale).toContain('Icon(Icons.Default.Settings,"Sale settings")');expect(sale).toContain('navigate("/workspace/account/settings")')})
 it("routes the full General rows and coming-soon currency page",()=>{const general=readFileSync("src/components/account/general-settings-form.tsx","utf8"),currency=readFileSync("src/app/workspace/account/settings/multi-currency/page.tsx","utf8");for(const label of ["Multi-Branch Settings","Godown / Warehouse & Stock Transfer","Backup Settings","MORE TRANSACTIONS"])expect(general).toContain(label);expect(currency).toContain("Coming Soon")});
 it("keeps feature-specific info copy and disabled future themes",()=>{const general=readFileSync("src/components/account/general-settings-form.tsx","utf8");for(const topic of ["Business Currency","Decimal Places","Estimate / Quotation","Proforma Invoice","Fixed Assets (FA)","Delivery Challan"])expect(general).toContain(topic);expect(general).toContain('<option disabled>Trending');expect(general).toContain('<option disabled>Modern')});
 it("uses existing branch and backup workflows",()=>{expect(readFileSync("src/app/workspace/account/settings/multi-branch/page.tsx","utf8")).toContain("listBranches");expect(readFileSync("src/app/workspace/account/settings/backup/page.tsx","utf8")).toContain('/workspace/account/utilities/backup')});
});
