import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
import {ACCOUNT_SETTINGS_MENU} from "../account-settings-menu";
describe("Account settings navigation",()=>{
 it("uses the exact requested list and order",()=>expect(ACCOUNT_SETTINGS_MENU.map(x=>x.label)).toEqual(["General","Transaction","Invoice Print","Taxes & GST","Employees","Transaction SMS","Reminders","Party","Item","Multi-Currency"]));
 it("makes profile Settings functional on Web and Android",()=>{const web=readFileSync("src/components/account/account-profile-menu.tsx","utf8"),android=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/NativeAccountApp.kt","utf8");expect(web).toContain('href="/workspace/account/settings"');expect(web).not.toContain('account-menu-placeholder">Settings');expect(android).toContain('Text("Settings")');expect(android).not.toContain('Settings · Coming soon')});
 it("keeps the same menu labels on Android",()=>{const android=readFileSync("android/app/src/main/java/com/salespunch360/mobile/ui/account/admin/AccountAdministrationScreen.kt","utf8");for(const item of ACCOUNT_SETTINGS_MENU)expect(android).toContain(`"${item.label}"`)})
 it("is a compact list without search or grid cards",()=>{const menu=readFileSync("src/components/account/account-settings-menu.tsx","utf8"),page=readFileSync("src/app/workspace/account/settings/page.tsx","utf8");expect(menu).not.toContain("Search settings");expect(page).not.toContain("search");expect(menu).toContain("account-settings-menu");expect(menu).not.toContain("card")});
 it("opens Sale settings as a full-screen state without the Sale footer",()=>{const sale=readFileSync("src/app/workspace/account/transactions/new/sale-invoice-editor.tsx","utf8");expect(sale).toContain('className="sale-gear"');expect(sale).toContain('if(settingsOpen)return <main className="sale-settings-page');expect(sale.indexOf("if(settingsOpen)return")).toBeLessThan(sale.indexOf('className="sale-actions"'))});
 it("keeps compact info and control sizing contracts",()=>{const css=readFileSync("src/app/globals.css","utf8");expect(css).toContain("width:14px!important;height:14px!important");expect(css).toContain("width:30px;min-height:30px")});
 it("waits for confirmed saves and prevents repeat General submissions",()=>{const form=readFileSync("src/components/account/general-settings-form.tsx","utf8"),actions=readFileSync("src/app/actions/account-settings.ts","utf8");expect(form).toContain("disabled={pending}");expect(form).toContain('<SaveFeedback state={state}/>');expect(actions.indexOf('await updateGeneralSettingsAction(fd)')).toBeLessThan(actions.indexOf('success:"Saved successfully"'));expect(actions).toContain("catch(error)")});
 it("routes the full General rows and coming-soon currency page",()=>{const general=readFileSync("src/components/account/general-settings-form.tsx","utf8"),currency=readFileSync("src/app/workspace/account/settings/multi-currency/page.tsx","utf8");for(const label of ["Multi-Branch Settings","Godown / Warehouse & Stock Transfer","Backup Settings","MORE TRANSACTIONS"])expect(general).toContain(label);expect(currency).toContain("Coming Soon")});
 it("keeps feature-specific info copy and disabled future themes",()=>{const general=readFileSync("src/components/account/general-settings-form.tsx","utf8");for(const topic of ["Business Currency","Decimal Places","Estimate / Quotation","Proforma Invoice","Fixed Assets (FA)","Delivery Challan"])expect(general).toContain(topic);expect(general).toContain('<option disabled>Trending');expect(general).toContain('<option disabled>Modern')});
 it("uses existing branch and backup workflows",()=>{expect(readFileSync("src/app/workspace/account/settings/multi-branch/page.tsx","utf8")).toContain("listBranches");expect(readFileSync("src/app/workspace/account/settings/backup/page.tsx","utf8")).toContain('/workspace/account/utilities/backup')});
});
