import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";

const read=(path:string)=>readFileSync(path,"utf8");

describe("Sale settings correction contracts",()=>{
 it("keeps the Web Sale editor mounted behind its specific settings panel",()=>{const source=read("src/app/workspace/account/transactions/new/sale-invoice-editor.tsx");expect(source).toContain('aria-label="Sale settings"');expect(source).toContain('role="dialog" aria-modal="true" aria-label="Sale settings panel"');expect(source).toContain('data-testid="sale-settings-backdrop"');expect(source).not.toContain("if(settingsOpen)return");for(const label of["Sale Prefix","Transaction SMS","Additional Fields","Additional Charges","Billing Type","More Settings"])expect(source).toContain(label);expect(source).toContain('className="more-settings" href="/workspace/account/settings/transactions"');expect(source).toContain('aria-label="Close Sale settings"')});
 it("retains Web draft state in the mounted editor and does not render the main menu",()=>{const source=read("src/app/workspace/account/transactions/new/sale-invoice-editor.tsx");for(const state of["partyId,setParty","saleMode,setSaleMode","lines,setLines","billingName,setBillingName","issueDate,setIssueDate"])expect(source).toContain(state);expect(source).not.toContain("AccountSettingsMenu")});
 it("places the existing eligible Account switch first in every Sales profile menu",()=>{for(const path of["android/app/src/main/java/com/salespunch360/mobile/ui/SalesDrawerShell.kt","android/app/src/main/java/com/salespunch360/mobile/ui/AdminManagerDrawer.kt","android/app/src/main/java/com/salespunch360/mobile/ui/PrimaryAdminDrawer.kt"]){const source=read(path),menu=source.slice(source.indexOf("DropdownMenu(expanded"));expect(menu).toContain('switchToAccount?.let');expect(menu).toContain('Text("Switch to Account")');expect(menu.indexOf("Switch to Account")).toBeLessThan(menu.indexOf("Company Details"))}expect(read("android/app/src/main/java/com/salespunch360/mobile/ui/SalesDrawer.kt")).not.toContain('SalesDrawerDestination("Switch to Account"')});
 it("uses the existing switch callback and functional Sales Settings drawer destination",()=>{const activity=read("android/app/src/main/java/com/salespunch360/mobile/MainActivity.kt"),admin=read("android/app/src/main/java/com/salespunch360/mobile/ui/AdminManagerDrawer.kt"),primary=read("android/app/src/main/java/com/salespunch360/mobile/ui/PrimaryAdminDrawer.kt");expect(activity).toContain("vm.switchToAccount()");for(const source of[admin,primary]){expect(source).toContain('nav.navigate("Settings")');expect(source).toContain('scope.launch{drawer.close()}');expect(source).toContain('route=="Settings"->SettingsScreen()')}});
 it("opens Android Sale settings natively and reserves full settings navigation for panel actions",()=>{const source=read("android/app/src/main/java/com/salespunch360/mobile/ui/account/sales/SalesDocumentEditor.kt");expect(source).toContain("var saleSettings by remember");expect(source).toContain("if(saleSettings)ModalBottomSheet");expect(source).toContain('onClick={saleSettings=true}');for(const label of["Sale Prefix","Transaction SMS","Additional Fields","Additional Charges","Billing Type","More Settings"])expect(source).toContain(label);expect(source).toContain('navigate("/workspace/account/settings/transactions")');expect(source).toContain("draft:SalesEditorDraft");expect(source).toContain("onDraft:(SalesEditorDraft)->Unit")});
});
