import{beforeEach,describe,expect,it,vi}from"vitest";
const mocks=vi.hoisted(()=>({transaction:vi.fn(),query:vi.fn(),company:vi.fn(),userFind:vi.fn(),count:vi.fn(),create:vi.fn(),subscription:vi.fn(),update:vi.fn()}));
vi.mock("@/lib/db",()=>({db:{$transaction:mocks.transaction}}));vi.mock("@/lib/auth/crypto",()=>({hashPassword:vi.fn().mockResolvedValue("hash")}));
import{createManagerForCompany,createSalesEmployeeForCompany,reactivateEmployeeForCompany}from"./service";
const companyId="11111111-1111-4111-8111-111111111111",adminId="22222222-2222-4222-8222-222222222222",employeeId="33333333-3333-4333-8333-333333333333";
const complete={subscriptionStatus:"ACTIVE",trialStartedAt:null,trialEndsAt:null,teamStructure:"MANAGERS_AND_SALES",productEdition:"SALESPUNCH360",name:"Acme",addressLine1:"1 Main",city:"Pune",state:"MH",postalCode:"411001",country:"India",primaryContactName:"Admin",primaryPhone:"9999999999",contactEmail:"admin@example.com"};
const input={name:"Manager",email:"manager@example.com",password:"StrongPassword1",confirmPassword:"StrongPassword1"};
beforeEach(()=>{vi.clearAllMocks();mocks.company.mockResolvedValue(complete);mocks.userFind.mockResolvedValue({emailVerifiedAt:new Date()});mocks.count.mockResolvedValue(0);mocks.subscription.mockResolvedValue({managerSeats:2,salesSeats:2});mocks.create.mockResolvedValue({id:employeeId});mocks.update.mockResolvedValue({count:1});mocks.transaction.mockImplementation(async(fn)=>fn({$queryRaw:mocks.query,company:{findFirst:mocks.company},user:{findFirst:mocks.userFind,count:mocks.count,create:mocks.create,updateMany:mocks.update},companySubscription:{findFirst:mocks.subscription}}))});
describe("employee readiness gates",()=>{
 it("requires the mandatory acting Company Admin to be verified",async()=>{mocks.userFind.mockResolvedValueOnce({emailVerifiedAt:null});await expect(createManagerForCompany(companyId,input,adminId)).rejects.toThrow("EMAIL_VERIFICATION_REQUIRED");expect(mocks.create).not.toHaveBeenCalled()});
 it("requires a complete authoritative company profile",async()=>{mocks.company.mockResolvedValue({...complete,addressLine1:null});await expect(createManagerForCompany(companyId,input,adminId)).rejects.toThrow("COMPANY_PROFILE_REQUIRED");expect(mocks.create).not.toHaveBeenCalled()});
 it("creates only after readiness and entitlement checks",async()=>{await expect(createManagerForCompany(companyId,input,adminId)).resolves.toMatchObject({id:employeeId});expect(mocks.count).toHaveBeenCalled();expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({salesRole:"MANAGER",salesAccessActive:true})}))});
 it("creates a Sales employee with active Sales lifecycle in a Sales edition",async()=>{await createSalesEmployeeForCompany(companyId,{...input,email:"sales@example.com"},adminId);expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({salesRole:"SALES",salesAccessActive:true})}))});
 it.each([["manager",createManagerForCompany],["sales",createSalesEmployeeForCompany]] as const)("keeps %s Sales lifecycle inactive when the edition does not permit Sales",async(_label,create)=>{mocks.company.mockResolvedValue({...complete,productEdition:"SALESPUNCH360_ACCOUNT"});await create(companyId,input,adminId);expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({salesAccessActive:false})}))});
 it("applies readiness before reactivation",async()=>{mocks.userFind.mockResolvedValueOnce({emailVerifiedAt:null});await expect(reactivateEmployeeForCompany(companyId,{employeeId},adminId)).rejects.toThrow("EMAIL_VERIFICATION_REQUIRED");expect(mocks.update).not.toHaveBeenCalled()});
 it("reactivates only Sales lifecycle when role and edition permit it",async()=>{mocks.userFind.mockResolvedValueOnce({emailVerifiedAt:new Date()}).mockResolvedValueOnce({id:employeeId,companyId,role:"MANAGER",salesRole:"MANAGER",accountRole:"PROJECT_MANAGER",isActive:false});await reactivateEmployeeForCompany(companyId,{employeeId},adminId);expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({data:{isActive:true,salesAccessActive:true}}));expect(mocks.update.mock.calls[0][0].data).not.toHaveProperty("accountRole");expect(mocks.update.mock.calls[0][0].data).not.toHaveProperty("accountAccessActive")});
 it("does not restore Sales lifecycle when the edition does not permit it",async()=>{mocks.company.mockResolvedValue({...complete,productEdition:"SALESPUNCH360_ACCOUNT"});mocks.userFind.mockResolvedValueOnce({emailVerifiedAt:new Date()}).mockResolvedValueOnce({id:employeeId,companyId,role:"SALES",salesRole:"SALES",accountRole:"DATA_ENTRY",isActive:false});await reactivateEmployeeForCompany(companyId,{employeeId},adminId);expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({data:{isActive:true,salesAccessActive:false}}));expect(mocks.update.mock.calls[0][0].data).not.toHaveProperty("accountRole");expect(mocks.update.mock.calls[0][0].data).not.toHaveProperty("accountAccessActive")});
});
